/**
 * Mapping slug/category → photo libre de droits (Wikimedia Commons).
 *
 * Source : Wikimedia Commons — fichiers sous licences libres / domaine public.
 * Chaque URL a été obtenue via l'API Commons puis VÉRIFIÉE (HTTP 200, image/*)
 * par le workflow scripts/fetch-images.workflow.js. Aucune URL devinée.
 *
 * Régénérer : node scripts/gen-images.mjs (après le workflow).
 * Priorité : ARTICLE_PHOTOS[slug] → CATEGORY_PHOTOS[category] → générique.
 */

import { CATEGORIES } from './categories';

interface PhotoMeta {
  src: string;
  alt: string;
}

export const CATEGORY_PHOTOS: Record<string, PhotoMeta> = {
  "jeunes": { src: "/img/jeune-hydrique.jpg", alt: "jeunes — Verre d'eau posé sur une table" },
  "purges": { src: "/img/huile-de-ricin.jpg", alt: "purges — Mise en bouteille d'huile de ricin" },
  "plantes": { src: "/img/achillee-millefeuille.jpg", alt: "plantes — Achillée millefeuille en fleurs" },
  "alimentation": { src: "/img/alimentation-vivante.jpg", alt: "alimentation — L'alimentation vivante" },
  "cures-saisonnieres": { src: "/img/cure-printemps.jpg", alt: "cures-saisonnieres — Pissenlits en fleur dans une prairie au printemps" },
  "hydrotherapie": { src: "/img/douche-ecossaise.jpg", alt: "hydrotherapie — Eau s'écoulant d'une pomme de douche" },
  "aromatherapie": { src: "/img/huiles-essentielles-introduction.jpg", alt: "aromatherapie — Flacons d'huiles essentielles" },
  "respiration-sommeil": { src: "/img/respiration-abdominale.jpg", alt: "respiration-sommeil — La respiration abdominale" },
  "stress-emotions": { src: "/img/stress-chronique-causes.jpg", alt: "stress-emotions — Stress chronique" },
  "vitamines": { src: "/img/vitamine-a.jpg", alt: "vitamines — Vitamine A" },
  "mineraux": { src: "/img/magnesium.jpg", alt: "mineraux — Magnésium" },
  "acides-gras": { src: "/img/omega-3-fondamentaux.jpg", alt: "acides-gras — Oméga-3" },
  "acides-amines": { src: "/img/tryptophane.jpg", alt: "acides-amines — Tryptophane" },
  "antioxydants": { src: "/img/glutathion.jpg", alt: "antioxydants — Glutathion" },
  "probiotiques": { src: "/img/microbiote-bases.jpg", alt: "probiotiques — Kit d'analyse du microbiote intestinal" },
  "adaptogenes": { src: "/img/plantes-adaptogenes-introduction.jpg", alt: "adaptogenes — Racines de plante adaptogène séchées" },
  "objectifs": { src: "/img/complements-fatigue-chronique.jpg", alt: "objectifs — Femme fatiguée devant son ordinateur" },
  "adaptogenes-plantes": { src: "/img/safran-depression-meta-2024.jpg", alt: "adaptogenes-plantes — Safran et dépression" },
  "microbiote-nutrition": { src: "/img/probiotiques-eczema-enfant.jpg", alt: "microbiote-nutrition — Probiotiques et eczéma de l'enfant" },
  "sommeil": { src: "/img/valeriane-sommeil.jpg", alt: "sommeil — Valériane" },
  "stress-anxiete": { src: "/img/ashwagandha-stress.jpg", alt: "stress-anxiete — Ashwagandha" },
  "digestion": { src: "/img/artichaut-digestion.jpg", alt: "digestion — Artichaut" },
  "immunite-infections": { src: "/img/echinacee-immunite.jpg", alt: "immunite-infections — Échinacée pourpre" },
  "circulation": { src: "/img/aubepine-circulation.jpg", alt: "circulation — Aubépine" },
  "respiration": { src: "/img/eucalyptus-respiration.jpg", alt: "respiration — Eucalyptus" },
  "peau-articulations": { src: "/img/ortie-articulations.jpg", alt: "peau-articulations — Ortie" },
  "feminin": { src: "/img/achillee-millefeuille-feminin.jpg", alt: "feminin — Achillée millefeuille" },
  "walker-fondamentaux": { src: "/img/jus-carotte-pur-walker.jpg", alt: "walker-fondamentaux — Jus de carotte pur — jus frais" },
  "detox": { src: "/img/jus-vert-detox-printemps.jpg", alt: "detox — Jus vert de printemps — jus frais" },
  "energie": { src: "/img/jus-gingembre-pomme-citron-matin.jpg", alt: "energie — Gingembre + pomme + citron — jus frais" },
  "immunite": { src: "/img/shot-gingembre-curcuma-citron.jpg", alt: "immunite — Shot gingembre + curcuma + citron — jus frais" },
  "peau-cheveux": { src: "/img/jus-carotte-concombre-pomme.jpg", alt: "peau-cheveux — Jus carotte, concombre et pomme — jus frais" },
  "minceur": { src: "/img/jus-concombre-celeri-citron-menthe.jpg", alt: "minceur — Jus concombre, céleri, citron et menthe — jus frais" },
  "sport": { src: "/img/jus-betterave-pre-effort.jpg", alt: "sport — Jus de betterave pré-effort — jus frais" },
};

export const ARTICLE_PHOTOS: Record<string, PhotoMeta> = {
  "jeune-hydrique": { src: "/img/jeune-hydrique.jpg", alt: "Verre d'eau posé sur une table" },
  "jeune-intermittent": { src: "/img/jeune-intermittent.jpg", alt: "Assiette vide avec couverts sur une table" },
  "jeune-aux-jus": { src: "/img/jeune-aux-jus.jpg", alt: "Verre de jus de légumes vert" },
  "jeune-sec": { src: "/img/jeune-sec.jpg", alt: "Verre vide sur fond clair" },
  "methode-buchinger": { src: "/img/methode-buchinger.jpg", alt: "Bol de bouillon de légumes fumant" },
  "preparation-jeune": { src: "/img/preparation-jeune.jpg", alt: "Assortiment de légumes frais pour la descente alimentaire" },
  "sortie-jeune": { src: "/img/sortie-jeune.jpg", alt: "Bol de compote de pommes pour la reprise alimentaire" },
  "crises-guerison": { src: "/img/crises-guerison.jpg", alt: "Personne au repos allongée" },
  "monodiete-raisin": { src: "/img/monodiete-raisin.jpg", alt: "Grappe de raisin" },
  "monodiete-pomme": { src: "/img/monodiete-pomme.jpg", alt: "Pommes rouges fraîches" },
  "monodiete-riz": { src: "/img/monodiete-riz.jpg", alt: "Bol de riz semi-complet cuit" },
  "monodiete-pasteque": { src: "/img/monodiete-pasteque.jpg", alt: "Tranches de pastèque" },
  "monodiete-carotte": { src: "/img/monodiete-carotte.jpg", alt: "Botte de carottes fraîches" },
  "jeune-court-vs-long": { src: "/img/jeune-court-vs-long.jpg", alt: "Sablier en bois symbolisant la durée du jeûne" },
  "restriction-calorique-autophagie": { src: "/img/restriction-calorique-autophagie.jpg", alt: "Bol de salade légère et saine" },
  "huile-de-ricin": { src: "/img/huile-de-ricin.jpg", alt: "Mise en bouteille d'huile de ricin" },
  "lavement-colon": { src: "/img/lavement-colon.jpg", alt: "Matériel d'irrigation pour lavement intestinal" },
  "drainage-hepatique-citron": { src: "/img/drainage-hepatique-citron.jpg", alt: "Citron et huile d'olive" },
  "cure-radis-noir": { src: "/img/cure-radis-noir.jpg", alt: "Radis noir entier et coupé" },
  "brossage-peau-sec": { src: "/img/brossage-peau-sec.jpg", alt: "Le brossage à sec de la peau" },
  "bentonite-psyllium": { src: "/img/bentonite-psyllium.jpg", alt: "Poudre de psyllium" },
  "argile-verte-cataplasme": { src: "/img/argile-verte-cataplasme.jpg", alt: "Argile préparée en cataplasme" },
  "sauna-hammam": { src: "/img/sauna-hammam.jpg", alt: "Intérieur en bois d'un sauna" },
  "fumeterre-cure-printemps": { src: "/img/fumeterre-cure-printemps.jpg", alt: "Fumeterre officinale (Fumaria officinalis)" },
  "drainage-lymphatique-manuel": { src: "/img/drainage-lymphatique-manuel.jpg", alt: "Massage manuel du dos" },
  "achillee-millefeuille": { src: "/img/achillee-millefeuille.jpg", alt: "Achillée millefeuille en fleurs" },
  "aubepine": { src: "/img/aubepine.jpg", alt: "Aubépine (Crataegus monogyna) en fleurs" },
  "artichaut": { src: "/img/artichaut.jpg", alt: "Plant d'artichaut (Cynara scolymus)" },
  "bardane": { src: "/img/bardane.jpg", alt: "Bardane (Arctium lappa)" },
  "boldo": { src: "/img/boldo.jpg", alt: "Feuilles de boldo (Peumus boldus)" },
  "camomille-romaine": { src: "/img/camomille-romaine.jpg", alt: "Camomille romaine" },
  "cassis-bourgeons": { src: "/img/cassis-bourgeons.jpg", alt: "Cassis (bourgeons)" },
  "chardon-marie": { src: "/img/chardon-marie.jpg", alt: "Chardon-Marie" },
  "desmodium": { src: "/img/desmodium.jpg", alt: "Desmodium" },
  "echinacee": { src: "/img/echinacee.jpg", alt: "Échinacée" },
  "eleutherocoque": { src: "/img/eleutherocoque.jpg", alt: "Éleuthérocoque (Ginseng sibérien)" },
  "fenouil": { src: "/img/fenouil.jpg", alt: "Fenouil" },
  "gentiane": { src: "/img/gentiane.jpg", alt: "Gentiane jaune" },
  "gingembre": { src: "/img/gingembre.jpg", alt: "Gingembre" },
  "ginkgo": { src: "/img/ginkgo.jpg", alt: "Ginkgo biloba" },
  "ginseng": { src: "/img/ginseng.jpg", alt: "Ginseng (Panax ginseng)" },
  "harpagophytum": { src: "/img/harpagophytum.jpg", alt: "Harpagophytum (griffe du diable)" },
  "lavande-vraie": { src: "/img/lavande-vraie.jpg", alt: "Lavande vraie" },
  "melisse": { src: "/img/melisse.png", alt: "Mélisse (Melissa officinalis)" },
  "menthe-poivree": { src: "/img/menthe-poivree.jpg", alt: "Menthe poivrée" },
  "ortie": { src: "/img/ortie.jpg", alt: "Ortie" },
  "passiflore": { src: "/img/passiflore.jpg", alt: "Passiflore" },
  "pissenlit": { src: "/img/pissenlit.png", alt: "Pissenlit" },
  "prele-des-champs": { src: "/img/prele-des-champs.jpg", alt: "Prêle des champs" },
  "reine-des-pres": { src: "/img/reine-des-pres.png", alt: "Reine-des-prés" },
  "rhodiole": { src: "/img/rhodiole.jpg", alt: "Rhodiole" },
  "romarin": { src: "/img/romarin.jpg", alt: "Romarin" },
  "sauge-officinale": { src: "/img/sauge-officinale.jpg", alt: "Sauge officinale" },
  "thym": { src: "/img/thym.jpg", alt: "Thym" },
  "valeriane": { src: "/img/valeriane.jpg", alt: "Valériane (Valeriana officinalis)" },
  "millepertuis-hypericum-depression": { src: "/img/millepertuis-hypericum-depression.jpg", alt: "Millepertuis (Hypericum perforatum)" },
  "5-htp-griffonia-serotonine": { src: "/img/5-htp-griffonia-serotonine.jpg", alt: "5-HTP (Griffonia simplicifolia)" },
  "safran-crocus-depression": { src: "/img/safran-crocus-depression.jpg", alt: "Safran (Crocus sativus)" },
  "alimentation-vivante": { src: "/img/alimentation-vivante.jpg", alt: "L'alimentation vivante" },
  "graines-germees": { src: "/img/graines-germees.jpg", alt: "Les graines germées" },
  "lacto-fermentation": { src: "/img/lacto-fermentation.jpg", alt: "Lacto-fermentation" },
  "associations-alimentaires": { src: "/img/associations-alimentaires.jpg", alt: "Assortiment varié de fruits et légumes disposés sur une table" },
  "chrono-nutrition-naturopathique": { src: "/img/chrono-nutrition-naturopathique.jpg", alt: "Petit-déjeuner sain disposé sur une table le matin" },
  "mastication": { src: "/img/mastication.jpg", alt: "Femme croquant dans une pomme" },
  "hydratation-naturopathique": { src: "/img/hydratation-naturopathique.jpg", alt: "Mains versant de l'eau d'une bouteille dans un verre" },
  "gluten-laitages": { src: "/img/gluten-laitages.jpg", alt: "Pain de blé et de seigle" },
  "sucres-additifs-perturbateurs": { src: "/img/sucres-additifs-perturbateurs.jpg", alt: "Morceaux de sucre blanc en cubes" },
  "mind-diet-cognition": { src: "/img/mind-diet-cognition.jpg", alt: "Épinards et chou kale frais, légumes à feuilles vertes" },
  "meal-timing-circadien-metabolique": { src: "/img/meal-timing-circadien-metabolique.jpg", alt: "Horloge murale blanche indiquant l'heure" },
  "cacao-flavanols-cognition": { src: "/img/cacao-flavanols-cognition.jpg", alt: "Fèves de cacao séchées" },
  "cure-printemps": { src: "/img/cure-printemps.jpg", alt: "Pissenlits en fleur dans une prairie au printemps" },
  "cure-ete": { src: "/img/cure-ete.jpg", alt: "Pastèque tranchée, fruit rafraîchissant d'été" },
  "cure-automne": { src: "/img/cure-automne.jpg", alt: "Grappes de raisin à l'automne" },
  "cure-hiver": { src: "/img/cure-hiver.jpg", alt: "Racine de gingembre frais" },
  "luminotherapie-depression-saisonniere": { src: "/img/luminotherapie-depression-saisonniere.jpg", alt: "Lampe de luminothérapie devant une fenêtre ensoleillée" },
  "douche-ecossaise": { src: "/img/douche-ecossaise.jpg", alt: "Eau s'écoulant d'une pomme de douche" },
  "bain-chaud-detox": { src: "/img/bain-chaud-detox.jpg", alt: "Détente dans un bain chaud dans une baignoire" },
  "bains-pieds": { src: "/img/bains-pieds.jpg", alt: "Bain de pieds dans une source chaude" },
  "compresse-chaude-foie": { src: "/img/compresse-chaude-foie.jpg", alt: "Bouillotte d'eau chaude posée sur le ventre" },
  "hydrotherapie-colon": { src: "/img/hydrotherapie-colon.jpg", alt: "Salle de soin d'hydrothérapie du côlon" },
  "exposition-froid-immersion": { src: "/img/exposition-froid-immersion.jpg", alt: "Baignade en eau froide, immersion hivernale" },
  "sauna-finlandais-cardiovasculaire": { src: "/img/sauna-finlandais-cardiovasculaire.jpg", alt: "Intérieur en bois d'un sauna" },
  "huiles-essentielles-introduction": { src: "/img/huiles-essentielles-introduction.jpg", alt: "Flacons d'huiles essentielles" },
  "he-lavande-vraie": { src: "/img/he-lavande-vraie.jpg", alt: "Fleurs de lavande vraie (Lavandula angustifolia)" },
  "he-arbre-a-the": { src: "/img/he-arbre-a-the.jpg", alt: "Arbre à thé (Melaleuca alternifolia)" },
  "he-eucalyptus-radie": { src: "/img/he-eucalyptus-radie.jpg", alt: "Feuilles d'eucalyptus" },
  "he-ravintsara": { src: "/img/he-ravintsara.jpg", alt: "Feuilles de Cinnamomum camphora (ravintsara)" },
  "he-menthe-poivree": { src: "/img/he-menthe-poivree.jpg", alt: "Plant de menthe poivrée (Mentha piperita)" },
  "he-helichryse-italienne": { src: "/img/he-helichryse-italienne.jpg", alt: "Fleurs d'hélichryse italienne (immortelle)" },
  "he-niaouli": { src: "/img/he-niaouli.jpg", alt: "Niaouli (Melaleuca quinquenervia)" },
  "synergies-aromatherapeutiques": { src: "/img/synergies-aromatherapeutiques.jpg", alt: "Flacon d'huile essentielle et plante aromatique" },
  "silexan-lavande-anxiete": { src: "/img/silexan-lavande-anxiete.jpg", alt: "Bouquets de lavande" },
  "aromatherapie-post-operatoire": { src: "/img/aromatherapie-post-operatoire.jpg", alt: "Aromathérapie en post-opératoire" },
  "respiration-abdominale": { src: "/img/respiration-abdominale.jpg", alt: "La respiration abdominale" },
  "respiration-4-7-8": { src: "/img/respiration-4-7-8.jpg", alt: "La technique du 4-7-8" },
  "hygiene-sommeil": { src: "/img/hygiene-sommeil.jpg", alt: "Hygiène du sommeil" },
  "coherence-cardiaque": { src: "/img/coherence-cardiaque.jpg", alt: "Cohérence cardiaque (respiration lente)" },
  "insomnie-naturelle": { src: "/img/insomnie-naturelle.jpg", alt: "Insomnie" },
  "melatonine-naturelle": { src: "/img/melatonine-naturelle.jpg", alt: "Mélatonine naturelle" },
  "tryptophane-sommeil": { src: "/img/tryptophane-sommeil.jpg", alt: "Tryptophane et sommeil" },
  "stress-chronique-causes": { src: "/img/stress-chronique-causes.jpg", alt: "Stress chronique" },
  "meditation-pleine-conscience": { src: "/img/meditation-pleine-conscience.jpg", alt: "Méditation de pleine conscience" },
  "fleurs-de-bach": { src: "/img/fleurs-de-bach.jpg", alt: "Fleurs de Bach" },
  "ecriture-cathartique": { src: "/img/ecriture-cathartique.jpg", alt: "L'écriture cathartique" },
  "bain-foret-shinrin-yoku": { src: "/img/bain-foret-shinrin-yoku.jpg", alt: "Bain de forêt (Shinrin-Yoku)" },
  "yoga-anti-stress": { src: "/img/yoga-anti-stress.jpg", alt: "Le yoga anti-stress" },
  "acceptance-commitment-therapie-act": { src: "/img/acceptance-commitment-therapie-act.jpg", alt: "Thérapie ACT (acceptance and commitment)" },
  "ecriture-expressive-immunite": { src: "/img/ecriture-expressive-immunite.jpg", alt: "Écriture expressive" },
  "vitamine-a": { src: "/img/vitamine-a.jpg", alt: "Vitamine A" },
  "vitamine-b1": { src: "/img/vitamine-b1.jpg", alt: "Vitamine B1 (thiamine)" },
  "vitamine-b6": { src: "/img/vitamine-b6.jpg", alt: "Vitamine B6 (P5P)" },
  "vitamine-b9": { src: "/img/vitamine-b9.jpg", alt: "Vitamine B9 (méthylfolate)" },
  "vitamine-b12": { src: "/img/vitamine-b12.jpg", alt: "Vitamine B12" },
  "vitamine-c": { src: "/img/vitamine-c.jpg", alt: "Vitamine C" },
  "vitamine-d": { src: "/img/vitamine-d.jpg", alt: "Vitamine D3" },
  "vitamine-e": { src: "/img/vitamine-e.jpg", alt: "Vitamine E naturelle" },
  "vitamine-k2": { src: "/img/vitamine-k2.jpg", alt: "Vitamine K2 (MK-7)" },
  "vitamine-b2": { src: "/img/vitamine-b2.jpg", alt: "Vitamine B2 (riboflavine)" },
  "vitamine-b3": { src: "/img/vitamine-b3.jpg", alt: "Vitamine B3 (niacine)" },
  "vitamine-b5": { src: "/img/vitamine-b5.jpg", alt: "Vitamine B5 (acide pantothénique)" },
  "magnesium": { src: "/img/magnesium.jpg", alt: "Magnésium" },
  "zinc": { src: "/img/zinc.jpg", alt: "Zinc" },
  "fer": { src: "/img/fer.png", alt: "Fer" },
  "calcium": { src: "/img/calcium.jpg", alt: "Calcium" },
  "iode": { src: "/img/iode.jpg", alt: "Iode" },
  "selenium": { src: "/img/selenium.jpg", alt: "Sélénium" },
  "chrome": { src: "/img/chrome.jpg", alt: "Chrome" },
  "cuivre": { src: "/img/cuivre.jpg", alt: "Cuivre" },
  "silicium": { src: "/img/silicium.jpg", alt: "Silicium organique" },
  "manganese": { src: "/img/manganese.jpg", alt: "Manganèse" },
  "potassium": { src: "/img/potassium.jpg", alt: "Potassium" },
  "molybdene": { src: "/img/molybdene.jpg", alt: "Molybdène" },
  "lithium-oligo": { src: "/img/lithium-oligo.jpg", alt: "Lithium oligo" },
  "bore": { src: "/img/bore.jpg", alt: "Bore" },
  "omega-3-fondamentaux": { src: "/img/omega-3-fondamentaux.jpg", alt: "Oméga-3" },
  "omega-3-vegetaux": { src: "/img/omega-3-vegetaux.png", alt: "Oméga-3 végétaux" },
  "huile-cco-mct": { src: "/img/huile-cco-mct.jpg", alt: "Huile de coco et huile MCT" },
  "huiles-cuisson": { src: "/img/huiles-cuisson.jpg", alt: "Bien choisir ses huiles de cuisson" },
  "huile-perilla": { src: "/img/huile-perilla.jpg", alt: "Huile de périlla" },
  "ghee-beurre-clarifie": { src: "/img/ghee-beurre-clarifie.jpg", alt: "Le ghee" },
  "tryptophane": { src: "/img/tryptophane.jpg", alt: "Tryptophane" },
  "tyrosine": { src: "/img/tyrosine.jpg", alt: "Tyrosine" },
  "glutamine": { src: "/img/glutamine.jpg", alt: "L-glutamine" },
  "taurine": { src: "/img/taurine.jpg", alt: "Taurine" },
  "glycine": { src: "/img/glycine.jpg", alt: "Glycine" },
  "arginine-citrulline": { src: "/img/arginine-citrulline.jpg", alt: "L-arginine et L-citrulline" },
  "carnitine-acetyl": { src: "/img/carnitine-acetyl.jpg", alt: "L-carnitine et acétyl-L-carnitine" },
  "glutathion": { src: "/img/glutathion.jpg", alt: "Glutathion" },
  "coenzyme-q10-detail": { src: "/img/coenzyme-q10-detail.jpg", alt: "CoQ10 (ubiquinol)" },
  "resveratrol": { src: "/img/resveratrol.jpg", alt: "Resvératrol" },
  "astaxanthine": { src: "/img/astaxanthine.jpg", alt: "Astaxanthine" },
  "acide-alpha-lipoique": { src: "/img/acide-alpha-lipoique.jpg", alt: "Acide alpha-lipoïque (ALA)" },
  "quercetine": { src: "/img/quercetine.jpg", alt: "Quercétine" },
  "polyphenols-fruits-rouges": { src: "/img/polyphenols-fruits-rouges.jpg", alt: "Anthocyanes" },
  "microbiote-bases": { src: "/img/microbiote-bases.jpg", alt: "Kit d'analyse du microbiote intestinal" },
  "probiotiques-multi-souches": { src: "/img/probiotiques-multi-souches.jpg", alt: "Bactéries probiotiques Lactobacillus acidophilus au microscope" },
  "prebiotiques-fibres": { src: "/img/prebiotiques-fibres.jpg", alt: "Poireaux, légumes riches en fibres prébiotiques" },
  "perméabilité-intestinale": { src: "/img/perméabilité-intestinale.png", alt: "Anatomie de l'intestin grêle" },
  "candidose-intestinale": { src: "/img/candidose-intestinale.jpg", alt: "Levures de Candida albicans au microscope" },
  "plantes-adaptogenes-introduction": { src: "/img/plantes-adaptogenes-introduction.jpg", alt: "Racines de plante adaptogène séchées" },
  "ashwagandha": { src: "/img/ashwagandha.jpg", alt: "Plante d'ashwagandha (Withania somnifera)" },
  "rhodiole-rhodiola": { src: "/img/rhodiole-rhodiola.jpg", alt: "Rhodiole (Rhodiola rosea) en fleur" },
  "schisandra": { src: "/img/schisandra.jpg", alt: "Baies de schisandra (Schisandra chinensis)" },
  "cordyceps-maitake-champignons": { src: "/img/cordyceps-maitake-champignons.jpg", alt: "Champignon médicinal reishi (Ganoderma lucidum)" },
  "complements-fatigue-chronique": { src: "/img/complements-fatigue-chronique.jpg", alt: "Femme fatiguée devant son ordinateur" },
  "complements-anxiete": { src: "/img/complements-anxiete.jpg", alt: "Femme anxieuse, mains sur le visage près d'une fenêtre" },
  "complements-sommeil": { src: "/img/complements-sommeil.jpg", alt: "Chambre avec lit propice au sommeil" },
  "complements-immunite": { src: "/img/complements-immunite.jpg", alt: "Échinacée pourpre, plante immunostimulante" },
  "complements-articulations": { src: "/img/complements-articulations.jpg", alt: "Complément pour les articulations" },
  "complements-thyroide": { src: "/img/complements-thyroide.jpg", alt: "Glande thyroïde dans le cou" },
  "complements-peau": { src: "/img/complements-peau.jpg", alt: "Aloe vera, plante pour la peau" },
  "complements-sport": { src: "/img/complements-sport.jpg", alt: "Athlète en course à pied sur la piste" },
  "complements-cognition": { src: "/img/complements-cognition.jpg", alt: "Illustration du cerveau humain" },
  "complements-cardio": { src: "/img/complements-cardio.jpg", alt: "Capsules d'oméga-3 (huile de poisson)" },
  "cure-equinoxe-printemps": { src: "/img/cure-equinoxe-printemps.jpg", alt: "Floraison printanière" },
  "cure-equinoxe-automne": { src: "/img/cure-equinoxe-automne.jpg", alt: "Feuilles d'automne en forêt" },
  "transition-saisons-emonctoires": { src: "/img/transition-saisons-emonctoires.png", alt: "Un arbre à travers les quatre saisons" },
  "cure-printemps-foie-21j": { src: "/img/cure-printemps-foie-21j.jpg", alt: "Pissenlit (Taraxacum officinale), plante détox du foie" },
  "cure-automne-reins-poumons": { src: "/img/cure-automne-reins-poumons.png", alt: "Schéma du système respiratoire" },
  "preparation-hiver-immunite": { src: "/img/preparation-hiver-immunite.jpg", alt: "Orange, source de vitamine C" },
  "emonctoires-foie-vesicule": { src: "/img/emonctoires-foie-vesicule.jpg", alt: "Foie et vésicule biliaire" },
  "emonctoires-reins-eau": { src: "/img/emonctoires-reins-eau.jpg", alt: "Modèle anatomique du rein" },
  "emonctoires-intestins-elimination": { src: "/img/emonctoires-intestins-elimination.jpg", alt: "Anatomie du côlon et du gros intestin" },
  "emonctoires-peau-sudation": { src: "/img/emonctoires-peau-sudation.jpg", alt: "Sudation sur la peau" },
  "emonctoires-poumons-bronches": { src: "/img/emonctoires-poumons-bronches.png", alt: "Poumons humains et bronches" },
  "rotation-emonctoires-protocole": { src: "/img/rotation-emonctoires-protocole.jpg", alt: "Tisane détox en tasse" },
  "rituel-sommeil-90-minutes": { src: "/img/rituel-sommeil-90-minutes.jpg", alt: "Lecture apaisante avant le coucher" },
  "lumiere-bleue-melatonine": { src: "/img/lumiere-bleue-melatonine.jpg", alt: "Utilisation du smartphone la nuit" },
  "temperature-chambre-sommeil-profond": { src: "/img/temperature-chambre-sommeil-profond.jpg", alt: "Chambre à coucher cosy" },
  "respiration-coherente-quotidien": { src: "/img/respiration-coherente-quotidien.jpg", alt: "Respiration et méditation au calme" },
  "cortisol-rythme-circadien": { src: "/img/cortisol-rythme-circadien.jpg", alt: "Lever de soleil et rythme circadien" },
  "burn-out-phases-naturopathie": { src: "/img/burn-out-phases-naturopathie.jpg", alt: "Épuisement et stress" },
  "gratitude-pratique-quotidienne": { src: "/img/gratitude-pratique-quotidienne.jpg", alt: "Journal de gratitude" },
  "nature-walking-shinrin-yoku": { src: "/img/nature-walking-shinrin-yoku.jpg", alt: "Marche en forêt" },
  "petit-dejeuner-proteine": { src: "/img/petit-dejeuner-proteine.jpg", alt: "Petit-déjeuner protéiné aux œufs et avocat" },
  "cuisson-douce-vitalite": { src: "/img/cuisson-douce-vitalite.jpg", alt: "Cuisson vapeur des légumes" },
  "masticer-30-fois": { src: "/img/masticer-30-fois.jpg", alt: "Mastication d'un fruit" },
  "eau-citronnee-matin": { src: "/img/eau-citronnee-matin.jpg", alt: "Verre d'eau citronnée" },
  "syndrome-metabolique-nutritherapie": { src: "/img/syndrome-metabolique-nutritherapie.jpg", alt: "Mesure du tour de taille" },
  "fibromyalgie-protocole-curtay": { src: "/img/fibromyalgie-protocole-curtay.png", alt: "Douleur chronique à l'épaule" },
  "migraine-mg-b2-coq10": { src: "/img/migraine-mg-b2-coq10.jpg", alt: "Migraine et maux de tête" },
  "sii-fodmap-glutamine": { src: "/img/sii-fodmap-glutamine.jpg", alt: "Douleurs abdominales" },
  "thyroidite-hashimoto-selenium": { src: "/img/thyroidite-hashimoto-selenium.jpg", alt: "Noix du Brésil, source de sélénium" },
  "menopause-phytoestrogenes": { src: "/img/menopause-phytoestrogenes.jpg", alt: "Soja, source de phyto-œstrogènes" },
  "arthrose-curcuma-collagene": { src: "/img/arthrose-curcuma-collagene.jpg", alt: "Racines de curcuma" },
  "depression-tryptophane-omega3": { src: "/img/depression-tryptophane-omega3.jpg", alt: "Saumon riche en oméga-3" },
  "insomnie-melatonine-magnesium": { src: "/img/insomnie-melatonine-magnesium.jpg", alt: "Réveil lumineux la nuit (insomnie)" },
  "stress-oxydatif-glutathion": { src: "/img/stress-oxydatif-glutathion.jpg", alt: "Légumes colorés antioxydants" },
  "mitochondries-energie-cellulaire": { src: "/img/mitochondries-energie-cellulaire.jpg", alt: "Mitochondries, énergie cellulaire (microscopie)" },
  "methylation-b9-b12-mthfr": { src: "/img/methylation-b9-b12-mthfr.jpg", alt: "Épinards, source de folates" },
  "vitamine-d-supplementation-hiver": { src: "/img/vitamine-d-supplementation-hiver.jpg", alt: "Comprimés de vitamine D" },
  "b9-folates-alimentation-moderne": { src: "/img/b9-folates-alimentation-moderne.jpg", alt: "Légumes verts à feuilles, riches en folates" },
  "b12-vegetariens-supplementation": { src: "/img/b12-vegetariens-supplementation.jpg", alt: "Œufs de saumon, source de vitamine B12" },
  "vitamine-k2-mk7-os-coeur": { src: "/img/vitamine-k2-mk7-os-coeur.jpg", alt: "Natto, source de vitamine K2" },
  "magnesium-bisglycinate-forme": { src: "/img/magnesium-bisglycinate-forme.jpg", alt: "Complément de magnésium glycinate" },
  "zinc-immunite-fertilite": { src: "/img/zinc-immunite-fertilite.jpg", alt: "Graines de courge, source de zinc" },
  "fer-bisglycinate-anemie": { src: "/img/fer-bisglycinate-anemie.jpg", alt: "Fer bisglycinate" },
  "iode-thyroide-france": { src: "/img/iode-thyroide-france.jpg", alt: "Iode et thyroïde" },
  "omega-3-epa-dha-ratio": { src: "/img/omega-3-epa-dha-ratio.jpg", alt: "Oméga-3 EPA/DHA" },
  "omega-6-omega-3-desequilibre": { src: "/img/omega-6-omega-3-desequilibre.jpg", alt: "Le déséquilibre oméga-6/oméga-3 dans l'alimentation moderne" },
  "microbiote-lagarde-cellulaire": { src: "/img/microbiote-lagarde-cellulaire.jpg", alt: "Microbiote et nutrithérapie cellulaire (approche Lagarde)" },
  "fatigue-chronique-curtay-mitochondrie": { src: "/img/fatigue-chronique-curtay-mitochondrie.jpg", alt: "Fatigue chronique" },
  "cure-thermale-tradition": { src: "/img/cure-thermale-tradition.jpg", alt: "Les cures thermales" },
  "douche-soleil-vivifiante": { src: "/img/douche-soleil-vivifiante.jpg", alt: "La douche du soleil vivifiante (méthode Kneipp)" },
  "enveloppement-froid-priessnitz": { src: "/img/enveloppement-froid-priessnitz.jpg", alt: "L'enveloppement froid de Priessnitz" },
  "cataplasme-argile-applications": { src: "/img/cataplasme-argile-applications.jpg", alt: "Le cataplasme d'argile verte" },
  "roll-on-anti-stress-formules": { src: "/img/roll-on-anti-stress-formules.jpg", alt: "Roll-on anti-stress" },
  "diffusion-bureau-concentration": { src: "/img/diffusion-bureau-concentration.jpg", alt: "Diffusion au bureau" },
  "olfactotherapie-base": { src: "/img/olfactotherapie-base.jpg", alt: "L'olfactothérapie" },
  "huile-massage-jambes-lourdes": { src: "/img/huile-massage-jambes-lourdes.png", alt: "Huile de massage maison pour jambes lourdes" },
  "gemmotherapie-bases": { src: "/img/gemmotherapie-bases.jpg", alt: "La gemmothérapie" },
  "teintures-meres-fabrication": { src: "/img/teintures-meres-fabrication.jpg", alt: "Fabriquer ses teintures-mères à la maison" },
  "cure-bourgeon-cassis-printemps": { src: "/img/cure-bourgeon-cassis-printemps.jpg", alt: "La cure bourgeon de cassis au printemps" },
  "desmodium-foie-renaissance": { src: "/img/desmodium-foie-renaissance.jpg", alt: "Desmodium adscendens" },
  "vitamine-d-mortalite-toute-cause": { src: "/img/vitamine-d-mortalite-toute-cause.jpg", alt: "Vitamine D et mortalité toute cause" },
  "b12-cognition-personne-agee": { src: "/img/b12-cognition-personne-agee.jpg", alt: "Vitamine B12 et cognition de la personne âgée" },
  "vitamine-k2-mk7-osteoporose": { src: "/img/vitamine-k2-mk7-osteoporose.jpg", alt: "Vitamine K2 (MK-7) et os" },
  "magnesium-syndrome-metabolique": { src: "/img/magnesium-syndrome-metabolique.jpg", alt: "Magnésium et syndrome métabolique" },
  "zinc-fertilite-masculine": { src: "/img/zinc-fertilite-masculine.jpg", alt: "Zinc et fertilité masculine" },
  "selenium-cancer-prevention-update": { src: "/img/selenium-cancer-prevention-update.jpg", alt: "Sélénium et prévention du cancer" },
  "safran-depression-meta-2024": { src: "/img/safran-depression-meta-2024.jpg", alt: "Safran et dépression" },
  "curcuma-arthrose-genou-update": { src: "/img/curcuma-arthrose-genou-update.jpg", alt: "Curcuma et arthrose du genou" },
  "rhodiole-fatigue-recente": { src: "/img/rhodiole-fatigue-recente.jpg", alt: "Rhodiola rosea et fatigue" },
  "probiotiques-eczema-enfant": { src: "/img/probiotiques-eczema-enfant.jpg", alt: "Probiotiques et eczéma de l'enfant" },
  "mediterraneen-mortalite-cohorte": { src: "/img/mediterraneen-mortalite-cohorte.jpg", alt: "Régime méditerranéen et mortalité" },
  "jeune-intermittent-poids-mortalite": { src: "/img/jeune-intermittent-poids-mortalite.jpg", alt: "Jeûne intermittent" },
  "vitamine-c-non-toxicite-limites": { src: "/img/vitamine-c-non-toxicite-limites.jpg", alt: "Vitamine C" },
  "vitamine-d-supplementation-infections-respiratoires": { src: "/img/vitamine-d-supplementation-infections-respiratoires.jpg", alt: "Vitamine D" },
  "vitamine-b12-vegetariens-deficit": { src: "/img/vitamine-b12-vegetariens-deficit.jpg", alt: "Vitamine B12" },
  "folates-methylfolate-depression": { src: "/img/folates-methylfolate-depression.jpg", alt: "L-méthylfolate (B9 active)" },
  "vitamine-k2-arteres-os": { src: "/img/vitamine-k2-arteres-os.jpg", alt: "Vitamine K2" },
  "magnesium-formes-biodisponibilite": { src: "/img/magnesium-formes-biodisponibilite.jpg", alt: "Magnésium" },
  "zinc-immunite-infections-respiratoires": { src: "/img/zinc-immunite-infections-respiratoires.jpg", alt: "Zinc et immunité" },
  "fer-bisglycinate-vs-sulfate": { src: "/img/fer-bisglycinate-vs-sulfate.jpg", alt: "Fer" },
  "iode-thyroide-carence": { src: "/img/iode-thyroide-carence.jpg", alt: "Iode et thyroïde" },
  "selenium-hashimoto-thyroidite": { src: "/img/selenium-hashimoto-thyroidite.jpg", alt: "Sélénium et thyroïdite de Hashimoto" },
  "ashwagandha-stress-cortisol": { src: "/img/ashwagandha-stress-cortisol.jpg", alt: "Ashwagandha et stress" },
  "rhodiole-fatigue-performance-mentale": { src: "/img/rhodiole-fatigue-performance-mentale.jpg", alt: "Rhodiola rosea" },
  "curcuma-piperine-biodisponibilite": { src: "/img/curcuma-piperine-biodisponibilite.jpg", alt: "Curcuma" },
  "ginseng-fatigue-meta-analyses": { src: "/img/ginseng-fatigue-meta-analyses.jpg", alt: "Ginseng et fatigue" },
  "cordyceps-performance-sportive": { src: "/img/cordyceps-performance-sportive.jpg", alt: "Cordyceps militaris" },
  "probiotiques-axe-intestin-cerveau": { src: "/img/probiotiques-axe-intestin-cerveau.jpg", alt: "Axe intestin-cerveau" },
  "omega-3-epa-dha-cardiovasculaire": { src: "/img/omega-3-epa-dha-cardiovasculaire.jpg", alt: "Oméga-3 EPA/DHA" },
  "jeune-intermittent-autophagie-metabolisme": { src: "/img/jeune-intermittent-autophagie-metabolisme.jpg", alt: "Jeûne intermittent" },
  "polyphenols-regime-mediterraneen-cardiovasculaire": { src: "/img/polyphenols-regime-mediterraneen-cardiovasculaire.jpg", alt: "Polyphénols et santé cardiovasculaire" },
  "fibres-prebiotiques-acides-gras-chaine-courte": { src: "/img/fibres-prebiotiques-acides-gras-chaine-courte.jpg", alt: "Fibres prébiotiques et acides gras à chaîne courte" },
  "vitamine-a-toxicite-retinol": { src: "/img/vitamine-a-toxicite-retinol.jpg", alt: "Vitamine A" },
  "vitamine-e-alpha-gamma-tocopherol": { src: "/img/vitamine-e-alpha-gamma-tocopherol.jpg", alt: "Vitamine E" },
  "vitamine-b6-neuropathie-dose-elevee": { src: "/img/vitamine-b6-neuropathie-dose-elevee.jpg", alt: "Vitamine B6" },
  "niacine-vitamine-b3-flush-lipides": { src: "/img/niacine-vitamine-b3-flush-lipides.jpg", alt: "Niacine (vitamine B3)" },
  "thiamine-wernicke-alcool": { src: "/img/thiamine-wernicke-alcool.jpg", alt: "Thiamine (B1) et encéphalopathie de Wernicke" },
  "calcium-supplementation-cardiovasculaire-controverse": { src: "/img/calcium-supplementation-cardiovasculaire-controverse.jpg", alt: "Calcium en supplément" },
  "potassium-tension-arterielle-meta-analyses": { src: "/img/potassium-tension-arterielle-meta-analyses.jpg", alt: "Potassium et tension" },
  "manganese-neurotoxicite-exposition": { src: "/img/manganese-neurotoxicite-exposition.jpg", alt: "Manganèse" },
  "cuivre-zinc-equilibre-ratio": { src: "/img/cuivre-zinc-equilibre-ratio.jpg", alt: "Zinc et cuivre" },
  "chrome-picolinate-diabete-type-2": { src: "/img/chrome-picolinate-diabete-type-2.jpg", alt: "Chrome picolinate dans le diabète de type 2" },
  "reishi-ganoderma-immunite-cancer": { src: "/img/reishi-ganoderma-immunite-cancer.jpg", alt: "Reishi (Ganoderma lucidum)" },
  "maca-lepidium-meyenii-fonction-sexuelle": { src: "/img/maca-lepidium-meyenii-fonction-sexuelle.png", alt: "Maca (Lepidium meyenii)" },
  "astragale-membranaceus-immunite": { src: "/img/astragale-membranaceus-immunite.png", alt: "Astragale (Astragalus membranaceus)" },
  "bacopa-monnieri-memoire-cognition": { src: "/img/bacopa-monnieri-memoire-cognition.jpg", alt: "Bacopa monnieri" },
  "ginkgo-biloba-cognition-dementia": { src: "/img/ginkgo-biloba-cognition-dementia.jpg", alt: "Ginkgo biloba" },
  "probiotiques-prevention-diarrhee-antibiotiques": { src: "/img/probiotiques-prevention-diarrhee-antibiotiques.jpg", alt: "Probiotiques et antibiothérapie" },
  "resveratrol-sirtuines-vieillissement": { src: "/img/resveratrol-sirtuines-vieillissement.jpg", alt: "Resvératrol et sirtuines" },
  "coq10-myopathie-statines": { src: "/img/coq10-myopathie-statines.jpg", alt: "Coenzyme Q10 et myopathie sous statines" },
  "nmn-nad-anti-vieillissement": { src: "/img/nmn-nad-anti-vieillissement.jpg", alt: "NMN et NAD+" },
  "valeriane-sommeil": { src: "/img/valeriane-sommeil.jpg", alt: "Valériane" },
  "passiflore-sommeil": { src: "/img/passiflore-sommeil.jpg", alt: "Passiflore" },
  "melisse-sommeil": { src: "/img/melisse-sommeil.jpg", alt: "Mélisse" },
  "tilleul-sommeil": { src: "/img/tilleul-sommeil.jpg", alt: "Tilleul" },
  "aubepine-sommeil": { src: "/img/aubepine-sommeil.jpg", alt: "Aubépine" },
  "ashwagandha-stress": { src: "/img/ashwagandha-stress.jpg", alt: "Ashwagandha" },
  "rhodiole-stress": { src: "/img/rhodiole-stress.jpg", alt: "Rhodiole" },
  "basilic-sacre-stress": { src: "/img/basilic-sacre-stress.jpg", alt: "Basilic sacré (Tulsi)" },
  "eschscholtzia-stress": { src: "/img/eschscholtzia-stress.jpg", alt: "Eschscholtzia (pavot de Californie)" },
  "artichaut-digestion": { src: "/img/artichaut-digestion.jpg", alt: "Artichaut" },
  "chardon-marie-digestion": { src: "/img/chardon-marie-digestion.jpg", alt: "Chardon-Marie" },
  "romarin-digestion": { src: "/img/romarin-digestion.jpg", alt: "Romarin" },
  "gentiane-digestion": { src: "/img/gentiane-digestion.jpg", alt: "Gentiane jaune" },
  "fenouil-digestion": { src: "/img/fenouil-digestion.jpg", alt: "Fenouil" },
  "menthe-poivree-digestion": { src: "/img/menthe-poivree-digestion.jpg", alt: "Menthe poivrée" },
  "echinacee-immunite": { src: "/img/echinacee-immunite.jpg", alt: "Échinacée pourpre" },
  "thym-immunite": { src: "/img/thym-immunite.jpg", alt: "Thym commun" },
  "sureau-noir-immunite": { src: "/img/sureau-noir-immunite.jpg", alt: "Sureau noir" },
  "propolis-immunite": { src: "/img/propolis-immunite.jpg", alt: "Propolis" },
  "cypres-immunite": { src: "/img/cypres-immunite.jpg", alt: "Cyprès toujours vert" },
  "aubepine-circulation": { src: "/img/aubepine-circulation.jpg", alt: "Aubépine" },
  "vigne-rouge-circulation": { src: "/img/vigne-rouge-circulation.jpg", alt: "Vigne rouge" },
  "hamamelis-circulation": { src: "/img/hamamelis-circulation.jpg", alt: "Hamamélis" },
  "marronnier-inde-circulation": { src: "/img/marronnier-inde-circulation.jpg", alt: "Marronnier d'Inde" },
  "ginkgo-biloba-circulation": { src: "/img/ginkgo-biloba-circulation.jpg", alt: "Ginkgo biloba" },
  "eucalyptus-respiration": { src: "/img/eucalyptus-respiration.jpg", alt: "Eucalyptus" },
  "plantain-lanceole-respiration": { src: "/img/plantain-lanceole-respiration.jpg", alt: "Plantain lancéolé" },
  "mauve-respiration": { src: "/img/mauve-respiration.jpg", alt: "Mauve" },
  "bourgeon-pin-respiration": { src: "/img/bourgeon-pin-respiration.jpg", alt: "Bourgeon de pin" },
  "hysope-respiration": { src: "/img/hysope-respiration.jpg", alt: "Hysope" },
  "ortie-articulations": { src: "/img/ortie-articulations.jpg", alt: "Ortie" },
  "prele-silicium": { src: "/img/prele-silicium.jpg", alt: "Prêle des champs" },
  "harpagophytum-griffe-diable": { src: "/img/harpagophytum-griffe-diable.jpg", alt: "Harpagophytum" },
  "curcuma-peau-articulations": { src: "/img/curcuma-peau-articulations.jpg", alt: "Curcuma" },
  "bardane-peau": { src: "/img/bardane-peau.jpg", alt: "Bardane" },
  "calendula-peau": { src: "/img/calendula-peau.jpg", alt: "Calendula (souci)" },
  "achillee-millefeuille-feminin": { src: "/img/achillee-millefeuille-feminin.jpg", alt: "Achillée millefeuille" },
  "gattilier-vitex-feminin": { src: "/img/gattilier-vitex-feminin.jpg", alt: "Gattilier" },
  "alchemille-feminin": { src: "/img/alchemille-feminin.jpg", alt: "Alchémille" },
  "sauge-officinale-menopause": { src: "/img/sauge-officinale-menopause.jpg", alt: "Sauge officinale" },
  "framboisier-feuilles-feminin": { src: "/img/framboisier-feuilles-feminin.jpg", alt: "Framboisier (feuilles)" },
  "verveine-officinale-sommeil": { src: "/img/verveine-officinale-sommeil.jpg", alt: "Verveine officinale" },
  "coquelicot-sommeil": { src: "/img/coquelicot-sommeil.jpg", alt: "Coquelicot" },
  "houblon-sommeil": { src: "/img/houblon-sommeil.jpg", alt: "Houblon" },
  "oranger-fleurs-sommeil": { src: "/img/oranger-fleurs-sommeil.jpg", alt: "Fleurs d'oranger" },
  "pissenlit-digestion": { src: "/img/pissenlit-digestion.jpg", alt: "Pissenlit" },
  "boldo-digestion": { src: "/img/boldo-digestion.jpg", alt: "Boldo" },
  "radis-noir-digestion": { src: "/img/radis-noir-digestion.jpg", alt: "Radis noir" },
  "angelique-digestion": { src: "/img/angelique-digestion.jpg", alt: "Angélique" },
  "griffonia-stress": { src: "/img/griffonia-stress.jpg", alt: "Griffonia simplicifolia" },
  "safran-stress": { src: "/img/safran-stress.jpg", alt: "Safran" },
  "magnolia-stress": { src: "/img/magnolia-stress.jpg", alt: "Magnolia officinalis" },
  "pavot-de-californie-stress": { src: "/img/pavot-de-californie-stress.jpg", alt: "Pavot de Californie (Eschscholtzia)" },
  "pelargonium-immunite": { src: "/img/pelargonium-immunite.jpg", alt: "Pélargonium" },
  "sureau-noir-immunite-batch2": { src: "/img/sureau-noir-immunite-batch2.jpg", alt: "Sureau noir baies" },
  "astragale-immunite-batch2": { src: "/img/astragale-immunite-batch2.jpg", alt: "Astragale" },
  "olivier-circulation": { src: "/img/olivier-circulation.jpg", alt: "Olivier feuilles" },
  "fragon-petit-houx-circulation": { src: "/img/fragon-petit-houx-circulation.jpg", alt: "Petit houx (fragon)" },
  "mélilot-circulation": { src: "/img/mélilot-circulation.jpg", alt: "Mélilot" },
  "lierre-grimpant-respiration": { src: "/img/lierre-grimpant-respiration.jpg", alt: "Lierre grimpant" },
  "erysimum-respiration": { src: "/img/erysimum-respiration.jpg", alt: "Érysimum" },
  "pin-sylvestre-respiration": { src: "/img/pin-sylvestre-respiration.jpg", alt: "Pin sylvestre" },
  "vigne-rouge-feminin": { src: "/img/vigne-rouge-feminin.jpg", alt: "Vigne rouge feuilles" },
  "gattilier-feminin-batch2": { src: "/img/gattilier-feminin-batch2.jpg", alt: "Gattilier" },
  "actée-à-grappes-feminin": { src: "/img/actée-à-grappes-feminin.jpg", alt: "Actée à grappes" },
  "jus-carotte-pur-walker": { src: "/img/jus-carotte-pur-walker.jpg", alt: "Jus de carotte pur — jus frais" },
  "jus-carotte-celeri-walker": { src: "/img/jus-carotte-celeri-walker.jpg", alt: "Carotte + céleri — jus frais" },
  "jus-carotte-epinards-walker": { src: "/img/jus-carotte-epinards-walker.jpg", alt: "Carotte + épinards — jus frais" },
  "jus-carotte-betterave-concombre-walker": { src: "/img/jus-carotte-betterave-concombre-walker.jpg", alt: "Carotte + betterave + concombre — jus frais" },
  "jus-celeri-pur-walker": { src: "/img/jus-celeri-pur-walker.jpg", alt: "Jus de céleri-branche pur — jus frais" },
  "jus-carotte-persil-walker": { src: "/img/jus-carotte-persil-walker.jpg", alt: "Carotte + persil — jus frais" },
  "jus-epinards-celeri-persil-carotte-walker": { src: "/img/jus-epinards-celeri-persil-carotte-walker.jpg", alt: "Épinards + céleri + persil + carotte — jus frais" },
  "jus-chou-cru-walker": { src: "/img/jus-chou-cru-walker.jpg", alt: "Jus de chou cru — jus frais" },
  "jus-vert-detox-printemps": { src: "/img/jus-vert-detox-printemps.jpg", alt: "Jus vert de printemps — jus frais" },
  "jus-pissenlit-pomme-citron": { src: "/img/jus-pissenlit-pomme-citron.jpg", alt: "Pissenlit + pomme + citron — jus frais" },
  "jus-betterave-carotte-gingembre": { src: "/img/jus-betterave-carotte-gingembre.jpg", alt: "Betterave + carotte + gingembre — jus frais" },
  "jus-citron-curcuma-matin": { src: "/img/jus-citron-curcuma-matin.jpg", alt: "Eau citronnée au curcuma — jus frais" },
  "jus-persil-celeri-concombre": { src: "/img/jus-persil-celeri-concombre.jpg", alt: "Persil + céleri + concombre — jus frais" },
  "jus-radis-noir-pomme-citron": { src: "/img/jus-radis-noir-pomme-citron.jpg", alt: "Radis noir + pomme + citron — jus frais" },
  "jus-chou-kale-pomme-citron": { src: "/img/jus-chou-kale-pomme-citron.jpg", alt: "Kale + pomme + citron — jus frais" },
  "jus-gingembre-pomme-citron-matin": { src: "/img/jus-gingembre-pomme-citron-matin.jpg", alt: "Gingembre + pomme + citron — jus frais" },
  "jus-betterave-orange-gingembre-sport": { src: "/img/jus-betterave-orange-gingembre-sport.jpg", alt: "Betterave + orange + gingembre — jus frais" },
  "jus-carotte-orange-citron-booster": { src: "/img/jus-carotte-orange-citron-booster.jpg", alt: "Carotte + orange + citron — jus frais" },
  "jus-green-energy-pomme-epinards-celeri": { src: "/img/jus-green-energy-pomme-epinards-celeri.jpg", alt: "Green energy — jus frais" },
  "jus-betterave-pomme-carotte-endurance": { src: "/img/jus-betterave-pomme-carotte-endurance.jpg", alt: "Betterave + pomme + carotte — jus frais" },
  "jus-ananas-menthe-gingembre": { src: "/img/jus-ananas-menthe-gingembre.jpg", alt: "Ananas + menthe + gingembre — jus frais" },
  "jus-orange-citron-curcuma-poivre": { src: "/img/jus-orange-citron-curcuma-poivre.jpg", alt: "Orange + citron + curcuma + poivre — jus frais" },
  "shot-gingembre-curcuma-citron": { src: "/img/shot-gingembre-curcuma-citron.jpg", alt: "Shot gingembre + curcuma + citron — jus frais" },
  "jus-agrumes-orange-pamplemousse-citron": { src: "/img/jus-agrumes-orange-pamplemousse-citron.jpg", alt: "Orange + pamplemousse + citron — jus frais" },
  "jus-carotte-orange-citron-gingembre-hiver": { src: "/img/jus-carotte-orange-citron-gingembre-hiver.jpg", alt: "Carotte + orange + citron + gingembre — jus frais" },
  "jus-pomme-cannelle-clou-girofle-hiver": { src: "/img/jus-pomme-cannelle-clou-girofle-hiver.jpg", alt: "Pomme tiède + cannelle + clou de girofle — jus frais" },
  "shot-ail-citron-miel-prevention": { src: "/img/shot-ail-citron-miel-prevention.jpg", alt: "Shot ail + citron + miel — jus frais" },
  "jus-betterave-grenade-gingembre": { src: "/img/jus-betterave-grenade-gingembre.jpg", alt: "Betterave + grenade + gingembre — jus frais" },
  "jus-chou-pomme-citron-walker-inspired": { src: "/img/jus-chou-pomme-citron-walker-inspired.jpg", alt: "Chou cru + pomme + citron — jus frais" },
  "jus-chou-cru-pomme-walker": { src: "/img/jus-chou-cru-pomme-walker.jpg", alt: "Jus de chou cru et pomme — jus frais" },
  "jus-carotte-fenouil-gingembre": { src: "/img/jus-carotte-fenouil-gingembre.jpg", alt: "Jus carotte, fenouil et gingembre — jus frais" },
  "jus-aloe-citron-pomme": { src: "/img/jus-aloe-citron-pomme.png", alt: "Jus aloe vera, citron et pomme — jus frais" },
  "jus-papaye-ananas-menthe": { src: "/img/jus-papaye-ananas-menthe.jpg", alt: "Jus papaye, ananas et menthe — jus frais" },
  "jus-carotte-gingembre-curcuma": { src: "/img/jus-carotte-gingembre-curcuma.jpg", alt: "Jus carotte, gingembre et curcuma — jus frais" },
  "jus-pomme-celeri-fenouil": { src: "/img/jus-pomme-celeri-fenouil.jpg", alt: "Jus pomme, céleri-branche et fenouil — jus frais" },
  "jus-carotte-concombre-pomme": { src: "/img/jus-carotte-concombre-pomme.jpg", alt: "Jus carotte, concombre et pomme — jus frais" },
  "jus-betterave-carotte-orange": { src: "/img/jus-betterave-carotte-orange.jpg", alt: "Jus betterave, carotte et orange — jus frais" },
  "jus-concombre-pomme-menthe": { src: "/img/jus-concombre-pomme-menthe.jpg", alt: "Jus concombre, pomme verte et menthe — jus frais" },
  "jus-ortie-pomme-version-douce": { src: "/img/jus-ortie-pomme-version-douce.jpg", alt: "Jus d'ortie fraîche et pomme — jus frais" },
  "jus-celeri-epinards-pomme": { src: "/img/jus-celeri-epinards-pomme.jpg", alt: "Jus céleri, épinards et pomme — jus frais" },
  "jus-persil-carotte-pomme": { src: "/img/jus-persil-carotte-pomme.jpg", alt: "Jus persil, carotte et pomme — jus frais" },
  "jus-concombre-celeri-citron-menthe": { src: "/img/jus-concombre-celeri-citron-menthe.jpg", alt: "Jus concombre, céleri, citron et menthe — jus frais" },
  "jus-pomme-verte-epinards-citron": { src: "/img/jus-pomme-verte-epinards-citron.jpg", alt: "Jus pomme verte, épinards et citron — jus frais" },
  "jus-pamplemousse-citron-menthe": { src: "/img/jus-pamplemousse-citron-menthe.jpg", alt: "Jus pamplemousse, citron et menthe — jus frais" },
  "jus-kale-concombre-pomme-citron": { src: "/img/jus-kale-concombre-pomme-citron.jpg", alt: "Jus chou kale, concombre, pomme et citron — jus frais" },
  "jus-ananas-celeri-gingembre-minceur": { src: "/img/jus-ananas-celeri-gingembre-minceur.jpg", alt: "Jus ananas, céleri et gingembre — jus frais" },
  "jus-carotte-pomme-celeri-citron": { src: "/img/jus-carotte-pomme-celeri-citron.jpg", alt: "Jus carotte, pomme, céleri et citron — jus frais" },
  "jus-betterave-pre-effort": { src: "/img/jus-betterave-pre-effort.jpg", alt: "Jus de betterave pré-effort — jus frais" },
  "jus-cerises-griottes-post-effort": { src: "/img/jus-cerises-griottes-post-effort.jpg", alt: "Jus de cerises griottes — jus frais" },
  "jus-pasteque-recuperation": { src: "/img/jus-pasteque-recuperation.jpg", alt: "Jus de pastèque — jus frais" },
  "jus-orange-curcuma-poivre": { src: "/img/jus-orange-curcuma-poivre.jpg", alt: "Jus orange, curcuma et poivre noir — jus frais" },
  "smoothie-banane-epinards-amande-post-effort": { src: "/img/smoothie-banane-epinards-amande-post-effort.jpg", alt: "Smoothie banane, épinards et amande post-effort — jus frais" },
  "jus-ananas-celeri-gingembre-recuperation": { src: "/img/jus-ananas-celeri-gingembre-recuperation.jpg", alt: "Jus ananas, céleri et gingembre — jus frais" },
  "jus-carotte-betterave-gingembre-pre-seance": { src: "/img/jus-carotte-betterave-gingembre-pre-seance.jpg", alt: "Jus carotte, betterave et gingembre — jus frais" },
  "jus-carotte-betterave-walker": { src: "/img/jus-carotte-betterave-walker.jpg", alt: "Jus carotte-betterave — jus frais" },
  "jus-concombre-betterave-walker": { src: "/img/jus-concombre-betterave-walker.jpg", alt: "Jus concombre-betterave — jus frais" },
  "jus-carotte-laitue-alfalfa-walker": { src: "/img/jus-carotte-laitue-alfalfa-walker.jpg", alt: "Jus carotte-laitue-luzerne — jus frais" },
  "jus-celeri-persil-walker": { src: "/img/jus-celeri-persil-walker.jpg", alt: "Jus céleri-persil — jus frais" },
  "jus-pomme-celeri-walker": { src: "/img/jus-pomme-celeri-walker.jpg", alt: "Jus pomme-céleri — jus frais" },
  "jus-printemps-pissenlit-pomme": { src: "/img/jus-printemps-pissenlit-pomme.jpg", alt: "Jus de printemps pissenlit-pomme — jus frais" },
  "jus-ete-pasteque-menthe-citron": { src: "/img/jus-ete-pasteque-menthe-citron.jpg", alt: "Jus d'été pastèque-menthe-citron — jus frais" },
  "jus-automne-pomme-cannelle-betterave": { src: "/img/jus-automne-pomme-cannelle-betterave.jpg", alt: "Jus d'automne pomme-cannelle-betterave — jus frais" },
  "jus-hiver-orange-curcuma-gingembre": { src: "/img/jus-hiver-orange-curcuma-gingembre.jpg", alt: "Jus d'hiver orange-curcuma-gingembre — jus frais" },
  "jus-equinoxe-vert-cresson": { src: "/img/jus-equinoxe-vert-cresson.jpg", alt: "Jus vert d'équinoxe au cresson — jus frais" },
  "protocole-jus-21-jours": { src: "/img/protocole-jus-21-jours.jpg", alt: "Protocole 21 jours — jus frais" },
  "jus-monodiete-raisin-rentree": { src: "/img/jus-monodiete-raisin-rentree.jpg", alt: "Monodiète raisin de rentrée — jus frais" },
  "jus-bouillon-legumes-soir": { src: "/img/jus-bouillon-legumes-soir.jpg", alt: "Bouillon de légumes du soir — jus frais" },
  "jus-acerola-camu-camu-shot": { src: "/img/jus-acerola-camu-camu-shot.jpg", alt: "Shot acérola-camu camu vitamine C — jus frais" },
  "jus-spiruline-citron-sport": { src: "/img/jus-spiruline-citron-sport.jpg", alt: "Jus spiruline-citron pré-effort — jus frais" },
};

const GENERIC_FALLBACK = "/img/jeune-hydrique.jpg";

/**
 * Récupère la photo d'un article. Priorité : slug → catégorie → générique.
 */
export function getArticleImage(slug: string, category: string): PhotoMeta {
  if (ARTICLE_PHOTOS[slug]) return ARTICLE_PHOTOS[slug];
  if (CATEGORY_PHOTOS[category]) return CATEGORY_PHOTOS[category];
  const cat = CATEGORIES.find((c) => c.slug === category);
  return {
    src: GENERIC_FALLBACK,
    alt: cat ? `${cat.nom} — alimentation et bien-être` : 'Naturopathie et nutrithérapie',
  };
}

/** URL d'image Open Graph pour partage social. */
export function getArticleOgImage(slug: string, category: string): string {
  const params = new URLSearchParams({ cat: category, slug });
  return `/api/og?${params.toString()}`;
}
