import type { Micronutriment } from './types';

export const MICRONUTRIMENTS: Micronutriment[] = [
  {
    slug: 'vitamine-d3',
    nom: 'Vitamine D3 (cholécalciférol)',
    categorie: 'vitamine',
    formes_recommandees: ['cholécalciférol végétal (lichen) ou animal (lanoline)', 'huileuse pour absorption optimale'],
    formes_a_eviter: ['ergocalciférol (D2) — moins bioactif'],
    ajr_officiel: '200 UI/jour (largement insuffisant en pratique)',
    dosage_optimal: "2 000 à 5 000 UI/jour selon profil, en cure d'hiver minimum, à prendre le soir au repas",
    roles: [
      'Hormone (synthèse, transcription génique)',
      'Immunité innée et adaptative',
      'Modulation inflammation',
      'Métabolisme phosphocalcique',
      'Neuroprotection, humeur',
      'Régulation pression artérielle',
    ],
    signes_carence: [
      'Fatigue chronique inexpliquée',
      'Infections ORL à répétition',
      'Douleurs musculaires diffuses',
      'Tendance dépressive saisonnière',
      'Fragilité osseuse',
      'Troubles du sommeil',
    ],
    sources_alimentaires: [
      'Poissons gras sauvages (sardine, maquereau, hareng)',
      "Jaunes d'œufs de poules élevées au soleil",
      'Foie de morue (huile)',
      'Exposition solaire (15-30 min/jour, bras et jambes, été)',
    ],
    interactions: ['Magnésium (cofacteur d\'activation)', 'Vitamine K2 (orientation du calcium)'],
    contre_indications: ['Hypercalcémie', 'Sarcoïdose', 'Lithiase oxalique'],
    temperaments_prioritaires: ['lymphatique', 'nerveux'],
    note:
      "La prise du soir améliore la conversion hépatique en 25-OH-D. Le dosage sanguin (25-OH-D) doit viser 50-70 ng/mL, bien au-dessus du seuil officiel de 30 ng/mL.",
  },
  {
    slug: 'magnesium',
    nom: 'Magnésium',
    categorie: 'mineral',
    formes_recommandees: ['glycérophosphate de magnésium', 'bisglycinate', 'malate', 'taurate'],
    formes_a_eviter: ["oxyde de magnésium (taux d'absorption < 5%, effet laxatif)", 'chlorure (acidifiant)', 'sulfate'],
    ajr_officiel: '375 mg/jour',
    dosage_optimal: '400 à 600 mg/jour de magnésium-élément, en 2 prises, associé à B6 (P5P)',
    roles: [
      'Cofacteur de 300+ enzymes',
      'Production ATP (énergie cellulaire)',
      'Transmission neuromusculaire',
      'Régulation stress, anti-anxiolytique',
      'Synthèse ADN et protéines',
      'Régulation glycémie et tension',
    ],
    signes_carence: [
      'Crampes, tétanie, spasmes paupière',
      'Anxiété, stress chronique, irritabilité',
      'Insomnies, sommeil non réparateur',
      'Fatigue inexpliquée',
      'Maux de tête, migraines',
      'Constipation ou diarrhée selon forme',
    ],
    sources_alimentaires: [
      'Algues (varech, dulse, nori)',
      'Cacao cru (100g = 500 mg)',
      'Graines de courge, tournesol, sésame',
      'Amandes, noix du Brésil',
      'Légumes verts feuillus',
      'Sarrasin, quinoa, légumineuses',
    ],
    interactions: ['Antagoniste calcium (équilibre Ca/Mg essentiel)', 'B6 indispensable pour absorption cellulaire', 'Vit D pour absorption intestinale'],
    contre_indications: ['Insuffisance rénale sévère'],
    temperaments_prioritaires: ['nerveux', 'bilieux', 'sanguin'],
    note:
      "Le glycérophosphate est la forme la plus biodisponible et neutre digestivement. Association obligatoire avec B6 sous forme P5P pour entrée intracellulaire.",
  },
  {
    slug: 'vitamine-b12',
    nom: 'Vitamine B12 (méthylcobalamine)',
    categorie: 'vitamine',
    formes_recommandees: ['méthylcobalamine (forme active)', 'adénosylcobalamine'],
    formes_a_eviter: ['cyanocobalamine (synthétique, libère du cyanure)', 'hydroxocobalamine (synthétique)'],
    ajr_officiel: '2,5 µg/jour',
    dosage_optimal: '500 à 1 000 µg/jour sublingual pour végétariens, vegans, > 60 ans, troubles digestifs',
    roles: [
      'Synthèse de la myéline (gaine des nerfs)',
      'Synthèse ADN, division cellulaire',
      'Cycle de méthylation',
      'Hématopoïèse (globules rouges)',
      'Métabolisme homocystéine',
    ],
    signes_carence: ['Fatigue chronique sévère', 'Anémie macrocytaire', 'Fourmillements extrémités', 'Troubles cognitifs, mémoire', 'Glossite', 'Dépression'],
    sources_alimentaires: ['Foie, abats', 'Œufs', 'Poissons (sardine, hareng)', 'Crustacés', 'Aucune source végétale fiable (spiruline = analogue inactif)'],
    interactions: ['B9 (méthylfolate) — partenaire de méthylation', 'IPP, metformine = pillage'],
    temperaments_prioritaires: ['nerveux', 'lymphatique'],
    note:
      "La cyanocobalamine est à proscrire absolument : elle libère du cyanure que l'organisme doit détoxifier, et son utilisation cellulaire est moins efficace que la méthylcobalamine.",
  },
  {
    slug: 'omega-3',
    nom: 'Oméga-3 EPA/DHA',
    categorie: 'acide_gras',
    formes_recommandees: ['huile de poisson certifiée IFOS (5 étoiles)', "huile d'algue (Schizochytrium) — option végétale", 'forme triglycérides naturels (TG) supérieure aux esters éthyliques'],
    ajr_officiel: '250 mg EPA+DHA/jour',
    dosage_optimal: '1 000 à 2 000 mg EPA+DHA/jour, à toujours associer à un antioxydant (Vit E naturelle)',
    roles: [
      'Constituant majeur des membranes neuronales (DHA)',
      'Anti-inflammatoire (EPA → résolvines)',
      'Fluidification sanguine',
      'Soutien cardiovasculaire',
      'Développement et maintien cerveau',
    ],
    signes_carence: ['Peau sèche, eczéma', 'Troubles de concentration', 'Humeur dépressive', 'Inflammation chronique', 'Cheveux ternes, ongles cassants'],
    sources_alimentaires: ['Sardines, anchois, hareng, maquereau', 'Saumon sauvage', 'Huile de lin, cameline, chanvre (ALA)', 'Graines de chia, lin, noix', 'Œufs Bleu-Blanc-Cœur'],
    interactions: ['Vitamine E (protection contre oxydation)'],
    contre_indications: ['Hémophilie', 'Trouble de la coagulation', 'Avant chirurgie (arrêt 7 jours)'],
    temperaments_prioritaires: ['sanguin', 'nerveux', 'bilieux'],
    note:
      "Ne jamais prendre d'oméga-3 sans antioxydants (vitamine E naturelle). Les AGPI sont oxydables, et leur supplémentation isolée peut être contre-productive.",
  },
  {
    slug: 'vitamine-e',
    nom: 'Vitamine E (tocophérols)',
    categorie: 'vitamine',
    formes_recommandees: ['mélange naturel RRR-d-alpha + gamma + delta tocophérols', 'forme "tocophérols mixtes" naturels'],
    formes_a_eviter: ['dl-alpha-tocophérol synthétique', 'alpha-tocophérol seul à haute dose'],
    ajr_officiel: '12 mg/jour',
    dosage_optimal: '15 à 30 mg/jour de mélange naturel, à associer aux oméga-3',
    roles: ['Antioxydant majeur des membranes (lipophile)', 'Protection des AGPI contre peroxydation', 'Modulation immunitaire', 'Anti-inflammatoire', 'Fonction vasculaire'],
    signes_carence: ['Fragilité capillaire', 'Anémie hémolytique', 'Troubles neuromusculaires', 'Vieillissement cutané accéléré'],
    sources_alimentaires: ['Huile de germe de blé', 'Huile de tournesol non raffinée', 'Amandes, noisettes', 'Graines de tournesol', 'Avocat'],
    interactions: ['Sélénium (cofacteur glutathion peroxydase)', 'Vitamine C (régénération de E oxydée)', 'Anticoagulants — risque hémorragique'],
    contre_indications: ['Avant chirurgie', 'Anticoagulothérapie'],
    temperaments_prioritaires: ['sanguin', 'bilieux'],
    note:
      "Seule la vitamine E naturelle (RRR-d-alpha-tocophérol et mélange) est utile. La forme synthétique (dl-alpha) est non seulement inactive mais déséquilibre les ratios naturels.",
  },
  {
    slug: 'zinc',
    nom: 'Zinc',
    categorie: 'mineral',
    formes_recommandees: ['citrate de zinc', 'bisglycinate', 'gluconate', 'picolinate'],
    formes_a_eviter: ['sulfate (irritant gastrique)', 'oxyde (peu absorbé)'],
    ajr_officiel: '10 mg/jour',
    dosage_optimal: '15 à 30 mg/jour selon profil, à distance du fer et du calcium',
    roles: ['Cofacteur de 300+ enzymes', 'Immunité (lymphocytes, thymus)', 'Cicatrisation, peau, muqueuses', 'Synthèse protéique', 'Métabolisme hormonal', 'Antioxydant (SOD)'],
    signes_carence: ['Infections à répétition', 'Cicatrisation lente', 'Acné, problèmes cutanés', 'Perte de cheveux', 'Trouble du goût, de l\'odorat', 'Baisse de libido'],
    sources_alimentaires: ['Huîtres (top source, 60 mg/100g)', 'Foie, viandes rouges', 'Graines de courge', 'Lentilles, pois chiches', 'Cacao cru'],
    interactions: ['Antagoniste cuivre (équilibre Zn/Cu)', 'Phytates des céréales = blocage absorption'],
    contre_indications: ['Hémochromatose'],
    temperaments_prioritaires: ['bilieux', 'lymphatique', 'nerveux'],
    note: "Le ratio Zn/Cu est crucial. Une supplémentation prolongée en zinc seul peut induire une carence en cuivre. Privilégier les périodes de 2 à 3 mois puis pause.",
  },
  {
    slug: 'selenium',
    nom: 'Sélénium',
    categorie: 'mineral',
    formes_recommandees: ['sélénométhionine (forme organique)', 'levure enrichie en sélénium'],
    formes_a_eviter: ['sélénite, sélénate (formes inorganiques)'],
    ajr_officiel: '70 µg/jour',
    dosage_optimal: '100 à 200 µg/jour de sélénométhionine',
    roles: ['Cofacteur glutathion peroxydase', 'Détoxification métaux lourds', 'Conversion T4 → T3 thyroïdienne', 'Protection cardiovasculaire', 'Modulation immunitaire'],
    signes_carence: ['Faiblesse musculaire', 'Troubles thyroïdiens (T3 basse)', 'Vieillissement prématuré', 'Susceptibilité aux infections virales'],
    sources_alimentaires: ['Noix du Brésil (1-2 noix = AJR)', 'Poissons', 'Œufs', 'Champignons'],
    interactions: ['Vit E (synergie antioxydante)', 'Iode (thyroïde)'],
    contre_indications: ['Marge thérapeutique étroite — ne pas dépasser 400 µg/jour'],
    temperaments_prioritaires: ['bilieux', 'lymphatique'],
    note: "Fenêtre thérapeutique étroite. À forte dose chronique (>400µg), peut devenir prooxydant. Alternative naturelle : 1 à 2 noix du Brésil/jour.",
  },
  {
    slug: 'vitamine-c',
    nom: 'Vitamine C',
    categorie: 'vitamine',
    formes_recommandees: ['acérola (forme alimentaire + bioflavonoïdes)', 'ascorbate de magnésium ou de potassium'],
    formes_a_eviter: ['acide ascorbique seul à très forte dose (acidifiant)'],
    ajr_officiel: '110 mg/jour',
    dosage_optimal: "500 à 1 000 mg/jour répartis en 2-3 prises, jusqu'à 2-3 g en cas d'infection",
    roles: ['Antioxydant hydrosoluble majeur', 'Synthèse du collagène', 'Absorption du fer non héminique', 'Immunité (phagocytose)', 'Synthèse neurotransmetteurs', 'Régénération de la vit E'],
    signes_carence: ['Fatigue, baisse de moral', 'Saignements gencives', 'Bleus faciles', 'Cicatrisation lente', 'Susceptibilité aux infections'],
    sources_alimentaires: ['Acérola (1500 mg/100g)', 'Camu-camu, baies de goji fraîches', 'Cassis, kiwi, agrumes', 'Poivron rouge cru', 'Persil, ciboulette frais', 'Brocoli, chou-fleur crus'],
    interactions: ['Synergie avec bioflavonoïdes', 'Régénère vit E oxydée'],
    contre_indications: ['Calculs oxaliques (à très forte dose)'],
    temperaments_prioritaires: ['sanguin', 'bilieux', 'lymphatique'],
    note: "Préférer l'acérola ou l'ascorbate à l'acide ascorbique pur. Répartir les prises dans la journée.",
  },
  {
    slug: 'iode',
    nom: 'Iode',
    categorie: 'mineral',
    formes_recommandees: ['iodure de potassium', 'algues naturelles (varech, dulse, kombu)'],
    formes_a_eviter: ['iode élémentaire pur (toxique)'],
    ajr_officiel: '150 µg/jour',
    dosage_optimal: '150 à 300 µg/jour selon dosage TSH/T3/T4 — bilan thyroïdien préalable indispensable',
    roles: ['Synthèse hormones thyroïdiennes', 'Métabolisme basal', 'Développement cérébral fœtal', 'Drainage tissulaire et lymphatique'],
    signes_carence: ['Hypothyroïdie', 'Goitre', 'Troubles cognitifs', 'Sein fibrokystique'],
    sources_alimentaires: ['Algues (varech, kombu)', 'Poissons et fruits de mer', 'Sel marin non raffiné', 'Œufs'],
    contre_indications: ['Hyperthyroïdie (Basedow)', 'Hashimoto en poussée', 'Thyroïdite — toujours bilan préalable'],
    temperaments_prioritaires: ['lymphatique'],
    note: "Toujours un bilan TSH + T3 + T4 + anticorps avant supplémentation. La consommation régulière modérée d'algues couvre les besoins.",
  },
  {
    slug: 'vitamine-b6',
    nom: 'Vitamine B6 (P5P)',
    categorie: 'vitamine',
    formes_recommandees: ['Pyridoxal-5-Phosphate (P5P)'],
    formes_a_eviter: ['pyridoxine seule à très forte dose chronique'],
    ajr_officiel: '1,4 mg/jour',
    dosage_optimal: '25 à 50 mg de P5P/jour, à associer au magnésium',
    roles: ['Cofacteur de 100+ enzymes', 'Synthèse neurotransmetteurs (sérotonine, GABA, dopamine)', 'Entrée du magnésium intracellulaire', 'Métabolisme protéique', 'Métabolisme homocystéine', 'Synthèse hémoglobine'],
    signes_carence: ['Anxiété, irritabilité', 'Dépression', 'Anémie microcytaire', 'Glossite', 'Crampes'],
    sources_alimentaires: ['Foie, abats', 'Saumon, thon', 'Pois chiches, lentilles', 'Pommes de terre', 'Banane', 'Avocat'],
    interactions: ['Magnésium (entrée intracellulaire)', 'B9, B12 (méthylation)'],
    temperaments_prioritaires: ['nerveux', 'bilieux'],
    note: "La P5P est la forme directement active. La pyridoxine doit être convertie hépatiquement, étape souvent défaillante. Indissociable du magnésium.",
  },
  {
    slug: 'coenzyme-q10',
    nom: 'Coenzyme Q10',
    categorie: 'antioxydant',
    formes_recommandees: ['ubiquinol (forme réduite, active)', 'ubiquinone + huile pour absorption'],
    dosage_optimal: '100 à 300 mg/jour d\'ubiquinol, surtout après 40 ans et sous statines',
    roles: ['Cofacteur de la chaîne respiratoire mitochondriale', 'Antioxydant lipophile', 'Régénération de la vit E', 'Protection cardiovasculaire'],
    signes_carence: ['Fatigue chronique inexpliquée', 'Faiblesse musculaire', 'Insuffisance cardiaque', 'Sous statines : myalgies'],
    sources_alimentaires: ['Cœur de bœuf, foie', 'Poissons gras', 'Huile de soja, colza', 'Cacahuètes'],
    interactions: ['Statines (les statines bloquent la synthèse — supplémentation systématique recommandée)'],
    temperaments_prioritaires: ['sanguin', 'lymphatique'],
    note: "Toute prescription de statines devrait être accompagnée de CoQ10 (300 mg/jour). L'ubiquinol est 4x plus biodisponible que l'ubiquinone après 50 ans.",
  },
  {
    slug: 'methylfolate',
    nom: 'Vitamine B9 (méthylfolate)',
    categorie: 'vitamine',
    formes_recommandees: ['5-MTHF (L-méthylfolate)', 'folate naturel des aliments'],
    formes_a_eviter: ['acide folique synthétique (problématique chez les MTHFR mutés)'],
    ajr_officiel: '300 µg/jour (500 µg en grossesse)',
    dosage_optimal: '400 à 800 µg/jour de 5-MTHF',
    roles: ['Cycle de méthylation (avec B12)', 'Synthèse ADN, division cellulaire', 'Métabolisme homocystéine', 'Développement neural embryonnaire', 'Hématopoïèse'],
    signes_carence: ['Anémie macrocytaire', 'Hyperhomocystéinémie', 'Spina-bifida fœtal', 'Glossite', "Trouble de l'humeur"],
    sources_alimentaires: ['Foie, abats', 'Légumes verts feuillus crus', 'Légumineuses', 'Asperges, brocoli', 'Levure de bière'],
    interactions: ['B12 (méthylation indissociable)', 'B6'],
    temperaments_prioritaires: ['nerveux', 'bilieux'],
    note: "30 à 50% de la population porte une mutation MTHFR qui réduit la conversion d'acide folique en forme active. Le 5-MTHF actif s'impose.",
  },
  {
    slug: 'curcuma',
    nom: 'Curcumine (extrait de curcuma)',
    categorie: 'antioxydant',
    formes_recommandees: ['avec pipérine (poivre noir) — biodisponibilité x20', 'phospholipidique (Meriva)', 'micellaire'],
    formes_a_eviter: ['curcuma en poudre seul (biodisponibilité < 1%)'],
    dosage_optimal: '500 à 1 500 mg/jour de curcuminoïdes standardisés à 95%',
    roles: ['Anti-inflammatoire systémique majeur', 'Antioxydant', 'Hépatoprotection', 'Modulation NF-kB', 'Effets neuroprotecteurs'],
    signes_carence: ['Non essentiel — usage thérapeutique'],
    sources_alimentaires: ['Racine de curcuma fraîche', 'Poudre de curcuma (avec poivre + matière grasse)'],
    contre_indications: ['Calculs biliaires', 'Anticoagulothérapie', 'Avant chirurgie'],
    temperaments_prioritaires: ['bilieux', 'lymphatique', 'sanguin'],
    note: "L'absorption du curcuma natif est ridicule. Pipérine ou formulation lipidique indispensable.",
  },
  {
    slug: 'vitamine-k2',
    nom: 'Vitamine K2 (MK-7)',
    categorie: 'vitamine',
    formes_recommandees: ['MK-7 trans-isomère (natto, fermentations)'],
    formes_a_eviter: ['MK-4 synthétique seule à haute dose'],
    dosage_optimal: '90 à 200 µg/jour de MK-7',
    roles: ['Orientation du calcium vers les os', "Activation de l'ostéocalcine", 'Activation de la MGP (prévention calcifications vasculaires)', 'Synergie majeure avec vit D3'],
    signes_carence: ['Ostéoporose', 'Calcifications vasculaires', 'Caries dentaires'],
    sources_alimentaires: ['Natto (top source, 1000 µg/100g)', 'Fromages affinés', 'Jaune d\'œuf de poules au pâturage', "Foie d'oie"],
    interactions: ['Vit D3 (synergie indispensable)', 'Anticoagulants AVK — contre-indication'],
    contre_indications: ['Sous AVK (warfarine, etc.)'],
    temperaments_prioritaires: ['sanguin', 'lymphatique'],
    note: "La vit D3 sans K2 augmente l'absorption calcique mais peut favoriser les calcifications vasculaires. La supplémentation D3 + K2 est devenue standard.",
  },
  {
    slug: 'probiotiques',
    nom: 'Probiotiques (multi-souches)',
    categorie: 'probiotique',
    formes_recommandees: ['multi-souches Lactobacillus + Bifidobacterium', 'gélules gastro-résistantes', 'minimum 10 milliards UFC'],
    formes_a_eviter: ['mono-souches systématiques', 'sans étude clinique'],
    dosage_optimal: '10 à 50 milliards UFC/jour, en cure de 2-3 mois',
    roles: ['Équilibre du microbiote intestinal', 'Immunité (70% est intestinale)', 'Synthèse de vitamines (K, B12, B9)', 'Modulation axe intestin-cerveau', 'Barrière intestinale'],
    signes_carence: ['Troubles digestifs chroniques', 'Infections récidivantes', 'Mycoses récidivantes', 'Hyperperméabilité intestinale', 'Post-antibiothérapie'],
    sources_alimentaires: ['Choucroute crue lacto-fermentée', 'Kimchi', 'Kéfir (de fruits ou de lait)', 'Kombucha', 'Miso non pasteurisé', 'Yaourt artisanal'],
    temperaments_prioritaires: ['lymphatique', 'nerveux'],
    note: "La diversité du microbiote prime sur les souches isolées. Les aliments lacto-fermentés quotidiens restent la meilleure source.",
  },
];

export function getMicronutriment(slug: string): Micronutriment | undefined {
  return MICRONUTRIMENTS.find((m) => m.slug === slug);
}
