import type { Micronutriment, RegleCurtay } from './types';

export const MICRONUTRIMENTS: Micronutriment[] = [
  {
    slug: 'vitamine-d3',
    nom: 'Vitamine D3 (cholécalciférol)',
    categorie: 'vitamine',
    formes_recommandees: ['cholécalciférol végétal (lichen) ou animal (lanoline)', 'huileuse pour absorption optimale'],
    formes_a_eviter: ['ergocalciférol (D2) — moins bioactif'],
    ajr_officiel: '200 UI/jour (largement insuffisant selon Curtay)',
    dosage_curtay: '2 000 à 5 000 UI/jour selon profil, en cure d\'hiver minimum, à PRENDRE LE SOIR au repas',
    roles: [
      'Hormone (synthèse, transcription génique)',
      'Immunité innée et adaptative',
      'Modulation inflammation',
      'Métabolisme phosphocalcique',
      'Neuroprotection, humeur',
      'Régulation pression artérielle',
    ],
    signes_carence: [
      'Fatigue chronique inexpliquée',
      'Infections ORL à répétition',
      'Douleurs musculaires diffuses',
      'Tendance dépressive saisonnière',
      'Fragilité osseuse',
      'Troubles du sommeil',
    ],
    sources_alimentaires: [
      'Poissons gras sauvages (sardine, maquereau, hareng)',
      'Jaunes d\'œufs de poules élevées au soleil',
      'Foie de morue (huile)',
      'Exposition solaire (15-30 min/jour, bras et jambes, été)',
    ],
    interactions: ['Magnésium (cofacteur d\'activation)', 'Vitamine K2 (orientation du calcium)'],
    contre_indications: ['Hypercalcémie', 'Sarcoïdose', 'Lithiase oxalique'],
    temperaments_prioritaires: ['lymphatique', 'nerveux'],
    note_curtay:
      "Curtay a démontré que la prise du soir améliore la conversion hépatique en 25-OH-D. Le dosage sanguin (25-OH-D) doit viser 50-70 ng/mL, bien au-dessus du seuil officiel de 30 ng/mL.",
  },
  {
    slug: 'magnesium',
    nom: 'Magnésium',
    categorie: 'mineral',
    formes_recommandees: ['glycérophosphate de magnésium', 'bisglycinate', 'malate', 'taurate'],
    formes_a_eviter: [
      'oxyde de magnésium (taux d\'absorption < 5%, effet laxatif)',
      'chlorure (acidifiant)',
      'sulfate',
    ],
    ajr_officiel: '375 mg/jour (souvent insuffisant selon Curtay)',
    dosage_curtay: '400 à 600 mg/jour de magnésium-élément, en 2 prises, associé à B6 (P5P) pour entrée intracellulaire',
    roles: [
      'Cofacteur de 300+ enzymes',
      'Production ATP (énergie cellulaire)',
      'Transmission neuromusculaire',
      'Régulation stress, anti-anxiolytique',
      'Synthèse ADN et protéines',
      'Régulation glycémie et tension',
    ],
    signes_carence: [
      'Crampes, tétanie, spasmes paupière',
      'Anxiété, stress chronique, irritabilité',
      'Insomnies, sommeil non réparateur',
      'Fatigue inexpliquée',
      'Maux de tête, migraines',
      'Constipation ou diarrhée selon forme',
    ],
    sources_alimentaires: [
      'Algues (varech, dulse, nori) — top source',
      'Cacao cru (100g = 500 mg)',
      'Graines de courge, tournesol, sésame',
      'Amandes, noix du Brésil',
      'Légumes verts feuillus (épinards, blettes)',
      'Sarrasin, quinoa, légumineuses',
    ],
    interactions: [
      'Antagoniste calcium (équilibre Ca/Mg essentiel)',
      'B6 indispensable pour absorption cellulaire',
      'Vit D pour absorption intestinale',
    ],
    contre_indications: ['Insuffisance rénale sévère'],
    temperaments_prioritaires: ['nerveux', 'bilieux', 'sanguin'],
    note_curtay:
      "Le glycérophosphate est la forme retenue par Curtay pour sa biodisponibilité, son absence d'effet laxatif et sa neutralité gastrique. Association obligatoire avec B6 sous forme P5P pour entrée intracellulaire.",
  },
  {
    slug: 'vitamine-b12',
    nom: 'Vitamine B12 (méthylcobalamine)',
    categorie: 'vitamine',
    formes_recommandees: ['méthylcobalamine (forme active)', 'adénosylcobalamine'],
    formes_a_eviter: ['cyanocobalamine (synthétique, libère du cyanure)', 'hydroxocobalamine (synthétique)'],
    ajr_officiel: '2,5 µg/jour',
    dosage_curtay: '500 à 1 000 µg/jour sublingual pour végétariens, vegans, > 60 ans, troubles digestifs',
    roles: [
      'Synthèse de la myéline (gaine des nerfs)',
      'Synthèse ADN, division cellulaire',
      'Cycle de méthylation',
      'Hématopoïèse (globules rouges)',
      'Métabolisme homocystéine',
    ],
    signes_carence: [
      'Fatigue chronique sévère',
      'Anémie macrocytaire',
      'Fourmillements extrémités',
      'Troubles cognitifs, mémoire',
      'Glossite (langue inflammée)',
      'Dépression',
    ],
    sources_alimentaires: [
      'Foie, abats (top source)',
      'Œufs',
      'Poissons (sardine, hareng)',
      'Crustacés',
      'Aucune source végétale fiable (spiruline = analogue inactif)',
    ],
    interactions: ['B9 (méthylfolate) — partenaire de méthylation', 'IPP, metformine = pillage'],
    temperaments_prioritaires: ['nerveux', 'lymphatique'],
    note_curtay:
      "Curtay insiste : la cyanocobalamine est à proscrire absolument. Elle libère du cyanure que l'organisme doit détoxifier, et son utilisation par les cellules est moins efficace que la méthylcobalamine, forme directement active.",
  },
  {
    slug: 'omega-3',
    nom: 'Oméga-3 EPA/DHA',
    categorie: 'acide_gras',
    formes_recommandees: [
      'huile de poisson certifiée IFOS (5 étoiles)',
      'huile d\'algue (Schizochytrium) — option végétale',
      'forme triglycérides naturels (TG) supérieure aux esters éthyliques',
    ],
    ajr_officiel: '250 mg EPA+DHA/jour',
    dosage_curtay: '1 000 à 2 000 mg EPA+DHA/jour, à toujours associer à un antioxydant (Vit E naturelle)',
    roles: [
      'Constituant majeur des membranes neuronales (DHA)',
      'Anti-inflammatoire (EPA → résolvines)',
      'Fluidification sanguine',
      'Soutien cardiovasculaire',
      'Développement et maintien cerveau',
    ],
    signes_carence: [
      'Peau sèche, eczéma',
      'Troubles de concentration',
      'Humeur dépressive',
      'Inflammation chronique',
      'Cheveux ternes, ongles cassants',
    ],
    sources_alimentaires: [
      'Sardines, anchois, hareng, maquereau (petits poissons gras)',
      'Saumon sauvage',
      'Huile de lin, cameline, chanvre (ALA — précurseur)',
      'Graines de chia, lin, noix',
      'Œufs Bleu-Blanc-Cœur',
    ],
    interactions: ['Vitamine E (protection contre oxydation — JAMAIS oméga-3 seuls)'],
    contre_indications: ['Hémophilie', 'Trouble de la coagulation', 'Avant chirurgie (arrêt 7 jours)'],
    temperaments_prioritaires: ['sanguin', 'nerveux', 'bilieux'],
    note_curtay:
      "Règle d'or Curtay n°7 : ne jamais prendre d'oméga-3 sans antioxydants (vitamine E naturelle). Les AGPI sont oxydables, et leur supplémentation isolée peut être contre-productive. Curtay recommande aussi de PRIVILÉGIER les petits poissons gras à la supplémentation pour la qualité nutritionnelle globale.",
  },
  {
    slug: 'vitamine-e',
    nom: 'Vitamine E (tocophérols)',
    categorie: 'vitamine',
    formes_recommandees: [
      'mélange naturel RRR-d-alpha + gamma + delta tocophérols',
      'forme "tocophérols mixtes" naturels',
    ],
    formes_a_eviter: [
      'dl-alpha-tocophérol synthétique (CONTRE-PRODUCTIF selon Curtay)',
      'alpha-tocophérol seul à haute dose (déséquilibre les gamma)',
    ],
    ajr_officiel: '12 mg/jour',
    dosage_curtay: '15 à 30 mg/jour de mélange naturel, à associer aux oméga-3',
    roles: [
      'Antioxydant majeur des membranes (lipophile)',
      'Protection des AGPI contre peroxydation',
      'Modulation immunitaire',
      'Anti-inflammatoire',
      'Fonction vasculaire',
    ],
    signes_carence: [
      'Fragilité capillaire',
      'Anémie hémolytique',
      'Troubles neuromusculaires',
      'Vieillissement cutané accéléré',
    ],
    sources_alimentaires: [
      'Huile de germe de blé (top source)',
      'Huile de tournesol non raffinée',
      'Amandes, noisettes',
      'Graines de tournesol',
      'Avocat',
    ],
    interactions: [
      'Sélénium (cofacteur glutathion peroxydase)',
      'Vitamine C (régénération de E oxydée)',
      'Anticoagulants — risque hémorragique',
    ],
    contre_indications: ['Avant chirurgie', 'Anticoagulothérapie'],
    temperaments_prioritaires: ['sanguin', 'bilieux'],
    note_curtay:
      "Règle d'or Curtay n°6 : seule la vitamine E NATURELLE (RRR-d-alpha-tocophérol et mélange) est utile. La forme synthétique (dl-alpha) est non seulement inactive mais déséquilibre les ratios naturels. Une supplémentation isolée en alpha-tocophérol fait baisser le gamma-tocophérol qui est protecteur cardiovasculaire.",
  },
  {
    slug: 'zinc',
    nom: 'Zinc',
    categorie: 'mineral',
    formes_recommandees: ['citrate de zinc', 'bisglycinate', 'gluconate', 'picolinate'],
    formes_a_eviter: ['sulfate (irritant gastrique)', 'oxyde (peu absorbé)'],
    ajr_officiel: '10 mg/jour',
    dosage_curtay: '15 à 30 mg/jour selon profil, à distance du fer et du calcium',
    roles: [
      'Cofacteur de 300+ enzymes',
      'Immunité (lymphocytes, thymus)',
      'Cicatrisation, peau, muqueuses',
      'Synthèse protéique',
      'Métabolisme hormonal (testostérone, thyroïde)',
      'Antioxydant (SOD)',
    ],
    signes_carence: [
      'Infections à répétition',
      'Cicatrisation lente',
      'Acné, problèmes cutanés',
      'Perte de cheveux',
      'Trouble du goût, de l\'odorat',
      'Baisse de libido',
    ],
    sources_alimentaires: [
      'Huîtres (top source, 60 mg/100g)',
      'Foie, viandes rouges',
      'Graines de courge',
      'Lentilles, pois chiches',
      'Cacao cru',
    ],
    interactions: ['Antagoniste cuivre (équilibre Zn/Cu)', 'Phytates des céréales = blocage absorption'],
    contre_indications: ['Hémochromatose'],
    temperaments_prioritaires: ['bilieux', 'lymphatique', 'nerveux'],
    note_curtay:
      "Le ratio Zn/Cu est crucial selon Curtay. Une supplémentation prolongée en zinc seul peut induire une carence en cuivre. Privilégier les périodes de 2 à 3 mois puis pause.",
  },
  {
    slug: 'selenium',
    nom: 'Sélénium',
    categorie: 'mineral',
    formes_recommandees: ['sélénométhionine (forme organique, mieux assimilée)', 'levure enrichie en sélénium'],
    formes_a_eviter: ['sélénite, sélénate (formes inorganiques, marge thérapeutique étroite)'],
    ajr_officiel: '70 µg/jour',
    dosage_curtay: '100 à 200 µg/jour de sélénométhionine, en cure',
    roles: [
      'Cofacteur glutathion peroxydase (antioxydant majeur)',
      'Détoxification métaux lourds',
      'Conversion T4 → T3 thyroïdienne',
      'Protection cardiovasculaire',
      'Modulation immunitaire',
    ],
    signes_carence: [
      'Faiblesse musculaire',
      'Troubles thyroïdiens (T3 basse)',
      'Vieillissement prématuré',
      'Susceptibilité aux infections virales',
    ],
    sources_alimentaires: [
      'Noix du Brésil (1-2 noix = AJR)',
      'Poissons (sardine, thon)',
      'Œufs',
      'Champignons',
    ],
    interactions: ['Vit E (synergie antioxydante)', 'Iode (thyroïde)'],
    contre_indications: ['Marge thérapeutique étroite — ne pas dépasser 400 µg/jour'],
    temperaments_prioritaires: ['bilieux', 'lymphatique'],
    note_curtay:
      "Curtay alerte sur la fenêtre thérapeutique étroite du sélénium. À forte dose chronique (>400µg), il peut devenir prooxydant. La supplémentation par 1 à 2 noix du Brésil/jour reste une excellente alternative naturelle.",
  },
  {
    slug: 'vitamine-c',
    nom: 'Vitamine C',
    categorie: 'vitamine',
    formes_recommandees: ['acérola (forme alimentaire + bioflavonoïdes)', 'ascorbate de magnésium ou de potassium'],
    formes_a_eviter: ['acide ascorbique seul à très forte dose (acidifiant)'],
    ajr_officiel: '110 mg/jour',
    dosage_curtay: '500 à 1 000 mg/jour répartis en 2-3 prises, jusqu\'à 2-3g en cas d\'infection',
    roles: [
      'Antioxydant hydrosoluble majeur',
      'Synthèse du collagène',
      'Absorption du fer non héminique',
      'Immunité (phagocytose)',
      'Synthèse neurotransmetteurs',
      'Régénération de la vit E',
    ],
    signes_carence: [
      'Fatigue, baisse de moral',
      'Saignements gencives',
      'Bleus faciles',
      'Cicatrisation lente',
      'Susceptibilité aux infections',
    ],
    sources_alimentaires: [
      'Acérola (1500 mg/100g)',
      'Camu-camu, baies de goji fraîches',
      'Cassis, kiwi, agrumes',
      'Poivron rouge cru',
      'Persil, ciboulette frais',
      'Brocoli, chou-fleur crus',
    ],
    interactions: ['Synergie avec bioflavonoïdes', 'Régénère vit E oxydée'],
    contre_indications: ['Calculs oxaliques (à très forte dose)'],
    temperaments_prioritaires: ['sanguin', 'bilieux', 'lymphatique'],
    note_curtay:
      "Préférer l'acérola ou l'ascorbate au lieu de l'acide ascorbique pur. Répartir les prises dans la journée car non stockée. En cas d'infection, monter à 3g/jour est utile (test de tolérance digestive).",
  },
  {
    slug: 'iode',
    nom: 'Iode',
    categorie: 'mineral',
    formes_recommandees: ['iodure de potassium', 'algues naturelles (varech, dulse, kombu)'],
    formes_a_eviter: ['iode élémentaire pur (toxique)'],
    ajr_officiel: '150 µg/jour',
    dosage_curtay: '150 à 300 µg/jour selon dosage TSH/T3/T4 — bilan thyroïdien préalable indispensable',
    roles: [
      'Synthèse hormones thyroïdiennes (T3, T4)',
      'Métabolisme basal',
      'Développement cérébral fœtal',
      'Drainage tissulaire et lymphatique',
    ],
    signes_carence: [
      'Hypothyroïdie (fatigue, prise de poids, frilosité)',
      'Goitre',
      'Troubles cognitifs',
      'Sein fibrokystique',
    ],
    sources_alimentaires: [
      'Algues (varech, kombu — très concentrées)',
      'Poissons et fruits de mer',
      'Sel marin non raffiné',
      'Œufs',
    ],
    contre_indications: [
      'Hyperthyroïdie (Basedow)',
      'Hashimoto en poussée — prudence',
      'Thyroïdite — toujours bilan préalable',
    ],
    temperaments_prioritaires: ['lymphatique'],
    note_curtay:
      "L'iode est l'un des micronutriments les plus mal connus. Carence et excès sont délétères pour la thyroïde — TOUJOURS un bilan TSH + T3 + T4 + anticorps avant supplémentation. La consommation régulière modérée d'algues (1g de dulse séchée 2-3x/semaine) couvre les besoins.",
  },
  {
    slug: 'vitamine-b6',
    nom: 'Vitamine B6 (P5P)',
    categorie: 'vitamine',
    formes_recommandees: ['Pyridoxal-5-Phosphate (P5P) — forme active'],
    formes_a_eviter: ['pyridoxine seule à très forte dose chronique (neuropathie)'],
    ajr_officiel: '1,4 mg/jour',
    dosage_curtay: '25 à 50 mg de P5P/jour, à associer au magnésium',
    roles: [
      'Cofacteur de 100+ enzymes',
      'Synthèse neurotransmetteurs (sérotonine, GABA, dopamine)',
      'Entrée du magnésium intracellulaire',
      'Métabolisme protéique',
      'Métabolisme homocystéine',
      'Synthèse hémoglobine',
    ],
    signes_carence: [
      'Anxiété, irritabilité',
      'Dépression',
      'Anémie microcytaire',
      'Glossite, chéilite',
      'Crampes',
    ],
    sources_alimentaires: [
      'Foie, abats',
      'Saumon, thon',
      'Pois chiches, lentilles',
      'Pommes de terre',
      'Banane',
      'Avocat',
    ],
    interactions: ['Magnésium (entrée intracellulaire)', 'B9, B12 (méthylation)'],
    temperaments_prioritaires: ['nerveux', 'bilieux'],
    note_curtay:
      "La P5P est la forme directement active dans la cellule. La pyridoxine doit être convertie hépatiquement, étape souvent défaillante. Indissociable du magnésium dans le protocole anti-stress Curtay.",
  },
  {
    slug: 'coenzyme-q10',
    nom: 'Coenzyme Q10',
    categorie: 'antioxydant',
    formes_recommandees: ['ubiquinol (forme réduite, active)', 'ubiquinone + huile pour absorption'],
    formes_a_eviter: ['poudre sèche sans matière grasse (absorption < 5%)'],
    ajr_officiel: 'Pas de RDA — synthèse endogène',
    dosage_curtay: '100 à 300 mg/jour d\'ubiquinol, surtout après 40 ans et sous statines',
    roles: [
      'Cofacteur de la chaîne respiratoire mitochondriale (production ATP)',
      'Antioxydant lipophile',
      'Régénération de la vit E',
      'Protection cardiovasculaire',
    ],
    signes_carence: [
      'Fatigue chronique inexpliquée',
      'Faiblesse musculaire',
      'Insuffisance cardiaque',
      'Sous statines : douleurs musculaires (myalgies)',
    ],
    sources_alimentaires: [
      'Cœur de bœuf, foie',
      'Poissons gras',
      'Huile de soja, colza',
      'Cacahuètes',
    ],
    interactions: ['Statines (les statines bloquent la synthèse — supplémentation systématique recommandée par Curtay)'],
    temperaments_prioritaires: ['sanguin', 'lymphatique'],
    note_curtay:
      "Curtay insiste : toute prescription de statines devrait être systématiquement accompagnée de CoQ10 (300 mg/jour). La forme ubiquinol est 4x plus biodisponible que l'ubiquinone, surtout après 50 ans.",
  },
  {
    slug: 'methylfolate',
    nom: 'Vitamine B9 (méthylfolate)',
    categorie: 'vitamine',
    formes_recommandees: ['5-MTHF (L-méthylfolate) — forme active', 'folate naturel des aliments'],
    formes_a_eviter: ['acide folique synthétique (ne franchit pas la barrière chez les MTHFR mutés)'],
    ajr_officiel: '300 µg/jour (500 µg en grossesse)',
    dosage_curtay: '400 à 800 µg/jour de 5-MTHF',
    roles: [
      'Cycle de méthylation (avec B12)',
      'Synthèse ADN, division cellulaire',
      'Métabolisme homocystéine',
      'Développement neural embryonnaire',
      'Hématopoïèse',
    ],
    signes_carence: [
      'Anémie macrocytaire',
      'Hyperhomocystéinémie (risque cardio-vasculaire)',
      'Spina-bifida fœtal',
      'Glossite',
      'Trouble de l\'humeur',
    ],
    sources_alimentaires: [
      'Foie, abats',
      'Légumes verts feuillus crus (épinards, mâche)',
      'Légumineuses',
      'Asperges, brocoli',
      'Levure de bière',
    ],
    interactions: ['B12 (méthylation indissociable)', 'B6'],
    temperaments_prioritaires: ['nerveux', 'bilieux'],
    note_curtay:
      "30 à 50% de la population porte une mutation MTHFR qui réduit la conversion d'acide folique en forme active. Pour eux, la supplémentation en acide folique est inefficace voire délétère. Le 5-MTHF actif s'impose.",
  },
  {
    slug: 'curcuma',
    nom: 'Curcumine (extrait de curcuma)',
    categorie: 'antioxydant',
    formes_recommandees: ['avec pipérine (poivre noir) — bioasimilable x20', 'phospholipidique (Meriva)', 'micellaire'],
    formes_a_eviter: ['curcuma en poudre seul (biodisponibilité < 1%)'],
    dosage_curtay: '500 à 1 500 mg/jour de curcuminoïdes standardisés à 95%',
    roles: [
      'Anti-inflammatoire systémique majeur',
      'Antioxydant',
      'Hépatoprotection',
      'Modulation NF-kB',
      'Effets neuroprotecteurs',
    ],
    signes_carence: ['Non essentiel — usage thérapeutique'],
    sources_alimentaires: [
      'Racine de curcuma fraîche',
      'Poudre de curcuma (toujours avec poivre + matière grasse)',
    ],
    contre_indications: ['Calculs biliaires', 'Anticoagulothérapie', 'Avant chirurgie'],
    temperaments_prioritaires: ['bilieux', 'lymphatique', 'sanguin'],
    note_curtay:
      "L'absorption du curcuma natif est ridicule. Toute supplémentation efficace nécessite soit la pipérine (poivre noir), soit une formulation lipidique ou micellaire. Curtay recommande surtout son usage alimentaire quotidien (curcuma + poivre + huile).",
  },
  {
    slug: 'vitamine-k2',
    nom: 'Vitamine K2 (MK-7)',
    categorie: 'vitamine',
    formes_recommandees: ['MK-7 trans-isomère (natto, fermentations)'],
    formes_a_eviter: ['MK-4 synthétique seule à haute dose'],
    dosage_curtay: '90 à 200 µg/jour de MK-7',
    roles: [
      'Orientation du calcium vers les os (et hors des artères)',
      'Activation de l\'ostéocalcine',
      'Activation de la MGP (Matrix Gla Protein) — prévention calcifications vasculaires',
      'Synergie majeure avec vit D3',
    ],
    signes_carence: [
      'Ostéoporose',
      'Calcifications vasculaires',
      'Caries dentaires',
    ],
    sources_alimentaires: [
      'Natto (top source mondiale — 1000 µg/100g)',
      'Fromages affinés (gouda, brie)',
      'Jaune d\'œuf de poules au pâturage',
      'Foie d\'oie',
    ],
    interactions: ['Vit D3 (synergie indispensable)', 'Anticoagulants AVK — contre-indication'],
    contre_indications: ['Sous AVK (warfarine, etc.)'],
    temperaments_prioritaires: ['sanguin', 'lymphatique'],
    note_curtay:
      "La vit D3 sans K2 augmente l'absorption calcique mais peut favoriser les calcifications vasculaires. La supplémentation D3 + K2 est devenue standard. La MK-7 a une demi-vie longue (24h), supérieure à la MK-4.",
  },
  {
    slug: 'probiotiques',
    nom: 'Probiotiques (multi-souches)',
    categorie: 'autre',
    formes_recommandees: [
      'multi-souches Lactobacillus + Bifidobacterium',
      'gélules gastro-résistantes',
      'minimum 10 milliards UFC',
    ],
    formes_a_eviter: ['mono-souches systématiques', 'sans étude clinique'],
    dosage_curtay: '10 à 50 milliards UFC/jour, en cure de 2-3 mois',
    roles: [
      'Équilibre du microbiote intestinal',
      'Immunité (70% est intestinale)',
      'Synthèse de vitamines (K, B12, B9)',
      'Modulation axe intestin-cerveau',
      'Barrière intestinale',
    ],
    signes_carence: [
      'Troubles digestifs chroniques',
      'Infections récidivantes',
      'Mycoses récidivantes',
      'Hyperperméabilité intestinale',
      'Post-antibiothérapie',
    ],
    sources_alimentaires: [
      'Choucroute crue lacto-fermentée',
      'Kimchi',
      'Kéfir (de fruits ou de lait)',
      'Kombucha',
      'Miso non pasteurisé',
      'Yaourt artisanal',
    ],
    temperaments_prioritaires: ['lymphatique', 'nerveux'],
    note_curtay:
      "Curtay insiste sur l'importance de la diversité du microbiote plus que sur les souches isolées. Les aliments lacto-fermentés quotidiens restent la meilleure source. La supplémentation est utile en cures (post-antibiotique, traitement spécifique).",
  },
];

export const REGLES_CURTAY: RegleCurtay[] = [
  {
    numero: 1,
    titre: 'Aucun sucre, édulcorant, colorant, arôme synthétique ni trophallergène',
    description:
      'Un complément digne de ce nom ne contient aucun additif inutile. Pas de sucre, pas de dioxyde de titane, pas de gluten, pas de soja, pas de lactose, pas de colorant azoïque. La liste d\'ingrédients doit être COURTE et CLAIRE.',
    exemple: 'Refuser les "gummies vitaminées" colorées et sucrées vendues comme des bonbons.',
  },
  {
    numero: 2,
    titre: 'Jamais de Fer (Fe), Cuivre (Cu) ni Manganèse (Mn) dans un complément de base',
    description:
      "Ces minéraux sont catalyseurs de réactions oxydatives (réaction de Fenton). En supplémentation systématique, ils peuvent générer un stress oxydatif. La supplémentation en fer doit être PERSONNALISÉE sur bilan ferritine, jamais systématique.",
    exemple: 'Refuser les multi-vitamines hospitaliers contenant 14 mg de fer pour les hommes adultes.',
  },
  {
    numero: 3,
    titre: 'Doses adaptées à la catégorie de population',
    description:
      'Les besoins ne sont pas universels. Un enfant, une femme enceinte, un senior, un sportif n\'ont pas les mêmes besoins. Le bon complément cible une population. Les multi-vitamines "tout public" sont rarement optimaux.',
    exemple: 'Vitamine D : 800 UI pour l\'adulte non carencé, 2000-4000 UI en cure d\'hiver, 5000 UI si déficit avéré.',
  },
  {
    numero: 4,
    titre: 'Caroténoïdes multiples pour les seniors (pas que du bêta-carotène)',
    description:
      "Pour les > 60 ans, il faut un mélange : bêta-carotène + lycopène + lutéine + zéaxanthine + astaxanthine. Le bêta-carotène isolé à haute dose chez les fumeurs a même montré un risque accru.",
    exemple: 'Cocktail caroténoïdes naturels pour protéger vision (DMLA) et peau.',
  },
  {
    numero: 5,
    titre: 'Fluor : uniquement par voie externe (dentifrice)',
    description:
      'Pas de fluor dans le complément ! La supplémentation orale en fluor est obsolète, contestée. Effets délétères thyroïdiens et osseux à long terme démontrés.',
    exemple: 'Refuser les compléments enfant fluorés. Utiliser uniquement le dentifrice fluoré (et encore, certains s\'en passent).',
  },
  {
    numero: 6,
    titre: 'Vit A → bêta-carotène uniquement ; Vit E → forme NATURELLE',
    description:
      "Le rétinol synthétique (vit A) à haute dose est tératogène et hépatotoxique. Le bêta-carotène est précurseur sûr. Pour la vit E, seul le mélange naturel RRR-d-alpha + gamma + delta tocophérols est utile. La forme dl-alpha synthétique est contre-productive.",
    exemple: 'Lire l\'étiquette : "d-alpha-tocophérol" naturel vs "dl-alpha-tocophérol" synthétique.',
  },
  {
    numero: 7,
    titre: 'Oméga-3 toujours associés à des antioxydants (vit E naturelle)',
    description:
      'Les AGPI (acides gras polyinsaturés) sont par nature oxydables. Les supplémenter sans antioxydants peut être contre-productif. La formule idéale associe oméga-3 + vit E naturelle.',
    exemple: 'Choisir une huile de poisson certifiée IFOS avec mention "tocophérols mixtes ajoutés".',
  },
  {
    numero: 8,
    titre: 'Minéraux sous formes biodisponibles (chélates, citrates, glycinates)',
    description:
      'Les oxydes et carbonates sont peu absorbés (5-20%). Les formes chélatées aux acides aminés (bisglycinate) ou aux acides organiques (citrate, gluconate) atteignent 60-90% d\'absorption. La différence est essentielle.',
    exemple: 'Magnésium glycérophosphate (Curtay) plutôt que magnésium oxyde (laxatif). Zinc citrate plutôt que zinc sulfate.',
  },
];

export function getMicronutriment(slug: string): Micronutriment | undefined {
  return MICRONUTRIMENTS.find((m) => m.slug === slug);
}
