import type { Article } from '../types';

export const NATURO_BATCH3_EMONCTOIRES: Article[] = [
  // ─── CURES SAISONNIÈRES ───────────────────────────────────────────────────
  {
    slug: 'cure-equinoxe-printemps',
    domain: 'naturopathie',
    category: 'cures-saisonnieres',
    title: "La cure équinoxe de printemps : transition cellulaire",
    excerpt: "L'équinoxe de printemps marque traditionnellement le moment idéal pour relancer les fonctions cellulaires après l'hiver.",
    readingTime: 5,
    intro: "Vers le 20-21 mars, l'équinoxe marque l'équilibre parfait entre jour et nuit. Traditionnellement, c'est la fenêtre d'or pour ouvrir le grand nettoyage de printemps. Les anciens considéraient cette période comme un moment de bascule cellulaire, où le corps se prépare à libérer les stocks accumulés en hiver.",
    sections: [
      { heading: "Le moment biologique de l'équinoxe", body: "En naturopathie traditionnelle, l'équinoxe de printemps correspond à un changement profond du rythme métabolique. La lumière revient, les jours s'allongent, et le corps semblerait orienter spontanément ses fonctions vers l'élimination plutôt que vers le stockage. C'est aussi le moment où la sève monte dans les arbres : les phytothérapeutes considèrent traditionnellement que les bourgeons fraîchement éclos contiennent une énergie particulièrement bien adaptée au drainage cellulaire humain." },
      { heading: "Préparer le terrain (10 jours avant)", body: "Dès le 10 mars, il semblerait judicieux de commencer à alléger : réduction progressive des protéines animales, suppression des fritures, des alcools et des sucres rapides. Augmentation des légumes verts crus (mâche, jeunes pousses), introduction du citron tiède matinal. Cette phase de pré-cure permet au foie et aux intestins de ne pas être brutalement sollicités. Sans préparation, beaucoup ressentent maux de tête et fatigue intense les premiers jours." },
      { heading: "La cure cellulaire (10 jours)", body: "Le protocole traditionnel associe trois axes : drainage hépatique (sève de bouleau fraîche, 1 cuillère à soupe matin et soir), drainage rénal (tisane de pissenlit racine, 2 tasses/jour), et drainage cellulaire profond (bourgeon de cassis ou de bouleau en macérat glycériné, 10 gouttes/jour). Alimentation : monodiète de jus verts 1 jour, repas légumes-céréales complètes les autres jours, fruits cuits au goûter." },
      { heading: "Reconstruire après (10 jours)", body: "Sortie de cure progressive : réintroduction des protéines végétales d'abord (légumineuses douces, tofu), puis œufs et poissons. Maintien d'une boisson d'ortie quotidienne pour la reminéralisation. Les anciens recommandaient traditionnellement de continuer la sève de bouleau jusqu'à fin avril. Beaucoup de personnes rapportent traditionnellement un regain d'énergie net en mai, signe que la cure a porté ses fruits sur le terrain." },
      { heading: "Erreurs classiques", body: "L'erreur la plus fréquente est de démarrer trop fort, sans préparation. La deuxième est de cumuler trop de drainants en même temps (foie + reins + intestins + lymphe), ce qui peut surcharger les émonctoires. La troisième est de ne pas prévoir de repos : une cure d'équinoxe demande de dormir davantage, pas de courir des marathons. Écouter les signaux du corps reste la règle d'or." },
    ],
    keyPoints: [
      "L'équinoxe (20-21 mars) marque une fenêtre traditionnelle de bascule métabolique",
      "Préparer le terrain 10 jours avant évite les crises curatives violentes",
      "Sève de bouleau fraîche : pilier traditionnel de la cure équinoxe",
      "Drainer progressivement plutôt que de tout cumuler",
      "Prévoir 30 jours au total (10 préparation + 10 cure + 10 reconstruction)",
    ],
    contre_indications: [
      "Grossesse et allaitement",
      "Insuffisance rénale ou hépatique avérée",
      "Maladies auto-immunes en poussée",
      "Sortie récente d'une maladie aiguë",
      "Enfants de moins de 12 ans",
    ],
    tags: ['equinoxe', 'printemps', 'cellulaire', 'detox'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'cure-equinoxe-automne',
    domain: 'naturopathie',
    category: 'cures-saisonnieres',
    title: "La cure équinoxe d'automne : reminéralisation et préparation",
    excerpt: "L'équinoxe d'automne ouvre la saison de reminéralisation et de préparation immunitaire avant l'hiver.",
    readingTime: 5,
    intro: "Vers le 22-23 septembre, l'équinoxe d'automne inverse la dynamique : les jours raccourcissent, le corps recommence à stocker. Traditionnellement, c'est le moment de combler les minéraux perdus pendant l'été et de préparer les défenses immunitaires pour les mois froids. Cure de raisin, ortie, champignons médicinaux : la palette automnale est riche.",
    sections: [
      { heading: "Pourquoi reminéraliser à l'équinoxe", body: "L'été déshydrate et déminéralise par la transpiration : magnésium, potassium, sodium, oligoéléments. Beaucoup de personnes arrivent à l'automne avec une fatigue diffuse, des crampes nocturnes, des cheveux qui chutent, des ongles cassants. Traditionnellement, l'équinoxe d'automne est considéré comme la dernière fenêtre avant l'hiver pour reconstituer ces stocks. Plus on attend, plus le terrain s'affaiblit à l'entrée de la saison froide." },
      { heading: "La cure de raisin équinoxale", body: "Septembre-octobre offre le raisin local mûr à point, traditionnellement la cure phare de l'année naturopathique. 1 à 1,5 kg de raisin biologique par jour, en monodiète stricte, pendant 3 à 7 jours selon le terrain. Mâcher les pépins (riches en OPC, antioxydants puissants). Cure d'hydratation cellulaire profonde, de drainage hépatique doux, et d'apport massif en polyphénols. À démarrer impérativement dans la semaine de l'équinoxe pour profiter du raisin à pleine maturité." },
      { heading: "Reminéralisation par les plantes", body: "L'ortie est la reine de l'automne : tisane longue (15 min), 2 à 3 tasses/jour pendant 21 jours minimum. Apport en fer, calcium, magnésium, silice. La prêle complète pour les tissus conjonctifs (cure de 3 semaines, pause d'une semaine). Le bambou tabashir pour la silice biodisponible. Les algues marines (wakamé, dulse) ajoutées aux soupes apportent iode et oligoéléments. Bouillon d'os long mijoté : tradition immémoriale de reconstruction." },
      { heading: "Préparation immunitaire", body: "Septembre est le mois où il semblerait traditionnellement opportun de commencer la cure de vitamine D (4000 UI/jour le soir, à réévaluer selon bilan sanguin). Cure de probiotiques (30 jours) pour reconstruire la flore intestinale, garante de 70% de l'immunité selon les données actuelles. Champignons médicinaux : reishi, shiitake, maïtake en gélules ou poudre. Propolis en cure de 21 jours dès la fin septembre." },
      { heading: "Alimentation d'automne", body: "Courges (potimarron, butternut, courge musquée) : bêta-carotène, fibres douces. Châtaignes : minéraux denses, énergie lente. Pommes biologiques (la peau riche en pectine). Poires (mucilages). Noix fraîches (oméga-3 à pleine teneur). Champignons sauvages cuits. Premiers choux. Patates douces. Soupes longuement mijotées plutôt que crudités froides. Boissons tièdes plutôt que glacées." },
    ],
    keyPoints: [
      "L'équinoxe d'automne (22-23 septembre) : dernière fenêtre de reminéralisation",
      "Cure de raisin : pilier traditionnel de la saison",
      "Ortie en tisane longue : reminéralisant majeur",
      "Démarrer la cure de vitamine D et probiotiques dès septembre",
      "Privilégier les cuissons douces et longues plutôt que les crudités",
    ],
    contre_indications: [
      "Diabète mal équilibré (cure de raisin contre-indiquée)",
      "Grossesse et allaitement (champignons médicinaux à éviter)",
      "Traitements anticoagulants (interactions possibles)",
      "Allergies aux salicylés (saule, reine-des-prés)",
    ],
    tags: ['equinoxe', 'automne', 'raisin', 'reminéralisation'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'transition-saisons-emonctoires',
    domain: 'naturopathie',
    category: 'cures-saisonnieres',
    title: "Pourquoi les changements de saison fatiguent les émonctoires",
    excerpt: "Les transitions saisonnières sollicitent fortement les organes d'élimination — comprendre pourquoi pour mieux les soutenir.",
    readingTime: 4,
    intro: "Chaque changement de saison met les émonctoires (foie, reins, intestins, peau, poumons) à rude épreuve. Variations de température, modifications alimentaires, changements de luminosité : autant de stress métaboliques que le corps doit absorber. Comprendre cette physiologie traditionnelle aide à anticiper et soutenir.",
    sections: [
      { heading: "Le corps comme un thermostat saisonnier", body: "Le métabolisme humain semblerait s'adapter de manière fine aux saisons : production hormonale (mélatonine, cortisol, hormones thyroïdiennes), composition du microbiote, profil enzymatique digestif. Aux intersaisons (mars-avril, septembre-octobre), le corps réorganise ses priorités. Cette transition demande de l'énergie aux émonctoires, qui doivent éliminer les molécules issues du métabolisme antérieur pour faire place au nouveau profil." },
      { heading: "Foie : le grand chef d'orchestre des transitions", body: "Le foie filtre, transforme, conjugue, élimine. À chaque changement saisonnier, il doit s'adapter aux nouveaux aliments (fruits d'été, racines d'hiver), aux nouvelles températures, aux nouveaux rythmes. Traditionnellement, c'est l'organe le plus sollicité aux intersaisons. Les signes de surcharge sont classiques : langue chargée, haleine désagréable au réveil, irritabilité matinale, sommeil agité entre 1h et 3h, digestion lente après les repas gras." },
      { heading: "Intestins et microbiote en mutation", body: "Le microbiote intestinal semblerait évoluer avec les saisons : études récentes montrant des compositions différentes selon l'apport en fibres saisonnières. À l'intersaison, la flore se réorganise. C'est pourquoi beaucoup de personnes connaissent des transits irréguliers en mars et en octobre. Soutenir avec des probiotiques de qualité, des fibres prébiotiques (chicorée, topinambour, oignon cru), et de la simplicité alimentaire facilite cette transition." },
      { heading: "Peau et poumons : émonctoires de surface", body: "La peau, plus grand organe d'élimination par surface, voit son rôle évoluer : sudation estivale active, sécheresse hivernale. Aux intersaisons, eczéma, acné, démangeaisons peuvent apparaître — signaux d'élimination, pas toujours pathologie. Les poumons, exposés aux pollens du printemps, aux climats secs ou humides, sont également sollicités. Traditionnellement, on parle de 'crise curative' : éliminations bruyantes mais salutaires." },
      { heading: "Comment soutenir intelligemment", body: "Plutôt que de cumuler les drainants violents, il semblerait préférable d'alléger l'alimentation 10 jours avant le changement de saison, de privilégier les bouillons et les tisanes, de dormir une heure de plus si possible. Marche quotidienne en extérieur pour oxygéner. Bains hyperthermiques 1 fois par semaine pour activer la sudation. Et surtout : écouter les signaux du corps plutôt que de forcer un protocole." },
    ],
    keyPoints: [
      "Les intersaisons demandent un travail métabolique intense aux émonctoires",
      "Le foie est l'organe le plus sollicité lors des transitions",
      "Le microbiote intestinal évolue avec les saisons",
      "Les manifestations cutanées aux intersaisons sont souvent éliminatoires",
      "Alléger 10 jours avant chaque changement de saison soulage le terrain",
    ],
    contre_indications: [
      "Pathologies aiguës en cours (consulter avant tout protocole)",
      "Grossesse (éviter les drainages intensifs)",
    ],
    tags: ['intersaisons', 'émonctoires', 'physiologie', 'transition'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'cure-printemps-foie-21j',
    domain: 'naturopathie',
    category: 'cures-saisonnieres',
    title: "Le protocole printemps 21 jours pour le foie",
    excerpt: "Un protocole structuré de 21 jours pour drainer le foie en profondeur au printemps.",
    readingTime: 5,
    intro: "Le foie est traditionnellement considéré comme l'organe du printemps en médecine chinoise, ayurvédique et hippocratique. Un protocole de 21 jours, progressif et bien dosé, permet selon la tradition naturopathique un drainage profond sans crise majeure. Voici un programme structuré en trois semaines.",
    sections: [
      { heading: "Semaine 1 : ouverture des émonctoires", body: "Avant de drainer le foie, il faut s'assurer que les portes de sortie sont ouvertes : intestins fluides, reins actifs, peau qui transpire. Au réveil : jus de citron tiède dans 250 ml d'eau. Petit-déjeuner allégé (fruits frais, oléagineux). Tisane de pissenlit feuille (1 tasse à 10h, 1 tasse à 16h). Repas du soir avant 19h, légumes cuits + protéine légère. Marche de 30 minutes quotidienne. Hydratation 1,5 L/jour minimum. Suppression alcool, fritures, charcuteries." },
      { heading: "Semaine 2 : drainage hépatique central", body: "Maintien des bases de la semaine 1. Ajout : décoction de racine de pissenlit le matin (1 c. à soupe pour 250 ml, 10 min de cuisson douce). Fumeterre en infusion 5 min, 1 tasse à 11h et 17h. Bourgeon de romarin en macérat glycériné, 5 gouttes matin et soir. Compresse d'huile de ricin tiède sur le foie 2 soirs dans la semaine (1h sous bouillotte). Repas : monodiète de pomme un jour dans la semaine. Légumes amers privilégiés (artichaut, endive, chicorée, roquette)." },
      { heading: "Semaine 3 : approfondissement et chardon-marie", body: "Le chardon-marie entre en scène pour la phase de régénération hépatocytaire : 200 mg de silymarine standardisée, 2 fois par jour, ou 1 c. à café de graines moulues dans une compote. Maintien des plantes de la semaine 2. Ajout d'un jus vert frais (concombre, céleri, persil, citron, gingembre) chaque matin à jeun. Possibilité d'une journée de jus liquides complète en milieu de semaine si la tolérance est bonne." },
      { heading: "Sortie de cure (3 jours)", body: "La sortie de cure est aussi importante que la cure elle-même. Jour 1 : reprise alimentaire douce, légumes cuits, riz semi-complet, poisson. Jour 2 : ajout de tofu, lentilles, œufs. Jour 3 : retour progressif à l'alimentation habituelle, en gardant l'allègement comme cap. Maintenir le citron matinal et les tisanes au moins jusqu'à fin avril. Beaucoup de personnes rapportent traditionnellement une meilleure énergie, un teint plus clair, et une digestion soulagée." },
      { heading: "Surveiller les signaux", body: "Une cure bien menée peut provoquer des manifestations dites curatives : maux de tête transitoires, fatigue les 3 premiers jours, parfois petits boutons. Ces signaux disparaissent généralement en 4-5 jours. En revanche : nausées persistantes, douleurs hépatiques marquées, jaunissement de la peau ou des yeux, sont des signaux d'alerte qui imposent l'arrêt immédiat et une consultation médicale." },
    ],
    keyPoints: [
      "Protocole structuré en 3 semaines progressives",
      "Ouverture des émonctoires AVANT le drainage hépatique",
      "Plantes piliers : pissenlit, fumeterre, chardon-marie",
      "Compresses d'huile de ricin : tradition bien tolérée",
      "Sortie de cure progressive sur 3 jours",
    ],
    contre_indications: [
      "Calculs biliaires connus (risque de mobilisation)",
      "Obstruction des voies biliaires",
      "Insuffisance hépatique ou rénale",
      "Grossesse et allaitement",
      "Prise de médicaments métabolisés par le foie (consulter)",
    ],
    tags: ['foie', 'printemps', 'protocole', '21-jours'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'cure-automne-reins-poumons',
    domain: 'naturopathie',
    category: 'cures-saisonnieres',
    title: "Le drainage automnal reins-poumons",
    excerpt: "L'automne sollicite traditionnellement les reins (élément Eau) et les poumons (élément Métal). Protocole de drainage adapté.",
    readingTime: 5,
    intro: "En médecine traditionnelle chinoise, l'automne correspond à l'élément Métal et aux organes poumons-gros intestin, tandis que la transition vers l'hiver active l'élément Eau et les reins. Drainer ces deux axes en septembre-octobre prépare un hiver serein. Voici comment procéder traditionnellement.",
    sections: [
      { heading: "Pourquoi associer reins et poumons", body: "Les médecines traditionnelles relient intimement ces deux organes : les reins seraient la 'racine' du souffle, les poumons en seraient la 'cime'. En physiologie moderne, on note effectivement des liens (équilibre acido-basique régulé par les deux, élimination d'eau et de CO2 complémentaire). Au début de l'automne, il semblerait traditionnellement opportun de soulager d'abord les reins (charge estivale par la sudation et l'hydratation parfois insuffisante), puis de fortifier les poumons pour affronter l'hiver." },
      { heading: "Phase 1 : drainage rénal (10 jours)", body: "Tisane d'aubier de tilleul (décoction longue, 30 min) : 1 L sur la journée, en cure de 10 jours. Alternative : piloselle, reine-des-prés, bouleau (feuilles), orthosiphon. Hydratation soutenue : 1,5 à 2 L d'eau peu minéralisée par jour. Réduction du sel, suppression des charcuteries, modération sur les protéines animales. Asperges et poireaux, légumes diurétiques traditionnels, ajoutés régulièrement. Bain de pieds chaud le soir pour activer la circulation rénale." },
      { heading: "Phase 2 : fortification pulmonaire (10 jours)", body: "Bourgeon de charme et de noisetier en macérat glycériné, 5 gouttes matin et soir (tradition gemmothérapique pour le système respiratoire). Tisane de thym (anti-infectieux respiratoire), 2 tasses/jour. Huile essentielle d'eucalyptus radié en diffusion 15 min matin et soir. Cure de propolis (15 gouttes de teinture dans une boisson chaude, 2 fois/jour). Exercices respiratoires : cohérence cardiaque 3 fois 5 min/jour, respiration abdominale au coucher." },
      { heading: "Phase 3 : reminéralisation des reins (10 jours)", body: "Une fois les reins drainés, on reminéralise : tisane d'ortie longue (15 min) 2 tasses/jour. Cure de magnésium (300 à 400 mg/jour, forme glycinate ou bisglycinate). Eaux minéralisées riches en magnésium et calcium (Hépar, Contrex, Rozana en alternance, modérément). Bouillon d'os 2 à 3 fois par semaine. Algues (wakamé, dulse) ajoutées aux soupes. Cette phase pose les bases de la résistance hivernale." },
      { heading: "Alimentation et hygiène de vie", body: "Soupes longuement mijotées privilégiées plutôt que crudités froides. Courges, châtaignes, racines (carottes, panais, navets) en abondance. Réduction des sucres et des produits laitiers (encombrent les poumons selon la tradition). Marche en forêt 30 min/jour si possible (oxygénation, sylvothérapie). Sauna ou bain hyperthermique 1 fois par semaine pour activer la sudation et soulager les reins. Coucher avant 23h pour respecter le cycle traditionnel des reins." },
    ],
    keyPoints: [
      "Drainer reins d'abord, fortifier poumons ensuite, reminéraliser pour finir",
      "Aubier de tilleul et piloselle : piliers du drainage rénal automnal",
      "Thym, propolis et eucalyptus : trio pulmonaire traditionnel",
      "Ortie en tisane longue pour reminéraliser",
      "Soupes mijotées et marches en forêt : hygiène de vie d'automne",
    ],
    contre_indications: [
      "Insuffisance rénale (formelle pour les drainants)",
      "Hypotension marquée (les drainants peuvent l'aggraver)",
      "Asthme sévère (huiles essentielles à éviter ou très prudent)",
      "Grossesse et allaitement",
      "Allergies aux salicylés (reine-des-prés)",
    ],
    tags: ['automne', 'reins', 'poumons', 'drainage'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'preparation-hiver-immunite',
    domain: 'naturopathie',
    category: 'cures-saisonnieres',
    title: "Préparer l'immunité dès septembre",
    excerpt: "Anticiper l'hiver en renforçant l'immunité dès la rentrée — protocole en 3 mois.",
    readingTime: 5,
    intro: "Attendre les premiers frimas pour soutenir son immunité, c'est arriver trop tard. Traditionnellement, le travail commence en septembre : vitamine D, probiotiques, plantes adaptogènes, hygiène de vie. Voici un protocole sur 3 mois pour traverser l'hiver avec un terrain solide.",
    sections: [
      { heading: "Septembre : poser les fondations", body: "Démarrage de la cure de vitamine D (4000 UI/jour le soir, à ajuster selon bilan sanguin idéalement). Cure de probiotiques de qualité (multi-souches, 10 milliards UFC minimum, 30 jours). Reminéralisation par l'ortie (tisane longue, 2 tasses/jour, 21 jours). Cure de champignons immunostimulants : reishi le soir (calme et immunité), shiitake en journée. Première cure de propolis (15 gouttes 2 fois/jour, 21 jours). Sommeil prioritaire : coucher avant 23h." },
      { heading: "Octobre : renforcer les défenses", body: "Cure d'échinacée : 10 jours par mois en préventif (à arrêter dès qu'on tombe malade, à reprendre ensuite). Vitamine C naturelle : acérola, cynorrhodon en poudre, 500 mg/jour. Zinc en cure courte (15 mg/jour pendant 30 jours, forme bisglycinate ou citrate). Oméga-3 si l'alimentation ne couvre pas (huile de poisson sauvage, 1 à 2 g d'EPA+DHA/jour). Maintien de la vitamine D, des probiotiques sur 1 mois supplémentaire si nécessaire." },
      { heading: "Novembre : adaptogènes et endurance", body: "Introduction d'un adaptogène pour soutenir les surrénales mises à l'épreuve par la fatigue saisonnière : ashwagandha (300-600 mg/jour, le soir), ou rhodiola (200-400 mg/jour, le matin, pour les terrains fatigués), ou éleuthérocoque (300-600 mg/jour, le matin). Cure de 6 à 8 semaines, jamais en continu. Continuer la propolis en cure si épidémie déjà présente. Sirop de sureau noir maison ou en pharmacie pour les premiers signes." },
      { heading: "Hygiène de vie hivernale", body: "Sommeil non négociable : 7 à 9 heures, coucher avant 23h. Activité physique régulière mais sans excès (le surentraînement immunodéprime). Marche extérieure quotidienne, même 20 minutes, pour la lumière et la vitamine D résiduelle. Sauna ou bains hyperthermiques 1 à 2 fois par semaine si possible. Alimentation chaude et cuite, peu de crudités, soupes mijotées, épices stimulantes (gingembre, cannelle, curcuma, clou de girofle)." },
      { heading: "Réagir au premier signe", body: "Aux premiers signes (gorge qui pique, frissons, fatigue inhabituelle), réagir immédiatement : doublement de la vitamine C, propolis intensive (toutes les 2 heures), repos absolu pendant 24 à 48h, jeûne court ou monodiète de bouillon, tisanes de thym, sureau, gingembre. Bain hyperthermique le soir (38-39°C pendant 20 min) pour faire monter la température corporelle. Beaucoup de virus saisonniers semblent désamorcés par cette réactivité précoce." },
    ],
    keyPoints: [
      "Démarrer le travail immunitaire dès septembre, pas en décembre",
      "Vitamine D et probiotiques : socle de l'immunité hivernale",
      "Échinacée en préventif rotatif (10j/mois)",
      "Adaptogène en novembre pour soutenir les surrénales",
      "Réactivité au premier signe : la fenêtre est étroite",
    ],
    contre_indications: [
      "Maladies auto-immunes (échinacée et certains champignons contre-indiqués)",
      "Grossesse et allaitement (vérifier chaque plante)",
      "Traitements immunosuppresseurs (consulter)",
      "Allergies aux astéracées (échinacée, échinacée, propolis pour certains)",
    ],
    tags: ['immunité', 'hiver', 'préparation', 'septembre'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },

  // ─── ÉMONCTOIRES (purges) ─────────────────────────────────────────────────
  {
    slug: 'emonctoires-foie-vesicule',
    domain: 'naturopathie',
    category: 'purges',
    title: "Le foie et la vésicule, premier émonctoire du naturopathe",
    excerpt: "Le foie est traditionnellement le premier émonctoire à soutenir en naturopathie — comprendre son rôle et ses besoins.",
    readingTime: 5,
    intro: "En naturopathie classique, le foie est considéré comme l'émonctoire roi : il filtre 1,5 litre de sang par minute, transforme 500 substances, élimine via la bile. La vésicule biliaire en est l'organe satellite indispensable. Sans soutien hépatique, aucune cure profonde n'est efficace.",
    sections: [
      { heading: "Anatomie fonctionnelle du foie", body: "Le foie pèse 1,5 kg chez l'adulte, soit la masse organique la plus importante après la peau. Il reçoit deux apports sanguins : artériel (oxygène) et porte (nutriments et toxines digestives). Ses hépatocytes effectuent les fonctions de filtration, conjugaison, synthèse (protéines, cholestérol, facteurs de coagulation), stockage (glycogène, fer, vitamines liposolubles), et production biliaire (700-1200 ml/jour). Cette complexité fonctionnelle explique pourquoi un foie fatigué retentit sur tout l'organisme." },
      { heading: "Les phases de détoxification hépatique", body: "La biologie moderne décrit traditionnellement deux phases de détoxification hépatique. Phase I (cytochromes P450) : oxydation, rendant les molécules plus réactives. Phase II (conjugaison) : liaison à des molécules hydrosolubles (glutathion, sulfates, glycine) pour élimination. Si la phase I est rapide mais la phase II lente, des intermédiaires toxiques s'accumulent. C'est pourquoi soutenir la phase II (acides aminés soufrés, vitamines B, glycine) est aussi crucial que stimuler la phase I." },
      { heading: "Rôle de la vésicule biliaire", body: "La vésicule biliaire concentre et stocke la bile produite par le foie. À chaque repas gras, elle se contracte et envoie la bile dans le duodénum pour émulsionner les graisses et activer la lipase pancréatique. La bile transporte également les déchets liposolubles (médicaments métabolisés, hormones usées, cholestérol). Une vésicule peu contractile (par habitudes alimentaires pauvres en bons gras, ou par stagnation) favoriserait selon la tradition la cristallisation et les calculs." },
      { heading: "Signes de surcharge hépato-biliaire", body: "Traditionnellement reconnus : langue chargée blanchâtre ou jaunâtre, haleine désagréable au réveil, goût amer en bouche, réveils entre 1h et 3h du matin (heure du foie selon la médecine chinoise), irritabilité matinale, digestion lente après les repas gras, intolérance subite à certains aliments (œufs, fritures, alcool), peau terne, cernes jaunâtres. Aucun de ces signes n'est pathognomonique mais leur accumulation oriente." },
      { heading: "Soutenir au quotidien", body: "Habitudes simples et puissantes : citron tiède au réveil (active la production biliaire), légumes amers à chaque repas (artichaut, endive, roquette, pissenlit, chicorée), curcuma quotidien (avec poivre noir et huile pour la biodisponibilité), aliments riches en glutathion ou en précurseurs (œuf, avocat, brocoli, asperge), réduction des graisses cuites et des sucres rapides. Suppression progressive de l'alcool, ou consommation strictement modérée et occasionnelle." },
    ],
    keyPoints: [
      "Le foie est l'émonctoire central de la naturopathie",
      "Deux phases de détoxification à soutenir simultanément",
      "La vésicule biliaire est indispensable à l'élimination des déchets liposolubles",
      "Réveils 1h-3h, langue chargée : signes traditionnels de surcharge",
      "Citron, amers, curcuma : trio quotidien de soutien hépatique",
    ],
    contre_indications: [
      "Calculs biliaires (les cholagogues peuvent les mobiliser dangereusement)",
      "Obstruction des voies biliaires",
      "Hépatite aiguë",
      "Insuffisance hépatique sévère",
    ],
    tags: ['foie', 'vésicule', 'émonctoire', 'détoxification'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'emonctoires-reins-eau',
    domain: 'naturopathie',
    category: 'purges',
    title: "Les reins, filtres et émonctoires d'eau",
    excerpt: "Les reins filtrent 180 litres de sang par jour pour produire 1,5 litre d'urine — comprendre cet émonctoire d'eau.",
    readingTime: 5,
    intro: "Les reins sont les filtres principaux du milieu intérieur. Ils éliminent les déchets hydrosolubles (urée, acide urique, créatinine), régulent l'équilibre acido-basique, gèrent la pression artérielle et la composition minérale. En naturopathie, ils sont l'émonctoire d'eau par excellence.",
    sections: [
      { heading: "Physiologie rénale en bref", body: "Les deux reins, situés de part et d'autre de la colonne lombaire, contiennent environ 1 million de néphrons chacun. Chaque néphron filtre, réabsorbe et sécrète : 180 litres de plasma filtrés quotidiennement, dont 178,5 sont réabsorbés. Reste 1,5 litre d'urine concentrée, transportant les déchets. Cette précision exige une hydratation suffisante : sous-hydratation, l'urine devient trop concentrée et favorise cristaux et calculs." },
      { heading: "Déchets éliminés par les reins", body: "Principalement : urée (issue du catabolisme protéique), acide urique (issu des purines), créatinine (issue du métabolisme musculaire), médicaments hydrosolubles, métabolites hormonaux, excès de minéraux (sodium, potassium, calcium). Les reins gèrent également l'élimination des acides métaboliques en complément des poumons : c'est l'équilibre acido-basique. Une alimentation acidifiante (excès de protéines animales, de céréales raffinées) surcharge cette fonction." },
      { heading: "Signes de surcharge rénale", body: "Traditionnellement décrits : cernes foncés sous les yeux, paupières gonflées au réveil, urines très foncées ou très claires (deux extrêmes signifiants), mictions trop fréquentes ou trop rares, sensation de lourdeur lombaire, soif inexpliquée ou absence de soif chez quelqu'un qui boit peu, peau sèche, fatigue chronique sans cause évidente. Un examen biologique (créatinine, urée, ionogramme) reste le moyen objectif d'évaluer la fonction." },
      { heading: "Soutenir les reins au quotidien", body: "Hydratation : 1,5 L d'eau peu minéralisée par jour (Mont Roucous, Volvic, eau du robinet filtrée selon la région). Modérer le sel (5 g/jour maximum, dont 80% caché dans les produits transformés). Modérer les protéines animales (1 g/kg/jour est suffisant pour la plupart). Légumes diurétiques : asperge, poireau, fenouil, céleri. Tisanes douces : pissenlit, ortie, bouleau. Bain de pieds chaud le soir pour activer la circulation rénale." },
      { heading: "Cures rénales saisonnières", body: "Au printemps et à l'automne, cure de drainage rénal de 21 jours : aubier de tilleul en décoction (1 L/jour, en remplacement des autres boissons), ou piloselle (15 gouttes de teinture mère 2 fois/jour), ou orthosiphon. À éviter en hiver (les reins préfèrent la chaleur, pas le drainage froid). Toujours sur des reins sains : un drainage sur insuffisance rénale aggraverait la situation. Bilan biologique préalable conseillé après 50 ans." },
    ],
    keyPoints: [
      "Les reins filtrent 180 litres de plasma par jour",
      "Hydratation suffisante = condition de bon fonctionnement",
      "Régulation acido-basique : fonction critique",
      "Cernes, lourdeur lombaire : signes traditionnels de surcharge",
      "Drainage rénal au printemps et à l'automne, pas en hiver",
    ],
    contre_indications: [
      "Insuffisance rénale (drainage formellement contre-indiqué)",
      "Hypotension marquée",
      "Calculs rénaux sans avis médical",
      "Grossesse pour la plupart des drainants",
      "Diurétiques médicamenteux (interactions)",
    ],
    tags: ['reins', 'émonctoire', 'eau', 'drainage'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'emonctoires-intestins-elimination',
    domain: 'naturopathie',
    category: 'purges',
    title: "Les intestins, émonctoires majeurs d'élimination",
    excerpt: "Sept à neuf mètres d'intestin grêle et gros intestin assurent l'élimination quotidienne des déchets solides et bien plus.",
    readingTime: 5,
    intro: "Les intestins ne sont pas seulement le lieu de l'absorption : ils éliminent quotidiennement déchets de digestion, métabolites biliaires, cellules épithéliales, et abritent 70% du système immunitaire. En naturopathie, leur santé conditionne tout le terrain.",
    sections: [
      { heading: "Physiologie de l'élimination intestinale", body: "Le gros intestin (côlon), long d'environ 1,5 m, est le terminal de l'élimination solide. Il reçoit chaque jour environ 1,5 L de chyme liquide, en réabsorbe l'eau et les minéraux, et forme les selles. Un transit normal va de 1 à 2 selles par jour à 1 selle tous les 2 jours (limite basse). Au-delà, on parle de constipation. La consistance, la couleur, la flottabilité, l'odeur des selles fournissent des indications précieuses sur l'état du terrain." },
      { heading: "Le microbiote intestinal", body: "100 000 milliards de bactéries, 1,5 à 2 kg de masse, plus de 1000 espèces. Le microbiote synthétise vitamines (K, B12, biotine), fermente les fibres en acides gras à chaîne courte (butyrate, nourricier des colonocytes), entraîne le système immunitaire, module l'inflammation systémique. Un microbiote équilibré est la première condition d'une bonne élimination. Probiotiques, prébiotiques (fibres), polyphénols (thé vert, baies, cacao) le soutiennent." },
      { heading: "Signes de dysfonction intestinale", body: "Traditionnellement repérés : constipation chronique (moins de 5 selles par semaine), diarrhées récurrentes, alternance des deux, ballonnements après les repas, flatulences malodorantes, selles dures et fragmentées (selles de chèvre) ou au contraire pâteuses qui collent à la cuvette, langue chargée, haleine désagréable, fatigue postprandiale, brouillard mental, problèmes cutanés. La fragmentation et la mauvaise odeur orientent vers une putréfaction colique." },
      { heading: "Soutenir l'élimination intestinale", body: "Hydratation suffisante (au moins 1,5 L/jour). Fibres en quantité (30-40 g/jour, légumes, fruits, légumineuses, graines de lin et de chia). Mastication longue (commence la digestion, signale au côlon). Activité physique quotidienne (le côlon a besoin de mouvement). Réflexe gastro-colique respecté : aller à la selle après le petit-déjeuner sans précipitation. Pruneaux trempés, kiwis le matin, eau magnésienne (Hépar) : remèdes traditionnels en cas de constipation." },
      { heading: "Restaurer un terrain perturbé", body: "Cure de probiotiques multi-souches (30 jours minimum, 10 milliards UFC). Prébiotiques : chicorée, topinambour, oignon cru, ail, asperge, banane légèrement verte. Polyphénols végétaux. Bouillon d'os pour les acides aminés régénérants (glutamine, glycine, proline). Suppression temporaire des irritants potentiels : gluten, produits laitiers, sucres raffinés, alcool. Évaluer une éventuelle hyperperméabilité intestinale avec un naturopathe ou un médecin formé." },
    ],
    keyPoints: [
      "Le côlon réabsorbe 1,5 L d'eau par jour pour former les selles",
      "Le microbiote pèse 1,5-2 kg et abrite 70% de l'immunité",
      "Forme, consistance et odeur des selles : indicateurs précieux",
      "Hydratation, fibres, mastication, mouvement : socle quotidien",
      "Probiotiques et prébiotiques pour restaurer un terrain dégradé",
    ],
    contre_indications: [
      "Maladies inflammatoires de l'intestin en poussée (consulter)",
      "Occlusion intestinale (urgence médicale)",
      "Diverticulite aiguë",
      "Allergies sévères à certaines fibres",
    ],
    tags: ['intestins', 'côlon', 'microbiote', 'émonctoire'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'emonctoires-peau-sudation',
    domain: 'naturopathie',
    category: 'purges',
    title: "La peau, émonctoire d'urgence par la sudation",
    excerpt: "Premier organe du corps par sa surface, la peau élimine par sudation des centaines de molécules — émonctoire d'urgence quand les autres saturent.",
    readingTime: 5,
    intro: "La peau, 1,5 à 2 m² chez l'adulte, est le plus grand organe humain. Outre ses fonctions de barrière, de thermorégulation et de perception, elle élimine par sudation eau, sels minéraux, urée, acides organiques, métaux lourds en faible quantité. En naturopathie, c'est l'émonctoire de secours.",
    sections: [
      { heading: "Physiologie de la sudation", body: "Le corps possède environ 2 à 4 millions de glandes sudoripares, principalement eccrines (sudation thermorégulatrice) et apocrines (zones axillaires, pubiennes, sudation hormonale). Production normale : 500 ml à 1,5 L/jour au repos, jusqu'à 12 L/jour en effort intense en climat chaud. La sueur contient 99% d'eau, 1% de solutés : sodium, chlorures, potassium, urée, acide lactique, ammoniaque, urochrome." },
      { heading: "Pourquoi la peau est un émonctoire 'd'urgence'", body: "Quand foie, reins et intestins saturent, le corps semblerait traditionnellement utiliser la peau comme issue de secours. Les manifestations sont alors visibles : eczéma, acné, urticaire, démangeaisons, transpiration nauséabonde, boutons. En naturopathie classique, on évite de supprimer brutalement ces éliminations cutanées (crèmes cortisonées en première intention) sans avoir d'abord soulagé les émonctoires principaux : sinon le travail revient vers l'intérieur." },
      { heading: "Activer la sudation thérapeutique", body: "Bains hyperthermiques : entrer dans un bain à 37°C, monter progressivement à 39-40°C sur 20 minutes, puis sortir et s'envelopper dans une serviette chaude pour continuer à transpirer. À faire le soir, 1 à 2 fois par semaine. Sauna finlandais (80-90°C) : 3 cycles de 10-15 minutes entrecoupés de douches fraîches. Hammam (40-50°C, vapeur humide) : doux pour les peaux sensibles. Activité physique soutenue : marche rapide, course, vélo." },
      { heading: "Soutenir la peau au quotidien", body: "Hydratation interne (1,5 L/jour). Brossage à sec quotidien (brosse à poils naturels, mouvements vers le cœur, 5 minutes, avant la douche) : stimule la circulation lymphatique et exfolie. Douches alternées chaud-froid en fin (alternances de 30 secondes pendant 3 minutes). Eviter les produits cosmétiques chargés (sulfates agressifs, parfums synthétiques, perturbateurs endocriniens). Préférer huiles végétales pures (jojoba, argan, noisette) et savons saponifiés à froid." },
      { heading: "Hygiène alimentaire pour une peau saine", body: "Légumes verts à chlorophylle (épinard, mâche, persil, brocoli) : reconnus traditionnellement comme dépuratifs sanguins. Pensée sauvage en tisane (3 semaines de cure) : tradition pour les terrains cutanés irritables. Zinc et oméga-3 (poissons gras, graines de lin) : structure cutanée. Vitamine A naturelle (foie, carottes, patate douce) : renouvellement cellulaire. Réduction des sucres rapides (acné), des laitages industriels (zones acnéiques), de l'alcool (couperose)." },
    ],
    keyPoints: [
      "1,5 à 2 m² de surface : plus grand organe du corps",
      "Émonctoire d'urgence quand les autres saturent",
      "Eczéma et acné : souvent éliminations cutanées de fond",
      "Bains hyperthermiques et sauna : activation thérapeutique",
      "Brossage à sec quotidien : tradition simple et efficace",
    ],
    contre_indications: [
      "Insuffisance cardiaque (sauna et bains chauds prudents)",
      "Hypertension non équilibrée",
      "Grossesse (température corporelle élevée à éviter)",
      "Maladies cutanées en poussée aiguë",
      "Enfants en bas âge",
    ],
    tags: ['peau', 'sudation', 'émonctoire', 'sauna'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'emonctoires-poumons-bronches',
    domain: 'naturopathie',
    category: 'purges',
    title: "Les poumons et bronches, émonctoires d'air",
    excerpt: "Les poumons éliminent le CO2 mais aussi des composés volatils — émonctoire d'air sous-estimé en naturopathie.",
    readingTime: 5,
    intro: "Avec 70 m² de surface alvéolaire, les poumons éliminent quotidiennement environ 500 g de CO2 et de nombreux composés volatils (acétone, alcools, dérivés terpéniques). En naturopathie, l'émonctoire pulmonaire est aussi crucial que les autres, et souvent négligé.",
    sections: [
      { heading: "Physiologie de l'élimination pulmonaire", body: "Chaque respiration : 500 ml d'air en moyenne au repos, 20 000 respirations par jour, 8 000 à 10 000 litres d'air mobilisés. À chaque expiration, le corps élimine CO2 (déchet majeur du métabolisme cellulaire), vapeur d'eau, et environ 200 composés organiques volatils. Une respiration ample, profonde, abdominale maximise cette élimination. À l'inverse, une respiration thoracique courte et superficielle (stress chronique) limite l'épuration." },
      { heading: "Pourquoi soutenir les poumons", body: "Pollution atmosphérique, tabagisme passif ou actif, climat sec ou humide excessif, allergènes (pollens, acariens), virus saisonniers : autant de stress sur les voies respiratoires. Traditionnellement, les poumons sont aussi liés à l'élimination émotionnelle (tristesse, deuil en médecine chinoise). Une respiration entravée traduit souvent un terrain encrassé ou émotionnellement chargé. Les poumons sont les premiers à se manifester en cas d'excès de produits laitiers et de mucus (selon la tradition)." },
      { heading: "Signes traditionnels de surcharge", body: "Respiration courte, sensation de manque d'air, glaires fréquentes au réveil, raclements de gorge, sinusite chronique, bronchites à répétition, voix enrouée, soupirs spontanés fréquents, fatigue inhabituelle après un effort modéré. Beaucoup de personnes ne réalisent pas qu'elles respirent mal jusqu'à ce qu'on leur fasse prendre conscience d'une respiration thoracique chronique et limitée." },
      { heading: "Exercices respiratoires de drainage", body: "Cohérence cardiaque : 6 respirations par minute (5 secondes inspiration, 5 secondes expiration), 5 minutes 3 fois par jour. Respiration carrée : inspiration 4 sec, rétention 4 sec, expiration 4 sec, rétention 4 sec. Pranayama Kapalabhati (souffle de feu) : expirations actives et rapides par le nez (pratique avancée, prudence). Respiration alternée (Nadi Shodhana) : équilibre les hémisphères et apaise. Au minimum : 10 grandes respirations abdominales au réveil et au coucher." },
      { heading: "Plantes et soutiens pulmonaires", body: "Thym (anti-infectieux, expectorant doux) : 2 à 3 tasses/jour en infusion. Plantain (antitussif et anti-allergique). Mauve (mucilages adoucissants pour les voies irritées). Eucalyptus radié en huile essentielle (diffusion ou inhalation, jamais sur peau pure non diluée). Pin sylvestre (HE tonifiante, surrénales et poumons). Bourgeon de charme et de noisetier en gemmothérapie. Marche en forêt (sylvothérapie) : oxygénation et molécules volatiles bénéfiques émises par les conifères." },
    ],
    keyPoints: [
      "70 m² de surface alvéolaire : émonctoire majeur",
      "20 000 respirations/jour mobilisent 8 000 L d'air",
      "Respiration thoracique chronique limite l'épuration",
      "Cohérence cardiaque : 3 x 5 minutes par jour",
      "Thym, eucalyptus, sylvothérapie : soutiens traditionnels",
    ],
    contre_indications: [
      "Asthme sévère (huiles essentielles très prudentes)",
      "Épilepsie (certaines HE contre-indiquées)",
      "Grossesse (HE à éviter pour la plupart)",
      "Enfants en bas âge (HE pulmonaires interdites)",
      "BPCO sévère (consulter avant tout protocole)",
    ],
    tags: ['poumons', 'bronches', 'respiration', 'émonctoire'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'rotation-emonctoires-protocole',
    domain: 'naturopathie',
    category: 'purges',
    title: "Rotation des émonctoires : protocole sur l'année",
    excerpt: "Travailler les émonctoires en rotation sur l'année plutôt qu'en cumul — protocole annuel naturopathique.",
    readingTime: 5,
    intro: "Plutôt que d'essayer de tout drainer en même temps, la naturopathie traditionnelle propose une rotation des émonctoires sur l'année. Chaque saison, un organe principal, soutenu par les autres. Voici un planning annuel structuré sur cette logique.",
    sections: [
      { heading: "Le principe de rotation", body: "Cumuler les drainants peut surcharger les émonctoires plutôt que de les soulager. En naturopathie classique, on préfère cibler un émonctoire prioritaire par saison, en maintenant les autres en soutien doux. Cette approche respecte la physiologie : on ne demande pas au foie, aux reins et aux intestins d'éliminer simultanément des charges supplémentaires. Le terrain s'allège progressivement, sans crise majeure ni dommage collatéral." },
      { heading: "Printemps : axe hépato-biliaire", body: "Mars-avril-mai. Émonctoire principal : foie + vésicule. Plantes maîtresses : pissenlit, fumeterre, chardon-marie, romarin. Sève de bouleau en cure de 3 semaines. Compresses d'huile de ricin sur le foie. Soutien doux : pissenlit feuille pour les reins, citron quotidien. Alimentation : verdures amères, jeunes pousses, asperges, artichauts. Évitement des alcools, fritures, charcuteries, sucres raffinés." },
      { heading: "Été : axe rénal et cutané", body: "Juin-juillet-août. Émonctoire principal : reins + peau. Plantes maîtresses : hibiscus, bouleau, reine-des-prés, prêle. Cures de jus verts hydratants. Monodiètes de fruits aqueux (pastèque, melon, raisin précoce). Sudation : sauna, bains hyperthermiques, activité physique en plein air. Brossage à sec quotidien. Hydratation 1,5-2 L/jour. Alimentation crue privilégiée (qui supporte). Réduction des protéines animales." },
      { heading: "Automne : axe pulmonaire et reminéralisation", body: "Septembre-octobre-novembre. Émonctoire principal : poumons + reminéralisation. Plantes maîtresses : thym, plantain, ortie, prêle, bambou. Cure de raisin équinoxale. Démarrage vitamine D, probiotiques, propolis. Exercices respiratoires intensifiés. Soutien doux : aubier de tilleul en début de saison pour les reins. Alimentation : courges, châtaignes, racines, soupes mijotées. Réduction des produits laitiers et sucres rapides." },
      { heading: "Hiver : repos et reconstruction", body: "Décembre-janvier-février. Aucun drainage intensif : la saison demande chaleur intérieure et reconstruction. Émonctoire central : intestins (transit). Plantes maîtresses : gingembre, cannelle, curcuma, échinacée en préventif. Cure de magnésium, bouillons d'os, soupes longuement mijotées. Sommeil prioritaire, activité physique modérée. Reminéralisation continue. Préparation discrète à la cure de printemps en allégeant progressivement à partir de fin février." },
    ],
    keyPoints: [
      "Une rotation saisonnière vaut mieux qu'un cumul de drainants",
      "Printemps : foie. Été : reins/peau. Automne : poumons/reminéralisation. Hiver : repos.",
      "L'hiver est une saison de reconstruction, pas de drainage",
      "Chaque saison : un émonctoire principal + soutiens doux",
      "Respecter le rythme naturel = résultats durables",
    ],
    contre_indications: [
      "Pathologies chroniques en cours : adapter avec un thérapeute formé",
      "Grossesse et allaitement",
      "Enfants : pas de cures de drainage avant 12 ans",
      "Insuffisances organiques (foie, reins) : drainage formellement contre-indiqué",
      "Maladies auto-immunes en poussée",
    ],
    tags: ['émonctoires', 'rotation', 'saisons', 'protocole-annuel'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
];
