import type { Article } from '../types';

export const NATURO_BATCH3_VITALITE: Article[] = [
  /* ─────────────────────────────────────────────────────────────
     RESPIRATION-SOMMEIL (4)
  ───────────────────────────────────────────────────────────── */
  {
    slug: 'rituel-sommeil-90-minutes',
    domain: 'naturopathie',
    category: 'respiration-sommeil',
    title: "Le rituel des 90 minutes avant coucher",
    excerpt: "Une fenêtre de 90 minutes pour signaler au corps qu'il est temps de dormir : la cascade hormonale a besoin de temps.",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "L'endormissement n'est pas un interrupteur que l'on bascule en se mettant au lit. C'est une cascade hormonale et nerveuse qui demande environ 90 minutes pour se déployer correctement : baisse du cortisol, libération progressive de mélatonine, abaissement de la température corporelle centrale, ralentissement cardiaque. Installer un rituel sur cette fenêtre transforme la qualité du sommeil sans recourir à aucune molécule.",
    sections: [
      { heading: "Pourquoi 90 minutes ?", body: "La mélatonine commence à être sécrétée environ 2 heures avant l'heure habituelle de coucher, à condition que la luminosité ambiante chute. Le pic n'est atteint qu'au bout d'une heure de pénombre prolongée. Parallèlement, la température corporelle centrale doit baisser de 0,3 à 0,5 °C pour autoriser le sommeil profond. Ces deux phénomènes physiologiques ont besoin de temps. Couper net les écrans à 22h45 pour se coucher à 23h ne laisse à l'organisme aucune marge pour préparer la transition." },
      { heading: "T-90 à T-60 : la décompression sensorielle", body: "Première demi-heure : on baisse l'intensité lumineuse de la maison, on bascule les lampes principales sur des sources chaudes et tamisées, on éteint les écrans principaux (télévision, ordinateur). On range, on prépare les affaires du lendemain. L'idée est d'envoyer au cerveau le signal que la journée est terminée, que plus aucune décision importante ne sera prise. Cette mise en ordre extérieure agit miroir d'une mise en ordre intérieure." },
      { heading: "T-60 à T-30 : la transition corporelle", body: "Douche ou bain tiède (37 à 39 °C, surtout pas chaud) : le pic thermique de surface qui suit favorise paradoxalement la déperdition de chaleur centrale, donc l'endormissement. Étirements doux, automassage de la nuque et des trapèzes, lecture papier ou journal de gratitude. On évite les conversations conflictuelles et les nouvelles anxiogènes. Tisane si désiré : tilleul, verveine, camomille, passiflore." },
      { heading: "T-30 à T-0 : le sas final", body: "Lumière minimale, idéalement seulement une veilleuse ambre. Respiration lente (cohérence cardiaque ou 4-7-8). Pour les esprits qui ruminent : écriture brève des préoccupations sur un carnet pour les externaliser. Pas d'écran, pas de mail, pas de réseaux. On rejoint le lit somnolent, pas seulement fatigué. Si l'endormissement ne vient pas dans les 20 minutes, sortir du lit et reprendre une activité calme à faible lumière, puis y retourner." },
      { heading: "Ce qui rend le rituel efficace", body: "La régularité bien plus que la perfection. Un rituel imparfait répété tous les soirs aux mêmes horaires créera un puissant conditionnement, alors qu'un rituel parfait mais erratique restera sans effet. Compter trois à quatre semaines avant que le corps anticipe la séquence et libère plus tôt la mélatonine. Les soirs où le rituel n'est pas possible (sortie, voyage), reprendre dès le lendemain sans culpabilité." },
    ],
    keyPoints: [
      "La mélatonine et la baisse thermique demandent environ 90 minutes de préparation",
      "Réduire la lumière progressivement plutôt que d'éteindre brutalement",
      "Bain tiède 60 minutes avant coucher favorise la déperdition thermique",
      "Régularité quotidienne supérieure à la perfection ponctuelle",
    ],
    contre_indications: [
      "En cas de troubles bipolaires, certains rituels d'introspection (écriture, journal de soir) peuvent réactiver des ruminations : à adapter avec un professionnel",
      "Ne pas remplacer une consultation pour insomnie chronique (> 3 mois) ou apnée du sommeil suspectée",
    ],
    tags: ['sommeil', 'rituel', 'mélatonine', 'hygiène de vie'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'lumiere-bleue-melatonine',
    domain: 'naturopathie',
    category: 'respiration-sommeil',
    title: "Lumière bleue et mélatonine : comprendre les écrans le soir",
    excerpt: "Pourquoi un écran tardif déprogramme l'horloge interne et comment limiter les dégâts sans bannir totalement la technologie.",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "La lumière bleue (longueur d'onde 460-480 nm) est interprétée par notre horloge biologique comme un signal de plein jour. Émise massivement par les écrans LED, elle inhibe la sécrétion de mélatonine et retarde l'endormissement. Comprendre ce mécanisme permet d'agir sans diaboliser la technologie : ce n'est pas l'écran en soi qui pose problème, c'est l'exposition lumineuse intense à des heures incompatibles avec la chronobiologie humaine.",
    sections: [
      { heading: "Le mécanisme rétinien", body: "Des cellules ganglionnaires rétiniennes contenant la mélanopsine sont spécifiquement sensibles aux longueurs d'onde bleues. Indépendantes de la vision consciente, elles informent le noyau suprachiasmatique de l'hypothalamus, chef d'orchestre de l'horloge biologique. Plus l'exposition à la lumière bleue est forte le soir, plus le cerveau croit qu'il est encore jour et reporte la sécrétion mélatoninergique." },
      { heading: "Ce que mesurent les études", body: "Des essais sur petits échantillons ont montré qu'une exposition de 2 h à un écran LED le soir réduisait significativement la mélatonine salivaire par rapport à un livre papier. L'amplitude de l'effet varie selon les individus, mais la direction est cohérente. Les enfants et adolescents seraient particulièrement sensibles car leur cristallin transparent laisse passer davantage de lumière bleue qu'un cristallin adulte." },
      { heading: "Les solutions hiérarchisées", body: "Solution optimale : éviction totale des écrans 60 à 90 minutes avant le coucher. Solution intermédiaire : mode nuit / filtre orange activé sur tous les appareils dès le coucher du soleil (Night Shift, f.lux, mode lecture). Solution minimale : luminosité écran réduite au maximum, distance d'au moins 50 cm, lunettes à verres ambrés si exposition prolongée inévitable (travail tardif)." },
      { heading: "Les fausses bonnes idées", body: "Les filtres « anti-lumière bleue » sur les lunettes de jour n'ont pas démontré de bénéfice clair et privent inutilement d'un signal lumineux diurne précieux. L'objectif n'est pas de fuir la lumière bleue, mais de la cadrer dans le bon créneau horaire. De même, les compléments de mélatonine doivent rester ponctuels (décalage horaire, travail posté) et ne remplacent pas l'éducation à l'hygiène lumineuse." },
      { heading: "L'exposition matinale, l'autre levier", body: "Symétrique de l'éviction du soir : 15 à 30 minutes de lumière vive (idéalement extérieure, même par temps gris : 10 000 lux contre 300 en intérieur) dès le réveil consolident l'amplitude du rythme circadien. Plus l'horloge biologique est nettement contrastée jour/nuit, mieux le sommeil sera structuré la nuit suivante. Les deux gestes sont indissociables." },
    ],
    keyPoints: [
      "La lumière bleue inhibe la mélatonine via les cellules à mélanopsine",
      "Effets dose-dépendants : durée et intensité comptent",
      "Filtres orange et mode nuit : compromis acceptable si éviction impossible",
      "Lumière matinale en pendant essentiel : contraste jour/nuit",
    ],
    contre_indications: [
      "Les filtres de lumière bleue peuvent altérer la perception des couleurs : à éviter pour les métiers de la création visuelle en journée",
      "Pas d'auto-supplémentation prolongée en mélatonine sans avis médical (interactions médicamenteuses, grossesse)",
    ],
    tags: ['lumière bleue', 'écrans', 'mélatonine', 'chronobiologie'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'temperature-chambre-sommeil-profond',
    domain: 'naturopathie',
    category: 'respiration-sommeil',
    title: "Température de chambre et sommeil profond (16-18 °C)",
    excerpt: "Pourquoi la fraîcheur de la chambre conditionne la profondeur du sommeil et facilite l'endormissement.",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "Le sommeil profond suppose une baisse de la température corporelle centrale d'environ 0,5 °C. Si la pièce est trop chaude, cette déperdition thermique devient impossible, et le corps reste cantonné aux stades légers du sommeil. La recommandation classique d'une chambre fraîche (16 à 18 °C) ne relève pas d'un dogme : elle a un fondement physiologique précis et accessible à l'expérimentation personnelle.",
    sections: [
      { heading: "La thermorégulation circadienne", body: "Notre température centrale n'est pas constante : elle culmine en fin d'après-midi vers 37,2 °C et tombe à environ 36,4 °C en milieu de nuit. Cette descente thermique est un signal d'endormissement aussi puissant que la mélatonine. Si l'environnement empêche le corps de perdre sa chaleur (chambre surchauffée, couette trop épaisse, sous-vêtements serrés), le sommeil profond se fragmente et la sensation de fatigue persiste au réveil." },
      { heading: "La fourchette optimale", body: "Les études polysomnographiques convergent vers une plage de 16 à 19 °C pour un adulte en bonne santé, sous une couette adaptée. La marge personnelle dépend du poids, du métabolisme basal, de la couette et de la saison. Le repère pratique : se sentir frais en entrant dans le lit, puis chaud sous la couette dans les 10 minutes. Si on a chaud en s'endormant et qu'on transpire la nuit, la chambre est trop chaude." },
      { heading: "Stratégies par saison", body: "Hiver : couper le chauffage de la chambre 1 h avant le coucher ou le maintenir au minimum (15 °C). Aérer 5 à 10 min juste avant. Été : ventilateur à vitesse douce, draps en lin ou coton, fenêtre entrouverte la nuit si possible, fermer volets et rideaux en journée. Une serviette humide à proximité ou des chaussettes humides peuvent abaisser de 1 à 2 °C par évaporation." },
      { heading: "L'astuce des extrémités", body: "Paradoxe utile : pour faciliter l'endormissement par climat froid, réchauffer ses pieds (chaussettes, bouillotte) accélère la vasodilatation périphérique et donc la déperdition thermique centrale. C'est exactement le mécanisme du bain tiède pré-coucher. À l'inverse, dormir avec des extrémités froides crampe la circulation et perturbe la transition de phase." },
      { heading: "Cas particuliers", body: "Femmes en péri-ménopause : les bouffées vasomotrices nocturnes imposent souvent une chambre encore plus fraîche (15 °C) et des textiles techniques. Personnes âgées : leur thermorégulation s'altère, une chambre trop froide (< 14 °C) peut au contraire troubler le sommeil et favoriser des problèmes cardiovasculaires. Nourrissons : recommandation officielle 18 à 20 °C avec gigoteuse adaptée, jamais plus chaud." },
    ],
    keyPoints: [
      "Sommeil profond requiert une baisse de 0,5 °C de température centrale",
      "Fourchette optimale 16-19 °C pour un adulte en bonne santé",
      "Réchauffer les pieds favorise la déperdition thermique centrale",
      "Adapter aux contextes : ménopause, âges extrêmes, saisons",
    ],
    contre_indications: [
      "Personnes âgées fragiles : ne pas descendre sous 16 °C (risque cardiovasculaire)",
      "Nourrissons : respecter strictement les recommandations 18-20 °C avec gigoteuse adaptée",
      "Pathologies cardiovasculaires : éviter les écarts thermiques brutaux",
    ],
    tags: ['sommeil profond', 'thermorégulation', 'chambre', 'environnement'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'respiration-coherente-quotidien',
    domain: 'naturopathie',
    category: 'respiration-sommeil',
    title: "Intégrer la respiration cohérente au quotidien",
    excerpt: "Au-delà des 3x5 minutes : comment ancrer la cohérence cardiaque dans des situations de la vie ordinaire.",
    readingTime: 5,
    evidence_level: 'rct',
    intro: "La cohérence cardiaque (6 respirations/minute) bénéficie d'un nombre croissant d'essais montrant un effet sur la variabilité de la fréquence cardiaque et le tonus parasympathique. Le protocole 365 (3 fois 5 minutes par jour à 6 cycles/min) est largement répandu, mais limite la pratique à des plages isolées. L'enjeu est d'intégrer cette respiration à des moments de transition naturels de la journée pour transformer une discipline en réflexe.",
    sections: [
      { heading: "Pourquoi 6 cycles par minute", body: "Cette fréquence (5 sec d'inspiration + 5 sec d'expiration) correspond chez la plupart des adultes à la fréquence de résonance du système cardiovasculaire. À cette cadence, la variabilité de la fréquence cardiaque atteint son amplitude maximale, signe d'un équilibre optimal entre branches sympathique et parasympathique du système nerveux autonome. C'est une fréquence à mémoriser plus qu'à mesurer : avec l'habitude, le corps la retrouve seul." },
      { heading: "Les trois moments-clés du 365", body: "Matin au réveil : avant tout, avant café, avant écran. Programme la qualité de la matinée. Midi avant le déjeuner : coupe la dynamique sympathique du travail, favorise une digestion détendue. Fin d'après-midi (16-17h) : prévient la baisse d'énergie et la nervosité de fin de journée, encadre la transition vers la soirée. Cinq minutes chaque fois, idéalement assis, dos droit." },
      { heading: "Les moments d'opportunité", body: "Au-delà du 365 protocolaire : avant un entretien, un appel difficile, une décision importante. Dans la file d'attente, dans les transports en commun, en marchant. Aux toilettes. Avant et après un repas. Pendant un embouteillage (sans fermer les yeux). Au lit avant l'endormissement (1 à 2 cycles suffisent souvent à basculer en sommeil). Chaque moment de transition est une porte d'entrée." },
      { heading: "Les outils d'aide à la pratique", body: "Applications gratuites (RespiRelax+, Petit BamBou, Calm) avec guide visuel circulaire ou sphère qui dilate. Vidéos YouTube de 5 min avec rythme sonore. Pour les pratiquants confirmés : abandonner les supports et compter mentalement, ce qui ajoute une discipline attentionnelle. Au bout de quelques semaines, le rythme s'installe spontanément dès qu'on porte attention au souffle." },
      { heading: "Ce qu'on observe au bout de 3 semaines", body: "Auto-rapports cohérents : sommeil plus rapide à venir, ruminations moins envahissantes, fréquence cardiaque de repos légèrement abaissée, sensation de retour au calme plus accessible en situation. Les essais publiés montrent une amélioration de la HRV et une baisse modeste de l'anxiété auto-évaluée. La pratique ne guérit pas un trouble anxieux mais offre un levier toujours disponible, gratuit et sans effet secondaire." },
    ],
    keyPoints: [
      "Fréquence cible : 6 cycles/minute (5 sec inspi + 5 sec expi)",
      "Protocole 365 : 3 fois 5 minutes répartis dans la journée",
      "Moments d'opportunité : avant événements stressants, transitions",
      "Outils gratuits puis autonomie au bout de quelques semaines",
    ],
    contre_indications: [
      "Pathologies pulmonaires sévères (BPCO, asthme instable) : adapter avec un kinésithérapeute respiratoire",
      "Vertiges paroxystiques : pratiquer assis ou allongé",
      "Pas un substitut à un traitement anxiolytique prescrit",
    ],
    tags: ['cohérence cardiaque', 'respiration', 'HRV', 'quotidien'],
    updatedAt: '2026-05-29',
  },

  /* ─────────────────────────────────────────────────────────────
     STRESS-EMOTIONS (4)
  ───────────────────────────────────────────────────────────── */
  {
    slug: 'cortisol-rythme-circadien',
    domain: 'naturopathie',
    category: 'stress-emotions',
    title: "Le cortisol et son rythme circadien naturel",
    excerpt: "Comprendre le cycle du cortisol pour respecter sa physiologie : haut le matin, bas le soir.",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "Le cortisol n'est pas une hormone du stress en soi, c'est une hormone du rythme. Sécrété par les glandes surrénales sous contrôle de l'axe hypothalamo-hypophyso-surrénalien, il suit normalement une courbe en cloche très précise sur 24 heures : pic au réveil, déclin progressif, plancher en début de nuit. Quand cette courbe se déforme, c'est tout l'équilibre énergétique et émotionnel qui vacille.",
    sections: [
      { heading: "La courbe physiologique", body: "Au réveil, dans les 30 à 45 minutes qui suivent l'ouverture des yeux, le cortisol monte de 50 à 75 % : c'est le « Cortisol Awakening Response » (CAR), signal de mise en route. Il reste élevé toute la matinée, déclinant doucement jusqu'à midi. L'après-midi continue la décrue. En soirée, il s'effondre, laissant la place à la mélatonine. Le minimum est atteint entre minuit et 3 h. Puis la remontée commence." },
      { heading: "Les déformations typiques", body: "Cortisol plat (épuisement) : la courbe perd son amplitude, le matin n'est pas franc, la fatigue est constante. Cortisol inversé : pic en soirée, plancher au réveil — typique du surmenage installé, on est épuisé le matin et tendu le soir. Cortisol haut chronique : la courbe ne redescend plus vraiment, hypervigilance, insomnie, prise de poids abdominale. Cortisol bas global : signe d'épuisement avancé, à explorer médicalement." },
      { heading: "Les facteurs qui pertubent la courbe", body: "Lumière artificielle nocturne (retarde le pic du lendemain). Café tardif (allonge l'effet du cortisol existant). Sport intense le soir (relance la production). Stress chronique non récupéré. Travail posté ou décalé. Repas tardifs et copieux. Alcool (perturbe l'amplitude). Manque de lumière naturelle matinale. Réveil sans transition (snooze répétés)." },
      { heading: "Comment soutenir la courbe naturelle", body: "Le matin : exposition à la lumière vive dès le lever (idéalement extérieur 10 min), petit-déjeuner protéiné dans l'heure, mouvement modéré (étirements, marche). Journée : caféine avant 14 h, repas réguliers. Soirée : lumière chaude tamisée dès le coucher du soleil, dîner léger avant 20 h, pas de sport intense, pas d'écran 1 h avant lit. Ces gestes simples respectent la sécrétion endogène." },
      { heading: "Quand mesurer ?", body: "Le dosage classique sanguin du matin reste peu informatif sur la courbe globale. Pour évaluer le rythme, le test salivaire à 4 points (réveil, 30 min après, midi, soir/coucher) est plus pertinent. Il n'est pas remboursé en France et reste indiqué seulement en cas de signes francs (épuisement profond, suspicion d'insuffisance surrénalienne). À discuter avec un médecin orienté chronobiologie." },
    ],
    keyPoints: [
      "Cortisol = hormone du rythme, pas seulement du stress",
      "Pic matinal CAR : 50-75 % d'augmentation en 30-45 min",
      "Déformations typiques : plat, inversé, haut chronique",
      "Lumière, café, repas, sport : leviers comportementaux clairs",
    ],
    contre_indications: [
      "Suspicion d'insuffisance surrénalienne ou Cushing : exploration médicale impérative, pas d'auto-prise en charge",
      "Pas de supplémentation hormonale (cortisone, prégnénolone) sans avis médical",
      "Les adaptogènes (ashwagandha, rhodiole) à éviter en cas de pathologie auto-immune sans avis spécialisé",
    ],
    tags: ['cortisol', 'surrénales', 'rythme circadien', 'stress'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'burn-out-phases-naturopathie',
    domain: 'naturopathie',
    category: 'stress-emotions',
    title: "Les 3 phases du burn-out vues par la naturopathie",
    excerpt: "Alarme, résistance, épuisement : le modèle adaptatif de Selye relu à l'aune de la naturopathie de terrain.",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "Hans Selye, endocrinologue, a décrit dès 1936 le « syndrome général d'adaptation » : la réponse stéréotypée de l'organisme face à toute agression prolongée. La naturopathie a repris ce modèle pour cartographier les phases du burn-out et identifier les leviers d'action à chaque étape. Comprendre où l'on en est conditionne la stratégie : ce qui aide en phase 1 peut aggraver en phase 3.",
    sections: [
      { heading: "Phase 1 : alarme (jours à semaines)", body: "Réponse aiguë au stress : adrénaline et cortisol grimpent, le sympathique s'emballe. Signes : sommeil dégradé (endormissement difficile, réveils précoces), tensions musculaires, irritabilité, café compensateur, alcool décompresseur. L'énergie semble encore là, on tient. C'est paradoxalement la phase la plus accessible : un repos vrai, des gestes simples de régulation suffisent souvent à revenir à l'équilibre. La fenêtre est étroite avant le glissement." },
      { heading: "Phase 2 : résistance (semaines à mois)", body: "L'organisme s'adapte au stress en sollicitant en continu les surrénales. Cortisol haut chronique. Apparaissent : prise de poids abdominale, hyperphagie ou pertes d'appétit, infections à répétition, troubles digestifs, baisse de libido, irritabilité chronique. On « tient » mais à un coût croissant. La vie sociale et créative se rétracte. C'est la phase où les adaptogènes (ashwagandha, rhodiole) peuvent encore aider, sous supervision." },
      { heading: "Phase 3 : épuisement (mois à années)", body: "Les surrénales ne suivent plus, la courbe de cortisol s'aplatit ou s'inverse. Fatigue profonde non récupérée par le sommeil, indifférence affective, perte de sens, dépression, troubles cognitifs (mémoire, concentration), parfois douleurs diffuses. Les stimulants (café, sucre, adaptogènes) ne fonctionnent plus, voire aggravent. Il faut sortir du contexte stressant, parfois plusieurs mois, et reconstruire pas à pas." },
      { heading: "Stratégies par phase", body: "Phase 1 : régulation immédiate (cohérence cardiaque, sommeil, magnésium, retrait des stimulants), examen du contexte avant qu'il ne devienne intenable. Phase 2 : soutien renforcé (adaptogènes, vitamine C, B5, B6, magnésium, oméga-3) ET réorganisation de fond du contexte (charge, frontières, accompagnement). Phase 3 : ARRÊT du contexte, suivi médical pluridisciplinaire (médecin traitant, psychiatre ou psychologue, parfois micronutritionniste), reconstruction lente sur 6 à 24 mois." },
      { heading: "L'erreur fréquente", body: "Vouloir traiter une phase 3 avec les outils de la phase 1. À ce stade, la cohérence cardiaque et les huiles essentielles ne suffisent pas, et les adaptogènes peuvent aggraver l'épuisement. Inversement, négliger une phase 1 en se disant « ça va passer » conduit souvent à la phase 2 puis 3. Reconnaître où l'on en est, sans honte ni dramatisation, est la première étape d'un retour vers la vitalité." },
    ],
    keyPoints: [
      "Modèle de Selye : alarme, résistance, épuisement",
      "Phase 1 : régulation simple suffit souvent",
      "Phase 2 : soutien + réorganisation du contexte",
      "Phase 3 : arrêt du contexte + suivi médical pluridisciplinaire",
    ],
    contre_indications: [
      "Le burn-out avéré relève d'une prise en charge médicale, pas naturopathique seule",
      "Idées noires, perte d'élan vital, troubles cognitifs marqués : urgence médicale, ne pas attendre",
      "Pas d'auto-supplémentation adaptogène en phase d'épuisement (effet possible inverse)",
    ],
    tags: ['burn-out', 'stress chronique', 'surrénales', 'Selye'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'gratitude-pratique-quotidienne',
    domain: 'naturopathie',
    category: 'stress-emotions',
    title: "La pratique de gratitude : impact sur la physiologie",
    excerpt: "Au-delà du développement personnel : ce que mesurent les essais sur la gratitude écrite quotidienne.",
    readingTime: 5,
    evidence_level: 'rct',
    intro: "La gratitude est passée du registre spirituel au laboratoire de psychologie positive. Plusieurs essais contrôlés randomisés ont évalué l'impact d'une pratique régulière (souvent : trois éléments de gratitude écrits chaque soir) sur la santé mentale et physique. Les résultats convergent vers un effet modeste mais réel : sommeil amélioré, biais attentionnels modifiés, marqueurs de stress diminués. La gratitude est devenue un outil naturopathique légitime.",
    sections: [
      { heading: "Le mécanisme proposé", body: "Notre cerveau est câblé pour détecter les menaces (biais de négativité) — utile à la survie, dévastateur pour le moral. Pratiquer la gratitude consiste à réentraîner volontairement l'attention vers le positif disponible. Cette répétition modifierait progressivement les réseaux attentionnels par défaut. Des études d'imagerie montrent une activation du cortex préfrontal médian associée à des baisses du cortisol salivaire après pratique répétée. Le mécanisme reste discuté mais la trace physiologique est mesurable." },
      { heading: "Le protocole le plus étudié", body: "Trois bonnes choses (Three Good Things) : chaque soir, écrire à la main trois éléments positifs de la journée, même minuscules (« le café était bon », « collègue qui m'a souri »), et pour chacun, noter en une phrase « pourquoi c'est arrivé » ou « ce qui m'a permis d'en profiter ». 5 minutes. Protocole validé par Seligman et collaborateurs avec des effets persistant à 6 mois post-intervention dans plusieurs essais." },
      { heading: "Ce que mesurent les essais", body: "Amélioration auto-rapportée du bien-être subjectif, baisse de symptômes dépressifs légers à modérés, amélioration de la qualité du sommeil (s'endormir avec un focus positif), réduction des plaintes somatiques. Sur biomarqueurs : baisse modeste mais cohérente du cortisol matinal et de marqueurs inflammatoires (CRP, IL-6) chez les pratiquants réguliers. L'effet est modeste — pas un médicament — mais réel et sans coût." },
      { heading: "Les variantes", body: "Lettre de gratitude : écrire à une personne à qui on n'a jamais dit merci, idéalement la lui remettre ou lire. Effet marqué dans un essai (jusqu'à 1 mois post-intervention). Gratitude au réveil : noter 3 éléments d'anticipation positive pour la journée. Gratitude relationnelle : exprimer chaque jour une reconnaissance verbalisée à un proche. Méditation de gratitude : 10 min de scan corporel orienté reconnaissance." },
      { heading: "Les pièges à éviter", body: "Faire de la gratitude un déni : nier les difficultés réelles, transformer en injonction positive aggrave parfois la souffrance (« je devrais être reconnaissant, pourquoi je ne le suis pas »). La pratique doit cohabiter avec la reconnaissance honnête des difficultés. Personnes en épisode dépressif majeur : la pratique seule ne suffit pas, elle peut accompagner mais pas remplacer un traitement. Pratique à abandonner si elle génère de la culpabilité." },
    ],
    keyPoints: [
      "Trois bonnes choses : 5 min/soir, effet durable jusqu'à 6 mois",
      "Mécanisme : réentraînement des biais attentionnels par défaut",
      "Mesurable sur cortisol, marqueurs inflammatoires, sommeil",
      "Outil complémentaire, pas substitut à un traitement",
    ],
    contre_indications: [
      "Épisode dépressif majeur : la pratique peut accompagner mais non remplacer un soin",
      "Personnes vivant un deuil aigu, traumatisme récent : risque d'injonction positive contre-productive",
      "Si la pratique génère culpabilité ou auto-jugement, l'arrêter sans hésiter",
    ],
    tags: ['gratitude', 'psychologie positive', 'cortisol', 'sommeil'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'nature-walking-shinrin-yoku',
    domain: 'naturopathie',
    category: 'stress-emotions',
    title: "Le walking en nature : adaptation française du shinrin-yoku",
    excerpt: "Le bain de forêt japonais sans forêt primaire : comment l'adapter avec les forêts tempérées françaises.",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "Le shinrin-yoku, ou « bain de forêt », est une pratique japonaise institutionnalisée depuis les années 1980 et adoptée par la santé publique nipponne. Plusieurs essais publiés au Japon, en Corée et plus récemment en Europe ont montré des effets mesurables sur le cortisol, la tension artérielle et l'immunité (cellules NK). En France, on peut transposer la pratique aux forêts tempérées sans en perdre les bénéfices essentiels.",
    sections: [
      { heading: "Le principe original", body: "Marcher lentement dans une forêt en mobilisant les cinq sens : sentir l'odeur de l'humus et des résines, écouter les bruits subtils, toucher les écorces, observer les détails de la canopée. La marche n'est pas sportive (4-5 km/h, pas plus), elle est contemplative. Durée recommandée : 2 à 4 heures pour un bénéfice classique, mais des effets sont mesurés dès 20 à 40 minutes selon plusieurs essais." },
      { heading: "Ce qu'on mesure", body: "Baisse de cortisol salivaire après 30 à 60 min en forêt par rapport à zone urbaine appariée. Baisse de la tension artérielle systolique et diastolique. Augmentation de l'activité des cellules NK (immunité) persistant plusieurs jours après l'exposition, attribuée en partie aux phytoncides (composés volatils terpéniques émis par les conifères). Amélioration des scores de bien-être et baisse des symptômes anxieux modérés. Effets observés autant chez sujets sains que pathologiques." },
      { heading: "L'adaptation française", body: "Pas besoin de forêt primaire japonaise. Toute forêt mature française fonctionne : chênaies, hêtraies, sapinières des Vosges ou du Jura, forêts méditerranéennes. Idéalement, choisir un sentier peu fréquenté, sans visée sportive. 90 minutes minimum, 2 à 3 fois par semaine pour les habitants à proximité, sinon une fois par semaine et une session longue (3-4 h) le week-end. Les pins maritimes ou douglas seraient particulièrement riches en phytoncides." },
      { heading: "Le protocole simple", body: "Couper le téléphone (mode avion ou silencieux profond), prévoir un temps non chronométré. 10 premières minutes : marche pour s'éloigner du parking ou de la route. Puis : ralentir progressivement, pauses régulières, s'asseoir contre un arbre, fermer les yeux 5 minutes, écouter. Reprendre lentement. Pas de podcast, pas de musique. Ramener un objet (feuille, écorce) comme ancrage sensoriel pour la semaine." },
      { heading: "Substitut urbain", body: "Quand la forêt n'est pas accessible : un grand parc avec arbres matures (Buttes-Chaumont, parc de Sceaux, jardin des Plantes) procure une partie des effets. Les essais récents montrent qu'un « green time » de 20 à 30 min en parc urbain dense baisse mesurablement le cortisol. Sans remplacer la forêt, c'est une option valable pour les citadins en semaine, à coupler avec une vraie immersion forestière le week-end." },
    ],
    keyPoints: [
      "Marche lente, sensorielle, 90 min minimum",
      "Phytoncides des conifères contribuent à l'effet immunitaire",
      "Effet mesurable sur cortisol, tension, cellules NK",
      "Forêts françaises tempérées : substituts pertinents",
    ],
    contre_indications: [
      "Allergies sévères aux pollens : éviter les pics saisonniers",
      "Maladie de Lyme : prévention indispensable (tenue, répulsifs, inspection au retour)",
      "Mobilité réduite : choisir des sentiers accessibles, ne pas surévaluer ses capacités",
    ],
    tags: ['shinrin-yoku', 'nature', 'cortisol', 'immunité'],
    updatedAt: '2026-05-29',
  },

  /* ─────────────────────────────────────────────────────────────
     ALIMENTATION (4)
  ───────────────────────────────────────────────────────────── */
  {
    slug: 'petit-dejeuner-proteine',
    domain: 'naturopathie',
    category: 'alimentation',
    title: "Le petit-déjeuner protéiné : pourquoi rompre avec le sucré",
    excerpt: "Le petit-déjeuner classique français est un dessert. Quelle alternative pour stabiliser l'énergie de la matinée ?",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "Le petit-déjeuner français traditionnel — pain, confiture, jus de fruit, café sucré — est une bombe glucidique qui produit une glycémie en montagnes russes : pic dans l'heure, chute brutale vers 11 h avec fatigue, fringale, irritabilité. Remplacer ces glucides rapides par une vraie source protéique transforme la matinée et nourrit progressivement l'idée d'autonomie énergétique.",
    sections: [
      { heading: "Le problème glycémique", body: "Pain blanc, viennoiserie, céréales sucrées et jus d'orange ont un index glycémique élevé. La glycémie monte rapidement, l'insuline est sécrétée massivement, le sucre est stocké, et 2 à 3 heures plus tard la glycémie chute sous son niveau de départ. Cette hypoglycémie réactionnelle déclenche : fatigue, fringale sucrée (cercle vicieux), perte de concentration. Sur la durée : prise de poids abdominale, fatigue chronique, terrain inflammatoire." },
      { heading: "Pourquoi les protéines stabilisent", body: "Les protéines (œufs, poisson, fromage de qualité, légumineuses, oléagineux) ralentissent la vidange gastrique, modèrent la glycémie post-prandiale et sont plus rassasiantes par gramme que les glucides. Elles fournissent les acides aminés précurseurs des neurotransmetteurs (tyrosine pour dopamine, tryptophane pour sérotonine) nécessaires au tonus et à la motivation de la matinée. Effet métabolique mais aussi neuro-cognitif." },
      { heading: "Trois formats simples", body: "Format œufs : 2 œufs (brouillés, mollets ou coque) + tranche de pain complet au levain + un fruit + thé. Format scandinave : tranche de pain complet + saumon fumé ou maquereau + avocat + café noir. Format végétal : porridge d'avoine cuit dans lait végétal enrichi + cuillère à soupe de purée d'amande + cuillère à café de graines de chia + petit fruit rouge. Compter 20 à 25 g de protéines effectives." },
      { heading: "La transition en douceur", body: "Passer d'un petit-déjeuner sucré à protéiné peut sembler abrupt. Stratégie progressive sur 2 semaines : semaine 1, on conserve le format habituel mais on ajoute systématiquement une source protéique (1 œuf, une portion de fromage blanc, des oléagineux). Semaine 2, on diminue le sucré tout en gardant le protéique. Goûter à 10 h non culpabilisé si la faim arrive : oléagineux et fruit. L'appétit matinal se stabilise en 2 à 3 semaines." },
      { heading: "Ce que ça change concrètement", body: "Énergie stable de 8 h à 12 h sans coup de barre. Disparition progressive des fringales sucrées de 11 h et 16 h. Concentration plus soutenue. Régulation de l'appétit globale, parfois perte des kilos abdominaux installés. Pour les sportifs : meilleure récupération matinale. Pour les diabétiques type 2 (sous contrôle médical) : amélioration documentée de la glycémie à jeun." },
    ],
    keyPoints: [
      "Petit-déjeuner sucré classique = pic glycémique puis chute",
      "Protéines : satiété, stabilité, précurseurs de neurotransmetteurs",
      "Viser 20-25 g de protéines effectives",
      "Transition progressive sur 2-3 semaines",
    ],
    contre_indications: [
      "Insuffisance rénale chronique : adapter l'apport protéique avec un médecin",
      "Pathologies digestives spécifiques (gastrite érosive, RGO matinal) : adapter au cas par cas",
      "Enfants en pleine croissance : ne pas restreindre les glucides, ajouter simplement des protéines",
    ],
    tags: ['petit-déjeuner', 'protéines', 'glycémie', 'énergie'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'cuisson-douce-vitalite',
    domain: 'naturopathie',
    category: 'alimentation',
    title: "Cuisson douce et préservation de la vitalité alimentaire",
    excerpt: "Vapeur, étouffée, basse température : comment cuire sans dénaturer ni générer de composés délétères.",
    readingTime: 5,
    evidence_level: 'preliminary',
    intro: "La cuisson transforme les aliments — elle améliore la digestibilité, neutralise certains anti-nutriments, libère des saveurs — mais à doses élevées, elle peut détruire vitamines thermosensibles, dénaturer protéines et lipides, et générer des composés indésirables (acrylamides, AGE, oxydation des huiles). Les cuissons dites « douces » cherchent l'équilibre : transformer ce qui doit l'être, préserver ce qui peut l'être.",
    sections: [
      { heading: "Les températures critiques", body: "À partir de 100 °C : pertes en vitamine C et folates (B9). À partir de 110 °C : début de la réaction de Maillard, savoureuse mais productrice de composés glycotoxiques (AGE) à hautes températures. À partir de 120 °C dans les amidons : formation d'acrylamide (potentiellement cancérigène). À partir de 180 °C : oxydation accélérée des huiles, formation d'aldéhydes. La cuisson douce vise à rester sous 100 °C autant que possible, ou à minimiser le temps au-dessus." },
      { heading: "Les modes de cuisson recommandés", body: "Vapeur douce (90-95 °C) : optimale pour légumes, poissons. Préserve textures et micronutriments. Étouffée (compote, ragoût à feu très doux dans un peu d'eau) : convient aux légumes-racines, viandes maigres. Basse température au four (60-80 °C en cœur de protéine) : magistrale pour viandes et poissons, attendrit sans dénaturer. Pochage léger (eau frémissante, 70-90 °C) : œufs, poissons, fruits." },
      { heading: "À limiter ou éviter", body: "Friture profonde : oxydation des huiles, formation d'aldéhydes, charge calorique vide. Grillade carbonisée : formation de HAP cancérigènes potentiels. Cuisson au micro-ondes prolongée : effet débattu, mais à modérer pour les légumes thermosensibles. Réchauffages successifs des huiles. Les cuissons rapides à très haute température (wok, plancha) sont acceptables ponctuellement si l'huile résiste (ghee, huile d'olive haute oléique)." },
      { heading: "Le geste cru complémentaire", body: "Toute cuisson, même douce, réduit certains micronutriments. Compléter chaque repas par une fraction crue (crudités d'entrée, fruit en fin) apporte vitamines C, enzymes, polyphénols intacts. Cible pratique : 30-40 % de l'apport végétal cru, 60-70 % cuit doux. Ratio à moduler selon la saison (plus de cru l'été, plus de cuit doux l'hiver) et la tolérance digestive individuelle (les terrains nerveux digèrent mal trop de cru)." },
      { heading: "Le matériel utile", body: "Cuit-vapeur en inox ou bambou (éviter aluminium nu et plastiques chauffés). Cocotte en fonte émaillée pour étouffées. Four avec sonde de cuisson pour basse température. Wok en acier pour cuissons brèves bien maîtrisées. Pas besoin d'investir lourdement : une casserole et un panier vapeur suffisent à transformer 80 % des cuissons quotidiennes vers la douceur. L'inertie d'une bonne casserole permet souvent de finir la cuisson hors feu." },
    ],
    keyPoints: [
      "Sous 100 °C : préservation maximale des nutriments thermosensibles",
      "Vapeur, étouffée, basse température : trois alliées principales",
      "Friture profonde et grillade carbonisée à limiter",
      "Compléter par une fraction crue à chaque repas",
    ],
    contre_indications: [
      "Personnes immunodéprimées : vigilance accrue sur la cuisson des produits animaux (température à cœur minimale impérative)",
      "Femmes enceintes : éviter les cuissons à cœur insuffisantes (toxoplasmose, listeria)",
      "Digestion fragile : ratio cru/cuit à diminuer en faveur du cuit doux",
    ],
    tags: ['cuisson', 'vapeur', 'vitamines', 'vitalité'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'masticer-30-fois',
    domain: 'naturopathie',
    category: 'alimentation',
    title: "La règle des 30 mastications : prédigestion et satiété",
    excerpt: "Mastiquer chaque bouchée 30 fois : tradition ancienne, levier digestif et de satiété mesurable.",
    readingTime: 5,
    evidence_level: 'tradition',
    intro: "Horace Fletcher, hygiéniste américain du début du XXᵉ siècle surnommé « le grand mastiqueur », recommandait 32 mastications par bouchée. Cette pratique paraît anecdotique mais condense plusieurs leviers physiologiques majeurs : prédigestion buccale, signaux de satiété, ralentissement du rythme alimentaire. Aucune méta-analyse récente n'évalue la règle des 30 mastications en tant que telle, mais les principes physiologiques sous-jacents sont solides.",
    sections: [
      { heading: "La bouche est un organe digestif", body: "La salive contient l'amylase, enzyme qui commence à découper l'amidon dès la bouche. La mastication broie mécaniquement les fibres végétales, ouvrant la cellulose qui emprisonne les nutriments. Bien mastiquer, c'est offrir à l'estomac un bol alimentaire déjà partiellement transformé. À l'inverse, avaler vite des morceaux insuffisamment broyés impose à l'estomac et à l'intestin un surtravail qui se traduit par lourdeurs, ballonnements, et absorption moindre des micronutriments." },
      { heading: "Le signal de satiété", body: "Le cerveau reçoit le signal de satiété environ 20 minutes après le début du repas, via la leptine et la cholécystokinine. Si on mange en 10 minutes, on a le temps d'ingérer beaucoup plus que ce dont le corps a besoin avant que le frein ne tombe. Mastiquer suffisamment ralentit mécaniquement le rythme, donne le temps au signal d'arriver, et conduit naturellement à manger moins sans sensation de privation. Plusieurs essais montrent une baisse spontanée de 10 à 15 % de l'apport calorique." },
      { heading: "Le test des 30 mastications", body: "Compter 30 mastications par bouchée semble fastidieux ; en pratique, on ne compte que les premières bouchées pour calibrer. Repère sensoriel plus utile : la bouchée doit avoir perdu sa texture initiale, devenir crémeuse, le goût doit avoir évolué. Pour un aliment liquide (soupe, jus) : « mastiquer » mentalement quelques secondes en bouche avant d'avaler. Le pain blanc, les céréales raffinées et les viandes molles passent souvent trop vite — y prêter attention en priorité." },
      { heading: "Effets observés", body: "Digestion plus légère, gaz et ballonnements réduits, sensation de satiété installée à la fin du repas plutôt qu'une heure après. Pour beaucoup, perte spontanée de quelques kilos sur 2 à 3 mois sans autre changement, par simple modération naturelle des quantités. Plaisir gustatif accru : les saveurs ont le temps de se déployer. Conversations apaisées à table — un repas mastiqué est par essence un repas partagé plus posément." },
      { heading: "Les obstacles pratiques", body: "Repas pris en 10 minutes au travail. Manger devant un écran (attention captée ailleurs). Stress qui pousse à avaler. Dentition altérée (consulter un dentiste si la mastication est douloureuse). Stratégies : poser la fourchette entre chaque bouchée. S'asseoir à table sans écran. Manger en pleine attention quelques bouchées au début du repas pour amorcer le ralentissement. La règle des 30 n'est pas un dogme : un effort imparfait apporte déjà un bénéfice net." },
    ],
    keyPoints: [
      "Mastication : prédigestion buccale + signal de satiété",
      "Signal de satiété à 20 min : ralentir, c'est manger moins sans frustration",
      "Repère sensoriel : bouchée devenue crémeuse, saveur évoluée",
      "Baisse spontanée d'apport calorique de 10-15 % dans plusieurs essais",
    ],
    contre_indications: [
      "Pathologies dentaires ou ATM douloureuses : consulter un dentiste, adapter texture",
      "Troubles du comportement alimentaire : ne pas surajouter de règle pouvant rigidifier le rapport à la nourriture",
      "Repas du nourrisson et jeune enfant : autres principes",
    ],
    tags: ['mastication', 'digestion', 'satiété', 'tradition'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'eau-citronnee-matin',
    domain: 'naturopathie',
    category: 'alimentation',
    title: "L'eau citronnée du matin : tradition et bénéfices",
    excerpt: "Un grand classique de la naturopathie : utile, neutre ou risqué ? Lecture nuancée d'une pratique populaire.",
    readingTime: 5,
    evidence_level: 'tradition',
    intro: "Un verre d'eau tiède avec le jus d'un demi-citron à jeun : c'est probablement le geste le plus partagé sur les réseaux du bien-être. La pratique a une histoire ancienne (Ayurveda, médecine traditionnelle européenne) et de nombreux bienfaits lui sont attribués. Que reste-t-il après examen ? Une boisson simple, plutôt utile pour beaucoup, mais inadaptée pour certains profils.",
    sections: [
      { heading: "Les bénéfices crédibles", body: "Réhydratation après la nuit (le corps a perdu de l'eau pendant le sommeil). Stimulation douce du péristaltisme intestinal, utile en cas de transit paresseux. Apport modeste en vitamine C (un demi-citron = environ 25 mg, soit un quart des AJR). Stimulation des sucs digestifs en amorce du petit-déjeuner. Plaisir sensoriel et signal de mise en route métabolique. Effet placebo positif documenté : un rituel matinal bien posé installe une discipline de santé globale." },
      { heading: "Les bénéfices surévalués", body: "« Alcalinise le corps » : les solutions de citron sont acides, et le pH sanguin est régulé strictement par les poumons et les reins. Aucun aliment ne modifie significativement le pH sanguin. « Détoxifie le foie » : le foie possède ses propres systèmes enzymatiques de détoxification, le citron ne les remplace ni ne les accélère mesurablement. « Fait maigrir » : aucune étude sérieuse ne confirme un effet amaigrissant direct ; l'effet, s'il existe, vient probablement de la routine globale et de la satiété qu'apporte un grand verre d'eau." },
      { heading: "Le protocole simple", body: "Le matin à jeun, 15-20 min avant le petit-déjeuner : jus d'un demi-citron pressé dans un grand verre (200-250 ml) d'eau tiède (pas chaude, pas glacée). Boire lentement. Rincer la bouche à l'eau claire après (acidité dentaire). Attendre au moins 30 min avant de se brosser les dents (l'émail est temporairement plus fragile après l'acide). Préférer un citron bio, jaune ou vert au choix." },
      { heading: "Pour qui ce n'est pas adapté", body: "Reflux gastro-œsophagien (RGO) : l'acidité peut aggraver les brûlures. Ulcère gastrique ou gastrite érosive : éviter. Émail dentaire fragile, hypersensibilité dentinaire : limiter ou diluer fortement. Lithiases rénales oxalo-calciques : le citron est plutôt protecteur (citrate) mais à valider médicalement selon le type de calcul. Allergie aux agrumes (rare). En cas de doute, écouter ses sensations : si la pratique génère brûlures, douleurs ou nausées, abandonner sans regret." },
      { heading: "L'esprit du geste", body: "Le bénéfice principal de l'eau citronnée n'est probablement pas chimique mais rituélique : se réveiller, prendre un temps pour soi, boire en pleine conscience avant les sollicitations de la journée, signaler au corps que la journée commence. Un grand verre d'eau plate à température ambiante apporte presque les mêmes bénéfices d'hydratation et de péristaltisme. L'essentiel est le geste, plus que la recette précise." },
    ],
    keyPoints: [
      "Bénéfices crédibles : hydratation, transit, vitamine C modeste",
      "Affirmations surévaluées : pas d'alcalinisation, pas de détox foie, pas d'effet amaigrissant direct",
      "Rinçage de bouche et délai avant brossage : protection de l'émail",
      "Le geste rituélique compte autant que le contenu chimique",
    ],
    contre_indications: [
      "Reflux gastro-œsophagien, ulcère, gastrite érosive : à éviter",
      "Émail dentaire fragile : limiter ou très diluer",
      "Lithiases rénales : valider avec un médecin selon le type",
      "Allergie aux agrumes",
    ],
    tags: ['citron', 'matin', 'hydratation', 'tradition'],
    updatedAt: '2026-05-29',
  },
];
