import type { Article } from '../types';

export const NATURO_BATCH3_TECHNIQUES: Article[] = [
  /* ─────────────────────────────────────────
     HYDROTHÉRAPIE (4 articles)
  ───────────────────────────────────────── */
  {
    slug: 'cure-thermale-tradition',
    domain: 'naturopathie',
    category: 'hydrotherapie',
    title: "Les cures thermales : tradition européenne",
    excerpt: "Trois semaines d'eau thermale, de boue et de vapeur : héritage millénaire toujours remboursé en France pour douze orientations thérapeutiques.",
    readingTime: 5,
    evidence_level: 'preliminary',
    evidence_note: "La balnéologie française dispose de quelques essais cliniques modestes (rhumatologie, voies respiratoires, dermatologie) montrant un signal favorable sur la douleur et la qualité de vie, sans méta-analyses concluantes. La tradition est solide, les preuves restent partielles.",
    intro: "La cure thermale — trois semaines de soins quotidiens dans une station agréée — est l'un des derniers vestiges institutionnels de la naturopathie en Europe. Héritée des bains romains, codifiée au XIXe siècle, encore remboursée par la Sécurité sociale française au titre de douze orientations thérapeutiques, elle combine eau minérale, boue, vapeur et repos dans un cadre médicalisé.",
    sections: [
      { heading: "Un héritage qui traverse les siècles", body: "Les Romains avaient compris l'importance des bains : Vichy, Aix-les-Bains, Bagnères s'épanouissent déjà sous l'Empire. La cure thermale moderne se structure au XIXe siècle avec la médicalisation des stations. Aujourd'hui, la France compte une centaine de stations agréées, chacune avec une eau spécifique : sulfurée (voies respiratoires), bicarbonatée (digestion), chlorurée (rhumatologie), oligo-minérale (dermatologie). La cure dure dix-huit jours, six jours par semaine." },
      { heading: "Le déroulé typique d'une journée", body: "Le curiste enchaîne trois à quatre soins quotidiens : bain en piscine thermale, douche au jet, application de boue (péloïdes) chauffée, inhalation de vapeur, massage sous eau. Chaque soin dure dix à vingt minutes. L'ensemble se termine en milieu de matinée, laissant l'après-midi libre. Le rythme lent, le climat de station, l'éloignement du quotidien contribuent autant que les soins eux-mêmes au bénéfice observé." },
      { heading: "Indications classiques", body: "Rhumatologie (arthrose, lombalgies chroniques) : eaux sulfurées et chlorurées. Voies respiratoires (sinusites chroniques, bronchites de l'enfant) : eaux sulfurées. Phlébologie (insuffisance veineuse) : eaux froides bicarbonatées. Dermatologie (psoriasis, eczéma) : eaux oligo-minérales d'Avène, La Roche-Posay. Affections digestives, neurologie, gynécologie complètent la liste des douze orientations agréées." },
      { heading: "Précautions et contre-indications", body: "Les cures thermales chaudes sollicitent le système cardiovasculaire. Hypertension non équilibrée, insuffisance cardiaque, antécédents d'AVC récents : contre-indication ou avis cardiologique préalable indispensable. Toute infection en poussée, fièvre, cancer évolutif, grossesse à risque : report de la cure. Prescription par un médecin traitant requise pour le remboursement. Bilan médical en début de cure dans la station." },
    ],
    keyPoints: [
      "Cure de 18 jours, 6 jours sur 7, dans une station agréée",
      "Tradition romaine codifiée au XIXe siècle, toujours remboursée en France",
      "12 orientations thérapeutiques officielles",
      "Le repos et le cadre comptent autant que les soins eux-mêmes",
    ],
    contre_indications: [
      "Hypertension non équilibrée (cures chaudes)",
      "Insuffisance cardiaque, antécédents d'AVC récent",
      "Toute infection en poussée, fièvre",
      "Cancer évolutif, grossesse à risque",
    ],
    tags: ['cure thermale', 'balnéologie', 'tradition'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'douche-soleil-vivifiante',
    domain: 'naturopathie',
    category: 'hydrotherapie',
    title: "La douche du soleil vivifiante (méthode Kneipp)",
    excerpt: "L'arrosage en cercle du tronc et du dos avec un jet froid : la technique signature du pasteur Kneipp pour réveiller la vitalité matinale.",
    readingTime: 5,
    evidence_level: 'tradition',
    evidence_note: "La pratique Kneipp est inscrite au patrimoine immatériel de l'UNESCO depuis 2015. Les bénéfices subjectifs sur la vitalité, le sommeil et l'immunité sont rapportés depuis 150 ans. Les données contrôlées restent limitées et anciennes.",
    intro: "Sébastien Kneipp, pasteur bavarois du XIXe siècle, a structuré une médecine de l'eau qui reste enseignée aujourd'hui. La douche du soleil — gussguss en allemand — est l'une de ses pratiques signature : un jet d'eau froide appliqué en cercle sur le tronc et le dos, debout, deux minutes le matin. Simple, gratuit, transformateur lorsqu'il est pratiqué quotidiennement.",
    sections: [
      { heading: "Origine de la méthode", body: "Sébastien Kneipp (1821-1897) guérit lui-même d'une tuberculose en s'immergeant dans le Danube en hiver. Il consacre sa vie à codifier l'usage thérapeutique de l'eau froide : affusions, marches dans la rosée, bains de pieds, enveloppements. Sa méthode repose sur cinq piliers : eau, plantes, exercice, alimentation, équilibre intérieur. Inscrite au patrimoine immatériel de l'UNESCO en 2015, la méthode Kneipp est encore enseignée en Allemagne et en Autriche dans des cures conventionnées." },
      { heading: "Technique de la douche du soleil", body: "Le matin, après la douche habituelle, régler l'eau sur froid (douze à seize degrés). Diriger le jet sur le pied droit, remonter par l'extérieur de la jambe jusqu'à la hanche, redescendre par l'intérieur. Idem côté gauche. Puis dessiner un grand cercle sur le ventre dans le sens des aiguilles d'une montre, trois fois. Passer dans le dos : cercles sur les reins, remontée vers les épaules. Durée totale : deux minutes. Sortir, ne pas se sécher : enfiler un peignoir et bouger." },
      { heading: "Ce qui se passe dans le corps", body: "Le froid provoque une vasoconstriction périphérique immédiate puis, à l'arrêt, une vasodilatation réactionnelle puissante. C'est cette gymnastique vasculaire répétée qui tonifie progressivement le système circulatoire. Libération de noradrénaline (vigilance), stimulation des leucocytes, activation du tissu adipeux brun. Effet subjectif rapporté : vitalité matinale, peau ferme, sommeil plus profond le soir suivant." },
      { heading: "Précautions et progression", body: "Démarrer en septembre, plus tolérable qu'en plein hiver. Première semaine : jet froid sur les jambes seulement, trente secondes. Augmenter progressivement. Contre-indications : hypertension non équilibrée, insuffisance cardiaque, syndrome de Raynaud sévère, infection urinaire en cours, règles douloureuses, grossesse au premier trimestre. Ne jamais pratiquer le matin sans s'être réchauffé d'abord (jamais sur peau froide)." },
    ],
    keyPoints: [
      "Pratique Kneipp codifiée au XIXe siècle, classée UNESCO",
      "Jet d'eau froide en cercle sur tronc et dos, 2 minutes",
      "Gymnastique vasculaire : vasoconstriction puis vasodilatation",
      "Démarrer en automne, progresser semaine par semaine",
    ],
    contre_indications: [
      "Hypertension artérielle non équilibrée",
      "Insuffisance cardiaque, troubles du rythme",
      "Syndrome de Raynaud sévère",
      "Infection urinaire en cours, règles douloureuses",
      "Grossesse au premier trimestre",
    ],
    tags: ['Kneipp', 'douche froide', 'vitalité'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'enveloppement-froid-priessnitz',
    domain: 'naturopathie',
    category: 'hydrotherapie',
    title: "L'enveloppement froid de Priessnitz",
    excerpt: "Un drap mouillé froid serré autour du corps, puis recouvert de couvertures sèches : la technique qui transforme le froid en chaleur curative.",
    readingTime: 5,
    evidence_level: 'tradition',
    evidence_note: "L'enveloppement de Priessnitz appartient à la tradition hydrothérapique européenne. Son usage en fièvre est encore mentionné dans certains protocoles d'éducation parentale en Allemagne. Aucune méta-analyse moderne, mais innocuité bien documentée dans le respect du protocole.",
    intro: "Vincent Priessnitz, paysan silésien autodidacte du début du XIXe siècle, fonde dans son village de Gräfenberg la première station hydrothérapique d'Europe. Sa technique signature — l'enveloppement humide froid — consiste à entourer le corps d'un drap mouillé froid, recouvert immédiatement de couvertures sèches. Le corps réagit en produisant une chaleur intense : sudation profonde, drainage, détente.",
    sections: [
      { heading: "Préparation du matériel", body: "Un drap de coton ou de lin (jamais synthétique), trempé dans l'eau froide à quinze degrés et essoré. Deux couvertures de laine sèches étalées sur le lit l'une au-dessus de l'autre. Une bouillotte chaude pour les pieds (essentielle au démarrage de la réaction). Un grand verre d'eau à boire avant. Pièce chauffée à dix-neuf ou vingt degrés. Toilettes à proximité (la sudation est intense)." },
      { heading: "Déroulé de l'enveloppement", body: "S'allonger sur le drap mouillé étalé sur les couvertures sèches. Replier rapidement le drap autour du corps, du cou aux orteils, en serrant. Refermer immédiatement les couvertures sèches par-dessus, pieds inclus. Bouillotte aux pieds. Tête seule à l'extérieur, sur un oreiller. Durée : quarante-cinq minutes à une heure. Phase un (cinq minutes) : froid désagréable. Phase deux (vingt minutes) : chaleur intense. Phase trois : sudation profuse." },
      { heading: "Indications traditionnelles", body: "Fièvre chez l'enfant (technique encore enseignée en Allemagne aux jeunes parents), surmenage du système nerveux, insomnie d'angoisse, début de rhume, fatigue chronique sans cause organique, convalescence. Cure : un enveloppement par semaine pendant quatre semaines en automne. Effet rapporté : détente neurovégétative profonde, sommeil réparateur, sensation de purification cutanée." },
      { heading: "Précautions impératives", body: "Ne jamais pratiquer si le corps est déjà refroidi (pieds froids au démarrage) : aucune réaction de chaleur ne se produit et l'effet est délétère. Contre-indications : insuffisance cardiaque, hypertension sévère, troubles du rythme, syndrome de Raynaud, infection grave en cours, maladie de peau étendue, grossesse. Toujours en présence d'une personne dans la maison. Boire abondamment après. Se reposer une heure ensuite." },
    ],
    keyPoints: [
      "Technique Priessnitz : drap froid + couvertures sèches",
      "Réaction thermique : chaleur intense et sudation profonde",
      "Indications : fièvre, surmenage, insomnie d'angoisse",
      "Conditions impératives : pieds chauds, présence d'une autre personne",
    ],
    contre_indications: [
      "Pieds froids au démarrage (échec garanti)",
      "Insuffisance cardiaque, hypertension sévère",
      "Troubles du rythme, syndrome de Raynaud",
      "Infection grave en cours, grossesse",
    ],
    tags: ['Priessnitz', 'enveloppement', 'sudation'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'cataplasme-argile-applications',
    domain: 'naturopathie',
    category: 'hydrotherapie',
    title: "Le cataplasme d'argile verte : applications classiques",
    excerpt: "Préparation, épaisseur, durée, zones : le mode d'emploi traditionnel du cataplasme d'argile en naturopathie quotidienne.",
    readingTime: 5,
    evidence_level: 'tradition',
    evidence_note: "L'argile verte (montmorillonite, illite) possède un fort pouvoir d'adsorption et des propriétés bactériostatiques in vitro bien documentées. L'usage cutané externe est traditionnel et sans risque significatif. L'usage interne, lui, soulève des inquiétudes (plomb, aluminium) et n'est plus recommandé.",
    intro: "Le cataplasme d'argile verte appartient au patrimoine universel de la médecine populaire. Adsorbante, reminéralisante, légèrement antiseptique, l'argile attire les impuretés à la surface de la peau et apaise les inflammations. Bien préparé, posé suffisamment épais et laissé en place le temps nécessaire, c'est l'un des soins externes les plus polyvalents de la pharmacopée familiale.",
    sections: [
      { heading: "Choisir et préparer l'argile", body: "Privilégier une argile verte surfine, montmorillonite ou illite, en pot non métallique (jamais d'aluminium). Marques traditionnelles : Cattier, Argiletz. Préparation la veille : mettre l'argile en poudre dans un récipient en verre ou bois, recouvrir d'eau de source jusqu'à immersion complète, laisser reposer une nuit. Le lendemain, mélanger avec une cuillère en bois ou plastique (jamais métal) jusqu'à obtenir une pâte épaisse, lisse et souple." },
      { heading: "Application en pratique", body: "Étaler une couche d'argile d'un à deux centimètres d'épaisseur sur un linge de coton, juste plus large que la zone à traiter. Appliquer côté argile contre la peau. Maintenir avec une bande de gaze ou un tissu. Durée : une à deux heures. Retirer dès que le cataplasme est sec (l'argile cesse alors d'agir et devient inerte). Rincer à l'eau tiède. Ne jamais réutiliser une argile usagée : elle est saturée de toxines, à jeter." },
      { heading: "Indications classiques par zone", body: "Sur le foie : drainage hépatique en cure de printemps, après les repas lourds. Sur les articulations : douleurs rhumatismales, entorses, tendinites (alterner argile froide en aigu, argile chaude en chronique). Sur le ventre : congestion digestive, ballonnements. Sur la nuque : céphalées de tension. Sur un furoncle ou un panaris : tirage et résolution. Sur un coup : résorption d'hématome." },
      { heading: "Précautions et erreurs fréquentes", body: "Ne jamais conserver un cataplasme une fois sec : l'effet s'inverse et la peau s'irrite. Ne jamais utiliser sur plaie ouverte profonde, sur peau lésée par un eczéma actif, sur le ventre d'une femme enceinte (foie autorisé sur avis), sur un sein qui allaite. Ne pas avaler d'argile : l'argile orale n'est plus recommandée (charge en plomb et aluminium, risque d'occlusion). L'argile externe reste sûre et utile." },
    ],
    keyPoints: [
      "Argile verte surfine, jamais en contact avec métal",
      "Couche d'1-2 cm, laisser 1-2 heures maximum",
      "Retirer dès que sec, ne jamais réutiliser",
      "Usage externe uniquement, jamais avaler",
    ],
    contre_indications: [
      "Plaie ouverte profonde, eczéma actif",
      "Ventre d'une femme enceinte (sauf avis)",
      "Sein en cours d'allaitement",
      "Usage oral à proscrire (plomb, aluminium)",
    ],
    tags: ['argile verte', 'cataplasme', 'pharmacopée familiale'],
    updatedAt: '2026-05-29',
  },

  /* ─────────────────────────────────────────
     AROMATHÉRAPIE (4 articles)
  ───────────────────────────────────────── */
  {
    slug: 'roll-on-anti-stress-formules',
    domain: 'naturopathie',
    category: 'aromatherapie',
    title: "Roll-on anti-stress : 3 formules à fabriquer chez soi",
    excerpt: "Lavande, petitgrain, ylang-ylang, camomille : trois mélanges prêts à porter au poignet pour traverser les pics de tension de la journée.",
    readingTime: 5,
    evidence_level: 'preliminary',
    evidence_note: "Plusieurs essais cliniques modestes suggèrent un effet anxiolytique léger de l'inhalation de lavande vraie sur l'anxiété aiguë (avant chirurgie, examens). Les autres huiles citées reposent sur la tradition. L'usage cutané dilué en roll-on est sûr dans le respect du dosage.",
    intro: "Le roll-on aromatique est l'outil pratique par excellence de l'aromathérapie nomade : un flacon de dix millilitres muni d'une bille, glissé dans la poche, à passer sur les poignets, la nuque ou les tempes au moment d'un pic d'anxiété. Trois formules classiques couvrent l'essentiel des situations : stress quotidien, panique aiguë, fin de journée tendue.",
    sections: [
      { heading: "Le matériel de base", body: "Flacon en verre coloré (ambré ou bleu) de dix millilitres avec bille roll-on, achetable en pharmacie ou en ligne pour deux à trois euros. Huile végétale neutre : jojoba (qui ne rancit pas), amande douce ou noyau d'abricot. Huiles essentielles de qualité HEBBD (huile essentielle botaniquement et biochimiquement définie) chémotypées. Étiquettes pour noter la formule et la date. Conservation : six mois à l'abri de la lumière." },
      { heading: "Formule un — stress quotidien", body: "Pour dix millilitres : remplir d'huile de jojoba aux trois quarts. Ajouter quinze gouttes de lavande vraie (Lavandula angustifolia), cinq gouttes de petitgrain bigarade, trois gouttes d'orange douce. Compléter avec l'huile végétale. Agiter. Appliquer sur la face interne des poignets, respirer profondément trois fois. À renouveler toutes les deux heures si besoin. Le mélange à porter en réunion, dans les transports, avant une présentation." },
      { heading: "Formule deux — panique aiguë", body: "Pour dix millilitres : huile de jojoba aux trois quarts. Vingt gouttes de camomille romaine (Anthemis nobilis) — onéreuse mais irremplaçable en cas d'angoisse vive. Cinq gouttes de marjolaine à coquilles. Cinq gouttes de mandarine rouge. Compléter. Appliquer sur le plexus solaire et la face interne des poignets. Respiration ventrale lente associée. Réservé aux situations aiguës (crise d'angoisse, mauvaise nouvelle, conflit), pas en usage chronique." },
      { heading: "Précautions et erreurs", body: "Toujours respecter la dilution maximale de trois à cinq pour cent en application cutanée. Ne pas utiliser chez l'enfant de moins de sept ans, la femme enceinte des trois premiers mois (toutes huiles essentielles déconseillées), la femme allaitante. Test cutané préalable au pli du coude vingt-quatre heures avant. Ne pas appliquer avant exposition solaire (orange, mandarine sont photosensibilisantes). Asthmatiques : prudence sur l'inhalation prolongée." },
    ],
    keyPoints: [
      "Roll-on 10 ml, huile végétale + 15-20 gouttes d'HE total",
      "Lavande vraie : stress quotidien — preuves cliniques modestes",
      "Camomille romaine : panique aiguë, plexus solaire",
      "Dilution 3-5%, jamais chez l'enfant de moins de 7 ans",
    ],
    contre_indications: [
      "Grossesse au premier trimestre, allaitement",
      "Enfant de moins de 7 ans",
      "Exposition solaire après application (agrumes)",
      "Asthme : prudence avec l'inhalation",
    ],
    tags: ['roll-on', 'huiles essentielles', 'stress'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'diffusion-bureau-concentration',
    domain: 'naturopathie',
    category: 'aromatherapie',
    title: "Diffusion au bureau : huiles essentielles pour la concentration",
    excerpt: "Citron, romarin, menthe poivrée : les synergies aromatiques qui soutiennent la vigilance cognitive en open space ou télétravail.",
    readingTime: 5,
    evidence_level: 'preliminary',
    evidence_note: "Quelques essais expérimentaux chez l'adulte sain rapportent un effet modeste mais reproductible de l'inhalation de romarin sur la mémoire de travail et de menthe poivrée sur la vigilance. Les conditions de bureau sont rarement reproduites dans les études. La prudence sanitaire impose une diffusion intermittente.",
    intro: "La diffusion atmosphérique d'huiles essentielles au poste de travail séduit, mais demande méthode. Mal pratiquée — diffuseur ouvert toute la journée, dosage excessif, en présence de tiers — elle devient une nuisance et un risque sanitaire. Pratiquée par séances courtes, en télétravail ou en bureau individuel, avec des huiles ciblées, elle soutient réellement la vigilance et l'attention.",
    sections: [
      { heading: "Choisir le bon diffuseur", body: "Trois technologies coexistent. Diffuseur à nébulisation (à froid, sans eau) : puissant, recommandé pour pièces de plus de quinze mètres carrés, idéal en aromathérapie. Diffuseur ultrasonique (humidificateur) : doux, peu coûteux, parfait pour un bureau personnel. Brûle-parfum à bougie : à éviter (la chaleur dégrade les molécules et libère des composés irritants). Bannir les diffusions par ventilation USB de mauvaise qualité." },
      { heading: "Synergie vigilance cognitive", body: "Pour vingt minutes de diffusion : trois gouttes de citron (Citrus limon), deux gouttes de romarin à cinéole (Rosmarinus officinalis), une goutte de menthe poivrée (Mentha piperita). Le citron apporte une fraîcheur olfactive qui réveille sans agresser. Le romarin soutient la mémoire de travail (étude Moss 2003 chez sujets sains). La menthe poivrée stimule la vigilance via le nerf trijumeau. Diffuser en début de matinée et en début d'après-midi." },
      { heading: "Synergie créativité et détente concentrée", body: "Pour une session d'écriture ou de réflexion : deux gouttes de petit grain bigarade, deux gouttes d'encens oliban, une goutte d'orange douce. Le mélange apaise sans endormir, ce qui favorise la pensée latérale. Idéal en seconde partie d'après-midi quand la fatigue cognitive s'installe. Diffusion de quinze à vingt minutes maximum, suivie d'une pause d'au moins une heure." },
      { heading: "Règles d'hygiène de diffusion", body: "Jamais plus de vingt minutes consécutives en présence humaine. Jamais en open space sans accord explicite de tous (le sens olfactif est intime, certains réagissent mal). Jamais avec menthe poivrée en présence d'un enfant de moins de six ans, d'une femme enceinte, d'un épileptique. Asthmatiques : éviter la diffusion en milieu fermé prolongé, signe de bronchoconstriction documenté. Aérer la pièce après chaque session." },
    ],
    keyPoints: [
      "Diffuseur à nébulisation ou ultrasonique, jamais à chaleur",
      "Sessions de 20 minutes maximum, jamais en continu",
      "Vigilance : citron + romarin à cinéole + menthe poivrée",
      "Open space : accord de tous les collègues impératif",
    ],
    contre_indications: [
      "Asthme : risque de bronchoconstriction (éviter ou test prudent)",
      "Enfant de moins de 6 ans présent dans la pièce",
      "Grossesse, épilepsie (menthe poivrée notamment)",
      "Open space sans accord collectif explicite",
    ],
    tags: ['diffusion', 'concentration', 'bureau'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'olfactotherapie-base',
    domain: 'naturopathie',
    category: 'aromatherapie',
    title: "L'olfactothérapie : utiliser le nerf olfactif comme porte d'entrée",
    excerpt: "Le nerf olfactif court-circuite la barrière hématoencéphalique et accède directement au système limbique : base anatomique de l'aromathérapie émotionnelle.",
    readingTime: 5,
    evidence_level: 'preliminary',
    evidence_note: "L'anatomie du nerf olfactif et ses connexions au système limbique sont bien établies. L'effet émotionnel des odeurs est démontré expérimentalement. Les protocoles d'olfactothérapie eux-mêmes restent peu évalués cliniquement et reposent largement sur la tradition.",
    intro: "L'olfactothérapie repose sur une particularité anatomique remarquable : le nerf olfactif est le seul nerf crânien qui contourne la barrière hématoencéphalique et se connecte directement au système limbique, siège des émotions et de la mémoire. Sentir une odeur, c'est court-circuiter la pensée rationnelle et toucher les structures les plus archaïques du cerveau. Cette voie d'accès rapide explique l'efficacité émotionnelle des huiles essentielles inhalées.",
    sections: [
      { heading: "L'anatomie en jeu", body: "Les molécules odorantes traversent la muqueuse olfactive, sont captées par les récepteurs des neurones sensoriels olfactifs, qui projettent leurs axones à travers la lame criblée de l'ethmoïde jusqu'au bulbe olfactif. Ce dernier se connecte directement au cortex piriforme, à l'amygdale (émotions) et à l'hippocampe (mémoire) — sans relais thalamique, contrairement aux autres sens. C'est pourquoi une odeur peut faire surgir un souvenir entier en une fraction de seconde." },
      { heading: "La séance d'olfactothérapie", body: "Position assise confortable, dos droit. Choisir une huile essentielle en lien avec un état émotionnel à traiter (peur, tristesse, colère). Déposer une à deux gouttes sur un mouchoir en papier ou directement au flacon. Inspirer profondément en visualisant l'émotion. Tenir le flacon à quelques centimètres du nez, fermer les yeux, respirer dix à quinze fois. Observer ce qui émerge — souvenirs, sensations, images — sans rien forcer. Une séance dure cinq à dix minutes." },
      { heading: "Quelques huiles emblématiques", body: "Bois de rose : ouverture du cœur, douceur. Encens (boswellie) : ancrage, dimension spirituelle, méditation. Néroli (fleur d'oranger amer) : apaisement profond, deuil, choc émotionnel. Patchouli : enracinement, sortir de la rumination. Rose de Damas : amour de soi, féminin profond, deuil. Ylang-ylang : libération de la colère retenue. Chacune ouvre un territoire émotionnel spécifique, à explorer avec patience." },
      { heading: "Précautions et limites", body: "L'olfactothérapie n'est pas une psychothérapie : elle ouvre des émergences émotionnelles parfois intenses, à accueillir dans un cadre sécurisé. Suivre un olfactothérapeute formé pour le travail sur traumas anciens. Asthmatiques : tester en très petite quantité, à distance. Femmes enceintes : limiter à des huiles douces (néroli, rose, lavande) en inhalation très brève. Ne jamais utiliser comme substitut à une prise en charge psychiatrique nécessaire." },
    ],
    keyPoints: [
      "Nerf olfactif : seule connexion directe sensorielle au limbique",
      "Court-circuite la barrière hématoencéphalique",
      "Séance d'inhalation consciente de 5 à 10 minutes",
      "Émergences émotionnelles à accueillir, pas à forcer",
    ],
    contre_indications: [
      "Asthme : tests prudents, à distance",
      "Grossesse : huiles très douces uniquement",
      "Pathologie psychiatrique active : avis spécialisé requis",
      "Trauma majeur : accompagnement professionnel impératif",
    ],
    tags: ['olfactothérapie', 'système limbique', 'émotions'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'huile-massage-jambes-lourdes',
    domain: 'naturopathie',
    category: 'aromatherapie',
    title: "Huile de massage maison pour jambes lourdes",
    excerpt: "Cyprès, hélichryse, menthe poivrée dans une base de calophylle : la synergie classique du drainage veino-lymphatique en automassage quotidien.",
    readingTime: 5,
    evidence_level: 'tradition',
    evidence_note: "Le cyprès toujours vert et l'hélichryse italienne sont traditionnellement reconnus pour l'action veinotonique et anti-hématome. Quelques études expérimentales suggèrent un effet vasoconstricteur du cyprès. L'effet du massage ascendant lui-même sur le drainage veino-lymphatique est bien documenté.",
    intro: "Les jambes lourdes — sensation pesante en fin de journée, chevilles enflées, varicosités — concernent près d'une femme sur deux en France. L'aromathérapie en massage ascendant matin et soir constitue l'un des outils non pharmacologiques les plus efficaces, à condition d'utiliser des huiles essentielles ciblées et une base végétale veinotonique elle-même.",
    sections: [
      { heading: "La formule de référence", body: "Pour cent millilitres d'huile, prendre cinquante millilitres d'huile de calophylle (calophyllum inophyllum), cinquante millilitres d'huile d'amande douce ou de noyau d'abricot. Ajouter vingt-cinq gouttes de cyprès toujours vert (Cupressus sempervirens), vingt gouttes d'hélichryse italienne (Helichrysum italicum), quinze gouttes de menthe poivrée, dix gouttes de lentisque pistachier si possible. Conservation : six mois en flacon ambré au frais." },
      { heading: "Pourquoi la calophylle", body: "L'huile de calophylle est l'huile végétale veinotonique de référence en aromathérapie. Sa couleur vert sombre signe sa richesse en composés actifs : calophyllolide aux propriétés anti-inflammatoires, acide calophyllique, coumarines. Tradition polynésienne (tamanu) : utilisée pour les œdèmes, les hématomes, les troubles circulatoires. Son odeur de noisette n'est pas universellement appréciée — diluer dans amande douce améliore l'expérience sensorielle." },
      { heading: "Technique du massage ascendant", body: "Position assise sur le bord du lit ou du canapé, jambes étendues. Verser une noisette d'huile dans la paume, frotter pour réchauffer. Démarrer par la cheville. Massage ferme et lent en remontant vers le genou, par pressions glissées paume entière. Insister sur l'arrière du mollet. Remonter ensuite de la cuisse vers l'aine. Toujours sens ascendant (jamais descendant). Cinq minutes par jambe. Idéal le matin avant les bas de contention, le soir avant le coucher." },
      { heading: "Précautions importantes", body: "Contre-indication absolue en cas de thrombose veineuse profonde ou suspicion (mollet chaud, dur, douloureux d'un seul côté) : urgence médicale, jamais de massage. Pas pendant la grossesse (cyprès phlébotonique mais hormono-mimétique, hélichryse anticoagulante). Allaitement : éviter. Hypertendus traités par anticoagulants : avis médical (hélichryse). Cancer hormono-dépendant : éviter le cyprès." },
    ],
    keyPoints: [
      "Base : 50% calophylle (veinotonique) + 50% amande douce",
      "Synergie : cyprès + hélichryse + menthe poivrée",
      "Massage ascendant uniquement, cheville vers aine",
      "Matin avant bas de contention, soir avant coucher",
    ],
    contre_indications: [
      "Thrombose veineuse profonde (urgence médicale)",
      "Grossesse, allaitement (cyprès hormono-mimétique)",
      "Traitement anticoagulant (hélichryse)",
      "Cancer hormono-dépendant (cyprès à éviter)",
    ],
    tags: ['jambes lourdes', 'circulation', 'massage'],
    updatedAt: '2026-05-29',
  },

  /* ─────────────────────────────────────────
     PLANTES (4 articles)
  ───────────────────────────────────────── */
  {
    slug: 'gemmotherapie-bases',
    domain: 'naturopathie',
    category: 'plantes',
    title: "La gemmothérapie : introduction aux macérats glycérinés",
    excerpt: "Bourgeons frais macérés dans glycérine, alcool et eau : la branche embryonnaire de la phytothérapie codifiée par le docteur Pol Henry.",
    readingTime: 5,
    evidence_level: 'tradition',
    evidence_note: "La gemmothérapie est une approche thérapeutique du XXe siècle, encore peu évaluée par essais cliniques contemporains. Les bourgeons contiennent effectivement une concentration intéressante de phytohormones, de minéraux et de composés actifs. La tradition francophone est solide ; les preuves cliniques formelles restent rares.",
    intro: "La gemmothérapie — du latin gemma, bourgeon — est une branche jeune de la phytothérapie, théorisée dans les années 1960 par le médecin belge Pol Henry. Son intuition : le bourgeon, tissu embryonnaire de la plante, concentre son potentiel total avant différenciation. Macéré frais dans un mélange glycérine-alcool-eau, il livre une préparation aux propriétés spécifiques, souvent décrites comme régénératrices et drainantes.",
    sections: [
      { heading: "La théorie du bourgeon embryonnaire", body: "Pol Henry observe que le bourgeon contient toute l'information génétique de la plante, des phytohormones de croissance (auxines, gibbérellines), des acides nucléiques en concentration élevée, et l'ensemble du spectre minéral. Une fois la plante développée, ces composés se répartissent et se diluent dans les différentes parties. Recueillir le bourgeon au printemps avant son éclosion permet, en théorie, de capter cette densité informationnelle." },
      { heading: "La préparation par macération", body: "Les bourgeons sont récoltés frais au printemps, à un stade précis (turgescents mais non éclos). Ils sont mis à macérer trois semaines dans un mélange standardisé : un tiers glycérine végétale, un tiers alcool éthylique à quatre-vingt-quinze degrés, un tiers eau. Filtration, puis dilution au dixième selon la tradition Henry (D1), ou en concentré (macérat-mère MG1 selon l'école française moderne). Pharmacien-préparateur ou laboratoires spécialisés (Herbalgem, Boiron, Ladrôme)." },
      { heading: "Les bourgeons emblématiques et leurs usages", body: "Cassis (Ribes nigrum) : grand fortifiant, anti-inflammatoire, soutien surrénalien, le plus utilisé. Bouleau (Betula pubescens) : drainage rénal puissant, cure de printemps. Figuier (Ficus carica) : régulation nerveuse, sommeil, somatisations digestives. Aubépine (Crataegus) : régulation cardiaque douce, palpitations émotionnelles. Romarin (Rosmarinus) : drainage hépatique, mémoire. Tilleul : sommeil de l'enfant et de la personne âgée." },
      { heading: "Posologie et précautions", body: "Posologie standard adulte : cinq à quinze gouttes une à trois fois par jour, dans un peu d'eau, à distance des repas. Cure de vingt et un jours, puis pause d'une semaine. Présence d'alcool : contre-indication pour enfant de moins de douze ans, femme enceinte, personne en sevrage alcoolique. Diabétiques : présence de glycérine, à signaler au prescripteur. Bourgeon d'aubépine : interaction possible avec traitements cardiaques, avis médical." },
    ],
    keyPoints: [
      "Bourgeons frais macérés dans glycérine-alcool-eau",
      "Théorie Pol Henry : densité informationnelle embryonnaire",
      "Posologie : 5-15 gouttes, 1-3 fois par jour, cure de 21 jours",
      "Cassis, bouleau, figuier : trio de base de la gemmothérapie",
    ],
    contre_indications: [
      "Enfant de moins de 12 ans (présence d'alcool)",
      "Grossesse, allaitement",
      "Sevrage alcoolique",
      "Diabète : signaler la glycérine au prescripteur",
    ],
    tags: ['gemmothérapie', 'bourgeons', 'macérat'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'teintures-meres-fabrication',
    domain: 'naturopathie',
    category: 'plantes',
    title: "Fabriquer ses teintures-mères à la maison",
    excerpt: "Plante fraîche, alcool à 70 degrés, trois semaines de macération : le procédé traditionnel pour extraire le spectre complet d'une plante.",
    readingTime: 5,
    evidence_level: 'tradition',
    evidence_note: "La teinture-mère est une forme galénique reconnue par la pharmacopée européenne. Le procédé de macération alcoolique extrait efficacement les principes actifs lipo et hydrosolubles. La fabrication maison est légale pour usage personnel ; la mise en circulation n'est pas autorisée sans agrément pharmaceutique.",
    intro: "La teinture-mère est la forme galénique la plus ancienne de la phytothérapie occidentale. Un macérat alcoolique concentré de plante fraîche, stable pendant des années, qui restitue dans une dose minime tout le spectre actif de la plante. Sa fabrication à la maison, simple, nécessite du matériel de base et trois semaines de patience. Réglementairement, la production est réservée à l'usage personnel.",
    sections: [
      { heading: "Le principe galénique", body: "L'alcool éthylique à soixante-dix degrés est un solvant universel : il dissout aussi bien les composés hydrosolubles (alcaloïdes, glycosides, mucilages) que les composés liposolubles (huiles essentielles, résines, terpènes). À cette concentration alcoolique, il conserve indéfiniment la préparation. La proportion classique : une partie de plante fraîche pour cinq parties d'alcool (ratio 1:5) ou de plante sèche pour dix parties d'alcool (1:10)." },
      { heading: "Matériel et plante", body: "Bocal en verre type Le Parfait, parfaitement propre et sec. Alcool de qualité alimentaire à soixante-dix degrés (alcool de fruits ou eau-de-vie diluée). Plante fraîche cueillie le matin par temps sec, hors période de pluie récente. Éviter les sites pollués (bords de route, champs traités). Identification botanique certaine — usage de la flore régionale ou d'un guide validé. Pour débuter : mélisse, lavande, romarin, ortie, calendula." },
      { heading: "Le protocole étape par étape", body: "Peser la plante fraîche, la hacher grossièrement (ciseaux, couteau). Placer dans le bocal. Verser cinq fois son poids en alcool à soixante-dix degrés (cent grammes de plante pour cinq cents millilitres). Fermer hermétiquement. Étiqueter avec nom de la plante, date, ratio. Stocker à l'abri de la lumière, agiter le bocal une fois par jour pendant trois semaines. Filtrer à la mousseline en pressant bien. Mettre en flacons compte-gouttes ambrés. Conservation : trois à cinq ans." },
      { heading: "Précautions et limites", body: "Posologie standard : vingt à cinquante gouttes, une à trois fois par jour selon la plante, dans un peu d'eau. Présence d'alcool concentré : contre-indication absolue pour l'enfant, la femme enceinte ou allaitante, la personne en sevrage alcoolique, la conduite ou l'activité dangereuse en cas de doses fortes. Toujours identifier la plante avec certitude. Ne jamais préparer de plante toxique (aconit, digitale, belladone) sans formation. Usage personnel uniquement, jamais à vendre." },
    ],
    keyPoints: [
      "Macération 3 semaines, alcool à 70° + plante fraîche",
      "Ratio 1:5 plante fraîche, 1:10 plante sèche",
      "Filtration, mise en flacon ambré, conservation 3-5 ans",
      "Usage personnel exclusif, jamais en vente",
    ],
    contre_indications: [
      "Enfant, grossesse, allaitement (alcool concentré)",
      "Sevrage alcoolique",
      "Identification botanique incertaine (plantes toxiques)",
      "Vente ou distribution interdite sans agrément",
    ],
    tags: ['teinture-mère', 'macération', 'phytothérapie'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'cure-bourgeon-cassis-printemps',
    domain: 'naturopathie',
    category: 'plantes',
    title: "La cure bourgeon de cassis au printemps",
    excerpt: "Quinze gouttes le matin pendant trois semaines : la cortisone-like végétale qui soutient les surrénales fatiguées et apaise les inflammations chroniques.",
    readingTime: 5,
    evidence_level: 'preliminary',
    evidence_note: "Le cassis (Ribes nigrum) est l'une des plantes les mieux étudiées pour son contenu en flavonoïdes, anthocyanes et vitamine C. Quelques travaux suggèrent un effet anti-inflammatoire et un soutien de la fonction surrénalienne. La forme bourgeon n'a pas été spécifiquement évaluée par des essais cliniques de bonne qualité, mais bénéficie d'un long usage en naturopathie francophone.",
    intro: "Le macérat de bourgeon de cassis (Ribes nigrum) est surnommé la cortisone-like végétale en gemmothérapie : il soutient les glandes surrénales, apaise les inflammations chroniques, soulage les allergies saisonnières et combat la fatigue de fin d'hiver. La cure de trois semaines au tout début du printemps prépare l'organisme aux pollens et relance la vitalité.",
    sections: [
      { heading: "Pourquoi le cassis et pourquoi le bourgeon", body: "Le cassis concentre dans ses bourgeons, ses feuilles et ses baies un complexe unique : anthocyanes (couleur foncée), proanthocyanidols, flavonoïdes (rutine, quercétine), vitamine C, huiles essentielles, polysaccharides. En gemmothérapie, le bourgeon est considéré comme le plus actif sur l'axe surrénalien et l'inflammation. Pol Henry et la tradition francophone en ont fait le bourgeon polyvalent par excellence, prescrit en cas de fatigue, d'allergie, de rhumatisme et de stress chronique." },
      { heading: "Le protocole de cure printanière", body: "Démarrer début mars, idéalement à l'équinoxe. Macérat de bourgeon de cassis D1 (dilution Pol Henry) ou MG1 (concentré moderne). Posologie : quinze gouttes dans un peu d'eau, le matin à jeun, dix minutes avant le petit-déjeuner. La prise matinale est essentielle (le cassis soutient le cortisol naturel matinal). Durée : vingt et un jours. Faire une semaine de pause, puis éventuellement repartir pour vingt et un jours si terrain allergique marqué." },
      { heading: "Indications classiques", body: "Allergies saisonnières (rhinite des foins, conjonctivite) : démarrer un mois avant la saison pollinique. Fatigue chronique de fin d'hiver, terrain hypoglycémique. Rhumatismes inflammatoires en accompagnement (jamais en substitution d'un traitement). Eczéma chronique en terrain allergique. Stress prolongé avec épuisement des surrénales. Récupération post-virale, convalescence." },
      { heading: "Contre-indications et interactions", body: "Hypertension artérielle traitée : le cassis a un effet hypertenseur léger documenté, à surveiller. Traitement par corticoïdes : risque d'interaction synergique, demander un avis médical. Anticoagulants type warfarine ou antiagrégants : interaction possible via la vitamine K présente dans la plante, vigilance. Grossesse et allaitement : contre-indiqué (présence d'alcool et action hormonale). Enfants de moins de douze ans : alcool. Insomnie : ne pas prendre le soir." },
    ],
    keyPoints: [
      "15 gouttes le matin à jeun, 21 jours, début mars",
      "Action cortisone-like : soutien surrénalien et anti-inflammatoire",
      "Indication phare : allergies saisonnières (démarrer 1 mois avant)",
      "Jamais le soir (effet stimulant via le cortisol)",
    ],
    contre_indications: [
      "Hypertension artérielle (effet hypertenseur léger)",
      "Traitement corticoïde (interaction synergique)",
      "Anticoagulants (interaction via la vitamine K)",
      "Grossesse, allaitement, enfant de moins de 12 ans",
    ],
    tags: ['cassis', 'gemmothérapie', 'cure de printemps'],
    updatedAt: '2026-05-29',
  },

  {
    slug: 'desmodium-foie-renaissance',
    domain: 'naturopathie',
    category: 'plantes',
    title: "Desmodium adscendens : foie et renaissance hépatique",
    excerpt: "Plante africaine d'urgence hépatique, le desmodium soutient les cellules du foie agressées par les médicaments, virus ou excès toxiques.",
    readingTime: 5,
    evidence_level: 'preliminary',
    evidence_note: "Le desmodium adscendens est utilisé en médecine traditionnelle africaine pour les hépatites aiguës. Quelques études expérimentales africaines et françaises rapportent un effet protecteur sur les hépatocytes (baisse de transaminases). Les preuves cliniques restent modestes mais convergentes. Cette plante mérite une place sérieuse dans l'arsenal hépatoprotecteur naturel.",
    intro: "Le desmodium adscendens — petite plante grimpante de l'Afrique de l'Ouest et du Centre — fut introduit en phytothérapie française dans les années 1970 par le docteur Pierre Tubéry, médecin missionnaire au Cameroun. Sa découverte spectaculaire : la plante soutient les hépatocytes agressés par les hépatites virales, les traitements lourds (chimiothérapie, antituberculeux), ou simplement par des excès chroniques. Une plante d'urgence hépatique entrée durablement dans l'arsenal naturopathique.",
    sections: [
      { heading: "Origine et découverte", body: "Le docteur Pierre Tubéry observe au Cameroun la guérison de patients atteints d'hépatite virale traités par décoction de desmodium. Il rapporte la plante en France, où il conduit dans les années 1970 et 1980 des observations cliniques sur des patients sous traitement antituberculeux (isoniazide hépatotoxique). Les transaminases chutent rapidement. La plante entre alors dans la pharmacopée des phytothérapeutes français. Aujourd'hui largement utilisée en accompagnement de chimiothérapies." },
      { heading: "Mécanismes pressentis", body: "Le desmodium contient des saponines triterpéniques, des alcaloïdes (tryptamines), des flavonoïdes spécifiques. Les travaux expérimentaux suggèrent une protection membranaire des hépatocytes contre les agressions oxydatives, une stimulation de la régénération cellulaire, et un effet sur le bronchospasme (usage traditionnel africain dans l'asthme également). Les mécanismes précis restent à élucider, mais l'effet clinique sur les transaminases est reproductible." },
      { heading: "Formes et posologies", body: "Plusieurs formes coexistent : décoction des tiges feuillées séchées (forme traditionnelle, dix grammes pour un litre d'eau, en boire un demi-litre par jour), extrait sec en gélules (six cents à mille deux cents milligrammes par jour), extrait fluide. Cure : trois semaines à trois mois selon l'intensité de l'atteinte hépatique. À prendre matin et midi (peut être discrètement stimulant le soir). Réévaluation des transaminases en cours de cure." },
      { heading: "Indications et précautions", body: "Indications principales : accompagnement de chimiothérapie (sous avis oncologique), hépatite virale en accompagnement médical, traitement antituberculeux, excès chronique alcool ou médicaments hépatotoxiques, cure de drainage hépatique majeure. Précautions : grossesse et allaitement par prudence (peu de données). Greffe d'organe ou immunosuppresseurs : avis médical impératif (effet immunomodulateur possible). Toujours en accompagnement, jamais en substitution d'un traitement médical d'une hépatite aiguë." },
    ],
    keyPoints: [
      "Plante africaine introduite par le Dr Tubéry dans les années 1970",
      "Soutien des hépatocytes en cas d'hépatite ou traitement hépatotoxique",
      "Posologie : 600-1200 mg/j extrait sec, ou décoction traditionnelle",
      "Toujours en accompagnement, jamais seul en pathologie aiguë",
    ],
    contre_indications: [
      "Grossesse, allaitement (par prudence, données limitées)",
      "Greffe d'organe, traitement immunosuppresseur (avis médical)",
      "Substitution à un traitement médical conventionnel d'hépatite",
      "Pathologie hépatique aiguë sans avis médical",
    ],
    tags: ['desmodium', 'foie', 'hépatoprotecteur'],
    updatedAt: '2026-05-29',
  },
];
