import type { Article } from '../types';

const a = (slug: string, title: string, excerpt: string, intro: string, sections: { heading: string; body: string }[], tags: string[]): Article => ({
  slug, domain: 'nutritherapie', category: 'mineraux', title, excerpt, readingTime: 5, intro, sections, tags,
});

export const NUTRI_MINERAUX: Article[] = [
  a('magnesium',
    "Magnésium : le minéral anti-stress n°1",
    "Glycérophosphate, bisglycinate, malate. Cofacteur de 300+ enzymes. Pourquoi 60-80% de la population française est carencée.",
    "Le magnésium est le minéral le plus largement carencé dans nos sociétés modernes : 60 à 80% des Français en sont déficients. Cofacteur de plus de 300 enzymes, il intervient dans la production d'énergie, la transmission nerveuse, la synthèse protéique, la régulation du stress. Sa carence chronique est probablement l'une des causes les plus négligées de l'anxiété, des insomnies, des crampes, de la fatigue.",
    [
      { heading: "Pourquoi tant de carences", body: "Sols agricoles appauvris (-30% en 50 ans). Aliments raffinés (le pain blanc contient 80% moins de Mg que le pain complet). Stress chronique (épuise les réserves intracellulaires). Café et thé (chélation). Eau adoucie. Alcool. Médicaments (IPP, diurétiques). Activité physique intense. Sueur. Conséquence : carence chronique invisible mais omniprésente." },
      { heading: "Formes : la guerre des biodisponibilités", body: "À PRIVILÉGIER : glycérophosphate de magnésium (biodisponibilité ~50%, sans laxatif, neutre digestivement). Bisglycinate (chélaté, très bien toléré). Malate (énergie). Taurate (sommeil). À ÉVITER : oxyde de magnésium (absorption < 5%, laxatif). Chlorure (acidifiant). Sulfate (irritant). Carbonate (peu absorbé). Tester l'étiquette : la quantité indiquée est en MAGNÉSIUM ÉLÉMENT (Mg)." },
      { heading: "Dosages", body: "AJR : 375 mg/jour. Carence : 400 à 600 mg/jour de magnésium-élément. À répartir en 2-3 prises (matin et soir, ou matin + midi + soir). À associer impérativement à la vitamine B6 (P5P) qui permet l'entrée intracellulaire du magnésium. Cure de 4-6 mois minimum pour reconstituer les stocks." },
      { heading: "Signes de carence", body: "Crampes, fasciculations (paupière qui saute). Tétanie, spasmophilie. Anxiété, irritabilité, hypersensibilité au bruit. Insomnies. Fatigue inexpliquée. Maux de tête, migraines. Constipation ou diarrhée selon forme. Hypertension. Syndrome prémenstruel. Calculs rénaux. Acouphènes." },
      { heading: "Sources alimentaires", body: "Algues (varech : 760 mg/100g). Cacao cru (500 mg/100g — 2 carrés de chocolat noir 85% = 60 mg). Graines de courge, tournesol, sésame. Amandes (250 mg/100g). Noix du Brésil. Légumes verts feuillus (épinards, blettes). Sarrasin. Quinoa. Légumineuses. Bananes. Avocat." },
    ],
    ['magnésium', 'stress', 'anxiété']
  ),
  a('zinc',
    "Zinc : immunité, peau, hormones",
    "Cofacteur de 300+ enzymes. Carence fréquente chez vegans, sportifs, séniors. Citrate ou bisglycinate.",
    "Le zinc est, avec le magnésium, l'un des minéraux les plus polyvalents et les plus carencés. Cofacteur de plus de 300 enzymes, il est central pour l'immunité (lymphocytes), la cicatrisation, la peau, les hormones (testostérone, thyroïde), la perception du goût et de l'odorat. Sa carence est fréquente — et souvent méconnue.",
    [
      { heading: "Rôles physiologiques", body: "Cofacteur enzymatique majeur. Immunité (lymphocytes T, thymus). Cicatrisation, intégrité des muqueuses et de la peau. Synthèse hormones thyroïdiennes et sexuelles (testostérone). Antioxydant (SOD). Synthèse ADN. Perception du goût et de l'odorat. Vision (rétine). Métabolisme alcool (alcool-déshydrogénase)." },
      { heading: "Signes de carence", body: "Infections à répétition. Cicatrisation lente. Acné persistante. Perte de cheveux (alopécie). Ongles cassants, taches blanches. Trouble du goût, de l'odorat. Baisse de libido. Vergetures. Hypogonadisme (homme). Cycles irréguliers (femme)." },
      { heading: "Formes recommandées", body: "À PRIVILÉGIER : citrate de zinc (très bien toléré, biodisponible). Bisglycinate (chélaté, optimal). Gluconate (bonne tolérance). Picolinate (excellente assimilation). À ÉVITER : sulfate (irritant gastrique). Oxyde (peu absorbé). Toujours en zinc-élément (lire étiquette)." },
      { heading: "Dosages", body: "AJR : 10 mg/jour. Maintenance : 15-25 mg/jour. Carence (acné, infections, cicatrisation) : 30-40 mg/jour pendant 2-3 mois. À prendre à distance du fer et du calcium (compétition d'absorption). À distance des phytates des céréales. Ne pas dépasser 50 mg/jour en continu (risque de carence cuivre). Cure de 2-3 mois puis pause." },
      { heading: "Le ratio Zinc/Cuivre", body: "Zinc et cuivre sont compétitifs : une supplémentation chronique de zinc peut induire une carence en cuivre. Surveillance : si supplémentation > 3 mois et > 30 mg/jour, ajouter 1-2 mg de cuivre par jour. Ratio idéal Zn/Cu plasma = 6 à 8." },
      { heading: "Sources alimentaires", body: "Huîtres (top source : 60 mg/100g — 1 huître = AJR). Foie, viandes rouges. Graines de courge (10 mg/100g). Cacao cru. Lentilles, pois chiches. Œufs. Noix du Brésil." },
    ],
    ['zinc', 'immunité', 'acné']
  ),
  a('fer',
    "Fer : ferritine avant tout, ne pas supplémenter à l'aveugle",
    "Anémie ferriprive vs surcharge ferrique : les deux existent. Pourquoi le bilan ferritine avant toute supplémentation.",
    "Le fer est probablement le minéral le plus mal géré en supplémentation. Carence fréquente chez les femmes en âge de procréer, les sportifs, les vegans — mais surcharge fréquente chez les hommes adultes et les femmes ménopausées. La supplémentation systématique est dangereuse : elle peut induire stress oxydatif et risque cardiovasculaire chez ceux qui n'en ont pas besoin. Toujours un bilan ferritine avant.",
    [
      { heading: "Le bilan obligatoire", body: "Ferritine sérique : reflet des stocks. Normes : femme 30-150 µg/L, homme 50-300 µg/L. Carence : < 30 µg/L (vraie carence) ; déplétion : 30-50 (limite). Saturation transferrine : optimum 25-35%. Hémoglobine seule insuffisante (chute tardive). Avant toute supplémentation : bilan complet (ferritine, transferrine, fer sérique, CRP)." },
      { heading: "Pourquoi pas de fer en aveugle", body: "Le fer en excès est pro-oxydant (réaction de Fenton avec H₂O₂). La ferritine élevée est un facteur de risque cardiovasculaire indépendant. L'hémochromatose (génétique, 1/300 caucasiens) entraîne surcharge ferrique sévère sans symptômes au début. L'homme adulte ne perd pas de fer (sauf saignements) : aucune supplémentation justifiée sans bilan." },
      { heading: "Quand supplémenter (carence avérée)", body: "Femme en âge de procréer avec règles abondantes. Femme enceinte (selon bilan). Vegan strict de longue date. Adolescent en croissance rapide. Saignement chronique digestif. Sportif endurance (microhémorragies digestives). En présence de ferritine basse + symptômes (fatigue, essoufflement, pâleur, chute cheveux)." },
      { heading: "Formes et dosages", body: "Bisglycinate de fer : la mieux tolérée (pas de constipation, peu de troubles digestifs), excellente biodisponibilité. Sulfate de fer : classique, mal toléré (constipation, gastralgie). Fumarate : intermédiaire. Dosage : 25 à 50 mg de fer-élément/jour à jeun avec vitamine C (multiplie absorption x3). À distance du calcium, du zinc, des phytates, du thé/café. Cure de 3 mois, puis recontrôle." },
      { heading: "Sources alimentaires", body: "Fer héminique (animal, très assimilable) : boudin noir (15 mg/100g), foie, viande rouge, palourdes, sardines. Fer non héminique (végétal, moins assimilable) : lentilles, haricots, épinards, persil, tofu, graines de sésame. Toujours avec vitamine C (citron sur les lentilles)." },
    ],
    ['fer', 'ferritine', 'anémie']
  ),
  a('calcium',
    "Calcium : l'obsession laitière à nuancer",
    "Sources alternatives (algues, légumes verts, eaux), biodisponibilité, synergies indispensables avec D3 et K2.",
    "Le calcium reste le minéral le plus présent dans le corps (1 kg chez l'adulte, 99% dans les os). L'idée que seuls les produits laitiers en apportent est fausse — et même problématique. Une approche moderne du calcium prend en compte les sources alternatives, la biodisponibilité réelle, et les cofacteurs indispensables (vitamine D, K2, magnésium).",
    [
      { heading: "Sources alternatives aux laitages", body: "Sardines avec arêtes (350 mg/100g). Sésame, graines de chia. Algues (varech, dulse). Amandes (250 mg/100g). Brocoli, chou kale, chou frisé. Eaux calciques : Hépar (550 mg/L), Contrex (450), Vittel (200), Salvetat (250). Tofu (selon coagulant). Figues sèches. Persil frais. Tahini. Pour qui retire les laitages : couverture facile par diversification." },
      { heading: "Biodisponibilité réelle", body: "Lait : 30-35% absorbé. Brocoli, chou kale : 50-60% (paradoxalement supérieur). Épinards : 5% (bloqué par oxalates). Tofu au sulfate de calcium : 30%. Eaux minérales : 25-30%. Une alimentation diversifiée végétale et marine couvre largement les besoins même sans laitages." },
      { heading: "Cofacteurs indispensables", body: "Vitamine D3 : multiplie x2 l'absorption intestinale. Vitamine K2 : oriente le calcium absorbé vers les os (et hors des artères). Magnésium : équilibre Ca/Mg essentiel (idéalement 2:1 Ca:Mg). Sans ces cofacteurs, supplémenter le calcium peut être contre-productif (calcifications vasculaires, lithiase rénale)." },
      { heading: "Quand supplémenter (rarement)", body: "Ostéoporose avérée avec carence alimentaire prouvée. Post-ménopause à risque + apports faibles. Le plus souvent : optimiser D3 + K2 + Mg + alimentation suffit. Pas de supplémentation systématique en calcium sans bilan et avis : la dose totale dans l'alimentation moderne est suffisante." },
      { heading: "AJR", body: "Adulte : 800-1000 mg/jour. Couvrable par : 30g sésame (300 mg) + 100g sardines avec arêtes (350) + 1L eau Contrex (450) + 200g brocoli (90). Sans aucun laitage." },
    ],
    ['calcium', 'os', 'D3', 'K2']
  ),
  a('iode',
    "Iode : la thyroïde et bien plus",
    "Bilan thyroïdien obligatoire avant. Hypothyroïdie, métaux lourds, sein fibrokystique : indications précises.",
    "L'iode est l'un des minéraux les plus mal compris. Sa carence (hypothyroïdie, goitre) ET son excès (hyperthyroïdie, Hashimoto) sont délétères. Sa zone thérapeutique est étroite. La supplémentation systématique sans bilan est dangereuse. Mais bien gérée, elle transforme des situations cliniques résistantes (hypothyroïdie infraclinique, sein fibrokystique, fatigue chronique).",
    [
      { heading: "Rôles physiologiques", body: "Synthèse hormones thyroïdiennes T3 et T4 (qui régulent métabolisme basal). Développement cérébral fœtal (carence = retard mental). Antiseptique tissulaire. Drainage lymphatique. Modulation de la prolifération mammaire (sein fibrokystique)." },
      { heading: "Le bilan obligatoire", body: "TSH : > 2,5 mUI/L = thyroïde fatiguée même si dans la norme officielle. T3 libre : optimum 4-6,5 pg/mL. T4 libre : optimum 12-15 pg/mL. Anticorps anti-TPO et anti-Tg : positifs = Hashimoto (auto-immune — prudence avec iode). Iodurie 24h : reflet de l'apport (norme 100-150 µg/L)." },
      { heading: "Quand supplémenter", body: "Hypothyroïdie infraclinique avec apport iodé faible avéré. Femme enceinte (besoin doublé). Sein fibrokystique. Régions à sols pauvres en iode (montagnes). Vegan strict sans algues. Drainage des halogènes (fluor, brome, chlore en excès). À EVITER en cas de : Hashimoto en poussée, Basedow, hyperthyroïdie." },
      { heading: "Dosages et formes", body: "AJR : 150 µg/jour. Maintenance : 150-300 µg/jour. Thérapeutique en hypothyroïdie : 1-3 mg/jour (sous suivi médical, jamais à l'aveugle). Forme : iodure de potassium (sel) ou Lugol (iodure + iode moléculaire). Algues : varech, dulse — concentrations très variables (50 à 4000 µg/g) — privilégier algues testées." },
      { heading: "Sources alimentaires", body: "Algues : varech (2000-3000 µg/g séché — minuscule pincée par jour suffit). Dulse, kombu, nori. Poissons et fruits de mer (50-200 µg/100g). Œufs (10-30 µg). Sel marin enrichi en iode. La consommation régulière modérée d'algues (1g de dulse séchée 2-3x/semaine) couvre les besoins." },
    ],
    ['iode', 'thyroïde', 'algues']
  ),
  a('selenium',
    "Sélénium : antioxydant et thyroïde",
    "Cofacteur glutathion peroxydase. Conversion T4→T3. Marge thérapeutique étroite : 2 noix du Brésil/jour suffisent.",
    "Le sélénium est un oligo-élément essentiel à la fenêtre thérapeutique très étroite : utile et nécessaire à faible dose, toxique à dose élevée. C'est le cofacteur de la glutathion peroxydase (antioxydant majeur) et un acteur central de la conversion T4→T3 thyroïdienne. Sa carence est fréquente dans les régions à sols pauvres.",
    [
      { heading: "Rôles physiologiques", body: "Cofacteur glutathion peroxydase (défense antioxydante majeure). Cofacteur de la déiodinase (conversion T4 → T3, hormone thyroïdienne active). Détoxification métaux lourds (mercure, arsenic). Soutien immunitaire (résistance virale). Protection cardiovasculaire." },
      { heading: "Indications principales", body: "Hashimoto, hypothyroïdie autoimmune (réduit anticorps anti-TPO). Conversion T4→T3 défaillante (T4 normale mais T3 basse). Détoxification mercure (amalgames, gros poissons). Soutien immunitaire (résistance virale). Cures antioxydantes (anti-âge, post-radiothérapie)." },
      { heading: "Formes et dosages", body: "À PRIVILÉGIER : sélénométhionine (forme organique, biodisponible, faible toxicité). Levure enrichie en sélénium. À ÉVITER : sélénite et sélénate de sodium (formes inorganiques, marge thérapeutique étroite). Dosage : 100 à 200 µg/jour, en cure de 2-3 mois. Ne JAMAIS dépasser 400 µg/jour chronique (devient prooxydant)." },
      { heading: "Sources alimentaires (privilégier)", body: "Noix du Brésil : 100 µg par noix en moyenne. 1-2 noix/jour = AJR. ATTENTION : variabilité énorme (de 8 à 200 µg). Privilégier sources contrôlées. Poissons (sardine, thon, hareng). Œufs. Champignons. Levure de bière." },
      { heading: "Toxicité (sélénose)", body: "Apport > 400 µg/jour chronique : odeur d'ail dans l'haleine (premier signe), chute de cheveux, ongles cassants, fatigue, troubles neurologiques. Marge thérapeutique étroite — ne pas dépasser les dosages. Les noix du Brésil restent la source la plus simple, mais maximum 3 par jour." },
    ],
    ['sélénium', 'thyroïde', 'noix Brésil']
  ),
  a('chrome',
    "Chrome : régulation glycémique",
    "Picolinate de chrome 200-400 µg/jour pour la résistance à l'insuline. Pré-diabète, surpoids.",
    "Le chrome (sous forme de chrome trivalent Cr³⁺) est un oligo-élément qui potentialise l'action de l'insuline. Sa carence aggrave la résistance à l'insuline. Sa supplémentation chez les pré-diabétiques et les personnes en surpoids améliore les paramètres glycémiques. Souvent négligé, c'est pourtant un outil simple dans la régulation des sucres.",
    [
      { heading: "Mécanisme", body: "Le chrome forme le 'facteur de tolérance au glucose' (GTF). Il facilite la liaison de l'insuline à ses récepteurs cellulaires et améliore la signalisation post-récepteur. Effet : pour une même quantité d'insuline, le glucose entre mieux dans les cellules. Particulièrement utile en résistance à l'insuline." },
      { heading: "Indications", body: "Résistance à l'insuline. Pré-diabète. Diabète de type 2 (en complément). Hypoglycémies réactionnelles. Fringales sucrées. Syndrome métabolique. Surpoids abdominal. Études : Anderson 1997, 2004 — amélioration significative HbA1c chez diabétiques type 2 supplémentés." },
      { heading: "Forme et dosage", body: "Picolinate de chrome (forme la plus biodisponible) : 200 à 400 µg/jour. Polynicotinate ou GTF (à base de levure de bière) : alternative naturelle, 200-500 µg/jour. Cure de 3 mois minimum pour effets. À prendre avec un repas." },
      { heading: "Sources alimentaires", body: "Levure de bière (top source naturelle). Brocoli. Pomme avec peau. Pomme de terre (peau). Viandes rouges. Œufs. Huîtres. Asperges. Sols modernes appauvris en chrome — supplémentation souvent justifiée chez les profils à risque." },
    ],
    ['chrome', 'insuline', 'glycémie']
  ),
  a('cuivre',
    "Cuivre : oligo-élément à doser",
    "Antagoniste du zinc, cofacteur du collagène. Carence rare mais possible avec supplémentation prolongée en zinc.",
    "Le cuivre est un oligo-élément essentiel souvent négligé. Cofacteur de plusieurs enzymes (céruloplasmine, lysyl-oxydase, dopamine bêta-hydroxylase), il participe à la production d'énergie, à la synthèse du collagène, à la formation des globules rouges. Sa supplémentation est rarement nécessaire — mais devient utile en cas de zincothérapie prolongée.",
    [
      { heading: "Rôles physiologiques", body: "Cofacteur lysyl-oxydase (synthèse collagène et élastine). Céruloplasmine (transporteur fer, antioxydant). Dopamine bêta-hydroxylase (synthèse noradrénaline). Cytochrome c oxydase (chaîne respiratoire mitochondriale). Mélanogenèse." },
      { heading: "Quand supplémenter", body: "Supplémentation en zinc > 3 mois (antagonisme Zn/Cu). Fragilité cutanée, mauvaise cicatrisation. Aphtes récurrents. Cheveux qui blanchissent prématurément. Anévrismes (en prévention chez sujets à risque, sous avis médical). Sinon : alimentation diversifiée suffit." },
      { heading: "Forme et dosage", body: "Bisglycinate de cuivre : la mieux tolérée. Gluconate. Dosage modéré : 1 à 2 mg/jour. AJR : 1,5 mg. Toujours en complément d'une supplémentation zinc prolongée (ratio Zn:Cu de 10:1). JAMAIS plus de 4 mg/jour (toxicité hépatique)." },
      { heading: "Sources alimentaires", body: "Foie, abats (top source). Huîtres. Cacao cru. Noix de cajou. Graines de tournesol. Champignons shiitake. Levure de bière. Alimentation moderne suffit en général." },
    ],
    ['cuivre', 'collagène', 'ratio zinc']
  ),
  a('silicium',
    "Silicium organique : collagène et tissus conjonctifs",
    "Indispensable au collagène, élastine, cartilages, os. Forme organique (ortho-silicique) la seule efficace.",
    "Le silicium est l'oligo-élément le plus abondant dans la croûte terrestre, et pourtant souvent négligé dans la santé humaine. Sous forme ORGANIQUE (ortho-silicique stabilisée), il est indispensable à la synthèse du collagène, à la santé des os, des cartilages, des cheveux et de la peau. C'est l'oligo-élément des tissus conjonctifs.",
    [
      { heading: "Pourquoi seul le silicium organique fonctionne", body: "Le silicium minéral (silicates, oxydes) n'est PAS biodisponible. Seule la forme ORGANIQUE (acide ortho-silicique stabilisé par choline ou silanol) est absorbée et utilisable. Les compléments à base de prêle non extraite, de bambou, ou de simple poudre de silice ne sont pas (ou très peu) actifs." },
      { heading: "Indications", body: "Vieillissement cutané (perte de fermeté). Cheveux fins, qui tombent. Ongles cassants, dédoublés. Arthrose, fragilité articulaire. Ostéoporose (en complément). Athérosclérose (santé vasculaire). Récupération post-fracture. Cure de 3 mois minimum pour effets visibles." },
      { heading: "Formes recommandées", body: "Silicium organique G5 (acide ortho-silicique stabilisé) : la forme la mieux étudiée. Choline-silicate (BioSil). Bambou Tabashir extrait : silicium végétal de qualité. Ortie tisane longue ou EPS : apport quotidien." },
      { heading: "Dosages", body: "Maintenance : 5-10 mg/jour de silicium-élément. Cure thérapeutique : 10-20 mg/jour pendant 3-6 mois. À prendre avec un repas. Cures longues bénéfiques (les effets sur les tissus conjonctifs sont progressifs)." },
      { heading: "Sources alimentaires", body: "Prêle des champs (cure longue). Ortie. Bambou. Avoine, orge, riz complet (silice biogénique). Concombre, courgette (peau). Eaux silicieuses (Volvic : 30 mg/L, Saint-Yorre)." },
    ],
    ['silicium', 'collagène', 'peau']
  ),
  a('manganese',
    "Manganèse : antioxydant et arthrose",
    "Cofacteur SOD mitochondriale. Synergie avec glucosamine pour le cartilage. Cure d'arthrose.",
    "Le manganèse est un oligo-élément essentiel souvent oublié des protocoles santé. Cofacteur de la superoxyde dismutase mitochondriale (SOD2, un des principaux antioxydants cellulaires), il intervient aussi dans la synthèse des protéoglycanes du cartilage. Précieux dans la prévention de l'arthrose et du vieillissement mitochondrial.",
    [
      { heading: "Rôles physiologiques", body: "Cofacteur SOD2 (mitochondrial). Synthèse des protéoglycanes (cartilage, tissus conjonctifs). Métabolisme énergétique. Cofacteur de plusieurs enzymes du cycle de Krebs. Soutien immunitaire." },
      { heading: "Indications", body: "Prévention et accompagnement arthrose. Récupération sportive (réparation cartilage). Vieillissement mitochondrial. Soutien antioxydant cellulaire. Souvent en association avec glucosamine, chondroïtine, collagène hydrolysé." },
      { heading: "Dosages et formes", body: "AJR : 2,5 mg/jour. Cure : 5-10 mg/jour pendant 2-3 mois. Bisglycinate de manganèse : forme assimilable. Ne pas dépasser 11 mg/jour (toxicité neurologique à hautes doses chroniques). En oligothérapie : ampoule Mn-Cu en sublingual." },
      { heading: "Sources alimentaires", body: "Pignons de pin (8,8 mg/100g). Pacanes (4,5 mg). Noisettes. Riz brun. Sarrasin. Avoine. Tofu. Thé vert (modération — chélation possible). Légumes verts feuillus. Ananas." },
    ],
    ['manganèse', 'arthrose', 'SOD']
  ),
  a('potassium',
    "Potassium : sortir du déséquilibre sodium/potassium",
    "Tension, rétention d'eau, crampes. Pourquoi l'alimentation moderne est trop riche en sodium et pauvre en potassium.",
    "Le potassium est l'antagoniste naturel du sodium au niveau cellulaire. Le couple sodium/potassium régule l'équilibre hydrique, la tension artérielle, la transmission nerveuse. L'alimentation moderne inverse complètement le ratio physiologique : trop de sodium (sel ajouté partout) et pas assez de potassium (peu de fruits et légumes). Rééquilibrer ce ratio transforme la tension et la santé cardiovasculaire.",
    [
      { heading: "Le ratio physiologique inversé", body: "Hommes préhistoriques : 6 g K / 1 g Na par jour (ratio 6:1). Aujourd'hui : 2 g K / 8 g Na (ratio 0,25:1). Inversion de facteur 24. Conséquence : rétention sodée, hypertension, fragilité vasculaire. Restauration du ratio = baisse tension, baisse risque cardiovasculaire (étude PURE 2014 : meilleur ratio K/Na = -30% mortalité)." },
      { heading: "Indications", body: "Hypertension. Rétention d'eau. Crampes musculaires. Asthénie. Préparation/récupération sportive intense. Diurétiques au long cours. Régulation glycémique. Ostéoporose (alcalinisation)." },
      { heading: "Apport optimal", body: "AJR : 3500 mg/jour. Apport moderne moyen : 1500-2000 mg. Cible : 4000 mg/jour pour les non-hypertendus, 5000 mg pour hypertendus (sauf insuffisance rénale). Privilégier les sources alimentaires plutôt que les compléments (sauf déshydratation aiguë). Sel de potassium : peut remplacer partiellement le sel de sodium en cuisine." },
      { heading: "Sources alimentaires", body: "Bananes (350 mg/100g — pas la première source). Champignons cuits (400). Patates douces (500). Avocat (500). Épinards (550). Lentilles cuites (370). Saumon (380). Pommes de terre AVEC peau (450). Abricots secs (1500 — concentrés). Eau de coco (250/100ml). Une banane + 1 avocat + 200 g d'épinards = déjà 2 g de K." },
      { heading: "Précautions", body: "Insuffisance rénale : hyperkaliémie dangereuse — ne PAS supplémenter sans avis. Sous IEC (Inhibiteurs Enzyme Conversion), ARA2, diurétiques épargneurs de K : prudence avec les compléments (risque hyperkaliémie). Sels de potassium en grande quantité : peuvent irriter l'estomac." },
    ],
    ['potassium', 'sodium', 'tension']
  ),
  a('molybdene',
    "Molybdène : oligo-élément des sulfites",
    "Cofacteur de la sulfite oxydase. Carence rare mais utile en cas d'intolérance aux sulfites.",
    "Le molybdène est un oligo-élément ultra-trace mais essentiel. Cofacteur de plusieurs enzymes (sulfite oxydase, xanthine oxydase, aldéhyde oxydase), il participe à la détoxification des sulfites et purines. Carence rare mais utile chez les personnes hypersensibles aux sulfites (vins, fruits secs, additifs).",
    [
      { heading: "Rôles physiologiques", body: "Cofacteur sulfite oxydase (détoxification sulfites). Cofacteur xanthine oxydase (métabolisme purines → acide urique). Cofacteur aldéhyde oxydase (détoxification des aldéhydes, dont alcools). Métabolisme du soufre." },
      { heading: "Indications", body: "Intolérance aux sulfites (réactions aux vins blancs, fruits secs sulfités, certains additifs E220-E228). Détoxification post-alcool (peut être adjuvant). Inflammation chronique. Souvent en complément d'autres détoxifiants (NAC, glutathion)." },
      { heading: "Dosages", body: "AJR : 50-65 µg/jour. Cure : 75 à 150 µg/jour pendant 2-3 mois. Ne pas dépasser 200 µg/jour. Forme : molybdate de sodium ou citrate de molybdène." },
      { heading: "Sources alimentaires", body: "Légumineuses (haricots blancs : 350 µg/100g — top source). Foie de bœuf. Lentilles. Pois chiches. Céréales complètes. Noix. Yaourt." },
    ],
    ['molybdène', 'sulfites', 'détox']
  ),
  a('lithium-oligo',
    "Lithium oligo : régulation de l'humeur",
    "Petites doses (lithium orotate) pour le terrain bipolaire léger, anxiété chronique. Différent du carbonate de lithium psychiatrique.",
    "Le lithium en oligothérapie (lithium orotate, gluconate, ou ampoules d'oligo-éléments) est très différent du carbonate de lithium utilisé en psychiatrie (à dose 100-1000x supérieure). À petites doses (1-20 mg/jour), il agit comme régulateur doux de l'humeur, utile dans les terrains à fluctuations d'humeur, l'anxiété chronique, certaines insomnies.",
    [
      { heading: "Lithium oligo vs lithium psychiatrique", body: "Lithium oligo : 1-20 mg de lithium-élément par jour. Sans risque hépato-rénal. Effet régulateur doux sur la sérotonine, le BDNF, la glycogène synthase kinase. Carbonate de lithium psychiatrique : 800-1200 mg/jour (200-400 mg de lithium-élément). Marge thérapeutique étroite, suivi sanguin obligatoire. Ne pas confondre." },
      { heading: "Indications de l'oligo", body: "Terrain bipolaire léger ou cyclothymique (sous avis médical). Anxiété chronique avec irritabilité. Insomnies de fin de nuit. Migraines liées à l'humeur. Soutien neurologique anti-âge (études prometteuses sur prévention démence). À considérer en complément d'autres approches naturelles." },
      { heading: "Forme et dosage", body: "Lithium orotate : 5 à 20 mg de lithium-élément par jour. Ampoules de gluconate de lithium (Oligosol) : 1-2 ampoules/jour en sublingual. À distance des repas, le matin. Cure de 3 mois, puis pause. Suivi clinique recommandé." },
      { heading: "Précautions", body: "Insuffisance rénale : éviter. Femmes enceintes : éviter (par précaution). Personnes sous lithium psychiatrique : ne pas cumuler. Diurétiques : prudence. Les doses oligothérapiques sont 50 à 100 fois inférieures aux doses toxiques, mais certaines précautions s'appliquent." },
    ],
    ['lithium', 'humeur', 'oligo-éléments']
  ),
  a('bore',
    "Bore : oligo-élément des os et des hormones",
    "Soutient la fixation calcique, équilibre les hormones sexuelles. Cure d'ostéoporose et de péri-ménopause.",
    "Le bore est un oligo-élément discret mais important pour la santé osseuse et l'équilibre hormonal. Il facilite l'utilisation du calcium et du magnésium, et module les hormones sexuelles (oestradiol, testostérone). Précieux en péri-ménopause et en prévention de l'ostéoporose.",
    [
      { heading: "Rôles physiologiques", body: "Métabolisme du calcium et du magnésium. Modulation des hormones sexuelles (augmente disponibilité de l'oestradiol et de la testostérone). Soutien des os et des articulations. Cofacteur de plusieurs enzymes. Anti-inflammatoire articulaire." },
      { heading: "Indications", body: "Ostéoporose, ostéopénie. Péri-ménopause (équilibrage hormonal). Hypogonadisme léger masculin. Arthrose (effet anti-inflammatoire). Cognition (études préliminaires). Souvent en association avec D3, K2, Mg, Ca pour la santé osseuse." },
      { heading: "Dosages", body: "AJR : non établi. Apport sécuritaire : 3 à 10 mg/jour. Cure : 3 à 6 mg/jour pendant 2-3 mois. Forme : citrate de bore ou bore amino-chélaté. Toxicité au-delà de 20 mg/jour." },
      { heading: "Sources alimentaires", body: "Prunes séchées (top source). Raisins secs. Amandes. Avocat. Brocoli. Pommes. Poires. Eau (variable selon source). Vin (non recommandé comme source)." },
    ],
    ['bore', 'os', 'hormones']
  ),
];
