import type { RecetteJus } from '../types';

/**
 * Batch 2 — Walker fondamentaux supplémentaires, jus de saison
 * et protocoles méthodologiques (15 recettes).
 *
 * Les références Walker citent : N.W. Walker, "Fresh Vegetable and Fruit Juices",
 * Norwalk Press, première édition 1936, révisée 1978. Les bénéfices indiqués
 * relèvent de la tradition naturopathique et de l'expérience clinique de Walker,
 * pas d'essais randomisés.
 */
export const JUS_BATCH2_SAISON_WALKER: RecetteJus[] = [
  /* ───────────────── WALKER FONDAMENTAUX ───────────────── */
  {
    slug: 'jus-carotte-betterave-walker',
    category: 'walker-fondamentaux',
    nom: 'Jus carotte-betterave (Walker)',
    excerpt: 'Le duo de Walker pour soutenir le foie et la vésicule biliaire.',
    intro:
      "Walker considérait l'association carotte-betterave comme l'une des formules les plus précieuses pour la fonction hépatobiliaire et la qualité du sang. Le rapport classique est environ 3 volumes de carotte pour 1 volume de betterave : la betterave seule est trop concentrée et peut provoquer un nettoyage trop brutal.",
    ingredients: [
      { item: 'Carottes (fanes coupées, lavées)', quantite: '350 g (≈ 4 carottes)' },
      { item: 'Betterave crue (épluchée si non bio)', quantite: '100 g (≈ ⅓ de betterave)' },
      { item: 'Citron pour stabiliser la couleur (facultatif)', quantite: '½ citron' },
    ],
    preparation: [
      'Brosser et rincer les carottes ; éplucher la betterave si elle n\'est pas bio.',
      'Couper en tronçons compatibles avec la cheminée de l\'extracteur.',
      'Passer carottes puis betterave en alternance pour ne pas saturer la vis.',
      'Ajouter le jus d\'un demi-citron, mélanger, boire dans les 15 minutes.',
    ],
    benefices: [
      'Soutien traditionnel de la fonction hépatique et biliaire',
      'Apport en bêta-carotène, bétaïne et nitrates naturels',
      'Contribue à la qualité du sang selon Walker',
      'Effet doucement laxatif et reminéralisant',
    ],
    frequence: '1 verre de 200 ml, 3 à 4 fois par semaine, plutôt le matin à jeun.',
    appareil: 'extracteur',
    walkerReference: 'Walker, Fresh Vegetable and Fruit Juices, 1936/1978',
    contre_indications: [
      'Calculs rénaux d\'oxalate de calcium : la betterave est riche en oxalates',
      'Diabète mal équilibré : surveiller la glycémie (jus de racines sucrées)',
      'Coloration rose des urines et des selles, sans gravité (béturie)',
    ],
    tradition: 'Formule centrale du protocole hépatique de Walker depuis les années 1930.',
    tags: ['walker', 'foie', 'vesicule', 'sang', 'classique'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-concombre-betterave-walker',
    category: 'walker-fondamentaux',
    nom: 'Jus concombre-betterave (Walker)',
    excerpt: 'Le duo de Walker pour les reins et la beauté de la peau.',
    intro:
      "Walker recommandait l'association concombre-betterave pour soutenir l'élimination rénale et la clarté du teint. Le concombre apporte une eau biologique très diurétique ; la betterave nettoie le sang. Le rapport recommandé est 2/3 concombre pour 1/3 betterave, avec une carotte pour adoucir.",
    ingredients: [
      { item: 'Concombre (peau gardée si bio)', quantite: '300 g (≈ 1 concombre)' },
      { item: 'Betterave crue épluchée', quantite: '80 g' },
      { item: 'Carotte', quantite: '150 g (≈ 2 carottes)' },
    ],
    preparation: [
      'Laver le concombre ; le couper en bâtonnets sans l\'éplucher s\'il est bio.',
      'Éplucher la betterave si elle est conventionnelle.',
      'Passer concombre, carotte puis betterave à l\'extracteur.',
      'Boire immédiatement, en dehors des repas.',
    ],
    benefices: [
      'Effet diurétique doux et reminéralisant',
      'Soutien rénal et nettoyage du sang selon Walker',
      'Hydratation profonde, teint plus lumineux',
      'Apport en silice du concombre, bétaïne de la betterave',
    ],
    frequence: '1 verre de 250 ml, 3 fois par semaine, l\'après-midi.',
    appareil: 'extracteur',
    walkerReference: 'Walker, Fresh Vegetable and Fruit Juices, 1936/1978',
    contre_indications: [
      'Antécédents de calculs rénaux d\'oxalate de calcium',
      'Insuffisance rénale : tout jus diurétique demande un avis médical',
      'Diabète : la part de betterave reste sucrée',
    ],
    tradition: 'Formule "rein et peau" classique de l\'école hygiéniste de Walker.',
    tags: ['walker', 'reins', 'peau', 'diuretique', 'silice'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-carotte-laitue-alfalfa-walker',
    category: 'walker-fondamentaux',
    nom: 'Jus carotte-laitue-luzerne (Walker, cheveux et peau)',
    excerpt: 'La formule de Walker pour la vitalité des cheveux et la peau.',
    intro:
      "Walker considérait cette association comme la formule majeure pour le cuir chevelu et la qualité des phanères : carotte pour le bêta-carotène, laitue romaine pour les minéraux, jeunes pousses de luzerne (alfalfa) pour les vitamines et chlorophylle. Elle se boit en cure longue plutôt qu'occasionnellement.",
    ingredients: [
      { item: 'Carottes', quantite: '300 g (≈ 3 à 4 carottes)' },
      { item: 'Laitue romaine ou batavia', quantite: '150 g (≈ ½ pomme)' },
      { item: 'Pousses ou herbe d\'alfalfa (luzerne)', quantite: '40 g' },
    ],
    preparation: [
      'Laver la laitue feuille à feuille ; rincer les pousses de luzerne.',
      'Couper les carottes en tronçons.',
      'Passer alternativement carotte, laitue compactée, luzerne.',
      'Mélanger et boire dans les 10 minutes pour préserver la chlorophylle.',
    ],
    benefices: [
      'Vitalité du cuir chevelu et des phanères (tradition Walker)',
      'Apport en silice, bêta-carotène, vitamine K et chlorophylle',
      'Soutien minéral global',
      'Action calmante du système nerveux (laitue)',
    ],
    frequence: '1 verre de 250 ml, 4 à 5 fois par semaine pendant 6 à 8 semaines.',
    appareil: 'extracteur',
    walkerReference: 'Walker, Fresh Vegetable and Fruit Juices, 1936/1978',
    contre_indications: [
      'Sous anticoagulants type AVK (warfarine, fluindione) : laitue et luzerne riches en vitamine K, demander un avis médical',
      'Pathologies auto-immunes (lupus) : la luzerne contient de la L-canavanine, à éviter',
      'Allergie aux Fabacées (légumineuses)',
    ],
    tradition: 'Formule "cheveux" historique de Walker, popularisée dans les années 1950.',
    tags: ['walker', 'cheveux', 'peau', 'chlorophylle', 'silice'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-celeri-persil-walker',
    category: 'walker-fondamentaux',
    nom: 'Jus céleri-persil (Walker)',
    excerpt: 'Le duo sodium organique + chlorophylle de Walker.',
    intro:
      "Walker insistait sur la distinction entre sodium inorganique (sel de table) et sodium organique du céleri, qu'il jugeait indispensable à l'équilibre acido-basique. Associé au persil, riche en chlorophylle et en fer, ce jus est un grand classique reminéralisant à consommer modérément à cause de la concentration en persil.",
    ingredients: [
      { item: 'Branches de céleri avec feuilles', quantite: '300 g (≈ ½ pied)' },
      { item: 'Persil plat frais', quantite: '30 g (1 petit bouquet)' },
      { item: 'Carotte (pour adoucir)', quantite: '100 g' },
      { item: 'Pomme verte (facultatif)', quantite: '½ pomme' },
    ],
    preparation: [
      'Laver soigneusement le céleri et le persil.',
      'Couper le céleri en tronçons de 5 cm.',
      'Compacter le persil dans la cheminée entre deux branches de céleri.',
      'Passer carotte et pomme en alternance.',
      'Mélanger et boire rapidement.',
    ],
    benefices: [
      'Apport en sodium organique selon Walker',
      'Chlorophylle, fer et vitamine K du persil',
      'Effet diurétique doux',
      'Soutien de l\'équilibre acido-basique',
    ],
    frequence: '1 verre de 200 ml, 2 à 3 fois par semaine maximum (persil concentré).',
    appareil: 'extracteur',
    walkerReference: 'Walker, Fresh Vegetable and Fruit Juices, 1936/1978',
    contre_indications: [
      'Grossesse : éviter de fortes doses de persil (effet emménagogue)',
      'Sous anticoagulants type AVK : vitamine K élevée',
      'Insuffisance rénale : association diurétique + persil concentré déconseillée',
      'Allergie aux Apiacées (céleri, persil, fenouil)',
    ],
    tradition: 'Couple "sodium organique" emblématique de la pensée nutritionnelle de Walker.',
    tags: ['walker', 'sodium', 'chlorophylle', 'fer', 'reminéralisant'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-pomme-celeri-walker',
    category: 'walker-fondamentaux',
    nom: 'Jus pomme-céleri (Walker, rééquilibrage alcalin)',
    excerpt: 'Le jus alcalinisant doux que Walker plaçait dans presque toutes ses cures.',
    intro:
      "Walker recommandait l'association pomme-céleri comme jus de fond, à intégrer dans les cures longues, parce qu'il combine le caractère alcalinisant des légumes-feuilles et la douceur sucrée de la pomme. C'est un excellent jus d'initiation pour les personnes peu habituées aux jus verts.",
    ingredients: [
      { item: 'Pommes (variétés peu sucrées : Granny, Reinette)', quantite: '300 g (≈ 2 pommes)' },
      { item: 'Branches de céleri avec feuilles', quantite: '250 g' },
      { item: 'Citron', quantite: '½ citron' },
    ],
    preparation: [
      'Laver les pommes ; les épépiner si extracteur lent.',
      'Couper le céleri en tronçons.',
      'Passer en alternance pomme et céleri à l\'extracteur.',
      'Ajouter le jus d\'un demi-citron, mélanger, boire frais.',
    ],
    benefices: [
      'Rééquilibrage acido-basique selon Walker',
      'Apport en potassium, sodium organique, fibres solubles',
      'Effet diurétique doux et hydratant',
      'Bonne porte d\'entrée aux jus de légumes pour les débutants',
    ],
    frequence: '1 verre de 250 ml par jour, en cure de 2 à 3 semaines.',
    appareil: 'les-deux',
    walkerReference: 'Walker, Fresh Vegetable and Fruit Juices, 1936/1978',
    contre_indications: [
      'Diabète mal équilibré : doser la part de pomme',
      'Allergie aux Apiacées (céleri)',
      'Reflux gastro-œsophagien : éviter le citron à jeun',
    ],
    tradition: 'Jus de fond des cures Walker, présenté comme "le jus de tous les jours".',
    tags: ['walker', 'alcalinisant', 'debutant', 'doux', 'cure'],
    updatedAt: '2026-05-29',
  },

  /* ───────────────── JUS DE SAISON ───────────────── */
  {
    slug: 'jus-printemps-pissenlit-pomme',
    category: 'detox',
    nom: 'Jus de printemps pissenlit-pomme',
    excerpt: 'Le grand classique drainant du printemps, sauvage et doux à la fois.',
    intro:
      "Le printemps est traditionnellement la saison de la cure hépatique. Le pissenlit (feuilles jeunes) est un draineur biliaire reconnu en phytothérapie ; la pomme l'adoucit et apporte de la pectine. C'est un jus à faire avec des feuilles bien jeunes, cueillies loin des routes et des champs traités.",
    ingredients: [
      { item: 'Jeunes feuilles de pissenlit', quantite: '60 g (≈ 2 poignées tassées)' },
      { item: 'Pommes', quantite: '300 g (≈ 2 pommes)' },
      { item: 'Carotte (pour adoucir)', quantite: '100 g' },
      { item: 'Citron', quantite: '½ citron' },
    ],
    preparation: [
      'Trier et laver soigneusement le pissenlit, deux ou trois passages d\'eau.',
      'Couper pommes et carotte en tronçons.',
      'Passer le pissenlit entre deux morceaux de pomme à l\'extracteur.',
      'Ajouter le jus de citron, mélanger, boire dans le quart d\'heure.',
    ],
    benefices: [
      'Soutien hépatobiliaire de printemps (tradition)',
      'Effet drainant et légèrement diurétique',
      'Apport en vitamines A, C, potassium',
      'Aide à relancer la vitalité après l\'hiver',
    ],
    frequence: '1 verre de 200 ml par jour pendant 10 à 14 jours, au printemps.',
    appareil: 'extracteur',
    contre_indications: [
      'Obstruction des voies biliaires, calculs : avis médical',
      'Allergie aux Astéracées (pissenlit, camomille, arnica)',
      'Sous anticoagulants type AVK : feuilles de pissenlit riches en vitamine K',
    ],
    tradition: 'Cure de printemps héritée de la médecine populaire européenne.',
    tags: ['printemps', 'detox', 'foie', 'pissenlit', 'saison'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-ete-pasteque-menthe-citron',
    category: 'detox',
    nom: 'Jus d\'été pastèque-menthe-citron',
    excerpt: 'Le jus rafraîchissant de canicule, riche en citrulline et en eau biologique.',
    intro:
      "La pastèque est composée à plus de 90 % d'eau et contient de la citrulline, intéressante pour la circulation. Associée à la menthe fraîche et au citron, elle compose un jus très désaltérant, particulièrement adapté aux journées chaudes. C'est un jus sucré : à doser pour les personnes diabétiques.",
    ingredients: [
      { item: 'Chair de pastèque sans pépins (ou avec pour les nutriments)', quantite: '500 g' },
      { item: 'Feuilles de menthe fraîche', quantite: '15 g (≈ 1 petit bouquet)' },
      { item: 'Citron jaune', quantite: '1 citron' },
      { item: 'Glaçons (au moment de servir)', quantite: '4 à 6 glaçons' },
    ],
    preparation: [
      'Découper la chair de pastèque en cubes.',
      'Passer pastèque et menthe à l\'extracteur, ou mixer puis filtrer.',
      'Ajouter le jus du citron pressé.',
      'Servir très frais sur glaçons.',
    ],
    benefices: [
      'Hydratation et reminéralisation par temps chaud',
      'Apport en citrulline et lycopène',
      'Effet diurétique doux',
      'Coupe-faim sain en collation d\'été',
    ],
    frequence: '1 verre de 250 ml par jour en saison chaude, en collation.',
    appareil: 'les-deux',
    contre_indications: [
      'Diabète mal équilibré : la pastèque a un index glycémique élevé',
      'Reflux gastro-œsophagien : adapter la dose de citron',
      'Coliques néphrétiques en cours : avis médical',
    ],
    tradition: 'Boisson estivale classique des pays méditerranéens.',
    tags: ['ete', 'pasteque', 'hydratation', 'menthe', 'saison'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-automne-pomme-cannelle-betterave',
    category: 'energie',
    nom: 'Jus d\'automne pomme-cannelle-betterave',
    excerpt: 'Le jus tonique des matins frais, parfumé à la cannelle de Ceylan.',
    intro:
      "À la rentrée, l'organisme cherche de l'énergie sans excès de stimulants. Ce jus combine la richesse en nitrates de la betterave (utile pour l'oxygénation), la douceur de la pomme et la cannelle de Ceylan, traditionnellement réchauffante. À privilégier en cannelle de Ceylan (Cinnamomum verum) plutôt que cassia, moins riche en coumarine.",
    ingredients: [
      { item: 'Pommes (Reinette, Boskoop)', quantite: '300 g (≈ 2 pommes)' },
      { item: 'Betterave crue épluchée', quantite: '100 g' },
      { item: 'Carotte', quantite: '150 g' },
      { item: 'Cannelle de Ceylan en poudre', quantite: '½ cuillère à café' },
      { item: 'Citron', quantite: '½ citron' },
    ],
    preparation: [
      'Éplucher la betterave si elle est conventionnelle.',
      'Couper pommes et carottes en tronçons.',
      'Passer pommes, carottes puis betterave à l\'extracteur.',
      'Saupoudrer de cannelle, ajouter le jus de citron, mélanger.',
      'Boire immédiatement.',
    ],
    benefices: [
      'Énergie matinale sans excitant',
      'Soutien de la circulation et de l\'oxygénation (nitrates de betterave)',
      'Effet réchauffant traditionnel de la cannelle',
      'Modulation glycémique avec la cannelle (données préliminaires)',
    ],
    frequence: '1 verre de 250 ml le matin, 3 à 4 fois par semaine d\'automne.',
    appareil: 'extracteur',
    contre_indications: [
      'Préférer la cannelle de Ceylan : la cassia est riche en coumarine (toxicité hépatique à forte dose)',
      'Calculs rénaux d\'oxalate : la betterave est riche en oxalates',
      'Diabète : surveiller la glycémie',
      'Grossesse : limiter la cannelle aux doses culinaires',
    ],
    tradition: 'Boisson chaude d\'automne adaptée en jus cru tonique.',
    tags: ['automne', 'energie', 'cannelle', 'betterave', 'saison'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-hiver-orange-curcuma-gingembre',
    category: 'immunite',
    nom: 'Jus d\'hiver orange-curcuma-gingembre',
    excerpt: 'Le trio hivernal classique, riche en vitamine C et en composés anti-inflammatoires.',
    intro:
      "Quand les premiers refroidissements arrivent, ce jus combine la vitamine C des oranges, la curcumine du curcuma frais (avec un peu de poivre pour l'assimiler) et le gingerol du gingembre. C'est un soutien immunitaire traditionnel, à prendre à la première sensation de fatigue ou de gorge irritée.",
    ingredients: [
      { item: 'Oranges (bio si possible, zeste utilisable)', quantite: '4 oranges (≈ 600 g)' },
      { item: 'Racine de curcuma frais', quantite: '20 g' },
      { item: 'Racine de gingembre frais', quantite: '20 g' },
      { item: 'Poivre noir moulu', quantite: '1 pincée' },
      { item: 'Citron', quantite: '1 citron' },
    ],
    preparation: [
      'Éplucher les oranges en laissant la partie blanche pour les bioflavonoïdes.',
      'Brosser curcuma et gingembre (épluchage facultatif si bio).',
      'Passer oranges, curcuma, gingembre puis citron à l\'extracteur.',
      'Ajouter une pincée de poivre noir, mélanger.',
      'Boire immédiatement, le curcuma s\'oxyde vite.',
    ],
    benefices: [
      'Soutien immunitaire saisonnier (vitamine C, bioflavonoïdes)',
      'Action anti-inflammatoire traditionnelle (curcuma, gingembre)',
      'Effet réchauffant et stimulant digestif',
      'Confort des voies respiratoires en début d\'infection',
    ],
    frequence: '1 verre de 200 ml par jour pendant 7 à 10 jours, en cure courte hivernale.',
    appareil: 'extracteur',
    contre_indications: [
      'Traitements anticoagulants : curcuma et gingembre fluidifient le sang',
      'Calculs biliaires : le curcuma stimule la sécrétion biliaire',
      'Reflux gastro-œsophagien : adapter la dose de gingembre',
      'Veille d\'opération : arrêter 1 semaine avant',
    ],
    tradition: 'Adaptation du chyavanprash ayurvédique en jus cru frais.',
    tags: ['hiver', 'immunite', 'curcuma', 'gingembre', 'saison'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-equinoxe-vert-cresson',
    category: 'detox',
    nom: 'Jus vert d\'équinoxe au cresson',
    excerpt: 'Le jus vert chlorophyllien des intersaisons pour relancer le métabolisme.',
    intro:
      "Aux changements de saison, un jus vert riche en chlorophylle et en glucosinolates aide à relancer les enzymes hépatiques de détoxication. Le cresson est l'une des plantes les plus denses en nutriments selon le CDC ; il s'associe ici à la pomme verte, au concombre et à l'épinard pour un jus puissant mais équilibré.",
    ingredients: [
      { item: 'Cresson frais (botte bien lavée)', quantite: '60 g' },
      { item: 'Épinards frais', quantite: '60 g' },
      { item: 'Concombre', quantite: '200 g' },
      { item: 'Pomme verte (Granny)', quantite: '1 pomme (≈ 150 g)' },
      { item: 'Citron', quantite: '½ citron' },
      { item: 'Gingembre frais', quantite: '5 g' },
    ],
    preparation: [
      'Laver très soigneusement cresson et épinards (terre, parasites).',
      'Couper concombre et pomme en bâtonnets.',
      'Passer alternativement feuilles vertes (compactées entre fruits) et fruits/légumes.',
      'Ajouter le jus de citron, mélanger, boire dans les 10 minutes.',
    ],
    benefices: [
      'Apport élevé en chlorophylle, vitamine K, folates, fer non héminique',
      'Glucosinolates du cresson : soutien des enzymes de détoxication hépatique',
      'Effet alcalinisant',
      'Adapté aux intersaisons (équinoxes printemps/automne)',
    ],
    frequence: '1 verre de 250 ml, 3 fois par semaine pendant 2 semaines aux équinoxes.',
    appareil: 'extracteur',
    contre_indications: [
      'Sous anticoagulants type AVK : très riche en vitamine K',
      'Hypothyroïdie non traitée : Brassicacées (cresson) à modérer si traitement antithyroïdien',
      'Calculs rénaux d\'oxalate : épinards riches en oxalates',
      'Cresson sauvage : risque de douve du foie, n\'utiliser que du cresson cultivé contrôlé',
    ],
    tradition: 'Adaptation moderne des cures "verdure" des hygiénistes du XXe siècle.',
    tags: ['detox', 'vert', 'cresson', 'intersaison', 'chlorophylle'],
    updatedAt: '2026-05-29',
  },

  /* ───────────────── PROTOCOLES & MÉTHODOLOGIE ───────────────── */
  {
    slug: 'protocole-jus-21-jours',
    category: 'detox',
    nom: 'Protocole 21 jours : trois semaines de cure jus',
    excerpt: 'Le protocole progressif de 21 jours pour intégrer les jus en profondeur.',
    intro:
      "Ce n'est pas un jus mais une méthodologie : trois semaines pour installer une cure complète. Semaine 1 introduction progressive, semaine 2 plein régime, semaine 3 reprise alimentaire. C'est un cadre prudent, inspiré des cures de Walker et de Norman, qui évite la brutalité des monodiètes trop courtes.",
    ingredients: [
      { item: 'Semaine 1 — Jus pomme-céleri-carotte', quantite: '500 ml/jour (2 prises)' },
      { item: 'Semaine 2 — Trois jus/jour (Walker carotte-épinard, vert d\'équinoxe, betterave-carotte)', quantite: '750 ml/jour total' },
      { item: 'Semaine 3 — Reprise : 1 jus + repas légers cuits', quantite: '300 ml/jour + soupes' },
      { item: 'Tisanes accompagnatrices (romarin, pissenlit, fenouil)', quantite: '500 ml/jour' },
      { item: 'Eau pure', quantite: '1,5 L/jour' },
    ],
    preparation: [
      'Semaine 1 : remplacer le petit-déjeuner par un jus doux pomme-céleri-carotte, garder repas normaux légers.',
      'Semaine 2 : trois jus dans la journée (matin tonique, midi vert, fin d\'après-midi reminéralisant), bouillon de légumes le soir.',
      'Semaine 3 : un jus le matin, puis réintroduction progressive : fruits cuits, légumes vapeur, céréales semi-complètes, puis légumineuses.',
      'Tout au long : hydratation, marche douce, repos, pas de sport intense.',
    ],
    benefices: [
      'Cadre progressif évitant les crises de détoxication brutales',
      'Soutien des émonctoires hépatique et rénal',
      'Sensation de légèreté, amélioration du sommeil souvent rapportée',
      'Méthodologie reproductible 1 à 2 fois par an',
    ],
    frequence: '1 à 2 cures de 21 jours par an, idéalement au printemps et à l\'automne.',
    appareil: 'extracteur',
    walkerReference: 'Walker, Fresh Vegetable and Fruit Juices, 1936/1978',
    contre_indications: [
      'Femme enceinte ou allaitante : cure complète déconseillée',
      'Diabète insulino-dépendant : nécessite suivi médical strict',
      'Troubles du comportement alimentaire',
      'Insuffisance rénale ou hépatique',
      'Enfants, adolescents en croissance',
      'Toute pathologie chronique sous traitement : avis médical avant de commencer',
    ],
    tradition: 'Protocole en trois temps issu de la naturopathie classique européenne et nord-américaine.',
    tags: ['protocole', 'cure', 'detox', 'methodologie', '21-jours'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-monodiete-raisin-rentree',
    category: 'detox',
    nom: 'Monodiète raisin de rentrée (cure courte)',
    excerpt: 'La cure courte de raisin frais, classique de la fin d\'été.',
    intro:
      "La monodiète de raisin est une cure traditionnelle décrite par Johanna Brandt au début du XXe siècle, populaire en septembre quand le raisin est mûr. Sur 1 à 3 jours, le raisin est le seul aliment, consommé en grappes et en jus frais. C'est une cure courte, à réserver aux personnes en bonne santé.",
    ingredients: [
      { item: 'Raisin frais bien mûr (Chasselas, Muscat, raisin noir) bio impérativement', quantite: '1 à 1,5 kg/jour' },
      { item: 'Eau pure ou tisane légère (verveine, mélisse)', quantite: '1,5 L/jour' },
    ],
    preparation: [
      'Choisir du raisin bio, bien lavé, à consommer avec la peau et les pépins (broyés à la mastication ou à l\'extracteur).',
      'Répartir la quantité sur 4 à 5 prises dans la journée : grains entiers le matin, jus frais l\'après-midi.',
      'Pour le jus : passer les grappes à l\'extracteur (200 à 250 ml par prise).',
      'Boire de l\'eau ou des tisanes entre les prises.',
      'Reprise alimentaire progressive : compote, légumes cuits, céréales.',
    ],
    benefices: [
      'Apport en polyphénols (resvératrol, anthocyanes, OPC)',
      'Effet drainant et reminéralisant traditionnel',
      'Repos digestif favorisé par la monodiète',
      'Sensation de légèreté après la cure',
    ],
    frequence: 'Cure de 1 à 3 jours en septembre, 1 fois par an maximum.',
    appareil: 'extracteur',
    contre_indications: [
      'Diabète : monodiète très sucrée, formellement déconseillée',
      'Hypoglycémie réactionnelle, troubles de la glycémie',
      'Grossesse, allaitement, enfants',
      'Troubles du comportement alimentaire',
      'Mycoses chroniques (sucre = substrat)',
      'Avis médical recommandé avant toute cure prolongée',
    ],
    tradition: 'Cure popularisée par Johanna Brandt (The Grape Cure, 1928) puis par les hygiénistes.',
    tags: ['monodiete', 'raisin', 'detox', 'rentree', 'cure-courte'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-bouillon-legumes-soir',
    category: 'digestion',
    nom: 'Bouillon de légumes du soir (alternative au jus cru)',
    excerpt: 'Le bouillon clair tiède, alternative chaude au jus cru pour les soirées fraîches.',
    intro:
      "Le jus cru n'est pas toujours adapté en fin de journée, surtout en hiver, ou pour les personnes au tube digestif sensible. Le bouillon de légumes clair, tiède, apporte minéraux et chaleur en respectant la digestion. C'est un complément naturel aux cures de jus, et un soutien quotidien pour les tempéraments frileux.",
    ingredients: [
      { item: 'Carottes', quantite: '200 g' },
      { item: 'Poireau (blanc et vert)', quantite: '1 poireau' },
      { item: 'Branche de céleri', quantite: '2 branches' },
      { item: 'Oignon', quantite: '1 oignon' },
      { item: 'Persil, thym, laurier', quantite: '1 bouquet' },
      { item: 'Eau pure', quantite: '1,5 L' },
      { item: 'Sel non raffiné (gris de Guérande)', quantite: '½ cuillère à café' },
    ],
    preparation: [
      'Laver et couper grossièrement tous les légumes (sans les éplucher si bio).',
      'Porter l\'eau à frémissement avec le bouquet garni.',
      'Ajouter les légumes, laisser cuire 30 minutes à feu très doux, couvert.',
      'Filtrer pour ne garder que le bouillon clair (les légumes peuvent être consommés à part).',
      'Saler légèrement et boire tiède.',
    ],
    benefices: [
      'Apport en minéraux solubles (potassium, magnésium, sodium organique)',
      'Effet hydratant et réchauffant',
      'Repos digestif comparable au jus, sans agression du froid',
      'Excellent en soutien de cures de jus l\'hiver ou en cas de tube digestif sensible',
    ],
    frequence: '1 bol de 300 ml en début de repas du soir, quotidien possible.',
    appareil: 'extracteur',
    contre_indications: [
      'Insuffisance rénale : limiter le sel, le potassium',
      'Régime hyposodé strict : adapter le sel',
      'Conserver au frais 48 h maximum, ou congeler',
    ],
    tradition: 'Le "bouillon Hauser" et les bouillons Kousmine sont les ancêtres reconnus de cette pratique.',
    tags: ['bouillon', 'soir', 'reminéralisant', 'hiver', 'doux'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-acerola-camu-camu-shot',
    category: 'immunite',
    nom: 'Shot acérola-camu camu vitamine C',
    excerpt: 'Le shot concentré en vitamine C naturelle pour les périodes de fatigue.',
    intro:
      "L'acérola et le camu camu sont parmi les fruits les plus riches en vitamine C naturelle au monde, à teneur très supérieure à l'orange. Cette préparation se rapproche du complément alimentaire que d'un jus traditionnel, à boire en cure courte sous forme de shot de 50 ml, plutôt qu'en grande quantité.",
    ingredients: [
      { item: 'Poudre d\'acérola 25 % (séchée à froid)', quantite: '½ cuillère à café (≈ 2 g)' },
      { item: 'Poudre de camu camu', quantite: '½ cuillère à café (≈ 1,5 g)' },
      { item: 'Jus d\'orange ou de mandarine pressé frais', quantite: '40 ml' },
      { item: 'Jus de citron', quantite: '10 ml (≈ ½ citron)' },
      { item: 'Eau pure ou de coco', quantite: '20 ml (facultatif)' },
    ],
    preparation: [
      'Presser orange et citron au presse-agrumes.',
      'Verser les jus dans un petit verre.',
      'Ajouter les poudres d\'acérola et de camu camu, fouetter à la fourchette.',
      'Boire immédiatement, le shot s\'oxyde rapidement.',
    ],
    benefices: [
      'Apport élevé en vitamine C naturelle (forme acide ascorbique entourée de cofacteurs)',
      'Soutien immunitaire en cure courte',
      'Antioxydants : polyphénols, anthocyanes',
      'Pratique en voyage ou périodes de surmenage',
    ],
    frequence: '1 shot de 50 ml par jour, le matin, en cure de 10 à 14 jours.',
    appareil: 'mortier',
    contre_indications: [
      'Calculs rénaux d\'oxalate : la vitamine C en très forte dose peut majorer le risque',
      'Hémochromatose : la vitamine C favorise l\'absorption du fer',
      'Reflux gastro-œsophagien : préparation acide',
      'Vérifier l\'origine et l\'absence de sulfites des poudres',
    ],
    tradition: 'Adaptation moderne en shot des fruits amazoniens utilisés par les peuples andins.',
    tags: ['immunite', 'vitamine-c', 'acerola', 'shot', 'cure-courte'],
    updatedAt: '2026-05-29',
  },
  {
    slug: 'jus-spiruline-citron-sport',
    category: 'sport',
    nom: 'Jus spiruline-citron pré-effort',
    excerpt: 'La boisson pré-entraînement à la spiruline, riche en fer et protéines.',
    intro:
      "Pour un effort modéré à intense, ce jus apporte de la spiruline (algue bleu-vert) connue pour sa richesse en protéines, fer et phycocyanine. Associée à un fruit pour les glucides et à du citron pour l'assimilation du fer, c'est une boisson pré-effort de 30 à 45 minutes avant l'entraînement.",
    ingredients: [
      { item: 'Spiruline en poudre (de qualité contrôlée, origine traçable)', quantite: '1 cuillère à café (≈ 3 g)' },
      { item: 'Jus de pomme frais (ou banane mixée)', quantite: '150 ml' },
      { item: 'Jus de citron pressé', quantite: '20 ml (≈ 1 citron)' },
      { item: 'Eau de coco (facultatif, pour les électrolytes)', quantite: '80 ml' },
      { item: 'Pincée de sel non raffiné (effort long)', quantite: '1 pincée' },
    ],
    preparation: [
      'Verser le jus de pomme et l\'eau de coco dans un shaker ou un bol.',
      'Ajouter la spiruline progressivement en fouettant pour éviter les grumeaux.',
      'Ajouter le jus de citron qui favorise l\'absorption du fer.',
      'Ajouter une pincée de sel pour les efforts de plus d\'une heure.',
      'Boire 30 à 45 minutes avant l\'effort.',
    ],
    benefices: [
      'Apport en protéines végétales, fer non héminique, phycocyanine',
      'Vitamine C du citron : meilleure absorption du fer',
      'Glucides rapidement disponibles pour l\'effort',
      'Soutien antioxydant post-effort',
    ],
    frequence: '1 verre de 250 ml avant les séances de sport, 3 à 4 fois par semaine.',
    appareil: 'mortier',
    contre_indications: [
      'Phénylcétonurie (spiruline riche en phénylalanine)',
      'Maladies auto-immunes : la spiruline stimule l\'immunité',
      'Hémochromatose : limiter les apports en fer',
      'Sous anticoagulants : prudence avec la vitamine K1 de la spiruline',
      'Choisir une spiruline analysée (microcystines, métaux lourds)',
    ],
    tradition: 'Spiruline consommée par les Aztèques et au Tchad (peuples Kanembou) depuis des siècles.',
    tags: ['sport', 'spiruline', 'fer', 'pre-effort', 'proteines'],
    updatedAt: '2026-05-29',
  },
];
