import type { Plante } from '../types';

export const PLANTES_BATCH2_MIXED: Plante[] = [
  // ============ SOMMEIL (4) ============
  {
    slug: 'verveine-officinale-sommeil',
    category: 'sommeil',
    nom: 'Verveine officinale',
    nomLatin: 'Verbena officinalis L.',
    partieUtilisee: 'Parties aériennes fleuries',
    excerpt: 'Plante calmante traditionnelle, utilisée pour favoriser la détente vespérale et un endormissement plus serein.',
    intro: 'La verveine officinale, à ne pas confondre avec la verveine citronnelle, est employée depuis l\'Antiquité pour ses vertus apaisantes. Elle accompagne les soirées tendues, en infusion légèrement amère, et soutient le passage vers le sommeil chez les personnes nerveuses ou contrariées.',
    proprietes: [
      'Sédative douce et anxiolytique légère',
      'Antispasmodique digestive',
      'Légèrement galactogène (tradition)',
      'Tonique nerveuse en cas de fatigue mentale',
      'Diaphorétique modérée',
    ],
    indications: [
      'Endormissement difficile sur fond de nervosité',
      'Spasmes digestifs liés au stress',
      'Tensions nerveuses du soir',
      'Maux de tête de tension',
      'Convalescence après surmenage',
    ],
    posologie: [
      'Infusion : 1 c. à café (2 g) par tasse, 10 minutes, 1 à 3 tasses/jour',
      'Une tasse 30 à 60 minutes avant le coucher',
      'Extrait fluide : 1 à 2 mL, 2 à 3 fois/jour',
      'Cure de 2 à 3 semaines, à renouveler si besoin',
    ],
    contre_indications: [
      'Grossesse (effet utérotonique à fortes doses)',
      'Allaitement (par prudence, hors usage galactogène encadré)',
      'Allergie connue aux Verbénacées',
    ],
    associations: [
      'Mélisse pour les troubles digestifs nerveux',
      'Tilleul pour les insomnies légères',
      'Aubépine en cas de palpitations émotionnelles',
    ],
    precautions: 'À éviter en cas de traitement anticoagulant ou de pathologie utérine sans avis médical.',
    tradition: 'Plante sacrée des druides et des Romains, la verveine officinale figurait dans les rituels de purification et les remèdes populaires contre l\'anxiété. Les herboristes du XIXe siècle la prescrivaient comme calmante des esprits agités.',
    tags: ['verveine', 'sommeil', 'calmante', 'nervosite', 'infusion', 'tradition'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'coquelicot-sommeil',
    category: 'sommeil',
    nom: 'Coquelicot',
    nomLatin: 'Papaver rhoeas L.',
    partieUtilisee: 'Pétales',
    excerpt: 'Pétales rouges aux propriétés sédatives douces, traditionnellement employés contre l\'insomnie des enfants et des personnes sensibles.',
    intro: 'Le coquelicot, cousin sans morphine du pavot, renferme des alcaloïdes doux comme la rhoeadine. Ses pétales, jadis cueillis dans les champs de blé, parfument les tisanes du soir et accompagnent les toux nerveuses ainsi que les sommeils légers.',
    proprietes: [
      'Sédative légère',
      'Béchique (calmante de la toux sèche)',
      'Émolliente des muqueuses',
      'Légèrement hypnotique',
      'Diaphorétique modérée',
    ],
    indications: [
      'Insomnie légère, notamment chez l\'enfant et la personne âgée',
      'Agitation nerveuse du soir',
      'Toux sèche et irritative',
      'Anxiété passagère',
      'Préparation au sommeil chez les sujets sensibles',
    ],
    posologie: [
      'Infusion : 1 à 2 c. à café (1 à 2 g) de pétales par tasse, 10 minutes',
      '1 tasse 30 minutes avant le coucher',
      'Sirop traditionnel : 1 à 2 c. à café au coucher',
      'Cure de quelques jours à 2 semaines',
    ],
    contre_indications: [
      'Grossesse et allaitement (données insuffisantes)',
      'Enfant de moins de 2 ans',
      'Allergie connue aux Papavéracées',
    ],
    associations: [
      'Tilleul et fleur d\'oranger pour les enfants nerveux',
      'Aubépine pour les sommeils légers de l\'adulte',
      'Mauve pour la toux sèche',
    ],
    precautions: 'À distance de toute prise de sédatifs ou hypnotiques de synthèse, par prudence.',
    tradition: 'Les pétales de coquelicot étaient récoltés dans les blés au début de l\'été et entraient dans les sirops contre la toux et les insomnies enfantines des herboristeries d\'autrefois.',
    tags: ['coquelicot', 'sommeil', 'enfant', 'toux', 'sedatif-doux', 'tradition'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'houblon-sommeil',
    category: 'sommeil',
    nom: 'Houblon',
    nomLatin: 'Humulus lupulus L.',
    partieUtilisee: 'Cônes (strobiles)',
    excerpt: 'Strobiles aromatiques aux propriétés sédatives reconnues, classiquement associés à la valériane pour les insomnies installées.',
    intro: 'Le houblon, célèbre pour son rôle dans la bière, est aussi une plante médicinale majeure du sommeil. Ses cônes femelles, riches en lupuline, exercent une action sédative et apaisent les ruminations nocturnes lorsqu\'ils sont employés seuls ou associés à la valériane.',
    proprietes: [
      'Sédative et hypnotique légère',
      'Anxiolytique douce',
      'Amère et tonique digestive',
      'Œstrogen-like (phyto-œstrogènes)',
      'Antispasmodique',
    ],
    indications: [
      'Insomnies d\'endormissement avec agitation mentale',
      'Réveils nocturnes anxieux',
      'Nervosité et irritabilité',
      'Bouffées de chaleur de la ménopause (en complément)',
      'Dyspepsies nerveuses',
    ],
    posologie: [
      'Infusion : 1 c. à café (1 à 2 g) de cônes par tasse, 10 minutes, le soir',
      'Extrait sec : 200 à 400 mg le soir',
      'Teinture mère : 30 à 50 gouttes au coucher',
      'Cure de 2 à 4 semaines',
    ],
    contre_indications: [
      'Antécédents de cancers hormono-dépendants (sein, utérus, prostate)',
      'Grossesse et allaitement',
      'Dépression sévère (effet sédatif peu adapté)',
      'Enfants',
    ],
    associations: [
      'Valériane : association classique de référence pour le sommeil',
      'Passiflore pour l\'anxiété nocturne',
      'Mélisse pour les troubles digestifs associés',
    ],
    precautions: 'Potentialise les sédatifs (alcool, benzodiazépines, antihistaminiques) : éviter l\'association sans avis médical.',
    tradition: 'Utilisé depuis le Moyen Âge dans les oreillers de houblon pour favoriser le sommeil, le houblon était également prescrit aux brasseurs sujets aux insomnies tenaces.',
    tags: ['houblon', 'sommeil', 'valeriane', 'hypnotique', 'anxiete', 'menopause'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'oranger-fleurs-sommeil',
    category: 'sommeil',
    nom: 'Fleurs d\'oranger',
    nomLatin: 'Citrus aurantium L.',
    partieUtilisee: 'Fleurs (néroli)',
    excerpt: 'Fleurs délicates et parfumées du bigaradier, calmantes traditionnelles des enfants nerveux et des sommeils agités.',
    intro: 'Les fleurs d\'oranger amer, ou néroli, sont employées depuis des siècles en eau distillée et en infusion pour leur effet apaisant. Elles accompagnent les coucher difficiles, les états émotifs et les digestions nerveuses, en particulier chez les enfants et les sujets sensibles.',
    proprietes: [
      'Sédative légère et anxiolytique douce',
      'Antispasmodique digestive',
      'Carminative',
      'Légèrement hypnotique',
      'Aromatique apaisante',
    ],
    indications: [
      'Endormissement difficile, surtout chez l\'enfant',
      'Nervosité émotionnelle, palpitations légères',
      'Spasmes digestifs et coliques nerveuses',
      'Anxiété passagère',
      'Convalescence et états de fatigue émotionnelle',
    ],
    posologie: [
      'Infusion : 1 c. à café (1 à 2 g) de fleurs séchées par tasse, 10 minutes',
      'Eau de fleur d\'oranger : 1 c. à café dans un verre d\'eau ou de lait tiède le soir',
      '1 à 2 tasses en fin de journée',
      'Cure de quelques jours à 3 semaines',
    ],
    contre_indications: [
      'Allergie connue aux Rutacées (agrumes)',
      'Prudence chez le nourrisson de moins de 12 mois',
    ],
    associations: [
      'Tilleul et coquelicot pour les enfants nerveux',
      'Mélisse pour les digestions difficiles du soir',
      'Aubépine en cas de palpitations émotionnelles',
    ],
    precautions: 'Bien distinguer l\'eau de fleur d\'oranger alimentaire (douce) de l\'huile essentielle de néroli (très concentrée, usage encadré).',
    tradition: 'Le néroli, distillé en Provence et en Tunisie depuis le XVIIe siècle, parfumait les gants des aristocrates et calmait, en eau florale, les sommeils des enfants nerveux.',
    tags: ['fleur-oranger', 'neroli', 'sommeil', 'enfant', 'apaisant', 'tradition'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },

  // ============ DIGESTION (4) ============
  {
    slug: 'pissenlit-digestion',
    category: 'digestion',
    nom: 'Pissenlit',
    nomLatin: 'Taraxacum officinale F.H. Wigg.',
    partieUtilisee: 'Racine et feuilles',
    excerpt: 'Amer classique du foie et du rein, stimulant la digestion et le drainage hépato-biliaire.',
    intro: 'Le pissenlit, plante humble des prairies, est l\'un des grands cholagogues de la phytothérapie occidentale. Sa racine soutient la fonction hépato-biliaire tandis que ses feuilles drainent doucement les reins, ce qui en fait un classique des cures de printemps.',
    proprietes: [
      'Cholérétique et cholagogue (racine)',
      'Diurétique douce (feuille)',
      'Apéritive et amère',
      'Légèrement laxative',
      'Dépurative générale',
    ],
    indications: [
      'Digestions lentes, lourdeurs après les repas',
      'Insuffisance biliaire fonctionnelle',
      'Constipation atone modérée',
      'Cures de drainage saisonnières',
      'Œdèmes légers d\'origine alimentaire',
    ],
    posologie: [
      'Décoction de racine : 1 c. à soupe (3 à 5 g) par tasse, bouillir 5 minutes, infuser 10 minutes, 1 à 3 tasses/jour avant les repas',
      'Infusion de feuilles : 2 g par tasse, 10 minutes, 2 à 3 fois/jour',
      'Extrait fluide : 2 à 4 mL, 2 à 3 fois/jour',
      'Cure de 2 à 4 semaines, classiquement au printemps',
    ],
    contre_indications: [
      'Occlusion des voies biliaires, lithiase biliaire symptomatique',
      'Ulcère gastro-duodénal actif',
      'Allergie aux Astéracées',
      'Insuffisance rénale sévère',
    ],
    associations: [
      'Artichaut et romarin pour le drainage hépatique',
      'Bouleau pour le drainage rénal',
      'Chardon-Marie pour la protection hépatocytaire',
    ],
    precautions: 'Prudence en cas de traitement diurétique ou antihypertenseur (effet additif).',
    tradition: 'Surnommé "dent-de-lion", le pissenlit était la plante de la cure de printemps des campagnes : feuilles en salade, racines torréfiées en succédané de café et amer du foie.',
    tags: ['pissenlit', 'digestion', 'foie', 'drainage', 'amer', 'depuratif'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'boldo-digestion',
    category: 'digestion',
    nom: 'Boldo',
    nomLatin: 'Peumus boldus Molina',
    partieUtilisee: 'Feuilles',
    excerpt: 'Feuilles aromatiques d\'Amérique du Sud, cholagogue puissant pour les digestions difficiles avec inconfort biliaire.',
    intro: 'Le boldo, originaire du Chili, est utilisé depuis longtemps par les Mapuche et a été intégré à la pharmacopée européenne au XIXe siècle. Ses feuilles, riches en boldine, soutiennent la sécrétion et l\'évacuation biliaire en cas de digestion lente et de sensation de foie engorgé.',
    proprietes: [
      'Cholérétique et cholagogue marquée',
      'Hépatoprotectrice (préliminaire)',
      'Stimulante de la digestion',
      'Antispasmodique légère',
      'Légèrement diurétique',
    ],
    indications: [
      'Dyspepsies avec inconfort hépato-biliaire',
      'Digestions lentes, ballonnements postprandiaux',
      'Aide aux cures de drainage hépatique',
      'Lithiase biliaire non compliquée (sous avis médical)',
      'Migraines digestives',
    ],
    posologie: [
      'Infusion : 1 c. à café (1 à 2 g) de feuilles par tasse, 10 minutes, 1 tasse après chaque repas principal',
      'Extrait sec : 100 à 200 mg, 2 à 3 fois/jour',
      'Teinture mère : 20 à 30 gouttes avant les repas',
      'Cure courte de 2 à 3 semaines maximum',
    ],
    contre_indications: [
      'Obstruction des voies biliaires',
      'Insuffisance hépatique sévère',
      'Grossesse et allaitement',
      'Enfants de moins de 12 ans',
      'Traitement anticoagulant (potentialisation possible)',
    ],
    associations: [
      'Artichaut pour le foie',
      'Pissenlit pour le drainage',
      'Romarin pour les digestions paresseuses',
    ],
    precautions: 'L\'huile essentielle de boldo est neurotoxique et abortive : ne jamais l\'utiliser. Seules les feuilles en tisane ou extraits standardisés sont recommandées, en cures courtes.',
    tradition: 'Découvert par les médecins européens au XIXe siècle après que des moutons malades du foie eurent recouvré la santé en broutant les feuilles de boldo au Chili.',
    tags: ['boldo', 'digestion', 'foie', 'bile', 'cholagogue', 'dyspepsie'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'radis-noir-digestion',
    category: 'digestion',
    nom: 'Radis noir',
    nomLatin: 'Raphanus sativus L. var. niger',
    partieUtilisee: 'Racine fraîche',
    excerpt: 'Racine soufrée stimulante du foie et de la vésicule, classique des cures de détoxification hépatique.',
    intro: 'Le radis noir, riche en composés soufrés (glucosinolates), est l\'un des grands drainants hépatiques de la phytothérapie. Sa racine, consommée fraîche ou en jus, stimule la production et l\'évacuation de la bile et accompagne les digestions lourdes et les cures saisonnières.',
    proprietes: [
      'Cholérétique et cholagogue',
      'Hépatoprotectrice (préliminaire)',
      'Mucolytique respiratoire',
      'Antioxydante (composés soufrés)',
      'Stimulante de la digestion des graisses',
    ],
    indications: [
      'Digestions lentes après repas gras',
      'Engorgement hépato-biliaire fonctionnel',
      'Cures de drainage du foie',
      'Lithiase biliaire non symptomatique (sous avis)',
      'Toux grasse en complément',
    ],
    posologie: [
      'Jus frais : 50 à 100 mL/jour, dilué dans de l\'eau, en plusieurs prises',
      'Ampoules ou extrait : 1 à 3 ampoules/jour selon présentation',
      'Cure de 10 à 21 jours, 2 à 3 fois par an',
      'À prendre de préférence avant les repas',
    ],
    contre_indications: [
      'Obstruction des voies biliaires, calculs symptomatiques',
      'Ulcère gastro-duodénal, gastrite',
      'Hypothyroïdie (par prudence, en cas de fortes doses)',
      'Grossesse et allaitement (par précaution)',
    ],
    associations: [
      'Artichaut et chardon-Marie pour le foie',
      'Pissenlit pour un drainage global',
      'Romarin pour stimuler la digestion',
    ],
    precautions: 'Peut provoquer des brûlures gastriques chez les sujets sensibles : commencer par de petites doses, éloignées des repas.',
    tradition: 'Aliment-médicament traditionnel des cures de printemps et d\'automne en Europe, le radis noir était également utilisé contre la toux et les coliques hépatiques.',
    tags: ['radis-noir', 'digestion', 'foie', 'detox', 'bile', 'cure'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'angelique-digestion',
    category: 'digestion',
    nom: 'Angélique',
    nomLatin: 'Angelica archangelica L.',
    partieUtilisee: 'Racine',
    excerpt: 'Racine aromatique tonique et carminative, employée contre les ballonnements et les digestions nerveuses.',
    intro: 'L\'angélique officinale, surnommée "herbe des anges", est une ombellifère robuste cultivée depuis le Moyen Âge. Sa racine, à l\'odeur musquée, est un tonique digestif majeur qui apaise les ballonnements, les spasmes et les digestions difficiles d\'origine nerveuse.',
    proprietes: [
      'Carminative et eupeptique',
      'Antispasmodique digestive',
      'Tonique générale et amère',
      'Diaphorétique légère',
      'Expectorante modérée',
    ],
    indications: [
      'Ballonnements, flatulences, aérophagie',
      'Digestions lentes et nerveuses',
      'Spasmes intestinaux d\'origine émotionnelle',
      'Manque d\'appétit en convalescence',
      'Sensation de lourdeur postprandiale',
    ],
    posologie: [
      'Infusion : 1 c. à café (1 à 2 g) de racine par tasse, 10 minutes, avant ou après les repas',
      'Teinture mère : 20 à 30 gouttes, 3 fois/jour',
      'Extrait sec : 100 à 200 mg avant les repas',
      'Cure de 2 à 4 semaines',
    ],
    contre_indications: [
      'Grossesse (effet emménagogue traditionnel)',
      'Ulcère gastro-duodénal actif',
      'Traitement anticoagulant (furocoumarines)',
      'Exposition solaire intense (photosensibilisation)',
    ],
    associations: [
      'Mélisse et fenouil pour l\'aérophagie',
      'Camomille pour les spasmes',
      'Romarin pour les digestions lentes',
    ],
    precautions: 'Les furocoumarines peuvent être photosensibilisantes : éviter le soleil intense pendant la cure. À distinguer de l\'angélique chinoise (Dong quai).',
    tradition: 'Selon la légende, un ange aurait révélé à un moine ses vertus pendant la peste de 1665 ; depuis, l\'angélique parfume liqueurs digestives (Chartreuse, Bénédictine) et tisanes de l\'après-repas.',
    tags: ['angelique', 'digestion', 'ballonnements', 'carminatif', 'amer', 'tradition'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },

  // ============ STRESS-ANXIETE (4) ============
  {
    slug: 'griffonia-stress',
    category: 'stress-anxiete',
    nom: 'Griffonia simplicifolia',
    nomLatin: 'Griffonia simplicifolia (DC.) Baill.',
    partieUtilisee: 'Graines',
    excerpt: 'Légumineuse africaine riche en 5-HTP, précurseur direct de la sérotonine, utilisée pour le moral et l\'équilibre émotionnel.',
    intro: 'Le griffonia, plante grimpante d\'Afrique de l\'Ouest, fournit dans ses graines un précurseur naturel de la sérotonine, le 5-hydroxytryptophane (5-HTP). Cet apport peut soutenir l\'humeur, le sommeil et l\'équilibre émotionnel dans les contextes de stress chronique et de baisse de moral léger à modéré.',
    proprietes: [
      'Précurseur sérotoninergique (5-HTP)',
      'Anxiolytique préliminaire',
      'Soutien de l\'humeur',
      'Aide à la régulation du sommeil paradoxal',
      'Modulateur de l\'appétit (compulsions sucrées)',
    ],
    indications: [
      'Baisse de moral légère à modérée',
      'Stress chronique avec irritabilité',
      'Troubles légers du sommeil liés à l\'humeur',
      'Compulsions alimentaires sucrées de fin de journée',
      'Syndrome prémenstruel (terrain émotionnel)',
    ],
    posologie: [
      'Extrait standardisé à 20-30% de 5-HTP : 50 à 100 mg de 5-HTP, 1 à 2 fois/jour',
      'Prise de préférence en fin d\'après-midi et/ou au coucher',
      'Commencer par la dose la plus faible et augmenter progressivement',
      'Cure de 4 à 8 semaines, à réévaluer',
    ],
    contre_indications: [
      'Traitement par ISRS, IRSNA, IMAO, tramadol, triptans (risque de syndrome sérotoninergique)',
      'Trisomie 21 (sensibilité particulière)',
      'Grossesse et allaitement',
      'Enfants',
      'Sclérodermie',
    ],
    associations: [
      'Magnésium et vitamine B6 (cofacteurs)',
      'Safran pour potentialiser l\'effet sur l\'humeur (sous avis)',
      'Rhodiole pour la fatigue émotionnelle',
    ],
    precautions: 'Interaction majeure avec tout traitement sérotoninergique : avis médical impératif avant utilisation. Ne pas associer à d\'autres précurseurs de sérotonine.',
    tradition: 'Utilisé traditionnellement en Afrique de l\'Ouest comme tonique et aphrodisiaque, le griffonia a été introduit en phytothérapie occidentale dans les années 1990 après la mise en évidence de sa richesse en 5-HTP.',
    tags: ['griffonia', '5-htp', 'serotonine', 'humeur', 'stress', 'anxiete'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'safran-stress',
    category: 'stress-anxiete',
    nom: 'Safran',
    nomLatin: 'Crocus sativus L.',
    partieUtilisee: 'Stigmates',
    excerpt: 'Stigmates rouges aux effets démontrés sur l\'humeur et l\'anxiété, comparables à certains antidépresseurs légers dans plusieurs essais cliniques.',
    intro: 'Le safran, épice la plus précieuse du monde, possède des propriétés psychotropes documentées par de nombreuses études cliniques. Standardisé à environ 28 à 30 mg/jour, il soutient l\'humeur dans les épisodes dépressifs légers à modérés et apaise l\'anxiété, avec un profil de tolérance favorable.',
    proprietes: [
      'Antidépresseur léger à modéré (efficacité démontrée)',
      'Anxiolytique',
      'Antioxydant (crocines, safranal)',
      'Neuroprotecteur (préliminaire)',
      'Soutien cognitif léger',
    ],
    indications: [
      'États dépressifs légers à modérés',
      'Anxiété chronique',
      'Syndrome prémenstruel',
      'Troubles de l\'humeur saisonniers',
      'Soutien cognitif léger chez la personne âgée',
    ],
    posologie: [
      'Extrait standardisé (safranal/crocines) : 28 à 30 mg/jour, en 1 à 2 prises',
      'Stigmates en infusion : 10 à 15 mg/jour (effet plus léger)',
      'Cure de 6 à 8 semaines pour une évaluation complète',
      'À prendre au cours d\'un repas',
    ],
    contre_indications: [
      'Grossesse (effet utérotonique aux fortes doses)',
      'Allaitement',
      'Trouble bipolaire (risque de virage maniaque)',
      'Traitement antidépresseur sans avis médical',
      'Hypotension marquée',
    ],
    associations: [
      'Rhodiole pour la fatigue émotionnelle associée',
      'Magnésium pour le stress chronique',
      'Vitamines B pour le terrain neuropsychique',
    ],
    precautions: 'Toujours utiliser des extraits standardisés et tracés (risque élevé de fraude sur le safran brut). Avis médical recommandé en cas de traitement antidépresseur en cours.',
    tradition: 'Cultivé depuis plus de 3 000 ans, le safran était déjà cité par les médecins gréco-arabes comme "épice du bonheur" et utilisé contre la mélancolie en Perse et dans la médecine ayurvédique.',
    tags: ['safran', 'humeur', 'depression-legere', 'anxiete', 'crocines', 'evidence'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'magnolia-stress',
    category: 'stress-anxiete',
    nom: 'Magnolia officinalis',
    nomLatin: 'Magnolia officinalis Rehder & E.H. Wilson',
    partieUtilisee: 'Écorce',
    excerpt: 'Écorce traditionnelle de la médecine chinoise, riche en honokiol et magnolol, aux effets anxiolytiques et apaisants.',
    intro: 'Le magnolia officinal, ou Hou Po dans la médecine traditionnelle chinoise, fournit une écorce dont les composés principaux (honokiol, magnolol) exercent des effets anxiolytiques, sédatifs légers et antioxydants. Il est employé pour les états de tension chronique et les troubles du sommeil liés au stress.',
    proprietes: [
      'Anxiolytique (modulation GABA)',
      'Sédative douce',
      'Anti-inflammatoire (préliminaire)',
      'Antioxydante',
      'Modulatrice du cortisol (préliminaire)',
    ],
    indications: [
      'Anxiété chronique modérée',
      'Stress avec ruminations mentales',
      'Difficultés d\'endormissement liées au stress',
      'Irritabilité et tension nerveuse',
      'Soutien en période de surcharge émotionnelle',
    ],
    posologie: [
      'Extrait standardisé (honokiol/magnolol) : 200 à 400 mg/jour, en 1 à 2 prises',
      'Prise de préférence en fin d\'après-midi ou au coucher',
      'Cure de 4 à 8 semaines',
      'Réévaluation après 8 semaines',
    ],
    contre_indications: [
      'Grossesse et allaitement',
      'Enfants',
      'Traitement sédatif (benzodiazépines, hypnotiques) sans avis médical',
      'Insuffisance hépatique sévère',
      'Hypotension marquée',
    ],
    associations: [
      'L-théanine pour la détente diurne',
      'Ashwagandha pour le stress chronique',
      'Mélisse pour les troubles digestifs nerveux',
    ],
    precautions: 'Potentialise l\'effet des sédatifs et de l\'alcool : éviter ces associations. Préférer des extraits standardisés et tracés.',
    tradition: 'Utilisé depuis plus de 2 000 ans dans la médecine chinoise pour "réguler le Qi" et apaiser les états de tension émotionnelle, le magnolia officinal entre dans de nombreuses formules classiques anti-stress.',
    tags: ['magnolia', 'honokiol', 'magnolol', 'stress', 'anxiete', 'mtc'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'pavot-de-californie-stress',
    category: 'stress-anxiete',
    nom: 'Pavot de Californie (Eschscholtzia)',
    nomLatin: 'Eschscholzia californica Cham.',
    partieUtilisee: 'Parties aériennes fleuries',
    excerpt: 'Pavot orange non opiacé aux propriétés sédatives et anxiolytiques douces, allié des sommeils agités et des anxiétés diurnes.',
    intro: 'L\'eschscholtzia, ou pavot de Californie, est une papavéracée sans morphine dont les parties aériennes renferment des alcaloïdes (californidine, eschscholtzine) à action sédative et anxiolytique. Plante familière des herboristeries, il accompagne les anxiétés du jour, les difficultés d\'endormissement et les réveils nocturnes.',
    proprietes: [
      'Anxiolytique douce (affinité GABA et benzodiazépines)',
      'Sédative et hypnotique légère',
      'Antispasmodique',
      'Légèrement analgésique',
      'Non opiacée (sans dépendance)',
    ],
    indications: [
      'Anxiété diurne, états émotifs',
      'Endormissement difficile, sommeil agité',
      'Réveils nocturnes anxieux',
      'Sommeil de l\'enfant nerveux (sous avis)',
      'Tensions psycho-corporelles',
    ],
    posologie: [
      'Infusion : 1 à 2 c. à café (2 g) par tasse, 10 minutes, 1 à 3 tasses/jour',
      'Teinture mère : 30 à 50 gouttes, 2 à 3 fois/jour',
      'Extrait sec : 200 à 400 mg, 1 à 2 fois/jour',
      'Cure de 2 à 4 semaines',
    ],
    contre_indications: [
      'Grossesse et allaitement',
      'Glaucome à angle fermé',
      'Traitement par IMAO',
      'Hypersensibilité aux Papavéracées',
      'Enfant de moins de 6 ans sans avis',
    ],
    associations: [
      'Aubépine pour les anxiétés avec palpitations',
      'Valériane pour les insomnies installées',
      'Passiflore pour les ruminations',
    ],
    precautions: 'Peut potentialiser les sédatifs et l\'alcool. Effet de somnolence diurne possible aux fortes doses : adapter les activités à risque (conduite).',
    tradition: 'Fleur emblème de la Californie, l\'eschscholtzia était utilisé par les Amérindiens contre les douleurs et les insomnies, avant d\'être introduit en phytothérapie européenne au XXe siècle.',
    tags: ['eschscholtzia', 'pavot-californie', 'sommeil', 'anxiete', 'sedatif-doux', 'gaba'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
];
