import type { Plante } from '../types';

export const PLANTES_BATCH2_SYSTEME: Plante[] = [
  /* ───────────────────────────────────────
     IMMUNITÉ / INFECTIONS
  ─────────────────────────────────────── */
  {
    slug: 'pelargonium-immunite',
    category: 'immunite-infections',
    nom: 'Pélargonium',
    nomLatin: 'Pelargonium sidoides DC.',
    partieUtilisee: 'Racines',
    excerpt: "Le « géranium d'Afrique du Sud », étudié dans les bronchites aiguës.",
    intro: "Originaire d'Afrique australe, le pélargonium (parfois nommé Umckaloabo) est traditionnellement employé par les Zoulous contre les affections respiratoires. L'extrait standardisé de ses racines (EPs 7630) fait l'objet de plusieurs essais cliniques contre la bronchite aiguë et les rhinopharyngites.",
    proprietes: ["Antibactérienne d'après des données précliniques", "Antivirale (interférence avec l'attachement viral)", "Expectorante et mucolytique douce", "Immunomodulante (stimulerait la phagocytose)", "Anti-adhésive sur les muqueuses"],
    indications: ["Bronchite aiguë non compliquée chez l'adulte", "Rhinopharyngite et sinusite bénigne", "Toux grasse en début d'épisode infectieux", "Soutien lors d'angine bénigne"],
    posologie: ["Extrait standardisé EPs 7630 : 30 gouttes, 3 fois par jour chez l'adulte", "Comprimés à 20 mg : 1 comprimé, 3 fois par jour", "Sirop pédiatrique : selon le poids et l'âge, sur conseil professionnel", "Cure courte de 7 à 10 jours, à arrêter dès la résolution des symptômes"],
    contre_indications: ["Insuffisance hépatique ou rénale sévère", "Traitements anticoagulants (interaction théorique)", "Allergie aux Géraniacées", "Grossesse et allaitement par mesure de précaution", "Enfants de moins de 1 an"],
    associations: ["Échinacée", "Thym", "Sureau noir"],
    precautions: "De rares cas d'hépatotoxicité ont été signalés : suspendre immédiatement en cas d'ictère, d'urines foncées ou de fatigue inhabituelle. Ne pas dépasser 3 semaines de cure sans avis médical.",
    tradition: "Utilisé depuis des siècles par les peuples Zoulous, Basuto et Xhosa pour les troubles respiratoires et la tuberculose. Introduit en Europe au début du XXe siècle par un Anglais qui en aurait été soigné en Afrique du Sud.",
    tags: ['bronchite', 'respiratoire', 'EPs 7630', 'racine'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'sureau-noir-immunite-batch2',
    category: 'immunite-infections',
    nom: 'Sureau noir baies',
    nomLatin: 'Sambucus nigra L.',
    partieUtilisee: 'Baies mûres (toujours cuites)',
    excerpt: "Les baies pourpres traditionnellement utilisées au début des syndromes grippaux.",
    intro: "Les baies de sureau noir, riches en anthocyanes et flavonoïdes, sont employées de longue date en médecine populaire européenne contre la grippe. Plusieurs essais cliniques de faible puissance suggèrent qu'un extrait standardisé (Sambucol®) pourrait raccourcir la durée des symptômes grippaux lorsqu'il est pris dans les 48 premières heures.",
    proprietes: ["Antivirale traditionnellement reconnue (notamment Influenza A et B in vitro)", "Antioxydante puissante (anthocyanes)", "Immunomodulante d'après des données préliminaires", "Diaphorétique douce", "Anti-inflammatoire"],
    indications: ["Début de syndrome grippal (dans les 48 premières heures)", "États fébriles modérés", "Refroidissements hivernaux", "Convalescence après infection virale"],
    posologie: ["Sirop de baies cuites : 15 mL, 4 fois par jour pendant 3 à 5 jours en phase aiguë", "Extrait standardisé : 175 mg, 4 fois par jour pendant 2 jours puis 2 fois par jour", "Décoction : 3 à 5 g de baies séchées pour 250 mL, 2 à 3 fois par jour", "Cure courte limitée à la durée de l'épisode infectieux"],
    contre_indications: ["Allergie aux Adoxacées", "Grossesse et allaitement par mesure de précaution", "Maladies auto-immunes (en raison de l'effet immunomodulant)", "Traitements immunosuppresseurs"],
    associations: ["Échinacée", "Propolis", "Thym"],
    precautions: "Ne jamais consommer les baies crues, les graines vertes, les feuilles ou l'écorce : ils contiennent des glycosides cyanogènes (sambunigrine) potentiellement toxiques. Seule la cuisson rend les baies sûres à la consommation.",
    tradition: "Surnommé « la pharmacie du paysan » en Europe rurale, le sureau est un arbre sacré dans les traditions celtiques. Hippocrate le qualifiait de « coffre à médicaments ». Les baies cuites étaient préparées en rob ou en vin médicinal pour traverser l'hiver.",
    tags: ['grippe', 'baies', 'hiver', 'antiviral'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'astragale-immunite-batch2',
    category: 'immunite-infections',
    nom: 'Astragale',
    nomLatin: 'Astragalus membranaceus (Fisch.) Bunge',
    partieUtilisee: 'Racines (huang qi)',
    excerpt: "Pilier de la pharmacopée chinoise pour soutenir le « Qi défensif ».",
    intro: "L'astragale (huang qi en chinois) figure parmi les plantes les plus prescrites de la médecine traditionnelle chinoise pour tonifier l'énergie défensive (Wei Qi). Ses racines contiennent des polysaccharides et des saponines (astragalosides) étudiés pour leurs effets immunomodulants en cures de fond.",
    proprietes: ["Immunomodulante (stimulerait macrophages et lymphocytes T)", "Adaptogène d'après la tradition chinoise", "Tonique général et de la rate selon la MTC", "Antioxydante", "Cardioprotectrice selon des données précliniques"],
    indications: ["Soutien immunitaire de fond chez les sujets fragiles ou en convalescence", "Fatigue chronique avec infections à répétition", "Prévention des refroidissements en saison froide", "Accompagnement de la convalescence après maladie longue"],
    posologie: ["Décoction de racines : 9 à 30 g par jour selon la tradition chinoise", "Extrait sec standardisé : 250 à 500 mg, 2 à 3 fois par jour", "Teinture : 30 à 50 gouttes, 2 à 3 fois par jour", "Cures longues (2 à 3 mois), avec fenêtres thérapeutiques"],
    contre_indications: ["Greffe d'organe et transplantation (immunosuppression nécessaire)", "Maladies auto-immunes (lupus, sclérose en plaques, polyarthrite)", "Traitements immunosuppresseurs", "Phase aiguë d'infection fébrile (à débuter après la phase aiguë selon la MTC)", "Grossesse et allaitement par mesure de précaution"],
    associations: ["Ginseng", "Reishi", "Échinacée (en alternance, pas simultanément)"],
    precautions: "À éviter chez les personnes transplantées ou sous immunosuppresseurs : interaction potentielle avec le cyclophosphamide et la ciclosporine. En MTC, on évite l'astragale en cas de « chaleur excessive » ou de fièvre aiguë.",
    tradition: "Inscrit au Shen Nong Ben Cao Jing (Ier siècle), l'astragale est classé parmi les plantes « supérieures » de la pharmacopée chinoise. Il entre dans la célèbre formule Yu Ping Feng San (« poudre du paravent de jade ») destinée à renforcer les défenses.",
    tags: ['immunité', 'adaptogène', 'MTC', 'huang qi'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },

  /* ───────────────────────────────────────
     CIRCULATION
  ─────────────────────────────────────── */
  {
    slug: 'olivier-circulation',
    category: 'circulation',
    nom: 'Olivier feuilles',
    nomLatin: 'Olea europaea L.',
    partieUtilisee: 'Feuilles',
    excerpt: "La feuille d'olivier, étudiée pour son intérêt sur la tension artérielle modérée.",
    intro: "Au-delà du fruit et de son huile, la feuille d'olivier est utilisée depuis l'Antiquité méditerranéenne. Riche en oleuropéine, elle est étudiée pour ses effets sur l'hypertension artérielle légère à modérée et sur le profil lipidique, avec quelques essais cliniques de qualité variable.",
    proprietes: ["Hypotensive douce d'après plusieurs essais cliniques", "Vasodilatatrice", "Antioxydante marquée (oleuropéine, hydroxytyrosol)", "Hypoglycémiante discrète", "Hypolipémiante d'après des données préliminaires"],
    indications: ["Hypertension artérielle légère à modérée en accompagnement", "Soutien du profil lipidique", "Prévention cardiovasculaire chez les sujets à risque", "Accompagnement du syndrome métabolique"],
    posologie: ["Extrait sec standardisé (16 à 20 % d'oleuropéine) : 500 à 1 000 mg par jour", "Infusion : 7 à 8 g de feuilles séchées pour 500 mL, à boire dans la journée", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour", "Cures de 1 à 3 mois, à renouveler selon les besoins"],
    contre_indications: ["Hypotension artérielle", "Traitements antihypertenseurs (risque d'effet additif, surveillance nécessaire)", "Insuffisance rénale sévère", "Grossesse et allaitement par mesure de précaution"],
    associations: ["Aubépine", "Ail", "Hibiscus (bissap)"],
    precautions: "Ne se substitue jamais à un traitement antihypertenseur prescrit : surveiller la tension régulièrement et informer son médecin en cas d'usage prolongé. Effet hypoglycémiant possible chez les diabétiques traités.",
    tradition: "L'olivier est sacré dans toutes les civilisations méditerranéennes (Grèce, Rome, monde sémitique). Hippocrate vantait déjà ses feuilles pour les fièvres et les ulcères. La tradition provençale en faisait une décoction contre la « tension nerveuse ».",
    tags: ['hypertension', 'cardiovasculaire', 'méditerranéen', 'oleuropéine'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'fragon-petit-houx-circulation',
    category: 'circulation',
    nom: 'Petit houx (fragon)',
    nomLatin: 'Ruscus aculeatus L.',
    partieUtilisee: 'Rhizome',
    excerpt: "Le fragon, plante veinotonique de référence pour les jambes lourdes.",
    intro: "Le fragon, aussi appelé petit houx ou houx-frelon, est une petite plante méditerranéenne dont le rhizome contient des saponosides stéroïdiens (ruscogénines). Son intérêt dans l'insuffisance veineuse chronique a été évalué par plusieurs essais et il figure dans plusieurs pharmacopées européennes.",
    proprietes: ["Veinotonique (action vasoconstrictrice sur les veines)", "Lymphotonique", "Anti-œdémateuse", "Anti-inflammatoire", "Protectrice de la paroi capillaire"],
    indications: ["Insuffisance veineuse chronique : jambes lourdes, gonflements, varices débutantes", "Hémorroïdes en complément", "Œdèmes des membres inférieurs liés à la chaleur ou à la station debout prolongée", "Drainage en accompagnement"],
    posologie: ["Extrait standardisé : 75 à 150 mg de ruscogénines par jour", "Gélules de poudre de rhizome : 300 à 500 mg, 2 à 3 fois par jour", "Décoction : 2 g de rhizome pour 150 mL, 2 à 3 fois par jour", "Cures de 4 à 8 semaines, à renouveler en cas de besoin"],
    contre_indications: ["Hypertension non contrôlée (effet vasoconstricteur)", "Grossesse et allaitement par mesure de précaution", "Allergie aux Asparagacées"],
    associations: ["Vigne rouge", "Marronnier d'Inde", "Mélilot"],
    precautions: "L'effet vasoconstricteur impose la prudence chez les hypertendus. Rares troubles digestifs possibles. Toujours associer aux mesures hygiéniques (marche, douche fraîche, surélévation des jambes).",
    tradition: "Connu de Dioscoride et de Pline l'Ancien, le fragon était utilisé pour les « rétentions d'urine » et les « jambes enflées ». La tradition rurale française en faisait des décoctions automnales pour soulager les jambes des vendangeurs.",
    tags: ['jambes lourdes', 'veinotonique', 'circulation', 'ruscogénines'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'mélilot-circulation',
    category: 'circulation',
    nom: 'Mélilot',
    nomLatin: 'Melilotus officinalis (L.) Pall.',
    partieUtilisee: 'Sommités fleuries',
    excerpt: "Le mélilot, plante au parfum de foin coupé, traditionnel du drainage lymphatique.",
    intro: "Le mélilot, petite légumineuse mellifère, contient de la coumarine responsable de son odeur caractéristique de foin séché. Il est traditionnellement employé dans l'insuffisance veino-lymphatique et figure dans la Pharmacopée européenne pour son intérêt sur les œdèmes lymphatiques.",
    proprietes: ["Veinotonique et lymphotonique", "Anti-œdémateuse", "Anti-inflammatoire douce", "Légèrement antispasmodique", "Cicatrisante en usage externe"],
    indications: ["Œdèmes lymphatiques (lymphœdèmes post-chirurgicaux en complément)", "Jambes lourdes avec composante lymphatique", "Sensations de gonflement, rétention modérée", "Contusions et hématomes en usage externe"],
    posologie: ["Infusion : 1 à 2 g de sommités séchées pour 150 mL, 2 à 3 fois par jour", "Extrait sec standardisé : selon les spécialités, en respectant 3 à 30 mg de coumarine par jour", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour", "Cures de 4 à 6 semaines"],
    contre_indications: ["Traitements anticoagulants (AVK type warfarine, AOD) : risque hémorragique majoré", "Antiagrégants plaquettaires (aspirine, clopidogrel)", "Troubles de la coagulation, hémophilie", "Insuffisance hépatique", "Période péri-opératoire (à arrêter 15 jours avant une intervention)", "Grossesse et allaitement"],
    associations: ["Fragon (petit houx)", "Vigne rouge", "Cassis (feuilles)"],
    precautions: "La coumarine présente dans le mélilot peut potentialiser les anticoagulants : interaction cliniquement documentée. À l'inverse, le mélilot mal séché peut produire du dicoumarol (toxique hépatique et hémorragique) : utiliser des plantes séchées correctement et issues de filières contrôlées.",
    tradition: "Très employé dans la médecine populaire d'Europe centrale pour les œdèmes et les contusions, le mélilot entrait dans la composition des « cataplasmes résolutifs » des herboristes du XIXe siècle. Son nom évoque le miel (« meli ») que les abeilles en tirent.",
    tags: ['lymphatique', 'œdème', 'drainage', 'coumarine'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },

  /* ───────────────────────────────────────
     RESPIRATION
  ─────────────────────────────────────── */
  {
    slug: 'lierre-grimpant-respiration',
    category: 'respiration',
    nom: 'Lierre grimpant',
    nomLatin: 'Hedera helix L.',
    partieUtilisee: 'Feuilles',
    excerpt: "Le lierre grimpant, étudié dans les toux grasses, notamment chez l'enfant.",
    intro: "L'extrait de feuilles de lierre grimpant figure parmi les rares phytothérapies de la toux grasse à disposer de données cliniques significatives, y compris en pédiatrie. Riche en saponines (hédéracosides), il fluidifie les sécrétions bronchiques et facilite l'expectoration.",
    proprietes: ["Expectorante (action sécrétolytique sur le mucus bronchique)", "Bronchodilatatrice douce (β2-agoniste indirect d'après les études)", "Antispasmodique des voies respiratoires", "Antitussive sur la toux grasse"],
    indications: ["Toux grasse productive de l'adulte et de l'enfant", "Bronchite aiguë non compliquée", "Bronchite chronique en accompagnement", "Encombrement bronchique des affections virales hivernales"],
    posologie: ["Sirop standardisé : selon les spécialités (souvent 5 à 7,5 mL, 2 à 3 fois par jour chez l'adulte)", "Posologie pédiatrique adaptée au poids et à l'âge, selon les spécialités", "Cure courte de 7 à 14 jours, à arrêter dès la résolution des symptômes"],
    contre_indications: ["Allergie aux Araliacées", "Toxicité de la plante fraîche : ne jamais utiliser hors préparations standardisées", "Grossesse et allaitement par précaution", "Enfants de moins de 1 an"],
    associations: ["Thym", "Plantain", "Pin sylvestre"],
    precautions: "Les feuilles et baies de lierre frais sont toxiques (saponines irritantes) : seuls les extraits standardisés préparés industriellement sont sûrs. Possibles troubles digestifs (nausées). Toux persistante au-delà de 7 jours : consultation médicale.",
    tradition: "Utilisé depuis Hippocrate pour la « pituite » (mucosités), le lierre est un symbole de fidélité dans l'Antiquité. La tradition populaire l'employait en cataplasmes contre les douleurs articulaires, usage à éviter aujourd'hui en raison de son potentiel irritant.",
    tags: ['toux grasse', 'bronchite', 'expectorant', 'enfant'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'erysimum-respiration',
    category: 'respiration',
    nom: 'Érysimum',
    nomLatin: 'Sisymbrium officinale (L.) Scop.',
    partieUtilisee: 'Parties aériennes fleuries',
    excerpt: "L'« herbe aux chantres », alliée traditionnelle des extinctions de voix.",
    intro: "L'érysimum, surnommé « herbe aux chantres » ou « velar », est traditionnellement employé pour soulager l'enrouement et les extinctions de voix. Cette petite Brassicacée commune des bords de chemins faisait partie de la pharmacopée des artistes lyriques.",
    proprietes: ["Adoucissante des cordes vocales et de la muqueuse pharyngée", "Anti-inflammatoire locale légère", "Expectorante douce", "Mucolytique discrète"],
    indications: ["Extinction de voix (aphonie), enrouement", "Laryngite aiguë bénigne", "Fatigue vocale des professionnels de la voix (chanteurs, enseignants, conférenciers)", "Toux d'irritation laryngée"],
    posologie: ["Sirop d'érysimum : 1 cuillère à soupe, 3 à 5 fois par jour", "Infusion : 3 à 5 g de plante séchée pour 250 mL, 3 fois par jour", "Teinture-mère : 30 à 50 gouttes, 3 fois par jour", "Cure courte (5 à 10 jours), le temps de la résolution"],
    contre_indications: ["Hypothyroïdie (Brassicacée contenant des composés goitrogènes en théorie)", "Allergie aux Brassicacées (chou, moutarde)", "Grossesse et allaitement par mesure de précaution", "Enfants de moins de 6 ans"],
    associations: ["Guimauve", "Plantain", "Bourgeons de cassis"],
    precautions: "Mesure de précaution chez les patients thyroïdiens (théorique). Une extinction de voix persistant au-delà de 15 jours impose une consultation ORL.",
    tradition: "Connu sous le nom d'« herbe aux chantres » depuis la Renaissance, l'érysimum était la plante des chanteurs d'opéra et des prédicateurs. La tradition rapporte qu'un ténor du XVIIIe siècle aurait été sauvé d'une aphonie par une décoction administrée juste avant son entrée en scène.",
    tags: ['voix', 'laryngite', 'enrouement', 'chantres'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'pin-sylvestre-respiration',
    category: 'respiration',
    nom: 'Pin sylvestre',
    nomLatin: 'Pinus sylvestris L.',
    partieUtilisee: 'Bourgeons, aiguilles et huile essentielle',
    excerpt: "Le grand pin nordique, balsamique et expectorant pour les bronches encombrées.",
    intro: "Le pin sylvestre, conifère emblématique des forêts d'Europe du Nord, fournit bourgeons, aiguilles et huile essentielle traditionnellement employés en phytothérapie respiratoire. Sa résine balsamique a inspiré nombre de sirops et inhalations contre les affections bronchiques.",
    proprietes: ["Expectorante et balsamique (action sur les sécrétions bronchiques)", "Antiseptique des voies respiratoires", "Décongestionnante en inhalation", "Stimulante générale et surrénalienne d'après la tradition gemmothérapique (bourgeons)", "Rubéfiante en application externe"],
    indications: ["Bronchites aiguës et chroniques en accompagnement", "Toux grasse avec encombrement", "Rhinites et sinusites bénignes (inhalations)", "Fatigue chronique avec terrain respiratoire fragile (bourgeons en gemmothérapie)"],
    posologie: ["Bourgeons (gemmothérapie, macérat-mère) : 5 à 15 gouttes, 1 à 2 fois par jour, cures de 3 semaines", "Infusion d'aiguilles : 2 à 3 g pour 150 mL, 2 à 3 fois par jour", "Inhalation : 3 à 5 gouttes d'huile essentielle dans un bol d'eau chaude, 2 fois par jour, 5 jours maximum", "Sirop balsamique : selon les spécialités"],
    contre_indications: ["Allergie aux résineux et térébenthines", "Asthme allergique (inhalations à risque)", "Grossesse, allaitement et jeunes enfants pour l'huile essentielle", "Insuffisance rénale (huile essentielle néphrotoxique à forte dose)", "Hypertension non équilibrée (effet cortison-like des bourgeons)"],
    associations: ["Thym", "Eucalyptus radié", "Lierre grimpant"],
    precautions: "L'huile essentielle est néphrotoxique et neurotoxique à forte dose : usage limité dans le temps et à dose adaptée. Préférer les voies douces (bourgeons, infusion, inhalation contrôlée) pour les usages prolongés.",
    tradition: "Les peuples du Grand Nord et les Lapons utilisent l'écorce intérieure et les bourgeons depuis des millénaires comme aliment et remède. Les sanatoriums alpins du XIXe siècle plantaient des pineraies pour l'air balsamique qu'elles diffusaient.",
    tags: ['bronches', 'balsamique', 'conifère', 'inhalation'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },

  /* ───────────────────────────────────────
     FÉMININ
  ─────────────────────────────────────── */
  {
    slug: 'vigne-rouge-feminin',
    category: 'feminin',
    nom: 'Vigne rouge feuilles',
    nomLatin: 'Vitis vinifera L.',
    partieUtilisee: 'Feuilles rouges (variétés teinturières)',
    excerpt: "Les feuilles de vigne rouge, traditionnelles pour les règles abondantes et la circulation pelvienne.",
    intro: "Les feuilles rouges de vigne, riches en anthocyanes et en polyphénols, sont employées depuis l'Antiquité pour leurs vertus astringentes et veinotoniques. Elles soutiennent la circulation pelvienne et figurent traditionnellement dans les formules destinées aux règles abondantes et à l'insuffisance veineuse.",
    proprietes: ["Veinotonique et lymphotonique", "Vasoconstrictrice", "Astringente (resserre les muqueuses)", "Antioxydante puissante (anthocyanes, OPC)", "Anti-inflammatoire", "Protectrice de la microcirculation"],
    indications: ["Règles abondantes (ménorragies) en accompagnement", "Insuffisance veineuse pelvienne, congestion pelvienne", "Jambes lourdes et varices", "Hémorroïdes", "Bouffées de chaleur d'origine vasomotrice en complément"],
    posologie: ["Extrait standardisé : 360 à 720 mg par jour", "Infusion : 2 à 4 g de feuilles séchées pour 150 mL, 2 à 3 fois par jour", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour", "Cures de 4 à 8 semaines, à renouveler si nécessaire"],
    contre_indications: ["Grossesse (effet vasoconstricteur)", "Allaitement par mesure de précaution", "Traitements anticoagulants ou antiagrégants (surveillance nécessaire)", "Allergie aux Vitacées"],
    associations: ["Fragon (petit houx)", "Achillée millefeuille (en cas de ménorragies)", "Marronnier d'Inde"],
    precautions: "Toute ménorragie persistante ou inhabituelle impose un avis gynécologique : la phytothérapie est un complément, pas un substitut au bilan médical. Possibles troubles digestifs légers.",
    tradition: "La vigne est l'une des plus anciennes cultures médicinales d'Europe. Les feuilles rouges étaient employées dès la médecine grecque pour les hémorragies et les « flux » excessifs. La tradition viticole française les utilisait à l'automne, fraîchement récoltées après les vendanges.",
    tags: ['règles abondantes', 'veinotonique', 'pelvis', 'anthocyanes'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'gattilier-feminin-batch2',
    category: 'feminin',
    nom: 'Gattilier',
    nomLatin: 'Vitex agnus-castus L.',
    partieUtilisee: 'Fruits (baies séchées)',
    excerpt: "L'« arbre au poivre » du Sud, modulateur hormonal de référence pour le SPM.",
    intro: "Le gattilier, petit arbre méditerranéen, voit ses baies séchées (parfois nommées « poivre des moines ») employées depuis l'Antiquité dans la sphère gynécologique. Ses extraits agissent au niveau de l'hypophyse et modulent l'équilibre prolactine/progestérone, ce qui en fait une plante de référence dans le syndrome prémenstruel.",
    proprietes: ["Modulatrice hormonale (action dopaminergique hypophysaire, baisse de la prolactine)", "Régulatrice du cycle menstruel", "Pro-progestéronique d'après les données mécanistiques", "Galactofuge (à fortes doses)"],
    indications: ["Syndrome prémenstruel : irritabilité, tension mammaire, ballonnements, baisse d'humeur", "Cycles irréguliers liés à un déficit progestéronique présumé", "Mastodynies (douleurs mammaires cycliques)", "Acné prémenstruelle"],
    posologie: ["Extrait sec standardisé : 20 à 40 mg par jour, le matin", "Teinture-mère : 30 à 50 gouttes le matin", "Décoction : 2 à 4 g de baies écrasées pour 250 mL, 1 fois par jour", "Cures longues de 3 à 6 mois, l'effet s'installant progressivement (2 à 3 cycles)"],
    contre_indications: ["Grossesse (action hormonale)", "Allaitement (effet galactofuge possible)", "Cancers hormono-dépendants ou antécédents (sein, endomètre)", "Traitements hormonaux : pilule œstroprogestative, traitement hormonal substitutif, fécondation in vitro (avis spécialisé indispensable)", "Maladie de Parkinson et traitements dopaminergiques (interaction)", "Adolescentes avant la stabilisation des cycles"],
    associations: ["Alchémille", "Achillée millefeuille", "Mélisse (volet émotionnel du SPM)"],
    precautions: "L'effet hormonal réel impose un avis médical avant tout usage prolongé, notamment chez les femmes sous contraception, en désir de grossesse ou avec antécédent de cancer hormonal. Effets indésirables possibles : nausées, céphalées, troubles cutanés transitoires en début de traitement.",
    tradition: "Hippocrate et Dioscoride mentionnaient déjà le gattilier pour les troubles utérins. Son surnom de « poivre des moines » vient de l'usage médiéval qui en faisait un anaphrodisiaque pour calmer les ardeurs des religieux, d'où le nom latin « agnus-castus » (« agneau chaste »).",
    tags: ['SPM', 'cycle', 'hormonal', 'prolactine'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'actée-à-grappes-feminin',
    category: 'feminin',
    nom: 'Actée à grappes',
    nomLatin: 'Cimicifuga racemosa (L.) Nutt. (syn. Actaea racemosa)',
    partieUtilisee: 'Rhizome et racines',
    excerpt: "Le « black cohosh » nord-américain, étudié pour les bouffées de chaleur de la ménopause.",
    intro: "L'actée à grappes (ou cimicifuga, black cohosh) est une plante des forêts d'Amérique du Nord traditionnellement employée par les peuples amérindiens pour les troubles féminins. Son rhizome fait l'objet d'essais cliniques pour son intérêt sur les symptômes vasomoteurs de la ménopause (bouffées de chaleur, sueurs nocturnes).",
    proprietes: ["Action sur les symptômes vasomoteurs de la ménopause (mécanisme exact débattu, sérotoninergique central probable)", "Anti-inflammatoire douce", "Spasmolytique utérin selon la tradition", "Effet anxiolytique léger d'après certaines études"],
    indications: ["Bouffées de chaleur et sueurs nocturnes de la ménopause", "Troubles de l'humeur péri-ménopausiques en accompagnement", "Sécheresse et irritabilité de la ménopause modérée", "Dysménorrhées (usage traditionnel)"],
    posologie: ["Extrait sec standardisé : 20 à 40 mg par jour (selon les spécialités)", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour", "Cures de 3 à 6 mois, à réévaluer ensuite", "Effet progressif s'installant en 4 à 8 semaines"],
    contre_indications: ["Grossesse et allaitement (effet utérotonique traditionnel)", "Cancers hormono-dépendants ou antécédents (sein, endomètre) sans avis oncologique", "Insuffisance hépatique ou antécédent d'hépatite (rares cas d'hépatotoxicité signalés)", "Traitements hormonaux substitutifs (avis spécialisé)", "Allergie aux Renonculacées"],
    associations: ["Sauge officinale (bouffées de chaleur)", "Alchémille", "Houblon (volet émotionnel)"],
    precautions: "De rares cas d'atteinte hépatique ont conduit les autorités européennes à imposer une mention de prudence : suspendre immédiatement et consulter en cas d'ictère, urines foncées, asthénie inhabituelle ou douleurs abdominales. Ne pas dépasser 6 mois sans réévaluation. Sécurité non établie chez les femmes ayant eu un cancer du sein : avis oncologique obligatoire.",
    tradition: "Plante sacrée des peuples Algonquins, Cherokees et Iroquois, qui l'utilisaient pour les « troubles des femmes », les rhumatismes et les morsures de serpent. Introduite dans la pharmacopée européenne au XIXe siècle par les médecins éclectiques américains, elle fut largement employée par l'école homéopathique avant son retour en phytothérapie moderne.",
    tags: ['ménopause', 'bouffées de chaleur', 'black cohosh', 'amérindien'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
];
