import type { Plante } from '../types';

export const PLANTES_CIRCULATION: Plante[] = [
  {
    slug: 'aubepine-circulation',
    category: 'circulation',
    nom: 'Aubépine',
    nomLatin: 'Crataegus monogyna Jacq.',
    partieUtilisee: 'Sommités fleuries',
    excerpt: "La plante du cœur par excellence, à la fois tonicardiaque et apaisante.",
    intro: "L'aubépine est traditionnellement considérée comme la plante du cœur. Ses sommités fleuries, riches en flavonoïdes et en procyanidines, ont fait l'objet de nombreuses études cliniques dans l'insuffisance cardiaque légère et les troubles fonctionnels du rythme.",
    proprietes: ["Tonicardiaque (soutient la contraction myocardique)", "Régulatrice du rythme cardiaque selon des données cliniques", "Légèrement hypotensive", "Vasodilatatrice coronarienne (préclinique)", "Sédative douce du système nerveux"],
    indications: ["Palpitations d'origine fonctionnelle", "Soutien en cas d'insuffisance cardiaque légère (sous suivi médical)", "Anxiété avec retentissement cardiaque", "Hypertension légère en complément", "Troubles du sommeil avec tension nerveuse"],
    posologie: ["Infusion : 1 à 2 g de sommités pour 150 mL, 2 à 3 fois par jour", "Extrait sec standardisé : 160 à 900 mg par jour", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour", "Cure prolongée possible (6 à 12 semaines) sous suivi"],
    contre_indications: ["Toute pathologie cardiaque connue sans avis médical", "Association avec digitaliques sans encadrement médical"],
    associations: ["Mélisse", "Passiflore", "Olivier"],
    precautions: "L'aubépine ne remplace jamais un traitement cardiologique. Délai d'action progressif (plusieurs semaines).",
    tradition: "Arbre sacré dans de nombreuses traditions celtiques et chrétiennes, l'aubépine est citée dès le Moyen Âge. Son usage cardiaque a été codifié par Leclerc.",
    tags: ['cœur', 'palpitations', 'tension', 'anxiété'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'vigne-rouge-circulation',
    category: 'circulation',
    nom: 'Vigne rouge',
    nomLatin: 'Vitis vinifera L.',
    partieUtilisee: 'Feuilles rougies à l\'automne',
    excerpt: "La plante de référence pour les jambes lourdes et l'insuffisance veineuse.",
    intro: "Les feuilles de vigne rouge, riches en anthocyanes, flavonoïdes et tanins, sont traditionnellement employées pour soutenir la circulation veineuse. Plusieurs essais cliniques ont évalué leur intérêt dans les symptômes de l'insuffisance veineuse chronique.",
    proprietes: ["Veinotonique reconnue par l'EMA", "Vasoprotectrice", "Anti-œdémateuse", "Antioxydante", "Légèrement astringente"],
    indications: ["Jambes lourdes", "Insuffisance veineuse chronique légère à modérée", "Œdèmes des membres inférieurs", "Fragilité capillaire", "Hémorroïdes en complément"],
    posologie: ["Infusion : 2 g de feuilles séchées pour 150 mL, 2 à 3 fois par jour", "Extrait sec standardisé : 360 à 720 mg par jour", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour", "Cure de 6 à 12 semaines"],
    contre_indications: ["Allergie connue", "Grossesse et allaitement par mesure de précaution"],
    associations: ["Marronnier d'Inde", "Hamamélis", "Cyprès"],
    precautions: "Bien tolérée. Toujours rechercher une cause sous-jacente en cas d'œdèmes inhabituels ou unilatéraux.",
    tradition: "Au XIXe siècle, les médecins ont remarqué la rareté des troubles veineux chez les vignerons manipulant les feuilles rougies.",
    tags: ['veineux', 'jambes lourdes', 'œdème', 'capillaires'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'hamamelis-circulation',
    category: 'circulation',
    nom: 'Hamamélis',
    nomLatin: 'Hamamelis virginiana L.',
    partieUtilisee: 'Feuilles et écorce',
    excerpt: "Astringent veineux d'usage à la fois interne et externe.",
    intro: "Originaire d'Amérique du Nord, l'hamamélis est traditionnellement utilisé pour ses propriétés astringentes et veinotoniques. Ses feuilles et son écorce sont employées à la fois en interne et en applications locales.",
    proprietes: ["Veinotonique et vasoconstrictrice locale", "Astringente marquée", "Anti-inflammatoire locale", "Hémostatique légère", "Antioxydante"],
    indications: ["Insuffisance veineuse, jambes lourdes", "Hémorroïdes", "Fragilité capillaire, couperose", "Petites irritations cutanées", "Saignements bénins"],
    posologie: ["Infusion : 1 à 2 g de feuilles pour 150 mL, 2 à 3 fois par jour", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour", "Eau d'hamamélis : application locale, 2 à 3 fois par jour"],
    contre_indications: ["Grossesse aux doses internes thérapeutiques", "Hypersensibilité aux tanins"],
    associations: ["Vigne rouge", "Marronnier d'Inde", "Cyprès"],
    precautions: "Les fortes doses internes peuvent irriter l'estomac. En usage local, préférer des préparations standardisées.",
    tradition: "Les peuples amérindiens (notamment Mohawks) utilisaient l'hamamélis pour les contusions et saignements. L'eau d'hamamélis est devenue un produit de pharmacie populaire dès le XIXe siècle.",
    tags: ['veineux', 'hémorroïdes', 'astringent', 'capillaires'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'marronnier-inde-circulation',
    category: 'circulation',
    nom: 'Marronnier d\'Inde',
    nomLatin: 'Aesculus hippocastanum L.',
    partieUtilisee: 'Graines',
    excerpt: "Plante veinotonique de référence, validée par méta-analyses dans l'insuffisance veineuse.",
    intro: "Le marronnier d'Inde est l'une des plantes veinotoniques les mieux documentées scientifiquement. Ses graines contiennent un complexe saponosidique (escine) dont l'efficacité dans l'insuffisance veineuse chronique a fait l'objet de plusieurs revues Cochrane.",
    proprietes: ["Veinotonique puissante (escine)", "Anti-œdémateuse documentée", "Anti-inflammatoire", "Vasoprotectrice", "Légèrement antithrombotique selon des données précliniques"],
    indications: ["Insuffisance veineuse chronique avec œdème", "Jambes lourdes", "Varices et fragilité capillaire", "Hémorroïdes", "Crampes nocturnes d'origine veineuse"],
    posologie: ["Extrait sec standardisé à 16-20 % d'escine : 250 à 312,5 mg, 2 fois par jour", "Teinture-mère : 20 à 30 gouttes, 2 à 3 fois par jour", "Gels et pommades à usage local : 2 à 3 applications par jour", "Cure de 8 à 12 semaines"],
    contre_indications: ["Insuffisance rénale ou hépatique sévère", "Grossesse et allaitement", "Traitements anticoagulants sans avis médical", "Allergie aux Sapindacées"],
    associations: ["Vigne rouge", "Hamamélis", "Mélilot"],
    precautions: "Les graines crues sont toxiques : seuls les extraits standardisés et titrés en escine sont à utiliser. Risque d'irritation gastrique, à prendre au cours des repas.",
    tradition: "Importé d'Asie Mineure en Europe au XVIe siècle, le marronnier d'Inde a été observé comme veinotonique au XIXe siècle.",
    tags: ['veineux', 'escine', 'œdème', 'varices'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'ginkgo-biloba-circulation',
    category: 'circulation',
    nom: 'Ginkgo biloba',
    nomLatin: 'Ginkgo biloba L.',
    partieUtilisee: 'Feuilles',
    excerpt: "L'arbre aux quarante écus, étudié pour la microcirculation cérébrale.",
    intro: "Le ginkgo est l'un des plus anciens arbres au monde. Ses feuilles, riches en flavonoïdes et en terpénolactones, sont utilisées dans des extraits standardisés (notamment EGb 761) qui ont fait l'objet de nombreuses études cliniques sur la microcirculation cérébrale et les fonctions cognitives.",
    proprietes: ["Vasodilatatrice de la microcirculation", "Antioxydante", "Neuroprotectrice selon des données précliniques", "Antiagrégante plaquettaire légère", "Améliorerait la viscosité sanguine"],
    indications: ["Troubles de la microcirculation cérébrale et périphérique", "Troubles cognitifs liés à l'âge", "Acouphènes et vertiges d'origine vasculaire", "Syndrome de Raynaud léger en complément"],
    posologie: ["Extrait sec standardisé (24 % flavonoïdes, 6 % terpènes) : 120 à 240 mg par jour", "Cure d'au moins 8 à 12 semaines pour évaluer l'effet"],
    contre_indications: ["Traitements anticoagulants ou antiagrégants", "Période péri-opératoire (à arrêter au moins 2 semaines avant)", "Épilepsie (signalements rares)", "Grossesse et allaitement"],
    associations: ["Aubépine", "Petite pervenche", "Olivier"],
    precautions: "Risque d'interactions médicamenteuses notable (saignements). Toujours signaler la prise au médecin et au pharmacien, surtout avant chirurgie.",
    tradition: "Originaire de Chine, le ginkgo est utilisé depuis des millénaires en médecine traditionnelle chinoise. L'extrait moderne standardisé a été développé en Europe à partir des années 1960.",
    tags: ['cérébral', 'mémoire', 'microcirculation', 'âge'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
];
