import type { Plante } from '../types';

export const PLANTES_DIGESTION: Plante[] = [
  {
    slug: 'artichaut-digestion',
    category: 'digestion',
    nom: 'Artichaut',
    nomLatin: 'Cynara scolymus L.',
    partieUtilisee: 'Feuilles (limbe), récoltées avant la floraison',
    excerpt: "Un classique des digestions paresseuses et du confort hépato-biliaire.",
    intro: "L'artichaut est traditionnellement réputé pour soutenir le travail du foie et de la vésicule biliaire. Les feuilles, riches en cynarine et en acides phénoliques, sont utilisées depuis l'Antiquité pour favoriser une digestion plus aisée après les repas copieux.",
    proprietes: [
      "Cholérétique : il semblerait stimuler la production de bile",
      "Cholagogue : favoriserait l'évacuation biliaire",
      "Hépatoprotecteur traditionnel",
      "Légèrement diurétique",
      "Soutien du métabolisme lipidique selon des données préliminaires",
    ],
    indications: [
      "Digestions lentes et lourdeurs post-prandiales",
      "Inconfort hépato-biliaire fonctionnel",
      "Nausées occasionnelles d'origine digestive",
      "Confort digestif lors des repas riches",
    ],
    posologie: [
      "Infusion : 1 à 2 g de feuilles séchées dans 150 mL d'eau, 3 fois par jour avant les repas",
      "Extrait sec standardisé : 300 à 600 mg, 2 à 3 fois par jour",
      "Teinture-mère : 20 à 30 gouttes dans un verre d'eau avant les repas",
      "Cure recommandée de 3 semaines, renouvelable après une pause",
    ],
    contre_indications: ["Obstruction des voies biliaires (calculs)", "Insuffisance hépatique sévère", "Allergie connue aux Astéracées"],
    associations: ["Chardon-marie", "Romarin", "Radis noir"],
    precautions: "À éviter en cas de calculs biliaires sans avis médical. Le goût très amer peut majorer le reflux chez certaines personnes sensibles.",
    tradition: "Cultivé dès l'Antiquité méditerranéenne, l'artichaut était déjà mentionné par Pline l'Ancien. Son usage hépato-biliaire a été codifié par les phytothérapeutes européens du XIXe siècle.",
    tags: ['foie', 'bile', 'digestion', 'amer'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'chardon-marie-digestion',
    category: 'digestion',
    nom: 'Chardon-Marie',
    nomLatin: 'Silybum marianum (L.) Gaertn.',
    partieUtilisee: 'Fruits (akènes) mûrs',
    excerpt: "La plante hépatoprotectrice la mieux documentée scientifiquement.",
    intro: "Le chardon-marie est traditionnellement employé pour soutenir et protéger le foie. Ses fruits contiennent un complexe flavonolignane appelé silymarine, dont l'action hépatoprotectrice fait l'objet de nombreuses publications.",
    proprietes: ["Hépatoprotecteur reconnu par l'EMA", "Antioxydant puissant au niveau hépatocytaire", "Régénérateur cellulaire selon des données précliniques", "Cholérétique modéré", "Stabilisateur des membranes hépatiques"],
    indications: ["Soutien hépatique en cas de surcharge alimentaire ou médicamenteuse", "Convalescence après troubles hépatiques fonctionnels", "Accompagnement des troubles dyspeptiques chroniques", "Soutien lors de traitements potentiellement hépatotoxiques (en complément, avec avis médical)"],
    posologie: ["Extrait sec standardisé à 70-80 % de silymarine : 200 à 400 mg par jour, en 2 à 3 prises", "Poudre de fruits : 1 à 3 g par jour", "Infusion : 3 à 4 g de fruits écrasés pour 150 mL, 3 fois par jour", "Cure de 6 à 8 semaines"],
    contre_indications: ["Allergie aux Astéracées", "Grossesse et allaitement par mesure de précaution"],
    associations: ["Artichaut", "Desmodium", "Romarin"],
    precautions: "Peut interagir avec certains médicaments métabolisés par le cytochrome P450. Demander un avis pharmaceutique en cas de polymédication.",
    tradition: "Connu depuis l'Antiquité gréco-romaine, le chardon-marie tire son nom d'une légende chrétienne. Son usage hépatique remonte au moins au Moyen Âge dans les traités d'herboristerie européens.",
    tags: ['foie', 'silymarine', 'détox', 'protection'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'romarin-digestion',
    category: 'digestion',
    nom: 'Romarin',
    nomLatin: 'Rosmarinus officinalis L.',
    partieUtilisee: 'Feuilles',
    excerpt: "L'aromate méditerranéen aux vertus hépato-digestives reconnues.",
    intro: "Plante emblématique du bassin méditerranéen, le romarin est traditionnellement utilisé pour stimuler la digestion et soutenir la fonction hépato-biliaire. Riche en acides phénoliques (acide rosmarinique) et en huile essentielle, il fait partie des aromates aux usages thérapeutiques les plus anciens.",
    proprietes: ["Cholérétique et cholagogue", "Antispasmodique digestif léger", "Antioxydant marqué", "Carminatif (favoriserait l'évacuation des gaz)", "Tonique général traditionnellement reconnu"],
    indications: ["Digestions difficiles et ballonnements", "Inconfort hépato-biliaire fonctionnel", "Asthénie passagère d'origine digestive", "Spasmes digestifs légers"],
    posologie: ["Infusion : 2 g de feuilles séchées dans 150 mL d'eau, 3 fois par jour après les repas", "Teinture-mère : 20 à 40 gouttes, 2 à 3 fois par jour", "Extrait sec : 100 à 200 mg, 2 fois par jour", "Cure traditionnelle de 3 semaines"],
    contre_indications: ["Obstruction biliaire avérée", "Grossesse aux doses thérapeutiques", "Épilepsie (pour l'huile essentielle)"],
    associations: ["Artichaut", "Menthe poivrée", "Fenouil"],
    precautions: "L'huile essentielle de romarin est réservée à un usage encadré. La tisane reste l'usage le plus sécurisé.",
    tradition: "Cultivé depuis l'Antiquité, le romarin était brûlé dans les hôpitaux pour assainir l'air. Hildegarde de Bingen le recommandait largement pour le foie et la digestion.",
    tags: ['foie', 'digestion', 'aromate', 'méditerranéen'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'gentiane-digestion',
    category: 'digestion',
    nom: 'Gentiane jaune',
    nomLatin: 'Gentiana lutea L.',
    partieUtilisee: 'Racine séchée',
    excerpt: "L'amère par excellence, stimulante des sécrétions digestives.",
    intro: "La gentiane jaune est l'une des plantes amères les plus puissantes de la pharmacopée européenne. Sa racine, riche en sécoiridoïdes (gentiopicroside, amarogentine), est traditionnellement employée pour stimuler l'appétit et préparer la digestion.",
    proprietes: ["Apéritive (stimule l'appétit)", "Stomachique (stimule les sécrétions gastriques)", "Cholérétique modérée", "Tonique amer général", "Eupeptique (faciliterait la digestion)"],
    indications: ["Perte d'appétit, notamment en convalescence", "Digestions lentes avec sensation de pesanteur gastrique", "Insuffisance des sécrétions digestives", "Asthénie liée à un défaut d'assimilation"],
    posologie: ["Décoction : 1 à 2 g de racine pour 150 mL, prise 15 à 30 minutes avant les repas", "Teinture-mère : 10 à 20 gouttes avant les repas", "Macération à froid : 0,5 à 1 g pour 150 mL pendant 8 heures"],
    contre_indications: ["Ulcère gastrique ou duodénal", "Hyperacidité gastrique", "Reflux gastro-œsophagien", "Grossesse"],
    associations: ["Romarin", "Menthe poivrée", "Camomille romaine"],
    precautions: "Goût extrêmement amer. Toujours prendre à doses faibles. À éviter en cas de troubles gastriques inflammatoires.",
    tradition: "Plante emblématique des montagnes européennes, la gentiane est utilisée depuis l'Antiquité. Elle reste un ingrédient phare des apéritifs amers traditionnels.",
    tags: ['amer', 'apéritif', 'digestion', 'estomac'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'fenouil-digestion',
    category: 'digestion',
    nom: 'Fenouil',
    nomLatin: 'Foeniculum vulgare Mill.',
    partieUtilisee: 'Fruits',
    excerpt: "Le carminatif doux par excellence, adapté à toute la famille.",
    intro: "Le fenouil est traditionnellement utilisé pour son action sur les ballonnements et les spasmes digestifs. Ses fruits figurent parmi les plantes carminatives les mieux tolérées, y compris chez l'enfant après avis médical.",
    proprietes: ["Carminatif (réduirait les gaz intestinaux)", "Antispasmodique digestif doux", "Stomachique", "Galactogène traditionnel", "Légèrement expectorant"],
    indications: ["Ballonnements et flatulences", "Spasmes digestifs légers", "Inconfort digestif post-prandial", "Aérophagie"],
    posologie: ["Infusion : 1 à 2 g de fruits écrasés pour 150 mL, 3 fois par jour après les repas", "Teinture-mère : 20 à 40 gouttes, 2 à 3 fois par jour", "Poudre : 1 à 2 g par jour"],
    contre_indications: ["Allergie aux Apiacées", "Antécédents de cancers hormono-dépendants pour des cures prolongées"],
    associations: ["Anis vert", "Carvi", "Menthe poivrée"],
    precautions: "L'huile essentielle de fenouil n'est pas recommandée chez la femme enceinte, allaitante ou le jeune enfant. La tisane reste l'usage le plus sécurisé.",
    tradition: "Connu des Égyptiens et des Grecs, le fenouil est mentionné dans le Capitulaire de Villis de Charlemagne. Il était traditionnellement donné aux nourrissons (eau de fenouil) pour apaiser les coliques.",
    tags: ['ballonnements', 'carminatif', 'doux', 'famille'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'menthe-poivree-digestion',
    category: 'digestion',
    nom: 'Menthe poivrée',
    nomLatin: 'Mentha × piperita L.',
    partieUtilisee: 'Feuilles',
    excerpt: "Antispasmodique digestif documenté, utile dans le syndrome de l'intestin irritable.",
    intro: "La menthe poivrée, hybride naturel entre la menthe verte et la menthe aquatique, est l'une des plantes digestives les mieux étudiées. Son huile essentielle, riche en menthol, fait l'objet d'essais cliniques notamment dans le syndrome de l'intestin irritable.",
    proprietes: ["Antispasmodique intestinal documenté", "Carminatif", "Cholérétique léger", "Antibactérienne (huile essentielle)", "Rafraîchissante et tonique"],
    indications: ["Spasmes digestifs", "Syndrome de l'intestin irritable (capsules gastro-résistantes)", "Digestions difficiles", "Nausées légères"],
    posologie: ["Infusion : 1 à 2 g de feuilles séchées pour 150 mL, 2 à 3 fois par jour", "Huile essentielle en capsule gastro-résistante : 0,2 à 0,4 mL, 2 à 3 fois par jour avant les repas, sous avis professionnel", "Teinture-mère : 20 à 30 gouttes, 2 à 3 fois par jour"],
    contre_indications: ["Reflux gastro-œsophagien", "Hernie hiatale", "Lithiase biliaire", "Enfants de moins de 8 ans pour l'huile essentielle", "Grossesse et allaitement pour l'huile essentielle"],
    associations: ["Fenouil", "Camomille romaine", "Mélisse"],
    precautions: "L'huile essentielle est puissante et doit être encadrée. Éviter le soir car la menthe peut perturber le sommeil chez certaines personnes.",
    tradition: "Hybride apparu en Angleterre au XVIIe siècle, la menthe poivrée a rapidement intégré toutes les pharmacopées européennes. Son usage digestif est aujourd'hui validé par l'EMA et l'ESCOP.",
    tags: ['spasmes', 'intestin', 'SII', 'menthol'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
];
