import type { Plante } from '../types';

export const PLANTES_FEMININ: Plante[] = [
  {
    slug: 'achillee-millefeuille-feminin',
    category: 'feminin',
    nom: 'Achillée millefeuille',
    nomLatin: 'Achillea millefolium',
    partieUtilisee: 'Sommités fleuries',
    excerpt: "L'« herbe aux femmes » des herboristes, régulatrice du cycle et apaisante des règles douloureuses.",
    intro: "Plante commune des prés et chemins, l'achillée millefeuille est l'une des plus anciennes plantes médicinales européennes. Surnommée « herbe aux femmes » par les herboristes médiévales, elle conjugue tropisme utérin antispasmodique, action veinotonique et propriétés hémostatiques douces. Inscrite à la Pharmacopée française.",
    proprietes: [
      "Antispasmodique utérin",
      "Emménagogue douce (régulatrice du flux menstruel)",
      "Hémostatique légère",
      "Tonique digestive et amère",
    ],
    indications: [
      "Règles douloureuses (dysménorrhées primaires)",
      "Cycles irréguliers ou règles peu abondantes d'origine fonctionnelle",
      "Petites pertes intermenstruelles fonctionnelles (sur avis professionnel)",
      "Inconforts digestifs liés au cycle",
    ],
    posologie: [
      "Infusion : 1 à 2 g de sommités sèches pour 250 ml, 10 minutes, 2 à 3 tasses par jour, en 2ᵉ partie de cycle",
      "Teinture mère : 30 à 50 gouttes, 2 à 3 fois par jour",
      "Cure de 10 à 15 jours par cycle (de l'ovulation jusqu'au début des règles)",
    ],
    contre_indications: [
      "Grossesse (effet emménagogue, formellement déconseillée)",
      "Allergie aux Astéracées (composées)",
      "Prudence avec les anticoagulants",
      "Allaitement (par précaution, données limitées)",
    ],
    associations: ['Alchémille', 'Mélisse', "Bourse-à-pasteur (sur avis professionnel)"],
    precautions: "Goût amer marqué. À distinguer formellement de la grande camomille (Tanacetum parthenium). En cas de saignements anormaux, consulter un professionnel de santé avant tout auto-traitement prolongé.",
    tradition: "Surnommée « herbe d'Achille » car le héros grec s'en serait servi pour soigner les plaies de ses soldats. Les sages-femmes du Moyen Âge la prescrivaient sous le nom d'« herbe aux charpentiers » (pour les coupures) et d'« herbe aux femmes ».",
    tags: ['achillée', 'cycle', 'règles', 'utérus'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'gattilier-vitex-feminin',
    category: 'feminin',
    nom: 'Gattilier',
    nomLatin: 'Vitex agnus-castus',
    partieUtilisee: 'Fruits (baies mûres séchées)',
    excerpt: "Le régulateur hormonal féminin de référence, étudié pour le syndrome prémenstruel.",
    intro: "Arbrisseau méditerranéen aux baies poivrées, le gattilier est l'une des plantes féminines les mieux étudiées de la phytothérapie moderne. Il agit sur l'axe hypothalamo-hypophysaire en modulant la sécrétion de prolactine. Plusieurs essais cliniques randomisés et méta-analyses documentent son intérêt dans le syndrome prémenstruel (SPM) et la mastodynie cyclique.",
    proprietes: [
      "Régulateur du cycle (action dopaminergique sur la prolactine)",
      "Soulagement du syndrome prémenstruel",
      "Action sur la mastodynie (tension mammaire cyclique)",
      "Soutien des cycles irréguliers d'origine fonctionnelle",
    ],
    indications: [
      "Syndrome prémenstruel : irritabilité, ballonnements, tension mammaire",
      "Mastodynie cyclique",
      "Cycles irréguliers en post-pilule (sur avis professionnel)",
      "Inconforts de la périménopause débutante",
    ],
    posologie: [
      "Extrait sec standardisé (en agnusides) : 4 à 20 mg par jour, le matin",
      "Teinture mère : 20 à 40 gouttes le matin",
      "Cure de 3 à 6 mois minimum pour évaluer le bénéfice (effet progressif)",
    ],
    contre_indications: [
      "Grossesse et allaitement",
      "Cancers hormono-dépendants ou antécédents familiaux (avis médical)",
      "Traitement hormonal (pilule, THS, fécondation in vitro) : interaction possible",
      "Antécédents de tumeur hypophysaire",
    ],
    associations: ['Alchémille', 'Achillée millefeuille', 'Mélisse'],
    precautions: "Action progressive : compter 3 cycles minimum avant d'évaluer l'effet. Quelques cas rares de céphalées, nausées ou démangeaisons rapportés. Ne pas associer aux agonistes dopaminergiques sans avis médical.",
    tradition: "Connu de Théophraste et Dioscoride sous le nom d'« agneau chaste » (agnus castus), il était utilisé dans les monastères pour calmer les ardeurs des moines, d'où son surnom de « poivre des moines ». Pline l'Ancien le décrivait déjà comme régulateur des troubles féminins.",
    tags: ['gattilier', 'vitex', 'SPM', 'cycle', 'prolactine'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'alchemille-feminin',
    category: 'feminin',
    nom: 'Alchémille',
    nomLatin: 'Alchemilla vulgaris',
    partieUtilisee: 'Parties aériennes',
    excerpt: "La « cape de Notre-Dame » des herboristes, plante traditionnelle de la sphère féminine.",
    intro: "Plante des prairies montagnardes et des sous-bois clairs, l'alchémille était surnommée « cape de Notre-Dame » pour la forme de ses feuilles en pèlerine. Riche en tanins, elle a une longue tradition d'usage féminin en seconde partie de cycle, en accompagnement des règles abondantes et lors de la périménopause.",
    proprietes: [
      "Astringente (tanins)",
      "Progestérone-like supposée selon la tradition (données scientifiques limitées)",
      "Tonique de la sphère utérine",
      "Anti-diarrhéique douce",
    ],
    indications: [
      "Règles abondantes ou prolongées d'origine fonctionnelle",
      "Inconforts de la seconde partie de cycle",
      "Périménopause : irrégularités du cycle, sueurs débutantes",
      "Suites de couches en accompagnement (tradition)",
    ],
    posologie: [
      "Infusion : 1 cuillère à café de plante sèche pour 250 ml, 10 minutes, 2 à 3 tasses par jour",
      "Teinture mère : 30 à 50 gouttes, 2 à 3 fois par jour",
      "Traditionnellement : prise du 14ᵉ au 28ᵉ jour du cycle",
    ],
    contre_indications: [
      "Grossesse (par précaution)",
      "Constipation chronique (effet astringent)",
      "Traitement anticoagulant (prudence, riche en vitamine K)",
    ],
    associations: ['Gattilier', 'Achillée millefeuille', 'Sauge officinale'],
    precautions: "L'action « progestérone-like » relève de la tradition européenne et n'a pas été démontrée par des essais cliniques de bonne qualité. À considérer comme une plante d'accompagnement, jamais comme un substitut hormonal.",
    tradition: "Les alchimistes la nommaient ainsi car ils utilisaient les gouttes de rosée perlant sur ses feuilles dans leurs préparations. Sainte Hildegarde et les sages-femmes médiévales en faisaient une plante centrale des affections féminines.",
    tags: ['alchémille', 'cycle', 'périménopause', 'tanins'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'sauge-officinale-menopause',
    category: 'feminin',
    nom: 'Sauge officinale',
    nomLatin: 'Salvia officinalis',
    partieUtilisee: 'Feuilles',
    excerpt: "L'apaisante des bouffées de chaleur, plante de référence des inconforts de la ménopause.",
    intro: "Plante sacrée des Romains (Salvia, « celle qui sauve »), la sauge officinale est traditionnellement utilisée contre la transpiration excessive et les bouffées de chaleur. Plusieurs essais cliniques préliminaires confirment son intérêt sur les bouffées de chaleur ménopausiques. Sa richesse en huile essentielle impose néanmoins une vigilance d'usage.",
    proprietes: [
      "Anti-hydrotique (réduit la transpiration excessive)",
      "Œstrogène-like légère (phyto-œstrogènes)",
      "Tonique digestive et stomachique",
      "Antiseptique buccale et pharyngée",
    ],
    indications: [
      "Bouffées de chaleur et sueurs nocturnes de la ménopause",
      "Transpiration excessive d'origine fonctionnelle",
      "Inconforts digestifs (ballonnements, digestion lente)",
      "Maux de gorge et inflammations buccales (en gargarisme)",
    ],
    posologie: [
      "Infusion : 1 à 2 g de feuilles sèches pour 250 ml, 5 à 10 minutes, 1 à 3 tasses par jour",
      "Extrait sec standardisé : 100 à 300 mg par jour",
      "Teinture mère : 20 à 40 gouttes, 2 à 3 fois par jour",
      "Cures courtes (3 à 4 semaines) avec pause",
    ],
    contre_indications: [
      "Grossesse et allaitement (formellement déconseillée — sauf usage culinaire ponctuel)",
      "Cancers hormono-dépendants (sein, endomètre) ou antécédents",
      "Épilepsie (la thuyone de l'huile essentielle est neurotoxique)",
      "Hypertension non équilibrée",
      "Mastopathies fibrokystiques",
    ],
    associations: ['Houblon', 'Cyprès (gemmothérapie)', 'Alchémille'],
    precautions: "Réserver à l'adulte. Ne jamais dépasser 4 à 6 semaines de cure consécutive en raison de la thuyone. L'huile essentielle de sauge officinale est strictement réservée à l'usage médical (préférer la sauge sclarée pour l'usage courant).",
    tradition: "« Qui a de la sauge dans son jardin n'a pas besoin de médecin », disait l'École de Salerne au XIIᵉ siècle. Les Romains la cueillaient avec un rituel précis, vêtus de blanc et sans outil de fer.",
    tags: ['sauge', 'ménopause', 'bouffées', 'œstrogène-like'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'framboisier-feuilles-feminin',
    category: 'feminin',
    nom: 'Framboisier (feuilles)',
    nomLatin: 'Rubus idaeus',
    partieUtilisee: 'Feuilles',
    excerpt: "La plante traditionnelle de la sphère utérine, alliée de la fin de grossesse et du cycle féminin.",
    intro: "Si l'on connaît surtout son fruit, c'est la feuille de framboisier qui possède une longue tradition d'usage féminin. Riche en flavonoïdes, en tanins et en minéraux, elle est employée par les sages-femmes anglo-saxonnes (« raspberry leaf tea ») comme tonique utérin en fin de grossesse et comme régulatrice du cycle, avec quelques essais cliniques de qualité modeste.",
    proprietes: [
      "Tonique utérin (effet régulateur supposé des contractions)",
      "Astringente douce (tanins)",
      "Reminéralisante (magnésium, calcium, manganèse, fer)",
      "Antispasmodique légère",
    ],
    indications: [
      "Préparation au dernier mois de grossesse (à partir de la 36ᵉ semaine, sous suivi sage-femme/médecin)",
      "Règles douloureuses fonctionnelles",
      "Soutien du post-partum",
      "Régularisation des cycles fonctionnels",
    ],
    posologie: [
      "Infusion : 1 à 2 cuillères à café de feuilles sèches pour 250 ml, 10 minutes, 2 à 3 tasses par jour",
      "Cure de 10 à 14 jours par cycle (2ᵉ partie de cycle)",
      "En fin de grossesse : 1 à 3 tasses par jour à partir du 8ᵉ mois, sur avis professionnel",
    ],
    contre_indications: [
      "1er et 2ème trimestres de grossesse (par précaution)",
      "Antécédents de fausses couches ou grossesse à risque (avis professionnel impératif)",
      "Constipation chronique (effet astringent)",
      "Allergie aux Rosacées",
    ],
    associations: ['Alchémille', 'Mélisse', 'Achillée millefeuille (hors grossesse)'],
    precautions: "L'usage en fin de grossesse doit s'inscrire dans un suivi professionnel (sage-femme, médecin). Les données scientifiques sur son effet « préparateur à l'accouchement » restent limitées, même si la tradition anglo-saxonne est ancienne.",
    tradition: "Les sages-femmes celtiques et amérindiennes l'utilisaient comme tisane de fin de grossesse. La tradition britannique (raspberry leaf tea) est documentée depuis le XVIᵉ siècle et reste très vivante chez les midwives anglo-saxonnes.",
    tags: ['framboisier', 'grossesse', 'utérus', 'sage-femme'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
];
