import type { Plante } from '../types';

export const PLANTES_IMMUNITE: Plante[] = [
  {
    slug: 'echinacee-immunite',
    category: 'immunite-infections',
    nom: 'Échinacée pourpre',
    nomLatin: 'Echinacea purpurea (L.) Moench',
    partieUtilisee: 'Parties aériennes fleuries et/ou racines',
    excerpt: "La plante immunomodulante la plus étudiée pour les infections hivernales.",
    intro: "Originaire d'Amérique du Nord, l'échinacée est traditionnellement utilisée pour soutenir les défenses naturelles et raccourcir la durée des refroidissements. Plusieurs revues systématiques ont évalué son intérêt en prévention et au début des infections respiratoires hautes.",
    proprietes: ["Immunomodulante (stimulerait l'activité des phagocytes)", "Anti-inflammatoire douce", "Antivirale d'après des données précliniques", "Cicatrisante en usage externe"],
    indications: ["Prévention des refroidissements en période hivernale", "Début d'infections ORL", "Soutien des défenses lors de fatigue saisonnière", "Petites plaies en usage externe"],
    posologie: ["Teinture-mère : 20 à 30 gouttes, 3 fois par jour dès les premiers signes", "Extrait sec standardisé : 300 à 500 mg, 2 à 3 fois par jour", "Jus frais stabilisé : 6 à 9 mL par jour", "Cure courte de 7 à 10 jours"],
    contre_indications: ["Maladies auto-immunes (lupus, sclérose en plaques, polyarthrite rhumatoïde)", "Traitements immunosuppresseurs", "Allergie aux Astéracées", "Tuberculose, infections systémiques évolutives"],
    associations: ["Propolis", "Thym", "Sureau noir"],
    precautions: "Réservée aux cures courtes (10 à 14 jours). L'usage prolongé n'est pas recommandé. Demander un avis médical en cas de pathologie chronique.",
    tradition: "Plante sacrée pour plusieurs peuples amérindiens des Grandes Plaines, l'échinacée a été introduite en Europe à la fin du XIXe siècle.",
    tags: ['immunité', 'rhume', 'hiver', 'défenses'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'thym-immunite',
    category: 'immunite-infections',
    nom: 'Thym commun',
    nomLatin: 'Thymus vulgaris L.',
    partieUtilisee: 'Sommités fleuries',
    excerpt: "L'antiseptique aromatique des voies respiratoires, accessible et polyvalent.",
    intro: "Le thym est l'une des plantes les plus utilisées en phytothérapie des voies respiratoires. Riche en thymol et carvacrol, il est traditionnellement employé en cas de toux, de maux de gorge et d'infections ORL bénignes.",
    proprietes: ["Antiseptique des voies respiratoires", "Antitussif et expectorant", "Spasmolytique bronchique", "Antibactérien et antifongique (huile essentielle)", "Tonique général"],
    indications: ["Toux d'irritation et toux grasse", "Maux de gorge et rhinopharyngites", "Bronchites bénignes", "Hygiène bucco-dentaire (en bain de bouche)"],
    posologie: ["Infusion : 1 à 2 g de plante sèche pour 150 mL, 3 à 4 fois par jour", "Sirop : 1 cuillère à soupe 3 fois par jour", "Teinture-mère : 20 à 40 gouttes, 3 fois par jour", "Gargarisme : infusion concentrée tiède, 2 à 3 fois par jour"],
    contre_indications: ["Allergie aux Lamiacées", "Grossesse et allaitement pour l'huile essentielle", "Enfants de moins de 6 ans pour l'huile essentielle"],
    associations: ["Échinacée", "Propolis", "Sureau noir"],
    precautions: "L'huile essentielle de thym à thymol est dermocaustique et hépatotoxique à forte dose : usage encadré uniquement. La tisane reste très sûre.",
    tradition: "Utilisé depuis l'Égypte antique (embaumements) et la Grèce classique, le thym est un pilier de la médecine populaire méditerranéenne. Son nom dérive du grec « thymos » (force, courage).",
    tags: ['respiratoire', 'toux', 'gorge', 'antiseptique'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'sureau-noir-immunite',
    category: 'immunite-infections',
    nom: 'Sureau noir',
    nomLatin: 'Sambucus nigra L.',
    partieUtilisee: 'Fleurs et baies mûres (cuites)',
    excerpt: "Les baies de sureau, traditionnellement utilisées contre les états grippaux.",
    intro: "Le sureau noir est employé depuis longtemps en médecine populaire européenne. Ses fleurs sont diaphorétiques, tandis que ses baies, riches en anthocyanes, font l'objet d'études cliniques pour leur intérêt potentiel dans les épisodes grippaux.",
    proprietes: ["Diaphorétique (fleurs) : favoriserait la transpiration et la baisse de fièvre", "Antioxydant marqué (baies)", "Immunomodulant selon des données préliminaires", "Anti-inflammatoire doux", "Légèrement diurétique"],
    indications: ["États fébriles et grippaux légers", "Refroidissements et rhinites", "Soutien immunitaire en saison hivernale", "Convalescence après infection virale"],
    posologie: ["Infusion de fleurs : 2 à 3 g pour 150 mL, 3 fois par jour", "Sirop de baies cuites : 10 à 15 mL, 2 à 3 fois par jour", "Extrait standardisé de baies : 175 à 300 mg par jour"],
    contre_indications: ["Allergie connue", "Grossesse et allaitement par mesure de précaution"],
    associations: ["Échinacée", "Thym", "Cyprès"],
    precautions: "Ne jamais consommer les baies crues, les graines vertes, les feuilles ou l'écorce : ils contiennent des composés cyanogènes potentiellement toxiques. La cuisson rend les baies sûres.",
    tradition: "Arbre sacré dans les traditions celtiques et germaniques, le sureau était surnommé « la pharmacie du paysan » en Europe rurale.",
    tags: ['grippe', 'fièvre', 'hiver', 'baies'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'propolis-immunite',
    category: 'immunite-infections',
    nom: 'Propolis',
    nomLatin: 'Propolis (résines de Populus, Betula récoltées par Apis mellifera)',
    partieUtilisee: 'Résine végétale transformée par l\'abeille',
    excerpt: "Le bouclier protecteur de la ruche, prisé pour la sphère ORL.",
    intro: "Bien que produite par les abeilles, la propolis est un produit d'origine végétale : elle provient de résines récoltées sur les bourgeons et écorces. Traditionnellement utilisée pour soutenir les défenses naturelles, elle est particulièrement réputée pour la sphère bucco-pharyngée.",
    proprietes: ["Antiseptique à large spectre", "Anti-inflammatoire local", "Immunostimulante selon des données préliminaires", "Cicatrisante des muqueuses", "Antioxydante"],
    indications: ["Maux de gorge et angines bénignes", "Aphtes et inflammations buccales", "Soutien immunitaire en période d'épidémie", "Hygiène bucco-dentaire"],
    posologie: ["Spray oropharyngé : 2 à 3 pulvérisations, 3 à 5 fois par jour", "Pastilles ou gommes : à laisser fondre lentement, 3 à 5 fois par jour", "Teinture : 15 à 30 gouttes diluées, 2 à 3 fois par jour", "Cure courte de 10 à 15 jours"],
    contre_indications: ["Allergie aux produits de la ruche", "Allergie aux pollens de peupliers ou de bouleaux", "Asthme allergique non équilibré"],
    associations: ["Échinacée", "Thym", "Sauge officinale"],
    precautions: "Risque allergique non négligeable : tester sur une petite zone avant un premier usage prolongé. Préférer les propolis tracées (origine, type chimique).",
    tradition: "Utilisée par les Égyptiens pour l'embaumement et par les médecins grecs (Aristote, Galien), la propolis a traversé toutes les médecines traditionnelles européennes.",
    tags: ['ORL', 'gorge', 'antiseptique', 'ruche'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'cypres-immunite',
    category: 'immunite-infections',
    nom: 'Cyprès toujours vert',
    nomLatin: 'Cupressus sempervirens L.',
    partieUtilisee: 'Cônes (noix de cyprès)',
    excerpt: "Traditionnellement employé en accompagnement des infections virales chroniques.",
    intro: "Le cyprès, arbre emblématique du pourtour méditerranéen, fournit des cônes employés en phytothérapie traditionnelle. Ils sont notamment cités pour leur intérêt en cas d'infections virales récurrentes et pour leur action veinotonique.",
    proprietes: ["Antivirale traditionnellement reconnue, notamment sur les Herpèsviridae", "Veinotonique et vasoconstrictrice", "Astringente", "Antitussive"],
    indications: ["Soutien lors de poussées d'herpès labial ou de zona", "Toux quinteuses en complément", "Hémorroïdes et varices", "Convalescence d'infections virales"],
    posologie: ["Décoction : 2 à 3 g de cônes broyés pour 150 mL, 2 à 3 fois par jour", "Teinture-mère : 30 à 50 gouttes, 2 à 3 fois par jour"],
    contre_indications: ["Antécédents de cancers hormono-dépendants par précaution", "Grossesse et allaitement", "Troubles de la coagulation sans avis médical"],
    associations: ["Échinacée", "Mélisse (pour l'herpès)", "Vigne rouge"],
    precautions: "Plante puissante : usage encadré par un professionnel formé. L'huile essentielle est réservée à un usage spécifique et contre-indiquée dans plusieurs situations.",
    tradition: "Symbole d'éternité dans l'Antiquité méditerranéenne, le cyprès était planté autour des temples et des cimetières.",
    tags: ['antiviral', 'herpès', 'méditerranéen', 'cônes'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
];
