import type { Plante } from '../types';

export const PLANTES_PEAU_ARTICULATIONS: Plante[] = [
  {
    slug: 'ortie-articulations',
    category: 'peau-articulations',
    nom: 'Ortie',
    nomLatin: 'Urtica dioica',
    partieUtilisee: 'Feuilles (parties aériennes) et racine',
    excerpt: "Reminéralisante majeure, soutien traditionnel des articulations enflammées.",
    intro: "Mal-aimée du promeneur, l'ortie est pourtant l'une des plantes les plus riches du règne végétal : silice, fer, calcium, magnésium, vitamines A, C, K, chlorophylle. Sa feuille est traditionnellement employée comme dépurative et reminéralisante, avec un intérêt clinique étudié sur les douleurs articulaires inflammatoires.",
    proprietes: [
      "Reminéralisante (silice, calcium, fer assimilable)",
      "Anti-inflammatoire articulaire d'appoint",
      "Diurétique et dépurative douce",
      "Anti-histaminique léger (feuille séchée)",
    ],
    indications: [
      "Douleurs articulaires arthrosiques et rhumatismes chroniques",
      "Asthénie minérale, convalescence, anémie ferriprive d'accompagnement",
      "Terrain dépuratif (associé à une cure de printemps)",
      "Inconfort articulaire lié à l'âge",
    ],
    posologie: [
      "Infusion : 1 à 2 cuillères à café de feuilles sèches pour 250 ml, 10 minutes, 2 à 3 tasses par jour",
      "Poudre de feuille : 1 à 3 g par jour mélangée à un yaourt ou une compote",
      "Extrait sec standardisé : 300 à 600 mg par jour en cure de 3 à 6 semaines",
    ],
    contre_indications: [
      "Œdèmes liés à insuffisance cardiaque ou rénale (sans avis médical)",
      "Prudence en cas de traitement diurétique, antihypertenseur ou anticoagulant",
      "Grossesse : usage alimentaire toléré, éviter les cures prolongées",
    ],
    associations: ['Prêle', 'Harpagophytum', 'Cassis (feuille)'],
    precautions: "Bien que très bien tolérée, l'ortie peut majorer l'effet de certains traitements. À prendre en cure plutôt qu'en continu. La cueillette se fait avec des gants ; la dessiccation neutralise les poils urticants.",
    tradition: "Plante de Thor chez les Vikings, utilisée par les médecins grecs comme tonique général, l'ortie a longtemps été cultivée comme légume et fibre textile. Hildegarde de Bingen la recommandait contre la mélancolie.",
    tags: ['ortie', 'reminéralisant', 'articulations', 'silice'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'prele-silicium',
    category: 'peau-articulations',
    nom: 'Prêle des champs',
    nomLatin: 'Equisetum arvense',
    partieUtilisee: "Parties aériennes stériles (tiges d'été)",
    excerpt: "La plante du silicium par excellence, soutien des os, des cartilages et des tissus conjonctifs.",
    intro: "Vestige végétal de l'ère carbonifère, la prêle des champs concentre une teneur exceptionnelle en silice biogène (5 à 8 %). Le silicium organique participe à la synthèse du collagène, des glycosaminoglycanes du cartilage et à la minéralisation osseuse. Elle est inscrite à la Pharmacopée européenne pour son action diurétique et reminéralisante.",
    proprietes: [
      "Reminéralisante (silicium organique, calcium, potassium)",
      "Diurétique d'appoint",
      "Cicatrisante et hémostatique douce",
      "Soutien du tissu conjonctif (cartilage, os, ongles, cheveux)",
    ],
    indications: [
      "Déminéralisation, fragilité osseuse, ongles cassants",
      "Convalescence après fracture (en complément médical)",
      "Soutien articulaire en cas d'arthrose débutante",
      "Cheveux ternes et ongles dédoublés",
    ],
    posologie: [
      "Décoction : 2 g de plante sèche pour 250 ml, frémir 10 minutes, infuser 15 minutes, 2 à 3 tasses par jour",
      "Extrait sec : 300 à 600 mg par jour, en cure de 3 semaines",
      "Cure traditionnelle de printemps et d'automne",
    ],
    contre_indications: [
      "Œdèmes liés à insuffisance cardiaque ou rénale",
      "Grossesse et allaitement (par précaution)",
      "Carence avérée en vitamine B1 (la prêle contient des thiaminases, neutralisées par décoction)",
      "Enfants de moins de 12 ans",
    ],
    associations: ['Ortie', 'Bambou tabashir', 'Lithothamne'],
    precautions: "Bien distinguer Equisetum arvense (comestible) d'Equisetum palustre (toxique). Toujours utiliser la décoction et non l'infusion simple, pour inactiver les thiaminases. Ne pas dépasser 6 semaines de cure consécutive.",
    tradition: "Galien et Dioscoride la décrivaient déjà comme cicatrisante. Les orfèvres et ébénistes du Moyen Âge l'utilisaient pour polir le bois et les métaux grâce à sa silice.",
    tags: ['prêle', 'silicium', 'collagène', 'os'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'harpagophytum-griffe-diable',
    category: 'peau-articulations',
    nom: 'Harpagophytum',
    nomLatin: 'Harpagophytum procumbens',
    partieUtilisee: 'Racine secondaire (tubercules)',
    excerpt: "La « griffe du diable » du Kalahari, plante de référence des douleurs articulaires chroniques.",
    intro: "Plante des savanes d'Afrique australe, l'harpagophytum doit son nom aux crochets de ses fruits. Sa racine, riche en iridoïdes (harpagoside, harpagide), est l'une des plantes les mieux étudiées pour les douleurs articulaires. Plusieurs essais cliniques randomisés et méta-analyses confirment son intérêt dans l'arthrose et la lombalgie chronique.",
    proprietes: [
      "Anti-inflammatoire articulaire (inhibition COX-2 et NF-κB)",
      "Antalgique sur douleurs chroniques",
      "Stimulante des sécrétions digestives (effet amer)",
      "Chondroprotectrice (données précliniques)",
    ],
    indications: [
      "Arthrose des grosses articulations (genou, hanche)",
      "Lombalgies chroniques d'origine mécanique",
      "Tendinites et douleurs musculo-tendineuses récidivantes",
      "Poussées rhumatismales d'intensité légère à modérée",
    ],
    posologie: [
      "Extrait sec standardisé (≥ 30 mg d'harpagoside par jour) : 400 à 600 mg, 2 à 3 fois par jour aux repas",
      "Poudre de racine : 1 à 3 g par jour",
      "Cure de 4 à 6 semaines, à renouveler après une pause",
    ],
    contre_indications: [
      "Ulcère gastrique ou duodénal en évolution (effet sécrétagogue)",
      "Calculs biliaires (effet cholérétique)",
      "Grossesse et allaitement",
      "Prudence avec anticoagulants (warfarine), antiarythmiques, antidiabétiques",
    ],
    associations: ['Cassis (feuille ou bourgeon)', 'Reine-des-prés', 'Curcuma'],
    precautions: "Plante issue d'une cueillette sauvage menacée : privilégier les filières certifiées (FairWild). Effet progressif : compter 2 à 4 semaines avant d'évaluer le bénéfice.",
    tradition: "Utilisée par les peuples San et Khoï du désert du Kalahari pour les douleurs articulaires et digestives. Introduite en Europe en 1953 par un fermier allemand soigné d'arthrose par un guérisseur namibien.",
    tags: ['harpagophytum', 'arthrose', 'anti-inflammatoire', 'douleur'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'curcuma-peau-articulations',
    category: 'peau-articulations',
    nom: 'Curcuma',
    nomLatin: 'Curcuma longa',
    partieUtilisee: 'Rhizome',
    excerpt: "Le rhizome d'or, anti-inflammatoire majeur de la médecine ayurvédique.",
    intro: "Pilier de la médecine ayurvédique depuis plus de 4 000 ans, le curcuma a fait l'objet d'innombrables études modernes. Sa curcumine module plusieurs voies inflammatoires (NF-κB, COX-2, cytokines). Plusieurs méta-analyses confirment son efficacité dans l'arthrose du genou, parfois comparable à certains AINS, avec une meilleure tolérance digestive.",
    proprietes: [
      "Anti-inflammatoire systémique (curcuminoïdes)",
      "Antioxydante puissante",
      "Hépatoprotectrice et cholérétique",
      "Bénéfique pour la peau inflammatoire en application traditionnelle",
    ],
    indications: [
      "Arthrose, en particulier du genou",
      "Inconforts articulaires inflammatoires chroniques",
      "Soutien hépato-digestif",
      "Peaux à tendance inflammatoire (eczéma, psoriasis léger, en accompagnement)",
    ],
    posologie: [
      "Extrait standardisé en curcuminoïdes (formule biodisponible avec pipérine ou phytosomes) : 500 à 1 000 mg par jour",
      "Poudre alimentaire : 1 à 3 g par jour avec un corps gras et du poivre noir",
      "Cure de 8 à 12 semaines pour évaluer l'effet articulaire",
    ],
    contre_indications: [
      "Obstruction des voies biliaires, calculs biliaires symptomatiques",
      "Grossesse à doses thérapeutiques (usage culinaire toléré)",
      "Prudence avec anticoagulants, antiagrégants, antidiabétiques",
      "Avant chirurgie (arrêter 15 jours avant)",
    ],
    associations: ['Gingembre', 'Boswellia', 'Harpagophytum'],
    precautions: "La curcumine est très peu biodisponible : préférer une forme galénique optimisée (phytosome, micelles, nanocurcumine) ou l'associer à la pipérine et à un corps gras. Surveiller les enzymes hépatiques lors de prises prolongées à hautes doses.",
    tradition: "Plante sacrée en Inde, utilisée dans les rituels védiques et la cuisine quotidienne. La médecine ayurvédique l'emploie en pâte (lepa) sur les peaux inflammatoires et en décoction lactée pour les douleurs articulaires.",
    tags: ['curcuma', 'ayurvéda', 'anti-inflammatoire', 'arthrose'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'bardane-peau',
    category: 'peau-articulations',
    nom: 'Bardane',
    nomLatin: 'Arctium lappa',
    partieUtilisee: 'Racine',
    excerpt: "La grande dépurative des peaux à problèmes, alliée traditionnelle des dermatoses.",
    intro: "Plante bisannuelle des friches et lisières, la bardane était présente dans tous les jardins de simples du Moyen Âge. Sa racine, riche en inuline, polyacétylènes et acide caféique, est l'une des plus anciennes dépuratives de la pharmacopée occidentale, traditionnellement employée pour les peaux à imperfections.",
    proprietes: [
      "Dépurative et drainante (foie, reins)",
      "Antibactérienne et antifongique (polyacétylènes)",
      "Hypoglycémiante légère (inuline)",
      "Sudorifique douce",
    ],
    indications: [
      "Acné juvénile et acné inflammatoire de l'adulte",
      "Eczéma chronique, peaux à imperfections, furoncles à répétition",
      "Terrain dépuratif (en cure de saison)",
      "Cheveux gras et pellicules (usage interne ou décoction en rinçage)",
    ],
    posologie: [
      "Décoction de racine : 3 à 5 g pour 250 ml, frémir 10 minutes, infuser 10 minutes, 2 à 3 tasses par jour",
      "Teinture mère : 30 à 50 gouttes, 3 fois par jour dans un peu d'eau",
      "Extrait sec : 300 à 600 mg par jour en cure de 3 à 6 semaines",
    ],
    contre_indications: [
      "Allergie aux Astéracées (composées)",
      "Diabète insulinotraité (surveillance glycémique)",
      "Grossesse et allaitement (par précaution)",
      "Déshydratation marquée",
    ],
    associations: ['Pensée sauvage', 'Pissenlit', 'Ortie'],
    precautions: "Effet souvent progressif : compter 4 à 8 semaines avant d'évaluer l'amélioration cutanée. Une légère réactivation initiale (« crise dépurative ») peut survenir ; elle s'atténue en quelques jours.",
    tradition: "Henri III en aurait été guéri d'une affection cutanée tenace. Au Moyen Âge, on l'appelait « herbe aux teigneux ». La fermeture velcro a été inventée en 1948 par l'ingénieur Georges de Mestral après observation des fruits accrochants de la bardane.",
    tags: ['bardane', 'acné', 'dépurative', 'peau'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'calendula-peau',
    category: 'peau-articulations',
    nom: 'Calendula (souci)',
    nomLatin: 'Calendula officinalis',
    partieUtilisee: 'Fleurs (capitules)',
    excerpt: "La fleur de soleil cicatrisante, apaisante des peaux fragiles et irritées.",
    intro: "Cultivé dans tous les jardins d'Europe depuis le Moyen Âge, le souci officinal est l'une des plantes cicatrisantes les mieux référencées. Sa fleur, riche en flavonoïdes, caroténoïdes, triterpènes et polysaccharides, est inscrite à la Pharmacopée européenne et à la monographie EMA pour le traitement symptomatique des inflammations cutanées mineures et des plaies superficielles.",
    proprietes: [
      "Cicatrisante (stimulation des fibroblastes)",
      "Anti-inflammatoire et apaisante cutanée",
      "Antibactérienne douce et antifongique",
      "Adoucissante des muqueuses (usage interne en infusion)",
    ],
    indications: [
      "Petites plaies superficielles, écorchures, brûlures du 1ᵉʳ degré",
      "Peaux irritées, rougeurs, érythèmes solaires modérés",
      "Eczéma sec et peaux atopiques (en accompagnement)",
      "Irritations buccales (en bains de bouche d'infusion)",
    ],
    posologie: [
      "Macérat huileux : application locale 2 à 3 fois par jour sur peau propre et sèche",
      "Crème ou pommade à 2-10 % d'extrait : application locale 1 à 3 fois par jour",
      "Infusion (usage externe ou bain de bouche) : 1 à 2 g de fleurs pour 150 ml, 10 minutes",
      "Teinture mère diluée (10 %) en compresse sur petites plaies",
    ],
    contre_indications: [
      "Allergie connue aux Astéracées (composées)",
      "Plaies profondes ou infectées (avis médical)",
      "Grossesse : usage cutané toléré, prudence avec l'usage interne prolongé",
    ],
    associations: ['Plantain lancéolé', 'Millepertuis (usage externe)', 'Camomille romaine'],
    precautions: "Très bonne tolérance cutanée, y compris chez le nourrisson et la femme enceinte (usage externe). Réaliser un test sur une petite zone en cas de peau très réactive.",
    tradition: "Sainte Hildegarde et Mésué l'ancien le citaient comme cicatrisant universel. Les femmes du Moyen Âge l'employaient en pommade pour les gerçures des mains et le visage. Sa floraison qui suit le soleil lui a valu son nom de « solsequium ».",
    tags: ['calendula', 'cicatrisation', 'peau', 'souci'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
];
