import type { Plante } from '../types';

export const PLANTES_RESPIRATION: Plante[] = [
  {
    slug: 'eucalyptus-respiration',
    category: 'respiration',
    nom: 'Eucalyptus',
    nomLatin: 'Eucalyptus globulus',
    partieUtilisee: 'Feuilles',
    excerpt: "L'arbre des voies respiratoires, riche en eucalyptol expectorant et antiseptique.",
    intro: "Originaire d'Australie et acclimaté au bassin méditerranéen au XIXᵉ siècle, l'eucalyptus est devenu en Europe une référence des affections respiratoires saisonnières. Son huile essentielle, riche en 1,8-cinéole (eucalyptol), est inscrite à la Pharmacopée européenne pour son action fluidifiante et antiseptique des voies aériennes.",
    proprietes: [
      "Expectorante et mucolytique (fluidifie les sécrétions bronchiques)",
      "Antiseptique des voies respiratoires",
      "Anti-inflammatoire bronchique",
      "Antitussive d'appoint",
    ],
    indications: [
      "Rhumes, rhinites et sinusites saisonnières",
      "Bronchites aiguës non compliquées",
      "Encombrement bronchique avec toux grasse",
      "Inconfort respiratoire d'origine virale",
    ],
    posologie: [
      "Infusion de feuilles : 2 g pour 250 ml d'eau bouillante, 10 minutes, 2 à 3 tasses par jour",
      "Extrait sec : 200 à 400 mg par prise, 2 à 3 fois par jour",
      "Inhalation : 3 à 5 gouttes d'huile essentielle dans un bol d'eau chaude, 5 à 10 minutes, 1 à 2 fois par jour",
    ],
    contre_indications: [
      "Enfant de moins de 6 ans pour l'huile essentielle (risque de bronchospasme)",
      "Asthme non équilibré (huile essentielle déconseillée)",
      "Grossesse et allaitement pour l'huile essentielle par voie interne",
      "Insuffisance hépatique sévère",
    ],
    associations: ['Thym', 'Plantain lancéolé', 'Bourgeon de pin'],
    precautions: "Privilégier la tisane et l'inhalation chez l'adulte. L'huile essentielle ne se prend pas par voie orale sans avis d'un professionnel formé. Tenir éloigné des nourrissons.",
    tradition: "Les Aborigènes d'Australie utilisaient les feuilles d'eucalyptus en fumigation pour assainir l'air et soulager les fièvres. Au XIXᵉ siècle, les colons l'ont planté dans les zones marécageuses d'Europe du Sud pour assécher les sols et lutter contre le paludisme.",
    tags: ['eucalyptus', 'respiration', 'bronches', 'rhume'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'plantain-lanceole-respiration',
    category: 'respiration',
    nom: 'Plantain lancéolé',
    nomLatin: 'Plantago lanceolata',
    partieUtilisee: 'Feuilles',
    excerpt: "L'adoucissant des muqueuses irritées, allié des toux sèches et des gorges enflammées.",
    intro: "Plante commune des prairies et bords de chemins, le plantain lancéolé est utilisé depuis l'Antiquité. Riche en mucilages, iridoïdes (aucuboside) et flavonoïdes, il calme les irritations des muqueuses respiratoires. Il figure aujourd'hui à la monographie de l'EMA pour la toux et les irritations buccopharyngées.",
    proprietes: [
      "Adoucissante et émolliente (muqueuses respiratoires)",
      "Anti-inflammatoire légère",
      "Antitussive d'appoint",
      "Antibactérienne douce (aucuboside)",
    ],
    indications: [
      "Toux sèches et irritatives",
      "Maux de gorge et laryngites",
      "Rhinites allergiques saisonnières (en accompagnement)",
      "Irritations buccales et pharyngées",
    ],
    posologie: [
      "Infusion : 1 à 2 g de feuilles sèches pour 250 ml d'eau, 10 minutes, 2 à 4 tasses par jour",
      "Sirop traditionnel : 1 cuillère à soupe 3 à 4 fois par jour",
      "Teinture mère : 20 à 40 gouttes, 3 fois par jour dans un peu d'eau",
    ],
    contre_indications: [
      "Allergie connue aux Plantaginacées",
      "Prudence en cas de prise concomitante d'anticoagulants (théorique)",
    ],
    associations: ['Mauve', 'Thym', 'Bourgeon de cassis'],
    precautions: "Très bien toléré, y compris chez l'enfant et la personne âgée. La feuille fraîche peut s'utiliser en cataplasme pour les piqûres d'insectes.",
    tradition: "Surnommé « herbe à cinq côtes » par les Celtes, le plantain figurait parmi les neuf herbes sacrées anglo-saxonnes. Les soldats le glissaient dans leurs chaussures pour prévenir les ampoules et l'appliquaient sur les plaies au champ de bataille.",
    tags: ['plantain', 'toux', 'gorge', 'mucilage'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'mauve-respiration',
    category: 'respiration',
    nom: 'Mauve',
    nomLatin: 'Malva sylvestris',
    partieUtilisee: 'Fleurs et feuilles',
    excerpt: "La douce protectrice des muqueuses, riche en mucilages apaisants.",
    intro: "Connue depuis Pythagore et Pline l'Ancien, la mauve sauvage tapisse les jardins et les talus d'Europe. Sa richesse en mucilages (jusqu'à 10 %) en fait l'une des plantes émollientes majeures de la tradition occidentale. Elle apaise les irritations respiratoires et digestives sans aucune toxicité.",
    proprietes: [
      "Émolliente et adoucissante (forte teneur en mucilages)",
      "Anti-inflammatoire légère des muqueuses",
      "Pectorale (calme la toux)",
      "Légèrement laxative (effet mécanique)",
    ],
    indications: [
      "Toux sèches et quinteuses",
      "Pharyngites et laryngites",
      "Bronchites légères avec inflammation des muqueuses",
      "Inconfort des voies aériennes hautes chez l'enfant et la personne âgée",
    ],
    posologie: [
      "Infusion (eau frémissante, non bouillante) : 1,5 g de fleurs séchées pour 250 ml, 10 minutes, 3 à 4 tasses par jour",
      "Macération à froid : 2 cuillères à café dans un verre d'eau froide, 2 à 4 heures, à boire dans la journée",
      "Sirop de mauve : 1 cuillère à soupe 3 à 5 fois par jour",
    ],
    contre_indications: [
      "Aucune contre-indication connue aux doses usuelles",
      "Espacer la prise d'autres médicaments oraux (les mucilages peuvent ralentir leur absorption)",
    ],
    associations: ['Plantain lancéolé', 'Coquelicot', 'Bouillon-blanc'],
    precautions: "Excellente tolérance, y compris chez les très jeunes enfants et les femmes enceintes. Préférer une eau frémissante pour préserver les mucilages.",
    tradition: "Les Romains la cultivaient comme légume et la nommaient « omnimorbia », celle qui guérit toutes les maladies. Charlemagne ordonna sa culture dans tous les jardins de l'Empire par le capitulaire De Villis.",
    tags: ['mauve', 'mucilage', 'toux', 'muqueuses'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'bourgeon-pin-respiration',
    category: 'respiration',
    nom: 'Bourgeon de pin',
    nomLatin: 'Pinus sylvestris',
    partieUtilisee: 'Bourgeons (jeunes pousses)',
    excerpt: "Le tonique respiratoire de la gemmothérapie, allié des bronches affaiblies.",
    intro: "En gemmothérapie, méthode mise au point au XXᵉ siècle par le médecin belge Pol Henry, les jeunes bourgeons concentrent l'énergie embryonnaire de la plante. Le bourgeon de pin sylvestre est traditionnellement employé pour restaurer le terrain respiratoire après infections répétées ou chez les personnes fatiguées.",
    proprietes: [
      "Tonique respiratoire général (usage traditionnel)",
      "Expectorante douce",
      "Reminéralisante (en gemmothérapie)",
      "Stimulante du terrain selon la tradition gemmothérapeutique",
    ],
    indications: [
      "Convalescence après bronchites ou pneumopathies",
      "Terrain respiratoire fragile et infections ORL récidivantes",
      "Fatigue accompagnée de troubles respiratoires chroniques",
      "Soutien hivernal préventif",
    ],
    posologie: [
      "Macérat glycériné concentré (1D) : 5 à 15 gouttes par jour dans un peu d'eau, à jeun",
      "Cure de 3 semaines, à renouveler après une semaine de pause",
      "Préférer une prise le matin ou en début d'après-midi",
    ],
    contre_indications: [
      "Allergie connue aux Pinacées",
      "Grossesse et allaitement (par précaution, données insuffisantes)",
      "Enfants de moins de 3 ans sans avis professionnel",
    ],
    associations: ['Bourgeon de cassis', "Bourgeon d'aulne", 'Thym'],
    precautions: "La gemmothérapie repose sur l'expérience clinique traditionnelle ; les essais cliniques contrôlés restent rares. À utiliser en cure, jamais en continu prolongé.",
    tradition: "Le pin sylvestre est l'arbre sacré des peuples du Nord. Les forestiers et bergers des Alpes en mâchaient les jeunes bourgeons au printemps comme cure de renouveau. Pol Henry a formalisé son usage en gemmothérapie dans les années 1950.",
    tags: ['gemmothérapie', 'pin', 'bronches', 'terrain'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'hysope-respiration',
    category: 'respiration',
    nom: 'Hysope',
    nomLatin: 'Hyssopus officinalis',
    partieUtilisee: 'Sommités fleuries',
    excerpt: "La pectorale aromatique des moines, expectorante et antiseptique des bronches.",
    intro: "Plante méditerranéenne cultivée dans les jardins monastiques depuis le Haut Moyen Âge, l'hysope officinale est mentionnée dans la Bible parmi les herbes de purification. Riche en huile essentielle (pinocamphone, isopinocamphone, marrubiine), elle est traditionnellement utilisée pour les affections bronchiques productives.",
    proprietes: [
      "Expectorante et mucolytique",
      "Antitussive et antispasmodique bronchique",
      "Antiseptique des voies respiratoires",
      "Tonique digestive (amer)",
    ],
    indications: [
      "Bronchites chroniques avec encombrement",
      "Toux grasse de fin de rhume",
      "Asthme léger d'accompagnement (sous avis médical)",
      "Affections ORL hivernales",
    ],
    posologie: [
      "Infusion : 1 à 2 g de sommités sèches pour 250 ml, 10 minutes, 2 à 3 tasses par jour",
      "Teinture mère : 20 à 30 gouttes, 2 à 3 fois par jour",
      "Sirop traditionnel d'hysope : 1 cuillère à soupe, 3 fois par jour",
    ],
    contre_indications: [
      "Grossesse et allaitement (formellement déconseillée)",
      "Enfants de moins de 12 ans",
      "Antécédents d'épilepsie ou de convulsions (l'huile essentielle est neurotoxique et abortive)",
      "Hypertension non équilibrée",
    ],
    associations: ['Thym', 'Eucalyptus', 'Marrube blanc'],
    precautions: "L'huile essentielle d'hysope officinale est l'une des plus neurotoxiques de la pharmacopée et strictement réservée à l'usage médical. La tisane et la teinture restent en revanche bien tolérées chez l'adulte sain.",
    tradition: "Mentionnée dans le Psaume 51 (« Asperge-moi avec l'hysope »), elle figure dans les jardins de la règle de saint Benoît. Hildegarde de Bingen la prescrivait pour purifier les poumons et le foie.",
    tags: ['hysope', 'bronches', 'expectorant', 'monastique'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
];
