import type { Plante } from '../types';

export const PLANTES_SOMMEIL: Plante[] = [
  {
    slug: 'valeriane-sommeil',
    category: 'sommeil',
    nom: 'Valériane',
    nomLatin: 'Valeriana officinalis',
    partieUtilisee: 'Racine',
    excerpt: "L'une des plantes du sommeil les mieux étudiées en phytothérapie occidentale.",
    intro: "La valériane officinale est traditionnellement utilisée depuis l'Antiquité gréco-romaine pour favoriser le sommeil et apaiser l'agitation. Plusieurs méta-analyses récentes en confirment l'intérêt sur la qualité subjective du sommeil, avec une bonne tolérance.",
    proprietes: [
      "Sédative et hypnotique légère",
      "Anxiolytique d'appoint",
      "Antispasmodique",
      "Modulatrice du système GABAergique (acide valérique et valépotriates)",
    ],
    indications: [
      "Difficultés d'endormissement liées à l'anxiété ou aux ruminations",
      "Réveils nocturnes ponctuels",
      "Stress anticipatoire (examens, prise de parole)",
      "Spasmes musculaires d'origine nerveuse",
    ],
    posologie: [
      "Extrait sec standardisé : 400 à 600 mg, 30 à 60 minutes avant le coucher",
      "Teinture mère : 30 à 60 gouttes en infusion d'eau tiède",
      "Infusion de racines sèches : 2 à 3 g pour 250 ml, infuser 10 minutes",
    ],
    contre_indications: [
      "Grossesse et allaitement (par précaution)",
      "Pas d'usage chronique au-delà de 4 à 6 semaines sans pause",
      "Avant la conduite automobile (effet sédatif possible)",
      "Association aux benzodiazépines : avis médical recommandé",
    ],
    associations: ['Passiflore', 'Mélisse', 'Aubépine'],
    precautions: "L'odeur très marquée de la valériane peut être désagréable. Les gélules ou comprimés sont mieux tolérés que la teinture.",
    tradition: "Hippocrate la mentionnait déjà. Au Moyen Âge, on la nommait « guérit-tout ». Les soldats de la Première Guerre mondiale en consommaient pour gérer le stress du front.",
    tags: ['valériane', 'sommeil', 'GABA', 'anxiété'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'passiflore-sommeil',
    category: 'sommeil',
    nom: 'Passiflore',
    nomLatin: 'Passiflora incarnata',
    partieUtilisee: 'Parties aériennes (feuilles, tiges, fleurs)',
    excerpt: "L'apaisante des ruminations mentales et de l'anxiété qui empêche de s'endormir.",
    intro: "Originaire d'Amérique du Sud, la passiflore a été ramenée en Europe au XVIIᵉ siècle. Elle est aujourd'hui inscrite à la Pharmacopée européenne pour son action sédative et anxiolytique légère. Plusieurs essais cliniques en ont confirmé l'efficacité sur l'anxiété situationnelle.",
    proprietes: [
      "Sédative et anxiolytique douce",
      "Antispasmodique nerveux",
      "Modulatrice GABAergique (flavonoïdes type chrysine)",
      "Sans effet de dépendance ni de tolérance documentés",
    ],
    indications: [
      "Anxiété d'anticipation (examens, opérations)",
      "Insomnie d'endormissement par ruminations",
      "Palpitations et oppression d'origine nerveuse",
      "Sevrage en accompagnement (alcool, tabac, médicaments) sur avis médical",
    ],
    posologie: [
      "Extrait sec : 250 à 500 mg, 30 minutes avant le coucher ou avant un événement stressant",
      "Teinture mère : 50 à 100 gouttes par jour, fractionnées",
      "Infusion : 1 cuillère à café de plante sèche pour 250 ml, 5 à 10 minutes",
    ],
    contre_indications: [
      "Grossesse (par précaution, données limitées)",
      "Association aux sédatifs hypnotiques (avis médical)",
      "Hypotension marquée",
    ],
    associations: ['Valériane', 'Aubépine', 'Mélisse'],
    precautions: "Bien tolérée. Quelques cas de somnolence diurne rapportés en cas de dose élevée.",
    tradition: "Les Amérindiens d'Amérique du Sud l'utilisaient comme calmant. Les conquistadors espagnols voyaient dans sa fleur les symboles de la Passion du Christ — d'où son nom.",
    tags: ['passiflore', 'anxiété', 'sommeil', 'GABA'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'melisse-sommeil',
    category: 'sommeil',
    nom: 'Mélisse',
    nomLatin: 'Melissa officinalis',
    partieUtilisee: 'Feuilles fraîches ou séchées',
    excerpt: "L'apaisement double — système nerveux et digestif. Adaptée aux enfants.",
    intro: "La mélisse, au parfum citronné délicat, est cultivée en Europe depuis l'Antiquité. Hildegarde de Bingen la recommandait pour le cœur troublé. Sa particularité : elle agit simultanément sur le système nerveux et le système digestif, ce qui en fait une plante idéale des « digestions nerveuses » et des troubles psychosomatiques.",
    proprietes: [
      "Sédative douce et anxiolytique légère",
      "Antispasmodique digestif",
      "Carminative (réduit les gaz)",
      "Antivirale (notamment contre HSV-1 en application locale)",
    ],
    indications: [
      "Sommeil agité, surtout chez l'enfant",
      "Digestion difficile d'origine émotionnelle",
      "Palpitations bénignes liées au stress",
      "Herpès labial (application en infusion concentrée ou crème)",
    ],
    posologie: [
      "Infusion : 1 cuillère à soupe de feuilles fraîches ou 1 cuillère à café sèche pour 250 ml, 5 à 10 minutes",
      "2 à 3 tasses par jour, dont une le soir",
      "Teinture mère : 30 gouttes 3 fois par jour",
      "Hydrolat : 1 cuillère à café dans un verre d'eau",
    ],
    contre_indications: [
      "Hypothyroïdie non équilibrée (effet thyréostatique léger rapporté in vitro)",
      "Sous traitement thyroïdien : avis médical",
    ],
    associations: ['Camomille romaine', 'Tilleul', 'Verveine'],
    tradition: "Théophraste, Dioscoride et Galien la connaissaient. Au Moyen Âge, les Carmélites en composaient l'« Eau de Mélisse des Carmes », tonique nerveuse encore commercialisée.",
    tags: ['mélisse', 'enfant', 'anxiété', 'digestion'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'tilleul-sommeil',
    category: 'sommeil',
    nom: 'Tilleul',
    nomLatin: 'Tilia cordata, Tilia platyphyllos',
    partieUtilisee: 'Inflorescences (bractées et fleurs)',
    excerpt: "Le grand classique des tisanes du soir, doux et adapté à toute la famille.",
    intro: "Le tilleul est l'arbre symbolique des places de village. Ses fleurs récoltées en juin donnent une infusion universellement appréciée pour préparer au sommeil. Sa douceur en fait la plante d'introduction à la phytothérapie pour toute la famille, des jeunes enfants aux aînés.",
    proprietes: [
      "Sédatif léger",
      "Diaphorétique (favorise la transpiration en cas de fièvre)",
      "Antispasmodique doux",
      "Béchique (apaise la toux d'irritation)",
    ],
    indications: [
      "Préparation au sommeil chez l'enfant comme l'adulte",
      "États fébriles bénins (rhume, grippe légère)",
      "Toux d'irritation",
      "Nervosité du soir",
    ],
    posologie: [
      "Infusion : 1 cuillère à soupe d'inflorescences pour 250 ml, 5 minutes",
      "1 à 3 tasses par jour, dont une le soir",
      "Pour les enfants : demi-dose adulte",
      "Bain de tilleul : 50 g d'inflorescences en décoction, ajoutées au bain",
    ],
    contre_indications: [
      "Aucune contre-indication majeure connue aux doses usuelles",
      "Allergies aux Tiliacées (très rares)",
    ],
    associations: ['Verveine', 'Mélisse', 'Camomille'],
    tradition: "Le tilleul de Sully (planté en 1605) est encore vivant en France. La phytothérapie populaire en a fait la tisane du soir par excellence.",
    tags: ['tilleul', 'enfant', 'famille', 'sommeil'],
    evidence_level: 'tradition',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'aubepine-sommeil',
    category: 'sommeil',
    nom: 'Aubépine',
    nomLatin: 'Crataegus monogyna, Crataegus laevigata',
    partieUtilisee: 'Sommités fleuries',
    excerpt: "Pour les insomnies avec palpitations ou sensation de cœur emballé.",
    intro: "L'aubépine est traditionnellement appelée « valériane du cœur ». Elle agit à la fois sur le système nerveux et le rythme cardiaque, ce qui en fait la plante des sujets qui se réveillent avec le cœur qui bat fort ou qui ont des palpitations émotionnelles au moment de s'endormir.",
    proprietes: [
      "Régulatrice du rythme cardiaque (légèrement bradycardisante)",
      "Hypotensive douce",
      "Sédative nerveuse",
      "Vasodilatatrice coronarienne",
    ],
    indications: [
      "Insomnies avec palpitations ou tachycardie émotionnelle",
      "Hypertension artérielle légère (en accompagnement, avec avis médical)",
      "Pré-ménopause avec bouffées de chaleur et palpitations",
      "Anxiété avec composante cardiaque",
    ],
    posologie: [
      "Extrait sec standardisé : 200 à 300 mg, 2 à 3 fois par jour",
      "Teinture mère : 30 gouttes 3 fois par jour",
      "Infusion : 1 cuillère à café de sommités pour 250 ml, 10 minutes",
      "Cure de 3 semaines à renouveler",
    ],
    contre_indications: [
      "Sous traitement antihypertenseur ou anti-arythmique : avis médical impératif",
      "Insuffisance cardiaque non explorée",
    ],
    associations: ['Valériane', 'Passiflore', 'Mélisse'],
    tradition: "Plante sacrée des druides celtes. Au Moyen Âge, son bois servait à fabriquer des couronnes pour les rois. Hyssop ses fleurs blanches symbolisaient la pureté.",
    tags: ['aubépine', 'cœur', 'sommeil', 'palpitations'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
];
