import type { Plante } from '../types';

export const PLANTES_STRESS_ANXIETE: Plante[] = [
  {
    slug: 'ashwagandha-stress',
    category: 'stress-anxiete',
    nom: 'Ashwagandha',
    nomLatin: 'Withania somnifera',
    partieUtilisee: 'Racine',
    excerpt: "L'adaptogène ayurvédique pour le stress chronique et la fatigue d'épuisement.",
    intro: "L'ashwagandha, parfois nommé « ginseng indien », est un pilier de la pharmacopée ayurvédique. Son nom signifie « odeur de cheval » en sanskrit, en référence à l'odeur de sa racine fraîche et, dit la tradition, à la force qu'elle est censée conférer. Plusieurs essais randomisés et méta-analyses récentes en confirment l'effet sur le cortisol salivaire.",
    proprietes: [
      "Adaptogène (module la réponse au stress)",
      "Réduit le cortisol salivaire dans plusieurs essais randomisés",
      "Anxiolytique léger",
      "Soutien de la testostérone et de la fertilité masculine (données préliminaires)",
    ],
    indications: [
      "Stress chronique avec composante d'épuisement",
      "Anxiété de fond",
      "Fatigue surrénalienne fonctionnelle",
      "Récupération sportive (athlètes de force)",
    ],
    posologie: [
      "Extrait standardisé (KSM-66, Sensoril) : 300 à 600 mg/jour",
      "Cure de 8 à 12 semaines, à renouveler",
      "Prise de préférence le matin ou en deux fois (matin et midi)",
    ],
    contre_indications: [
      "Grossesse et allaitement (effet utérotonique potentiel)",
      "Hyperthyroïdie (peut stimuler la thyroïde)",
      "Traitement immunosuppresseur",
      "Sédatifs et benzodiazépines : prudence",
    ],
    associations: ['Rhodiole', 'Basilic sacré', 'Magnésium'],
    precautions: "Quelques cas de troubles digestifs ou de somnolence en début de cure. À prendre avec un repas.",
    tradition: "Mentionnée dans le Charaka Samhita, traité ayurvédique vieux de plus de 2000 ans, comme rasayana (rajeunissant). Utilisée traditionnellement pour redonner la vigueur perdue.",
    tags: ['ashwagandha', 'adaptogène', 'cortisol', 'stress chronique'],
    evidence_level: 'meta-analysis',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'rhodiole-stress',
    category: 'stress-anxiete',
    nom: 'Rhodiole',
    nomLatin: 'Rhodiola rosea',
    partieUtilisee: 'Rhizome',
    excerpt: "L'adaptogène nordique pour la fatigue mentale et le stress aigu.",
    intro: "La rhodiole pousse dans les zones froides de Sibérie et de Scandinavie. Utilisée traditionnellement par les peuples nordiques pour résister au froid, au stress et à la fatigue, elle a fait l'objet de l'un des premiers essais randomisés sur un adaptogène (Darbinyan, 2000, chez des médecins en garde de nuit).",
    proprietes: [
      "Adaptogène à action plus rapide que l'ashwagandha",
      "Anti-fatigue mentale et physique",
      "Améliore la concentration sous stress aigu",
      "Légère action sérotoninergique",
    ],
    indications: [
      "Fatigue mentale en période de surcharge cognitive",
      "Stress aigu (préparation d'examen, charge de travail)",
      "État dépressif léger à modéré (en accompagnement)",
      "Préparation aux performances sportives ou intellectuelles",
    ],
    posologie: [
      "Extrait standardisé 3% rosavines, 1% salidroside : 200 à 600 mg/jour",
      "Prise le matin ou en début d'après-midi (effet stimulant)",
      "Cure de 4 à 8 semaines, suivie d'une pause",
    ],
    contre_indications: [
      "Troubles bipolaires (risque de virage maniaque)",
      "Grossesse et allaitement (données insuffisantes)",
      "Le soir (effet stimulant qui peut perturber le sommeil)",
      "Hypertension non équilibrée",
    ],
    associations: ['Magnésium', 'Vitamine B complexe', 'Ginseng (pour les profils plus robustes)'],
    tradition: "Les Vikings en prenaient avant le combat. Les empereurs chinois la cherchaient sur les hauts plateaux du Tibet. Les Soviétiques l'ont étudiée scientifiquement à partir des années 1950 pour les militaires et cosmonautes.",
    tags: ['rhodiole', 'adaptogène', 'fatigue', 'cognition'],
    evidence_level: 'rct',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'basilic-sacre-stress',
    category: 'stress-anxiete',
    nom: 'Basilic sacré (Tulsi)',
    nomLatin: 'Ocimum tenuiflorum',
    partieUtilisee: 'Feuilles',
    excerpt: "L'adaptogène doux et émotionnel de la tradition ayurvédique.",
    intro: "Le tulsi est considéré comme sacré en Inde, planté autour des temples hindous. Sa douceur en fait un adaptogène particulièrement adapté aux personnes émotives, aux profils nerveux et aux situations de stress émotionnel chronique. Son action ne « stimule » pas comme la rhodiole mais apaise tout en soutenant la résistance.",
    proprietes: [
      "Adaptogène doux à action émotionnelle",
      "Modulateur du cortisol (essais préliminaires)",
      "Hypoglycémiant léger",
      "Bronchodilatateur traditionnel",
    ],
    indications: [
      "Stress émotionnel chronique (deuil, rupture, charge mentale)",
      "Anxiété de fond avec composante somatique (estomac, respiration courte)",
      "Profils nerveux et hypersensibles",
      "Prévention saisonnière en accompagnement",
    ],
    posologie: [
      "Infusion : 1 cuillère à café de feuilles séchées pour 250 ml, 5 à 10 minutes, 2 à 3 fois par jour",
      "Extrait sec : 300 à 600 mg/jour",
      "Cure de 8 à 12 semaines",
    ],
    contre_indications: [
      "Grossesse (par précaution, effet utérotonique théorique)",
      "Traitement anticoagulant (prudence)",
      "Avant chirurgie programmée : arrêt 2 semaines avant",
    ],
    associations: ['Ashwagandha', 'Camomille romaine', 'Mélisse'],
    tradition: "Plante sacrée du Vishnouisme. La tradition ayurvédique distingue trois variétés (Rama, Krishna et Vana tulsi), aux usages légèrement différents.",
    tags: ['tulsi', 'basilic sacré', 'adaptogène', 'émotionnel'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
  {
    slug: 'eschscholtzia-stress',
    category: 'stress-anxiete',
    nom: 'Eschscholtzia (pavot de Californie)',
    nomLatin: 'Eschscholzia californica',
    partieUtilisee: 'Parties aériennes',
    excerpt: "L'apaisement progressif et le retour au calme intérieur, sans accoutumance.",
    intro: "L'eschscholtzia est de la même famille botanique que le pavot à opium mais sans en avoir les effets stupéfiants ni le risque de dépendance. Les Amérindiens d'Amérique du Nord l'utilisaient pour apaiser les enfants et calmer les douleurs. C'est aujourd'hui l'une des plantes anxiolytiques douces les mieux tolérées.",
    proprietes: [
      "Anxiolytique et sédative légère",
      "Action sur les récepteurs GABAergiques",
      "Antalgique douce",
      "Sans accoutumance ni effet stupéfiant",
    ],
    indications: [
      "Anxiété diffuse et trouble du sommeil chez l'enfant et l'adulte",
      "Tensions nerveuses avec composante douloureuse",
      "Sevrage en accompagnement des benzodiazépines (sur avis médical)",
      "Hyper-réactivité émotionnelle",
    ],
    posologie: [
      "Extrait sec : 200 à 400 mg en début de soirée",
      "Teinture mère : 30 gouttes 3 fois par jour ou 60 gouttes au coucher",
      "Infusion : 1 cuillère à café pour 250 ml, 10 minutes",
    ],
    contre_indications: [
      "Glaucome à angle fermé",
      "Grossesse et allaitement (par précaution)",
      "Association aux sédatifs : avis médical",
    ],
    associations: ['Valériane', 'Passiflore', 'Aubépine'],
    tradition: "Les Amérindiens du Nord-Ouest l'utilisaient en infusion pour calmer les enfants agités et soulager les maux de tête. Introduite en Europe au XIXᵉ siècle par les missions naturalistes.",
    tags: ['eschscholtzia', 'pavot californie', 'anxiété', 'enfant'],
    evidence_level: 'preliminary',
    updatedAt: '2026-05-29',
  },
];
